export const PageEightOfAdvance = [
  {
    audioData: ['/ˈvæn.ɪʃ/ ', '../../app_assets/audio/vanish.mp3'],
    word: 'vanish',
    meaning: ['disappear suddenly', 'cease to exist'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['disappear'],
    examples: ['Witness vanish overnight.', 'Evidence mysteriously vanished.'],
    synonyms: ['disappear', 'evaporate'],
    antonyms: ['appear'],
    shortStory: 'Key witness vanished before testimony scheduled.',
  },
  {
    audioData: ['/ˈveə.ri.ə.bəl/', '../../app_assets/audio/variable.mp3'],
    word: 'variable',
    meaning: ['changeable', 'factor affecting outcome'],
    partOfSpeech: ['adjective', 'noun'],
    simpleDefinition: ['changeable'],
    examples: ['Variable witness statements.', 'Key variable investigation.'],
    synonyms: ['changeable', 'factor'],
    antonyms: ['constant'],
    shortStory: 'Variable lighting compromised crime scene photos.',
  },
  {
    audioData: ['/ˌveə.riˈeɪ.ʃən/', '../../app_assets/audio/variation.mp3'],
    word: 'variation',
    meaning: ['difference/change', 'slight difference'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['difference'],
    examples: ['Signature variation forgery.', 'Alibi variation suspicious.'],
    synonyms: ['difference', 'change'],
    antonyms: ['sameness'],
    shortStory: 'DNA variation proved familial connection.',
  },
  {
    audioData: ['/ˈveə.rɪd/', '../../app_assets/audio/varied.mp3'],
    word: 'varied',
    meaning: ['different kinds', 'diverse'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['diverse'],
    examples: ['Varied suspect descriptions.', 'Varied forensic techniques.'],
    synonyms: ['diverse'],
    antonyms: ['uniform'],
    shortStory: 'Varied witness accounts created reasonable doubt.',
  },
  {
    audioData: ['/veɪn/', '../../app_assets/audio/vein.mp3'],
    word: 'vein',
    meaning: ['blood vessel', 'mood/style', 'lode deposit'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['blood tube'],
    examples: ['Same vein crimes.', 'Needle marks vein.'],
    synonyms: ['vessel', 'style'],
    antonyms: [],
    shortStory: 'Toxicology confirmed vein injection fentanyl.',
  },
  {
    audioData: ['/ˈven.tʃər/', '../../app_assets/audio/venture.mp3'],
    word: 'venture',
    meaning: ['risky undertaking', 'business enterprise'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['risky project'],
    examples: ['Joint venture laundering.', 'Venture capital fraud.'],
    synonyms: ['enterprise', 'risk'],
    antonyms: ['safe'],
    shortStory: 'Secret venture funded illicit operations.',
  },
  {
    audioData: ['/ˈvɜː.bəl/', '../../app_assets/audio/verbal.mp3'],
    word: 'verbal',
    meaning: ['spoken words', 'word-based'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['spoken'],
    examples: ['Verbal agreement illegal.', 'Verbal abuse harassment.'],
    synonyms: ['spoken', 'oral'],
    antonyms: ['written'],
    shortStory: 'Verbal contract unenforceable court.',
  },
  {
    audioData: ['/ˈvɜː.dɪkt/', '../../app_assets/audio/verdict.mp3'],
    word: 'verdict',
    meaning: ['jury decision', 'judgment'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['jury decision'],
    examples: ['Guilty verdict cheered.', 'Hung jury no verdict.'],
    synonyms: ['decision', 'judgment'],
    antonyms: [],
    shortStory: 'Shocking verdict acquitted corrupt official.',
  },
  {
    audioData: ['/ˈver.ə.faɪ/', '../../app_assets/audio/verify.mp3'],
    word: 'verify',
    meaning: ['confirm truth', 'authenticate'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['confirm'],
    examples: ['Verify alibi timeline.', 'Verify document authenticity.'],
    synonyms: ['confirm', 'authenticate'],
    antonyms: ['disprove'],
    shortStory: 'Fingerprint verify matched crime scene.',
  },
  {
    audioData: ['/vɜːs/', '../../app_assets/audio/verse.mp3'],
    word: 'verse',
    meaning: ['poetry line', 'Bible passage'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['poem line'],
    examples: ['Threatening verse poem.', 'Scripture verse quoted.'],
    synonyms: ['line', 'passage'],
    antonyms: [],
    shortStory: 'Anonymous verse contained coded threat.',
  },
  {
    audioData: ['/ˈvɜː.səs/', '../../app_assets/audio/versus.mp3'],
    word: 'versus',
    meaning: ['against', 'compared to'],
    partOfSpeech: ['preposition'],
    simpleDefinition: ['against'],
    examples: ['State versus defendant.', 'Police versus community.'],
    synonyms: ['against', 'vs'],
    antonyms: [],
    shortStory: 'Landmark case State versus Corruption.',
  },
  {
    audioData: ['/ˈvɜː.tɪ.kəl/', '../../app_assets/audio/vertical.mp3'],
    word: 'vertical',
    meaning: ['upright/straight up', 'highest level'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['upright'],
    examples: ['Vertical integration cartel.', 'Vertical career climb.'],
    synonyms: ['upright'],
    antonyms: ['horizontal'],
    shortStory: 'Vertical organization protected crime boss.',
  },
  {
    audioData: ['/ˈves.əl/', '../../app_assets/audio/vessel.mp3'],
    word: 'vessel',
    meaning: ['ship/boat', 'container', 'body tube'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['ship'],
    examples: ['Blood vessel rupture.', 'Smuggler vessel intercepted.'],
    synonyms: ['ship', 'container'],
    antonyms: [],
    shortStory: 'Rogue vessel transported contraband.',
  },
  {
    audioData: ['/ˈvet.ər.ən/', '../../app_assets/audio/veteran.mp3'],
    word: 'veteran',
    meaning: ['experienced person', 'former soldier'],
    partOfSpeech: ['noun', 'adjective'],
    simpleDefinition: ['experienced'],
    examples: ['Veteran detective instincts.', 'Veteran corruption fighter.'],
    synonyms: ['expert'],
    antonyms: ['novice'],
    shortStory: 'Veteran investigator saw case pattern.',
  },
  {
    audioData: ['/ˈvaɪ.ə.bəl/', '../../app_assets/audio/viable.mp3'],
    word: 'viable',
    meaning: ['capable of working', 'possible'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['possible'],
    examples: ['Viable suspect identified.', 'Viable defense strategy.'],
    synonyms: ['possible', 'workable'],
    antonyms: ['impossible'],
    shortStory: 'Viable alternative theory dismissed.',
  },
  {
    audioData: ['/ˈvaɪ.brənt/', '../../app_assets/audio/vibrant.mp3'],
    word: 'vibrant',
    meaning: ['full of energy', 'bright'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['energetic'],
    examples: ['Vibrant community protest.', 'Vibrant tattoo identification.'],
    synonyms: ['energetic'],
    antonyms: ['dull'],
    shortStory: 'Vibrant whistleblower movement grew.',
  },
  {
    audioData: ['/vaɪs/', '../../app_assets/audio/vice.mp3'],
    word: 'vice',
    meaning: ['moral fault', 'deputy position'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['bad habit'],
    examples: ['Vice squad corruption.', 'Vice president implicated.'],
    synonyms: ['sin', 'deputy'],
    antonyms: ['virtue'],
    shortStory: 'Vice president resigned scandal.',
  },
  {
    audioData: ['/ˈvɪʃ.əs/', '../../app_assets/audio/vicious.mp3'],
    word: 'vicious',
    meaning: ['cruel/violent', 'intense'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['cruel'],
    examples: ['Vicious assault weapon.', 'Vicious cycle corruption.'],
    synonyms: ['cruel', 'savage'],
    antonyms: ['kind'],
    shortStory: 'Vicious attack pattern repeated.',
  },
  {
    audioData: [' /ˈvjuː.pɔɪnt/ ', '../../app_assets/audio/viewpoint.mp3'],
    word: 'viewpoint',
    meaning: ['way of seeing', 'opinion'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['opinion'],
    examples: ['Media viewpoint biased.', 'Witness viewpoint obstructed.'],
    synonyms: ['opinion', 'perspective'],
    antonyms: [],
    shortStory: 'Different viewpoints created conflicting testimonies.',
  },
  {
    audioData: ['/ˈvɪl.ɪ.dʒər/', '../../app_assets/audio/villager.mp3'],
    word: 'villager',
    meaning: ['person from village'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['village person'],
    examples: ['Villager discovered body.', 'Villager testimony ignored.'],
    synonyms: ['local'],
    antonyms: [],
    shortStory: 'Villager found crime scene first.',
  },
  {
    audioData: ['/ˈvaɪ.ə.leɪt/', '../../app_assets/audio/violate.mp3'],
    word: 'violate',
    meaning: ['break law/rule', 'disrupt'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['break'],
    examples: ['Violate Miranda rights.', 'Violate parole conditions.'],
    synonyms: ['break', 'disobey'],
    antonyms: ['obey'],
    shortStory: 'Illegal search violated constitutional rights.',
  },
  {
    audioData: ['/ˌvaɪ.əˈleɪ.ʃən/', '../../app_assets/audio/violation.mp3'],
    word: 'violation',
    meaning: ['act of violating'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['breaking'],
    examples: ['Ethics violation charges.', 'Traffic violation pretext.'],
    synonyms: ['breach'],
    antonyms: ['compliance'],
    shortStory: 'Multiple violations led license revocation.',
  },

  {
    audioData: ['/ˈvɜː.tʃuː/', '../../app_assets/audio/virtue.mp3'],
    word: 'virtue',
    meaning: ['moral excellence', 'good quality'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['goodness'],
    examples: ['By virtue office.', 'Patience virtue investigation.'],
    synonyms: ['goodness', 'merit'],
    antonyms: ['vice'],
    shortStory: 'Public virtue masked private corruption.',
  },
  {
    audioData: [' ', '../../app_assets/audio/visa.mp3'],
    word: 'visa',
    meaning: ['entry permission document'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['entry permit'],
    examples: ['Forged visa smuggling.', 'Visa overstay deportation.'],
    synonyms: ['permit'],
    antonyms: [],
    shortStory: 'Fake visa ring busted airport.',
  },
  {
    audioData: ['/ˈvɪz.ə.bəl/', '../../app_assets/audio/visible.mp3'],
    word: 'visible',
    meaning: ['able to be seen'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['seen'],
    examples: ['Visible injuries assault.', 'Visible security cameras.'],
    synonyms: ['seen'],
    antonyms: ['invisible'],
    shortStory: 'Visible blood spatter mapped attack.',
  },
  {
    audioData: ['/ˈvəʊ.kəl/', '../../app_assets/audio/vocal.mp3'],
    word: 'vocal',
    meaning: ['making sounds', 'outspoken'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['outspoken'],
    examples: ['Vocal whistleblower campaign.', 'Vocal defense attorney.'],
    synonyms: ['outspoken'],
    antonyms: ['silent'],
    shortStory: 'Vocal critic exposed department corruption.',
  },
  {
    audioData: ['/ˈvɑlənˌtɛri/', '../../app_assets/audio/voluntary.mp3'],
    word: 'voluntary',
    meaning: ['done by choice'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['by choice'],
    examples: [
      'Voluntary confession admissible.',
      'Voluntary witness statement.',
    ],
    synonyms: ['willing'],
    antonyms: ['forced'],
    shortStory: 'Voluntary surrender earned leniency.',
  },
  {
    audioData: ['/ˈvoʊt̮ɪŋ/', '../../app_assets/audio/voting.mp3'],
    word: 'voting',
    meaning: ['act of casting vote'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['electing'],
    examples: ['Voting fraud charges.', 'Absentee voting scandal.'],
    synonyms: ['election'],
    antonyms: [],
    shortStory: 'Massive voting irregularities overturned election.',
  },
  {
    audioData: ['/vaʊ/', '../../app_assets/audio/vow.mp3'],
    word: 'vow',
    meaning: ['solemn promise'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['promise'],
    examples: ['Vow silence omertà.', 'Marriage vow broken.'],
    synonyms: ['pledge', 'oath'],
    antonyms: [],
    shortStory: 'Mafia vow prevented testimony.',
  },
  {
    audioData: [' /ˌvʌl.nər.əˈbɪl.ə.ti/', '../../app_assets/audio/.mp3'],
    word: 'vulnerability',
    meaning: ['weakness/susceptibility'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['weakness'],
    examples: [
      'System vulnerability hacked.',
      'Witness vulnerability exploited.',
    ],
    synonyms: ['weakness'],
    antonyms: ['strength'],
    shortStory: 'Security vulnerability allowed breach.',
  },
  {
    audioData: ['/ˈvʌl.nər.ə.bəl/', '../../app_assets/audio/vulnerable.mp3'],
    word: 'vulnerable',
    meaning: ['open to harm', 'weak position'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['weak'],
    examples: ['Vulnerable witness protection.', 'Vulnerable defense exposed.'],
    synonyms: ['weak'],
    antonyms: ['protected'],
    shortStory: 'Vulnerable informant flipped safely.',
  },
  {
    audioData: [' /ˈwɒn.dər/', '../../app_assets/audio/wander.mp3'],
    word: 'wander',
    meaning: ['move without direction'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['roam'],
    examples: ['Mind wander testimony.', 'Suspect wander streets.'],
    synonyms: ['roam'],
    antonyms: ['stay'],
    shortStory: 'Amnesiac witness wandered crime scene.',
  },
  {
    audioData: [' /wɔːd/', '../../app_assets/audio/ward.mp3'],
    word: 'ward',
    meaning: ['protection', 'hospital room', 'district'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['protection'],
    examples: ['Ward state custody.', 'Political ward boss.'],
    synonyms: ['protection', 'district'],
    antonyms: [],
    shortStory: 'Corrupt ward boss controlled votes.',
  },
  {
    audioData: [' /ˈweə.haʊs/', '../../app_assets/audio/warehouse.mp3'],
    word: 'warehouse',
    meaning: ['storage building'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['storage'],
    examples: ['Warehouse drug stash.', 'Evidence warehouse secure.'],
    synonyms: ['storage'],
    antonyms: [],
    shortStory: 'Abandoned warehouse hid crime proceeds.',
  },
  {
    audioData: [' /ˈwɔrfɛr/', '../../app_assets/audio/warfare.mp3'],
    word: 'warfare',
    meaning: ['armed conflict', 'struggle'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['war'],
    examples: ['Information warfare propaganda.', 'Price warfare competition.'],
    synonyms: ['conflict'],
    antonyms: ['peace'],
    shortStory: 'Corporate warfare destroyed competitors.',
  },
  {
    audioData: [' /ˈwɔrmɪŋ/', '../../app_assets/audio/warming.mp3'],
    word: 'warming',
    meaning: ['temperature increase'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['heating'],
    examples: ['Global warming fraud.', 'Seat warming metaphor.'],
    synonyms: ['heating'],
    antonyms: ['cooling'],
    shortStory: 'Climate data tampering warming scandal.',
  },
  {
    audioData: ['/ˈwɒr.ənt/', '../../app_assets/audio/warrant.mp3'],
    word: 'warrant',
    meaning: ['legal document authorizing', 'justification'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['legal order'],
    examples: ['Search warrant approved.', 'No warrant entry illegal.'],
    synonyms: ['order', 'justify'],
    antonyms: [],
    shortStory: 'Faulty warrant invalidated evidence.',
  },
  {
    audioData: ['/ˈwɒr.i.ər/', '../../app_assets/audio/warrior.mp3'],
    word: 'warrior',
    meaning: ['experienced fighter'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['fighter'],
    examples: ['Weekend warrior suspect.', 'Justice warrior prosecutor.'],
    synonyms: ['fighter'],
    antonyms: ['coward'],
    shortStory: 'Anti-corruption warrior never surrendered.',
  },
  {
    audioData: ['  /ˈwiː.kən/', '../../app_assets/audio/weaken.mp3'],
    word: 'weaken',
    meaning: ['make less strong'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['weaken'],
    examples: ['Weaken prosecution case.', 'Weaken resolve interrogation.'],
    synonyms: ['weaken'],
    antonyms: ['strengthen'],
    shortStory: 'Character witnesses weakened defense.',
  },
  {
    audioData: ['/wiːv/', '../../app_assets/audio/weave.mp3'],
    word: 'weave',
    meaning: ['make fabric', 'create story', 'move side to side'],
    partOfSpeech: ['verb', 'noun'],
    simpleDefinition: ['create or zigzag'],
    examples: ['Weave elaborate alibi.', 'Weave through traffic.'],
    synonyms: ['create', 'zigzag'],
    antonyms: [],
    shortStory: 'Suspect wove complex web lies.',
  },

  {
    audioData: ['/wiːd/', '../../app_assets/audio/weed.mp3'],
    word: 'weed',
    meaning: ['unwanted plant', 'marijuana', 'remove unwanted'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['unwanted plant'],
    examples: ['Weed out corrupt officers.', 'Marijuana evidence field.'],
    synonyms: ['plant', 'remove'],
    antonyms: ['flower'],
    shortStory: 'Internal affairs weeded corrupt cops department.',
  },
  {
    audioData: [' /ˈwiː.kli/', '../../app_assets/audio/weekly.mp3'],
    word: 'weekly',
    meaning: ['every week', 'weekly publication'],
    partOfSpeech: ['adjective', 'adverb', 'noun'],
    simpleDefinition: ['weekly'],
    examples: ['Weekly briefing corruption.', 'Weekly crime report.'],
    synonyms: ['every week'],
    antonyms: ['daily'],
    shortStory: 'Weekly surveillance report flagged suspicious pattern.',
  },
  {
    audioData: [' /wɪəd/', '../../app_assets/audio/weird.mp3'],
    word: 'weird',
    meaning: ['strange/unusual'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['strange'],
    examples: ['Weird crime scene ritual.', 'Weird alibi implausible.'],
    synonyms: ['strange', 'odd'],
    antonyms: ['normal'],
    shortStory: 'Weird signature linked serial crimes.',
  },
  {
    audioData: [' /ˈwel.feər/', '../../app_assets/audio/welfare.mp3'],
    word: 'welfare',
    meaning: ['well-being', 'government aid'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['well-being'],
    examples: ['Welfare fraud investigation.', 'Public welfare priority.'],
    synonyms: ['well-being', 'aid'],
    antonyms: [],
    shortStory: 'Welfare scam defrauded taxpayers millions.',
  },
  {
    audioData: ['  /wel/', '../../app_assets/audio/ukwelde004.mp3'],
    word: 'well',
    meaning: ['healthy', 'water source', 'properly'],
    partOfSpeech: ['adjective', 'noun', 'adverb'],
    simpleDefinition: ['healthy or properly'],
    examples: ['Well-preserved evidence.', 'Well-connected suspect.'],
    synonyms: ['healthy', 'properly'],
    antonyms: ['ill'],
    shortStory: 'Well-placed mole fed false information.',
  },
  {
    audioData: ['/ˈwelˈbi·ɪŋ/', '../../app_assets/audio/well_being.mp3'],
    word: 'well-being',
    meaning: ['state of being healthy/happy'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['health'],
    examples: ['Witness well-being concern.', 'Employee well-being program.'],
    synonyms: ['health'],
    antonyms: ['illness'],
    shortStory: 'Victim well-being deteriorated under pressure.',
  },
  {
    audioData: [' /ˌwɒt.səʊˈev.ər/', '../../app_assets/audio/whatsoever.mp3'],
    word: 'whatsoever',
    meaning: ['at all', 'of any kind'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['at all'],
    examples: ['No evidence whatsoever.', 'No remorse whatsoever.'],
    synonyms: ['any'],
    antonyms: [],
    shortStory: 'No fingerprints whatsoever crime scene.',
  },
  {
    audioData: [' /wiːt/', '../../app_assets/audio/wheat.mp3'],
    word: 'wheat',
    meaning: ['grain crop'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['grain'],
    examples: ['Wheat field body.', 'Grain silo smuggling.'],
    synonyms: ['grain'],
    antonyms: [],
    shortStory: 'Body discovered wheat field harvest.',
  },
  {
    audioData: ['/weəˈbaɪ/', '../../app_assets/audio/whereby.mp3'],
    word: 'whereby',
    meaning: ['by which', 'how'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['by which'],
    examples: ['Contract whereby bribed.', 'Process whereby laundered.'],
    synonyms: ['by which'],
    antonyms: [],
    shortStory: 'Scheme whereby officials received kickbacks.',
  },
  {
    audioData: ['  /waɪlst/', '../../app_assets/audio/whilst.mp3'],
    word: 'whilst',
    meaning: ['while', 'although'],
    partOfSpeech: ['conjunction'],
    simpleDefinition: ['while'],
    examples: ['Whilst claiming innocence.', 'Search whilst suspect waited.'],
    synonyms: ['while'],
    antonyms: [],
    shortStory: 'Whilst claiming cooperation evidence contradicted.',
  },
  {
    audioData: [' /wɪp/', '../../app_assets/audio/whip.mp3'],
    word: 'whip',
    meaning: ['beat with whip', 'political control'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['beat or control'],
    examples: ['Party whip discipline.', 'Whip vote loyalty.'],
    synonyms: ['lash', 'control'],
    antonyms: [],
    shortStory: 'Party whip enforced corruption silence.',
  },
  {
    audioData: ['  /huːˈev.ər/', '../../app_assets/audio/whoever.mp3'],
    word: 'whoever',
    meaning: ['any person who', 'no matter who'],
    partOfSpeech: ['pronoun'],
    simpleDefinition: ['anyone who'],
    examples: ['Whoever leaked documents.', 'Prosecute whoever responsible.'],
    synonyms: ['anyone'],
    antonyms: [],
    shortStory: 'Whoever planted evidence faced felony.',
  },
  {
    audioData: [' /ˈhəʊl.li/', '../../app_assets/audio/wholly.mp3'],
    word: 'wholly',
    meaning: ['completely', 'entirely'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['completely'],
    examples: ['Wholly owned subsidiary.', 'Wholly unreliable witness.'],
    synonyms: ['completely'],
    antonyms: ['partly'],
    shortStory: 'Wholly fabricated alibi collapsed.',
  },
  {
    audioData: [' /ˈwaɪ.dən/', '../../app_assets/audio/widen.mp3'],
    word: 'widen',
    meaning: ['make broader', 'expand'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['expand'],
    examples: ['Widen investigation scope.', 'Widen suspect pool.'],
    synonyms: ['expand', 'broaden'],
    antonyms: ['narrow'],
    shortStory: 'Prosecutors widened conspiracy charges.',
  },
  {
    audioData: [' /ˌwaɪdˈspred/', '../../app_assets/audio/widespread.mp3'],
    word: 'widespread',
    meaning: ['existing many places'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['common'],
    examples: [
      'Widespread corruption department.',
      'Widespread public outrage.',
    ],
    synonyms: ['common', 'extensive'],
    antonyms: ['limited'],
    shortStory: 'Widespread bribery exposed internal audit.',
  },
  {
    audioData: ['/ˈwɪd.əʊ/', '../../app_assets/audio/widow.mp3'],
    word: 'widow',
    meaning: ['woman lost husband'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['husbandless woman'],
    examples: ['Black widow serial.', 'Widow inheritance motive.'],
    synonyms: ['bereaved'],
    antonyms: [],
    shortStory: 'Widow collected million-dollar insurance.',
  },
  {
    audioData: ['/wɪtθ/', '../../app_assets/audio/width.mp3'],
    word: 'width',
    meaning: ['measurement across'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['breadth'],
    examples: ['Tire width matched.', 'River width escape.'],
    synonyms: ['breadth'],
    antonyms: ['length'],
    shortStory: 'Tire tread width identified vehicle.',
  },
  {
    audioData: [' /ˈwɪl.ɪŋ.nəs/ ', '../../app_assets/audio/willingness.mp3'],
    word: 'willingness',
    meaning: ['readiness to do'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['readiness'],
    examples: [
      'Witness willingness testify.',
      'Informant willingness cooperate.',
    ],
    synonyms: ['readiness'],
    antonyms: ['reluctance'],
    shortStory: 'Informant willingness earned reduced sentence.',
  },
  {
    audioData: ['  /waɪp/', '../../app_assets/audio/wipe.mp3'],
    word: 'wipe',
    meaning: ['clean/rub', 'remove completely'],
    partOfSpeech: ['verb', 'noun'],
    simpleDefinition: ['clean'],
    examples: ['Wipe hard drive.', 'Wipe fingerprints scene.'],
    synonyms: ['clean', 'erase'],
    antonyms: ['leave'],
    shortStory: 'Tech wipe removed crucial evidence.',
  },

  {
    audioData: [' /ˈwɪz.dəm/', '../../app_assets/audio/wisdom.mp3'],
    word: 'wisdom',
    meaning: ['good judgment', 'accumulated knowledge'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['good judgment'],
    examples: ['Conventional wisdom wrong.', 'Street wisdom survival.'],
    synonyms: ['judgment', 'insight'],
    antonyms: ['foolishness'],
    shortStory: 'Investigator wisdom spotted forged document flaw.',
  },
  {
    audioData: [' /wɪt/', '../../app_assets/audio/wit.mp3'],
    word: 'wit',
    meaning: ['clever intelligence', 'quick humor'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['cleverness'],
    examples: ['Legal wit argument.', 'Cross-examination wit sharp.'],
    synonyms: ['intelligence', 'humor'],
    antonyms: ['dullness'],
    shortStory: 'Defense attorney wit dismantled prosecution.',
  },
  {
    audioData: ['/wɪðˈdrɔː/ ', '../../app_assets/audio/withdraw.mp3'],
    word: 'withdraw',
    meaning: ['remove/pull back', 'stop participation'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['pull back'],
    examples: ['Withdraw plea deal.', 'Withdraw from case.'],
    synonyms: ['remove', 'retreat'],
    antonyms: ['deposit', 'enter'],
    shortStory: 'Star witness withdrew testimony suddenly.',
  },
  {
    audioData: ['/wɪðˈdrɔː.əl/', '../../app_assets/audio/withdrawal.mp3'],
    word: 'withdrawal',
    meaning: ['act of withdrawing', 'money removal'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['removal'],
    examples: ['Cash withdrawal suspicious.', 'Plea withdrawal motion.'],
    synonyms: ['removal', 'retreat'],
    antonyms: ['deposit'],
    shortStory: 'Large cash withdrawals funded smuggling.',
  },
  {
    audioData: [' /ˈwɜːk.fɔːs/ ', '../../app_assets/audio/workforce.mp3'],
    word: 'workforce',
    meaning: ['total employees'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['workers'],
    examples: ['Workforce reduction layoffs.', 'Corrupt workforce culture.'],
    synonyms: ['employees', 'staff'],
    antonyms: [],
    shortStory: 'Workforce decimated corruption purge.',
  },
  {
    audioData: ['/ˈwɜː.kaʊt/ ', '../../app_assets/audio/workout.mp3'],
    word: 'workout',
    meaning: ['exercise session', 'solution to problem'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['exercise'],
    examples: ['Timeline workout complex.', 'Budget workout impossible.'],
    synonyms: ['exercise', 'solution'],
    antonyms: [],
    shortStory: 'Alibi workout revealed timeline gaps.',
  },
  {
    audioData: [' /ˈwɜːk.pleɪs/', '../../app_assets/audio/workplace.mp3'],
    word: 'workplace',
    meaning: ['place where people work'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['work location'],
    examples: ['Workplace harassment suit.', 'Workplace surveillance cameras.'],
    synonyms: ['office'],
    antonyms: [],
    shortStory: 'Workplace cameras captured theft.',
  },
  {
    audioData: ['/ˈwɜːk.ʃɒp/ ', '../../app_assets/audio/workshop.mp3'],
    word: 'workshop',
    meaning: ['room for work', 'training session'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['training session'],
    examples: [
      'Forensic workshop training.',
      'Sensitivity workshop mandatory.',
    ],
    synonyms: ['seminar', 'studio'],
    antonyms: [],
    shortStory: 'Whistleblower workshop taught anonymity.',
  },
  {
    audioData: [' /wɜːm/', '../../app_assets/audio/worm.mp3'],
    word: 'worm',
    meaning: ['small crawling animal', 'computer virus'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['computer virus'],
    examples: ['Worm infected evidence server.', 'Worm information slowly.'],
    synonyms: ['virus', 'infest'],
    antonyms: [],
    shortStory: 'Digital worm extracted corporate secrets.',
  },
  {
    audioData: ['/ˈwɜː.ʃɪp/ ', '../../app_assets/audio/worship.mp3'],
    word: 'worship',
    meaning: ['religious devotion', 'extreme admiration'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['religious honor'],
    examples: ['Cargo cult worship.', 'Personality worship dangerous.'],
    synonyms: ['adoration'],
    antonyms: ['despise'],
    shortStory: 'Cult worship prevented defectors.',
  },
  {
    audioData: ['/ˌwɜːθˈwaɪl/ ', '../../app_assets/audio/worthwhile.mp3'],
    word: 'worthwhile',
    meaning: ['important/valuable enough'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['valuable'],
    examples: [
      'Worthwhile investigation leads.',
      'Worthwhile sacrifice justice.',
    ],
    synonyms: ['valuable'],
    antonyms: ['worthless'],
    shortStory: 'Long investigation proved worthwhile.',
  },
  {
    audioData: ['/ˈwɜː.ði/ ', '../../app_assets/audio/worthy.mp3'],
    word: 'worthy',
    meaning: ['having merit', 'deserving'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['deserving'],
    examples: ['Worthy cause donation.', 'Worthy adversary respect.'],
    synonyms: ['deserving', 'meritorious'],
    antonyms: ['unworthy'],
    shortStory: 'Worthy opponent nearly escaped.',
  },
  {
    audioData: ['/rɪst/ ', '../../app_assets/audio/wrist.mp3'],
    word: 'wrist',
    meaning: ['joint connecting hand arm'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['hand joint'],
    examples: ['Wrist slap penalty.', 'Handcuff wrist marks.'],
    synonyms: ['joint'],
    antonyms: [],
    shortStory: 'Broken wrist explained defensive wounds.',
  },
  {
    audioData: [' /jel/ ', '../../app_assets/audio/yell.mp3'],
    word: 'yell',
    meaning: ['loud shout'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['shout'],
    examples: ['Yell courtroom outburst.', 'Victim yell heard.'],
    synonyms: ['shout'],
    antonyms: ['whisper'],
    shortStory: 'Neighbor heard yell argument.',
  },
  {
    audioData: ['/jiːld/ ', '../../app_assets/audio/yield.mp3'],
    word: 'yield',
    meaning: ['produce/give', 'surrender'],
    partOfSpeech: ['verb', 'noun'],
    simpleDefinition: ['produce'],
    examples: ['Yield confession pressure.', 'Investment yield bribes.'],
    synonyms: ['produce', 'surrender'],
    antonyms: ['withhold'],
    shortStory: 'Intense interrogation yielded confession.',
  },
  {
    audioData: [' /ˈjʌŋ.stər/', '../../app_assets/audio/youngster.mp3'],
    word: 'youngster',
    meaning: ['young person/child'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['child'],
    examples: [
      'Youngster witness protected.',
      'Streetwise youngster informant.',
    ],
    synonyms: ['child', 'kid'],
    antonyms: ['adult'],
    shortStory: 'Youngster discovered crime scene first.',
  },
];
