export const PageTwoOfPhrase = [
  {
    audioData: [' ', ''],
    word: 'someone else',
    meaning: ['another person', 'not me/you'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['another'],
    examples: ['Ask someone else.', 'Give it to someone else.'],
    synonyms: ['another person'],
    antonyms: ['me'],
    shortStory: 'Someone else solved the puzzle first.',
  },
  {
    audioData: [' ', ''],
    word: 'speak to sb',
    meaning: ['talk directly to someone', 'address'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['talk to'],
    examples: ['Speak to the manager.', 'Can I speak to you?'],
    synonyms: ['talk to'],
    antonyms: ['ignore'],
    shortStory: 'Speak to the wise elder for guidance.',
  },
  {
    audioData: [' ', ''],
    word: 'spend time',
    meaning: ['pass time doing activity', 'use time'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['pass time'],
    examples: ['Spend time with family.', 'Spend time studying.'],
    synonyms: ['pass time'],
    antonyms: ['waste time'],
    shortStory: 'Spend time reading under the old oak.',
  },
  {
    audioData: [' ', ''],
    word: 'stand up',
    meaning: ['rise to feet', 'from sitting'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['rise'],
    examples: ['Stand up please.', 'Stand up straight.'],
    synonyms: ['get up'],
    antonyms: ['sit down'],
    shortStory: 'Stand up to face new challenges boldly.',
  },
  {
    audioData: [' ', ''],
    word: 'stay in',
    meaning: ['remain at home', 'not go out'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['home'],
    examples: ['Stay in tonight.', "Let's stay in."],
    synonyms: ['remain home'],
    antonyms: ['go out'],
    shortStory: 'Stay in when storm clouds gather darkly.',
  },
  {
    audioData: [' ', ''],
    word: 'such as',
    meaning: ['for example', 'like'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['e.g.'],
    examples: ['Fruits such as apples.', 'Sports such as soccer.'],
    synonyms: ['for example'],
    antonyms: ['unlike'],
    shortStory: 'Birds such as eagles soar majestically.',
  },
  {
    audioData: [' ', ''],
    word: 'swimming pool',
    meaning: ['pool for swimming', 'built water area'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['pool'],
    examples: ['Swim in the pool.', 'Public swimming pool.'],
    synonyms: ['pool'],
    antonyms: ['dry land'],
    shortStory: 'Dive into the cool swimming pool.',
  },
  {
    audioData: [' ', ''],
    word: 'talk about sb/sth',
    meaning: ['discuss person/thing', 'speak of'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['discuss'],
    examples: ['Talk about the movie.', 'Talk about your day.'],
    synonyms: ['discuss'],
    antonyms: ['ignore'],
    shortStory: 'Talk about dreams around the campfire.',
  },
  {
    audioData: [' ', ''],
    word: 'thank you',
    meaning: ['expression of gratitude', 'thanks'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['thanks'],
    examples: ['Thank you very much.', 'Thank you for help.'],
    synonyms: ['thanks'],
    antonyms: ['no thanks'],
    shortStory: 'Thank you mends more than apologies.',
  },
  {
    audioData: [' ', ''],
    word: 'that day',
    meaning: ['specific past day', 'particular date'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['then'],
    examples: ['That day changed everything.', 'Remember that day?'],
    synonyms: ['then'],
    antonyms: ['today'],
    shortStory: 'That day the stars aligned perfectly.',
  },
  {
    audioData: [' ', ''],
    word: 'the 20th century',
    meaning: ['1901-2000 period', '1900s'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['1900s'],
    examples: ['Born in 20th century.', '20th century inventions.'],
    synonyms: ['1900s'],
    antonyms: ['21st century'],
    shortStory: '20th century dreams launched moon landings.',
  },
  {
    audioData: [' ', ''],
    word: 'the next day',
    meaning: ['following day', 'tomorrow'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['tomorrow'],
    examples: ['The next day we left.', 'See you the next day.'],
    synonyms: ['tomorrow'],
    antonyms: ['previous day'],
    shortStory: 'The next day brought unexpected sunshine.',
  },
  {
    audioData: [' ', ''],
    word: 'there is',
    meaning: ['something exists now', 'one item present'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['exists'],
    examples: ['There is a book.', 'There is time.'],
    synonyms: ['exists'],
    antonyms: ["there isn't"],
    shortStory: 'There is magic in quiet moments.',
  },
  {
    audioData: [' ', ''],
    word: 'there are',
    meaning: ['multiple items exist', 'plural present'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['exist plural'],
    examples: ['There are books.', 'There are children.'],
    synonyms: ['exist'],
    antonyms: ["there aren't"],
    shortStory: 'There are stars lighting dark paths.',
  },
  {
    audioData: [' ', ''],
    word: 'there was',
    meaning: ['something existed then', 'past singular'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['existed'],
    examples: ['There was a storm.', 'There was noise.'],
    synonyms: ['existed'],
    antonyms: ["there wasn't"],
    shortStory: "There was hope in yesterday's rain.",
  },
  {
    audioData: [' ', ''],
    word: 'there were',
    meaning: ['multiple existed then', 'past plural'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['existed plural'],
    examples: ['There were birds.', 'There were people.'],
    synonyms: ['existed'],
    antonyms: ["there weren't"],
    shortStory: 'There were dreams in old letters.',
  },
  {
    audioData: [' ', ''],
    word: 'think about sb/sth',
    meaning: ['consider deeply', 'ponder or reflect'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['consider'],
    examples: ['Think about the plan.', 'Think about family.'],
    synonyms: ['ponder'],
    antonyms: ['ignore'],
    shortStory: "Think about tomorrow's bright sunrise.",
  },
  {
    audioData: [' ', ''],
    word: 'think of sb/sth',
    meaning: ['remember or imagine', 'bring to mind'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['remember'],
    examples: ['Think of happy times.', 'Think of her smile.'],
    synonyms: ['recall'],
    antonyms: ['forget'],
    shortStory: 'Think of childhood games in rain.',
  },
  {
    audioData: [' ', ''],
    word: 'This is…',
    meaning: ['introduce something', 'point out item'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['here is'],
    examples: ['This is my house.', 'This is important.'],
    synonyms: ['here is'],
    antonyms: ['that is'],
    shortStory: 'This is where magic begins quietly.',
  },
  {
    audioData: [' ', ''],
    word: 'this kind of…',
    meaning: ['this type or sort', 'similar category'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['this type'],
    examples: ['This kind of weather.', 'This kind of book.'],
    synonyms: ['this type'],
    antonyms: ['that kind'],
    shortStory: 'This kind of smile warms cold days.',
  },
  {
    audioData: [' ', ''],
    word: 'this morning',
    meaning: ["today's AM period", 'current morning'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['today AM'],
    examples: ['Saw her this morning.', 'Worked this morning.'],
    synonyms: ['today morning'],
    antonyms: ['last night'],
    shortStory: 'This morning dew sparkles like diamonds.',
  },
  {
    audioData: [' ', ''],
    word: 'this time',
    meaning: ['now occasion', 'current moment'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['now'],
    examples: ["This time it's different.", 'Try this time.'],
    synonyms: ['now'],
    antonyms: ['last time'],
    shortStory: 'This time courage wins the race.',
  },
  {
    audioData: [' ', ''],
    word: 'this year',
    meaning: ['current calendar year', 'now year'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['current year'],
    examples: ['Travel this year.', 'Goals this year.'],
    synonyms: ['current year'],
    antonyms: ['last year'],
    shortStory: 'This year dreams grow stronger wings.',
  },
  {
    audioData: [' ', ''],
    word: 'thousands of…',
    meaning: ['very large number', 'many thousands'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['huge amount'],
    examples: ['Thousands of stars.', 'Thousands of people.'],
    synonyms: ['countless'],
    antonyms: ['few'],
    shortStory: 'Thousands of fireflies light summer nights.',
  },
  {
    audioData: [' ', ''],
    word: 'too long',
    meaning: ['excessive duration', 'takes longer than needed'],
    partOfSpeech: ['adverb phrase'],
    simpleDefinition: ['excessive time'],
    examples: ['The movie was too long.', 'Waited too long.'],
    synonyms: ['overlong'],
    antonyms: ['brief'],
    shortStory: 'The wait felt too long before joy arrived.',
  },
  {
    audioData: [' ', ''],
    word: 'too much',
    meaning: ['excessive amount', 'more than needed'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['excessive'],
    examples: ['Too much sugar.', 'Too much noise.'],
    synonyms: ['excessive'],
    antonyms: ['just enough'],
    shortStory: 'Too much rain flooded the hopeful garden.',
  },
  {
    audioData: [' ', ''],
    word: 'town centre',
    meaning: ['central town area', 'downtown'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['downtown'],
    examples: ['Shops in town centre.', 'Meet at town centre.'],
    synonyms: ['downtown'],
    antonyms: ['outskirts'],
    shortStory: 'Town centre buzzed with market day excitement.',
  },
  {
    audioData: [' ', ''],
    word: 'TV show',
    meaning: ['television program', 'broadcast series'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['program'],
    examples: ['Favorite TV show tonight.', 'Watch TV show together.'],
    synonyms: ['program'],
    antonyms: ['movie'],
    shortStory: 'TV show captured hearts across neighborhoods.',
  },
  {
    audioData: [' ', ''],
    word: 'wait for sb/sth',
    meaning: ['remain until arrival', 'anticipate'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['await'],
    examples: ['Wait for the bus.', 'Wait for friends.'],
    synonyms: ['await'],
    antonyms: ['leave'],
    shortStory: 'Wait for the perfect moment to shine.',
  },
  {
    audioData: [' ', ''],
    word: 'wake up',
    meaning: ['stop sleeping', 'become alert'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['awaken'],
    examples: ['Wake up early.', 'Wake up now!'],
    synonyms: ['awaken'],
    antonyms: ['fall asleep'],
    shortStory: 'Wake up to birdsong symphony.',
  },
  {
    audioData: [' ', ''],
    word: 'welcome to sth',
    meaning: ['greeting new arrival', 'introduction'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['hello'],
    examples: ['Welcome to our home.', 'Welcome to class.'],
    synonyms: ['hello'],
    antonyms: ['goodbye'],
    shortStory: 'Welcome to endless summer adventures.',
  },
  {
    audioData: [' ', ''],
    word: 'What about…?',
    meaning: ['suggestion or inclusion', 'consider this?'],
    partOfSpeech: ['question'],
    simpleDefinition: ['and?'],
    examples: ['What about pizza?', 'What about you?'],
    synonyms: ['how about'],
    antonyms: ['no'],
    shortStory: 'What about ice cream for dessert?',
  },
  {
    audioData: [' ', ''],
    word: 'work as sth',
    meaning: ['have job role', 'employed as'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['job role'],
    examples: ['Work as teacher.', 'Works as engineer.'],
    synonyms: ['employed as'],
    antonyms: ['unemployed'],
    shortStory: 'Work as baker spreads morning warmth.',
  },
  {
    audioData: [' ', ''],
    word: 'work for sb/sth',
    meaning: ['employed by person/company', 'job for'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['employed by'],
    examples: ['Work for Google.', 'Works for manager.'],
    synonyms: ['employed by'],
    antonyms: ['self-employed'],
    shortStory: 'Work for family builds lasting security.',
  },
  {
    audioData: [' ', ''],
    word: 'work hard',
    meaning: ['great effort', 'diligent labor'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['effort'],
    examples: ['Students work hard.', 'Work hard daily.'],
    synonyms: ['toil'],
    antonyms: ['slack off'],
    shortStory: 'Work hard transforms dreams to reality.',
  },
  {
    audioData: [' ', ''],
    word: 'work together',
    meaning: ['collaborate', 'team effort'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['team'],
    examples: ['Work together on project.', 'Teams work together.'],
    synonyms: ['collaborate'],
    antonyms: ['work alone'],
    shortStory: 'Work together builds unbreakable bridges.',
  },
  {
    audioData: [' ', ''],
    word: 'work with sb',
    meaning: ['collaborate with person', 'team with'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['team with'],
    examples: ['Work with partner.', 'Works with colleagues.'],
    synonyms: ['collaborate'],
    antonyms: ['work against'],
    shortStory: 'Work with friends sparks best ideas.',
  },
  {
    audioData: [' ', ''],
    word: 'would like',
    meaning: ['polite want', 'desire politely'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['want'],
    examples: ['Would like coffee.', 'I would like help.'],
    synonyms: ['want'],
    antonyms: ["don't want"],
    shortStory: 'Would like one wish granted kindly.',
  },
  {
    audioData: [' ', ''],
    word: 'Would you like…?',
    meaning: ['polite offer', 'want this?'],
    partOfSpeech: ['question'],
    simpleDefinition: ['want?'],
    examples: ['Would you like tea?', 'Would you like help?'],
    synonyms: ['want?'],
    antonyms: ['no thanks'],
    shortStory: 'Would you like magic in your tea?',
  },
  {
    audioData: [' ', ''],
    word: 'X hours a day',
    meaning: ['daily duration', 'time per day'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['daily time'],
    examples: ['8 hours a day.', 'Study 2 hours a day.'],
    synonyms: ['daily'],
    antonyms: ['once a week'],
    shortStory: 'Practice 1 hour a day builds mastery.',
  },
  {
    audioData: [' ', ''],
    word: 'X times a…',
    meaning: ['frequency per period', 'repeated regularly'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['repeated'],
    examples: ['3 times a week.', 'Once a month.'],
    synonyms: ['repeatedly'],
    antonyms: ['never'],
    shortStory: 'Visit twice a year keeps bonds strong.',
  },
  {
    audioData: [' ', ''],
    word: 'X years ago',
    meaning: ['past time period', 'historical'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['past'],
    examples: ['10 years ago.', 'Built 5 years ago.'],
    synonyms: ['back then'],
    antonyms: ['future'],
    shortStory: '100 years ago dragons roamed skies.',
  },
  {
    audioData: [' ', ''],
    word: 'X years later',
    meaning: ['after X years passed', 'future time'],
    partOfSpeech: ['time phrase'],
    simpleDefinition: ['after years'],
    examples: ['10 years later he returned.', 'Years later she remembered.'],
    synonyms: ['afterwards'],
    antonyms: ['right away'],
    shortStory: '20 years later dreams came true.',
  },
  {
    audioData: [' ', ''],
    word: 'X years old',
    meaning: ['specific age', 'age in years'],
    partOfSpeech: ['age phrase'],
    simpleDefinition: ['age'],
    examples: ["I'm 25 years old.", 'Children 5 years old.'],
    synonyms: ['aged'],
    antonyms: ['timeless'],
    shortStory: 'At 10 years old she flew solo.',
  },
  {
    audioData: [' ', ''],
    word: "You're welcome",
    meaning: ['response to thanks', 'no problem'],
    partOfSpeech: ['response'],
    simpleDefinition: ['no problem'],
    examples: ["Thank you! You're welcome.", "You're very welcome."],
    synonyms: ['no problem'],
    antonyms: ['sorry'],
    shortStory: "You're welcome builds warm friendships.",
  },
  {
    audioData: [' ', ''],
    word: 'a bit',
    meaning: ['small amount', 'slightly'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['slightly'],
    examples: ['A bit tired.', 'Wait a bit.'],
    synonyms: ['slightly'],
    antonyms: ['a lot'],
    shortStory: 'A bit of courage changes everything.',
  },
  {
    audioData: [' ', ''],
    word: 'able to do sth',
    meaning: ['have ability/skill', 'capable'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['can'],
    examples: ['Able to swim.', 'Not able to come.'],
    synonyms: ['can'],
    antonyms: ['unable'],
    shortStory: 'Able to dream makes impossible possible.',
  },
  {
    audioData: [' ', ''],
    word: 'a couple of sth',
    meaning: ['two or small number', 'a few'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['two or few'],
    examples: ['A couple of days.', 'A couple of books.'],
    synonyms: ['a few'],
    antonyms: ['many'],
    shortStory: 'A couple of tries won the prize.',
  },
  {
    audioData: [' ', ''],
    word: 'add to sth',
    meaning: ['increase/combine', 'make bigger/better'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['increase'],
    examples: ['Add to the list.', 'Add sugar to tea.'],
    synonyms: ['increase'],
    antonyms: ['subtract'],
    shortStory: 'Add kindness to every conversation.',
  },
  {
    audioData: [' ', ''],
    word: 'again and again',
    meaning: ['repeatedly', 'many times'],
    partOfSpeech: ['adverb phrase'],
    simpleDefinition: ['repeatedly'],
    examples: ['Try again and again.', 'Heard it again and again.'],
    synonyms: ['repeatedly'],
    antonyms: ['once'],
    shortStory: 'Practice again and again brings mastery.',
  },
  {
    audioData: [' ', ''],
    word: 'all about…',
    meaning: ['mainly concerns', 'topic of'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['concerns'],
    examples: ['All about love.', 'Book all about history.'],
    synonyms: ['concerns'],
    antonyms: ['nothing about'],
    shortStory: 'Life all about chasing sunsets.',
  },
  {
    audioData: [' ', ''],
    word: 'all kinds of…',
    meaning: ['various types', 'many different'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['various'],
    examples: ['All kinds of fruits.', 'All kinds of problems.'],
    synonyms: ['various'],
    antonyms: ['one kind'],
    shortStory: 'All kinds of magic fill the forest.',
  },
  {
    audioData: [' ', ''],
    word: 'all over…',
    meaning: ['everywhere on surface/area', 'covering completely'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['everywhere'],
    examples: ['Spots all over face.', 'Mud all over clothes.'],
    synonyms: ['everywhere'],
    antonyms: ['only here'],
    shortStory: 'Stars all over the night sky.',
  },
  {
    audioData: [' ', ''],
    word: 'all sorts of…',
    meaning: ['various types/kinds', 'many different'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['various'],
    examples: ['All sorts of people.', 'All sorts of colors.'],
    synonyms: ['various'],
    antonyms: ['same kind'],
    shortStory: 'All sorts of adventures await.',
  },
  {
    audioData: [' ', ''],
    word: 'all the time',
    meaning: ['continuously', 'always'],
    partOfSpeech: ['adverb phrase'],
    simpleDefinition: ['always'],
    examples: ['Thinks all the time.', 'Rains all the time.'],
    synonyms: ['always'],
    antonyms: ['never'],
    shortStory: 'Love grows all the time quietly.',
  },
  {
    audioData: [' ', ''],
    word: 'a long time ago',
    meaning: ['distant past', 'far in past'],
    partOfSpeech: ['time phrase'],
    simpleDefinition: ['long ago'],
    examples: ['Happened long time ago.', 'Met a long time ago.'],
    synonyms: ['ages ago'],
    antonyms: ['recently'],
    shortStory: 'A long time ago dragons flew.',
  },
  {
    audioData: [' ', ''],
    word: 'a long way',
    meaning: ['great distance', 'far away'],
    partOfSpeech: ['distance phrase'],
    simpleDefinition: ['far'],
    examples: ['Long way to school.', 'Come a long way.'],
    synonyms: ['far'],
    antonyms: ['nearby'],
    shortStory: 'A long way from ordinary dreams.',
  },
  {
    audioData: [' ', ''],
    word: 'a number of sth',
    meaning: ['several items', 'some amount'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['several'],
    examples: ['A number of books.', 'A number of people.'],
    synonyms: ['several'],
    antonyms: ['none'],
    shortStory: 'A number of stars guided sailors.',
  },
  {
    audioData: [' ', ''],
    word: 'apply for sth',
    meaning: ['request formally', 'submit application'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['request'],
    examples: ['Apply for job.', 'Apply for visa.'],
    synonyms: ['request'],
    antonyms: ['reject'],
    shortStory: 'Apply for dreams that seem impossible.',
  },
  {
    audioData: [' ', ''],
    word: 'art gallery',
    meaning: ['building showing art', 'museum'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['art museum'],
    examples: ['Visit art gallery.', 'Paintings in art gallery.'],
    synonyms: ['museum'],
    antonyms: ['empty room'],
    shortStory: 'Art gallery whispers stories silently.',
  },
  {
    audioData: [' ', ''],
    word: 'as a result',
    meaning: ['therefore', 'consequently'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['therefore'],
    examples: ['Studied hard; as a result, passed.'],
    synonyms: ['therefore'],
    antonyms: ['however'],
    shortStory: 'Hard work; as a result, success.',
  },
  {
    audioData: [' ', ''],
    word: 'as soon as',
    meaning: ['immediately when', 'right after'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['immediately'],
    examples: ['As soon as I arrive.', 'Call as soon as possible.'],
    synonyms: ['when'],
    antonyms: ['later'],
    shortStory: 'As soon as dawn breaks, birds sing.',
  },
  {
    audioData: [' ', ''],
    word: 'as well',
    meaning: ['also', 'too'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['also'],
    examples: ['Coffee, and tea as well.', 'Me as well.'],
    synonyms: ['also'],
    antonyms: ['instead'],
    shortStory: 'Sunshine and rainbows as well.',
  },
  {
    audioData: [' ', ''],
    word: 'at first',
    meaning: ['initially', 'beginning'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['initially'],
    examples: ["At first I didn't understand.", 'At first it was hard.'],
    synonyms: ['initially'],
    antonyms: ['later'],
    shortStory: 'At first scared, then discovered joy.',
  },
  {
    audioData: [' ', ''],
    word: 'at least',
    meaning: ['minimum', 'not less than'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['minimum'],
    examples: ['At least try.', 'At least 5 people.'],
    synonyms: ['minimum'],
    antonyms: ['at most'],
    shortStory: 'At least one smile changes everything.',
  },
  {
    audioData: [' ', ''],
    word: 'at the age of…',
    meaning: ['specific age when', 'aged'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['aged'],
    examples: ['At the age of 10.', 'Started at age 5.'],
    synonyms: ['aged'],
    antonyms: ['timeless'],
    shortStory: 'At age 7, she wrote her first book.',
  },
  {
    audioData: [' ', ''],
    word: 'at the start of sth',
    meaning: ['beginning of event', 'initial phase'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['beginning'],
    examples: ['At the start of class.', 'At start of summer.'],
    synonyms: ['initially'],
    antonyms: ['end'],
    shortStory: 'At the start of journeys lie possibilities.',
  },
  {
    audioData: [' ', ''],
    word: 'at the time',
    meaning: ['then', 'back then'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['then'],
    examples: ['At the time I agreed.', 'Young at the time.'],
    synonyms: ['then'],
    antonyms: ['now'],
    shortStory: 'At the time seemed ordinary, now legendary.',
  },
  {
    audioData: [' ', ''],
    word: 'at the time of sth',
    meaning: ['during specific event', 'when sth happened'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['during'],
    examples: ['At the time of birth.', 'At time of war.'],
    synonyms: ['during'],
    antonyms: ['after'],
    shortStory: 'At time of festival, lights shone.',
  },
  {
    audioData: [' ', ''],
    word: 'at the top',
    meaning: ['highest position', 'summit'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['highest'],
    examples: ['Name at the top.', 'Climbed to the top.'],
    synonyms: ['highest'],
    antonyms: ['bottom'],
    shortStory: 'At the top, new horizons appeared.',
  },
  {
    audioData: [' ', ''],
    word: 'based on sth',
    meaning: ['founded on', 'using as foundation'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['using'],
    examples: ['Based on facts.', 'Decision based on evidence.'],
    synonyms: ['using'],
    antonyms: ['regardless'],
    shortStory: 'Based on courage, legends are born.',
  },
  {
    audioData: [' ', ''],
    word: 'be allowed to do sth',
    meaning: ['have permission', 'permitted'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['permitted'],
    examples: ['Allowed to go.', 'Not allowed to smoke.'],
    synonyms: ['permitted'],
    antonyms: ['forbidden'],
    shortStory: 'Allowed to dream makes life magical.',
  },
  {
    audioData: [' ', ''],
    word: 'believe in sb/sth',
    meaning: ['have faith in person/idea', 'trust existence'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['trust'],
    examples: ['Believe in yourself.', 'Believe in magic.'],
    synonyms: ['trust'],
    antonyms: ['doubt'],
    shortStory: 'Believe in dreams makes them real.',
  },
  {
    audioData: [' ', ''],
    word: 'belong to sb',
    meaning: ['owned by person', 'property of'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['owned by'],
    examples: ['This belongs to me.', 'Book belongs to her.'],
    synonyms: ['owned by'],
    antonyms: ['unowned'],
    shortStory: 'The crown belongs to the true heir.',
  },
  {
    audioData: [' ', ''],
    word: 'belong to sth',
    meaning: ['member of group', 'part of organization'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['member'],
    examples: ['Belong to club.', 'Belongs to team.'],
    synonyms: ['member'],
    antonyms: ['outsider'],
    shortStory: 'Stars belong to the night sky.',
  },
  {
    audioData: [' ', ''],
    word: 'be made of sth',
    meaning: ['constructed from material', 'composed of'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['made from'],
    examples: ['Made of wood.', 'Made of dreams.'],
    synonyms: ['composed'],
    antonyms: ['natural'],
    shortStory: 'Champions made of unbreakable spirit.',
  },
  {
    audioData: [' ', ''],
    word: 'by the end of sth',
    meaning: ['before completion', 'final deadline'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['before finish'],
    examples: ['By end of week.', 'By end of summer.'],
    synonyms: ['before'],
    antonyms: ['after'],
    shortStory: "By journey's end wisdom grows.",
  },
  {
    audioData: [' ', ''],
    word: 'care about sth',
    meaning: ['value/concern', 'have interest in'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['value'],
    examples: ['Care about family.', 'Care about environment.'],
    synonyms: ['value'],
    antonyms: ['indifferent'],
    shortStory: 'Care about others builds bridges.',
  },
  {
    audioData: [' ', ''],
    word: 'carry on',
    meaning: ['continue', 'keep going'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['continue'],
    examples: ['Carry on working.', 'Carry on talking.'],
    synonyms: ['continue'],
    antonyms: ['stop'],
    shortStory: 'Carry on despite the pouring rain.',
  },
  {
    audioData: [' ', ''],
    word: 'carry sth out',
    meaning: ['perform task', 'execute'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['perform'],
    examples: ['Carry out plan.', 'Carry out experiment.'],
    synonyms: ['execute'],
    antonyms: ['abandon'],
    shortStory: 'Carry out mission against all odds.',
  },
  {
    audioData: [' ', ''],
    word: 'check in',
    meaning: ['arrive/register at hotel/airport', 'report arrival'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['register'],
    examples: ['Check in at hotel.', 'Check in online.'],
    synonyms: ['register'],
    antonyms: ['check out'],
    shortStory: 'Check in begins new adventures.',
  },
  {
    audioData: [' ', ''],
    word: 'check out',
    meaning: ['leave hotel/pay bill', 'examine'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['leave/examine'],
    examples: ['Check out tomorrow.', 'Check out this book.'],
    synonyms: ['examine'],
    antonyms: ['check in'],
    shortStory: 'Check out hidden gems downtown.',
  },
  {
    audioData: [' ', ''],
    word: 'climate change',
    meaning: ['global temperature rise', 'weather pattern shift'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['warming'],
    examples: ['Climate change affects oceans.', 'Fight climate change now.'],
    synonyms: ['global warming'],
    antonyms: ['stability'],
    shortStory: 'Climate change wakes sleeping giants.',
  },
  {
    audioData: [' ', ''],
    word: 'close to sb/sth',
    meaning: ['near person/place', 'proximate'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['near'],
    examples: ['Close to home.', 'Close to station.'],
    synonyms: ['near'],
    antonyms: ['far'],
    shortStory: 'Close to heart lasts forever.',
  },
  {
    audioData: [' ', ''],
    word: 'come back',
    meaning: ['return', 'arrive again'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['return'],
    examples: ['Come back soon.', 'Memories come back.'],
    synonyms: ['return'],
    antonyms: ['leave'],
    shortStory: 'Wanderers always come back home.',
  },
  {
    audioData: [' ', ''],
    word: 'Come on!',
    meaning: ['encouragement', 'hurry/move'],
    partOfSpeech: ['interjection'],
    simpleDefinition: ['hurry'],
    examples: ['Come on, run!', 'Come on, you can do it!'],
    synonyms: ["let's go"],
    antonyms: ['slow down'],
    shortStory: 'Come on unlocks hidden strength.',
  },
  {
    audioData: [' ', ''],
    word: 'connected to sth',
    meaning: ['linked physically/technically', 'attached'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['linked'],
    examples: ['Connected to internet.', 'Connected to power.'],
    synonyms: ['attached'],
    antonyms: ['disconnected'],
    shortStory: 'Connected to roots grows strongest.',
  },
  {
    audioData: [' ', ''],
    word: 'connected with sb/sth',
    meaning: ['associated/related', 'relationship'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['related'],
    examples: ['Connected with family.', 'Connected with project.'],
    synonyms: ['related'],
    antonyms: ['unrelated'],
    shortStory: 'Connected with purpose finds direction.',
  },
  {
    audioData: [' ', ''],
    word: 'credit card',
    meaning: ['plastic payment card', 'bank card'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['payment card'],
    examples: ['Pay with credit card.', 'Lost credit card.'],
    synonyms: ['plastic'],
    antonyms: ['cash'],
    shortStory: 'Credit card opened world travel doors.',
  },
  {
    audioData: [' ', ''],
    word: 'deal with sb',
    meaning: ['handle person/situation', 'interact with'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['handle person'],
    examples: ['Deal with customers.', 'Deal with boss.'],
    synonyms: ['handle'],
    antonyms: ['ignore'],
    shortStory: 'Deal with kindness wins loyalty.',
  },
  {
    audioData: [' ', ''],
    word: 'deal with sth',
    meaning: ['handle problem/task', 'manage'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['manage'],
    examples: ['Deal with stress.', 'Deal with homework.'],
    synonyms: ['manage'],
    antonyms: ['avoid'],
    shortStory: 'Deal with challenges builds character.',
  },
  {
    audioData: [' ', ''],
    word: 'depend on sb/sth',
    meaning: ['rely on person/thing', 'need'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['rely'],
    examples: ['Depend on friends.', 'Depend on weather.'],
    synonyms: ['rely'],
    antonyms: ['independent'],
    shortStory: 'Depend on courage in dark times.',
  },
  {
    audioData: [' ', ''],
    word: 'depend on sth',
    meaning: ['contingent upon', 'based on condition'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['contingent'],
    examples: ['Depends on time.', 'Depends on money.'],
    synonyms: ['hinges'],
    antonyms: ['certain'],
    shortStory: 'Success depends on daily effort.',
  },
  {
    audioData: [' ', ''],
    word: 'do well',
    meaning: ['succeed', 'perform good'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['succeed'],
    examples: ['Do well in exams.', 'Business does well.'],
    synonyms: ['thrive'],
    antonyms: ['fail'],
    shortStory: 'Do well through persistent practice.',
  },
  {
    audioData: [' ', ''],
    word: 'each one',
    meaning: ['every single', 'individual'],
    partOfSpeech: ['pronoun'],
    simpleDefinition: ['every'],
    examples: ['Each one different.', 'Give each one.'],
    synonyms: ['every'],
    antonyms: ['all together'],
    shortStory: 'Each one holds unique magic.',
  },
  {
    audioData: [' ', ''],
    word: 'end with sth',
    meaning: ['finish with', 'conclude by'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['finish'],
    examples: ['Day ends with sunset.', 'Story ends with moral.'],
    synonyms: ['conclude'],
    antonyms: ['begin'],
    shortStory: 'Journeys end with wisdom gained.',
  },
  {
    audioData: [' ', ''],
    word: 'even more…',
    meaning: ['greater degree', 'additionally'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['greater'],
    examples: ['Even more beautiful.', 'Even more difficult.'],
    synonyms: ['additionally'],
    antonyms: ['less'],
    shortStory: 'Even more stars appeared suddenly.',
  },
  {
    audioData: [' ', ''],
    word: 'everyone else',
    meaning: ['all other people', 'others'],
    partOfSpeech: ['pronoun'],
    simpleDefinition: ['others'],
    examples: ['Better than everyone else.', 'Unlike everyone else.'],
    synonyms: ['others'],
    antonyms: ['me alone'],
    shortStory: 'Everyone else slept; she dreamed.',
  },
  {
    audioData: [' ', ''],
    word: 'except for',
    meaning: ['all but', 'excluding'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['but'],
    examples: ['All except for John.', 'Perfect except for rain.'],
    synonyms: ['but'],
    antonyms: ['including'],
    shortStory: 'Quiet except for cricket song.',
  },
  {
    audioData: [' ', ''],
    word: 'fall in love',
    meaning: ['develop romantic feelings', 'become enamored'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['love'],
    examples: ['Fall in love quickly.', 'They fell in love.'],
    synonyms: ['enamor'],
    antonyms: ['fall out'],
    shortStory: 'Fall in love under starlight.',
  },
  {
    audioData: [' ', ''],
    word: 'fall off',
    meaning: ['drop from position', 'become loose'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['drop'],
    examples: ['Apple fell off tree.', 'Poster fell off wall.'],
    synonyms: ['drop'],
    antonyms: ['hold on'],
    shortStory: 'Leaf fall off signals autumn.',
  },
  {
    audioData: [' ', ''],
    word: 'far away',
    meaning: ['great distance', 'distant'],
    partOfSpeech: ['adverb phrase'],
    simpleDefinition: ['distant'],
    examples: ['Land far away.', 'Stars far away.'],
    synonyms: ['distant'],
    antonyms: ['nearby'],
    shortStory: 'Far away lands call adventurers.',
  },
  {
    audioData: [' ', ''],
    word: 'feel good',
    meaning: ['happy/healthy state', 'positive emotion'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['happy'],
    examples: ['Exercise makes me feel good.', 'I feel good today.'],
    synonyms: ['happy'],
    antonyms: ['feel bad'],
    shortStory: 'Helping others makes you feel good.',
  },
  {
    audioData: [' ', ''],
    word: 'feel like sth',
    meaning: ['want to do/have', 'desire'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['want'],
    examples: ['Feel like pizza.', 'Feel like walking.'],
    synonyms: ['want'],
    antonyms: ["don't want"],
    shortStory: 'Feel like adventure calls quietly.',
  },
  {
    audioData: [' ', ''],
    word: 'fill sth in',
    meaning: ['complete form', 'add information'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['complete'],
    examples: ['Fill in the form.', 'Fill in blanks.'],
    synonyms: ['complete'],
    antonyms: ['leave blank'],
    shortStory: 'Fill in dreams on paper first.',
  },
  {
    audioData: [' ', ''],
    word: 'find it difficult to do sth',
    meaning: ['struggle with task', 'hard to do'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['struggle'],
    examples: [
      'Find it difficult to wake up.',
      'Find it difficult to concentrate.',
    ],
    synonyms: ['struggle'],
    antonyms: ['easy'],
    shortStory: 'Find it difficult but never quit.',
  },
  {
    audioData: [' ', ''],
    word: 'first of all',
    meaning: ['to begin with', 'initially'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['first'],
    examples: ['First of all, sit down.', 'First of all, listen.'],
    synonyms: ['firstly'],
    antonyms: ['finally'],
    shortStory: 'First of all, believe you can.',
  },
  {
    audioData: [' ', ''],
    word: 'focus on sb/sth',
    meaning: ['concentrate attention', 'pay attention'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['concentrate'],
    examples: ['Focus on studies.', 'Focus on goal.'],
    synonyms: ['concentrate'],
    antonyms: ['distracted'],
    shortStory: 'Focus on path ahead steadily.',
  },
  {
    audioData: [' ', ''],
    word: 'followed by sb/sth',
    meaning: ['after/then', 'next comes'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['then'],
    examples: ['A then B followed by C.', 'Rain followed by sunshine.'],
    synonyms: ['then'],
    antonyms: ['before'],
    shortStory: 'Storm followed by rainbow appears.',
  },
  {
    audioData: [' ', ''],
    word: 'for the rest of sth',
    meaning: ['remaining duration', 'until end'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['remaining'],
    examples: ['For the rest of life.', 'For rest of week.'],
    synonyms: ['remaining'],
    antonyms: ['briefly'],
    shortStory: 'For the rest of days happily.',
  },
  {
    audioData: [' ', ''],
    word: 'for this reason',
    meaning: ['therefore', "that's why"],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['therefore'],
    examples: [
      "It's late; for this reason, goodbye.",
      'Rainy; for this reason, stay.',
    ],
    synonyms: ['therefore'],
    antonyms: ['however'],
    shortStory: 'Hard work; for this reason, success.',
  },
  {
    audioData: [' ', ''],
    word: 'get back',
    meaning: ['return home/place', 'come back'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['return'],
    examples: ['Get back soon.', 'Get back to work.'],
    synonyms: ['return'],
    antonyms: ['leave'],
    shortStory: 'Get back to where you belong.',
  },
  {
    audioData: [' ', ''],
    word: 'get better',
    meaning: ['improve health/skill', 'recover'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['improve'],
    examples: ['Get better soon.', 'Skills get better.'],
    synonyms: ['improve'],
    antonyms: ['get worse'],
    shortStory: 'Practice makes everything get better.',
  },
  {
    audioData: [' ', ''],
    word: 'get lost',
    meaning: ['become disoriented', 'lose direction'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['lost'],
    examples: ['I got lost downtown.', "Don't get lost."],
    synonyms: ['lose way'],
    antonyms: ['find way'],
    shortStory: 'Get lost to find yourself.',
  },
  {
    audioData: [' ', ''],
    word: 'get out',
    meaning: ['leave place/vehicle', 'exit'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['leave'],
    examples: ['Get out of car.', 'Get out now!'],
    synonyms: ['exit'],
    antonyms: ['get in'],
    shortStory: 'Get out and explore the world.',
  },
  {
    audioData: [' ', ''],
    word: 'give up',
    meaning: ['stop trying', 'quit/surrender'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['quit'],
    examples: ["Don't give up.", 'Gave up smoking.'],
    synonyms: ['quit'],
    antonyms: ['keep going'],
    shortStory: 'Never give up on your dreams.',
  },
  {
    audioData: [' ', ''],
    word: 'give sth up',
    meaning: ['stop doing/using', 'quit habit'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['quit'],
    examples: ['Give up smoking.', 'Gave up candy.'],
    synonyms: ['quit'],
    antonyms: ['start'],
    shortStory: 'Give up bad habits daily.',
  },
  {
    audioData: [' ', ''],
    word: 'go and…',
    meaning: ['go do something', 'perform action'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['go do'],
    examples: ['Go and eat.', 'Go and see.'],
    synonyms: ['go do'],
    antonyms: ['stay'],
    shortStory: 'Go and chase your dreams.',
  },
  {
    audioData: [' ', ''],
    word: 'go away',
    meaning: ['leave/distance', 'depart'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['leave'],
    examples: ['Go away now.', 'Pain goes away.'],
    synonyms: ['leave'],
    antonyms: ['come'],
    shortStory: 'Go away winter; spring arrives.',
  },
  {
    audioData: [' ', ''],
    word: 'go down',
    meaning: ['descend/move lower', 'decrease'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['descend'],
    examples: ['Prices go down.', 'Sun goes down.'],
    synonyms: ['decrease'],
    antonyms: ['go up'],
    shortStory: 'Sun goes down; stars awaken.',
  },
  {
    audioData: [' ', ''],
    word: 'go down sth',
    meaning: ['travel down path/stairs', 'descend'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['descend path'],
    examples: ['Go down stairs.', 'Go down hill.'],
    synonyms: ['descend'],
    antonyms: ['go up'],
    shortStory: 'Go down the mysterious cave.',
  },
  {
    audioData: [' ', ''],
    word: 'go for sth',
    meaning: ['choose/attempt', 'try for'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['choose'],
    examples: ['Go for gold.', 'Go for pizza.'],
    synonyms: ['choose'],
    antonyms: ['reject'],
    shortStory: 'Go for dreams fearlessly.',
  },
  {
    audioData: [' ', ''],
    word: 'go up',
    meaning: ['ascend/increase', 'rise'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['rise'],
    examples: ['Prices go up.', 'Go up stairs.'],
    synonyms: ['increase'],
    antonyms: ['go down'],
    shortStory: 'Balloons go up into sky.',
  },
  {
    audioData: [' ', ''],
    word: 'good luck',
    meaning: ['wishing success', 'best wishes'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['success'],
    examples: ['Good luck exam!', 'Good luck tomorrow.'],
    synonyms: ['best wishes'],
    antonyms: ['bad luck'],
    shortStory: 'Good luck opens opportunity doors.',
  },
  {
    audioData: [' ', ''],
    word: 'happen to sb/sth',
    meaning: ['experience event', 'occur to'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['experience'],
    examples: ['What happened to you?', 'It happened to car.'],
    synonyms: ['occur'],
    antonyms: ['planned'],
    shortStory: 'Magic happens to dreamers.',
  },
  {
    audioData: [' ', ''],
    word: 'happy with sb/sth',
    meaning: ['satisfied/pleased with', 'content'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['pleased'],
    examples: ['Happy with results.', 'Happy with teacher.'],
    synonyms: ['pleased'],
    antonyms: ['unhappy'],
    shortStory: 'Happy with small daily victories.',
  },
  {
    audioData: [' ', ''],
    word: 'have a look',
    meaning: ['examine briefly', 'check'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['check'],
    examples: ['Have a look here.', 'Let me have a look.'],
    synonyms: ['check'],
    antonyms: ['ignore'],
    shortStory: 'Have a look reveals hidden beauty.',
  },
  {
    audioData: [' ', ''],
    word: 'have got to',
    meaning: ['must/obligation', 'have to'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['must'],
    examples: ["I've got to go.", 'You got to study.'],
    synonyms: ['must'],
    antonyms: ["don't have to"],
    shortStory: 'Got to try before giving up.',
  },
  {
    audioData: [' ', ''],
    word: 'Have you ever…?',
    meaning: ['past experience question', 'lifetime experience'],
    partOfSpeech: ['question'],
    simpleDefinition: ['experienced?'],
    examples: ['Have you ever been to Paris?', 'Have you ever tried sushi?'],
    synonyms: ['tried?'],
    antonyms: ['never'],
    shortStory: 'Have you ever chased a real rainbow?',
  },
  {
    audioData: [' ', ''],
    word: 'health problems',
    meaning: ['medical issues', 'illness conditions'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['illness'],
    examples: ['Serious health problems.', 'Minor health problems.'],
    synonyms: ['illness'],
    antonyms: ['good health'],
    shortStory: 'Health problems teach true strength.',
  },
  {
    audioData: [' ', ''],
    word: 'hear about sb/sth',
    meaning: ['learn of person/thing', 'get news'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['learn'],
    examples: ['Heard about the party.', 'Heard about her success.'],
    synonyms: ['learn'],
    antonyms: ['ignore'],
    shortStory: 'Heard about magic mountain secrets.',
  },
  {
    audioData: [' ', ''],
    word: "I don't care",
    meaning: ['uninterested', 'no concern'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['indifferent'],
    examples: [
      "I don't care what they say.",
      "Do what you want; I don't care.",
    ],
    synonyms: ['whatever'],
    antonyms: ['I care'],
    shortStory: "I don't care; I'm dancing anyway.",
  },
  {
    audioData: [' ', ''],
    word: 'if necessary',
    meaning: ['when needed', 'only if required'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['when needed'],
    examples: ['Call if necessary.', 'Change plans if necessary.'],
    synonyms: ['if needed'],
    antonyms: ['always'],
    shortStory: 'Help arrives if necessary only.',
  },
  {
    audioData: [' ', ''],
    word: 'if you want to',
    meaning: ['optional choice', 'your decision'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['optional'],
    examples: ['Come if you want to.', 'Leave if you want to.'],
    synonyms: ['optional'],
    antonyms: ['must'],
    shortStory: 'Fly if you want to soar.',
  },
  {
    audioData: [' ', ''],
    word: 'I guess',
    meaning: ['uncertain opinion', 'probably'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['probably'],
    examples: ['I guess so.', 'Maybe, I guess.'],
    synonyms: ['probably'],
    antonyms: ['certain'],
    shortStory: 'I guess stars whisper secrets nightly.',
  },
  {
    audioData: [' ', ''],
    word: "I'm afraid…",
    meaning: ['bad news politely', 'regretful statement'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['bad news'],
    examples: ["I'm afraid I can't.", "I'm afraid it's broken."],
    synonyms: ['sorry'],
    antonyms: ['good news'],
    shortStory: "I'm afraid the dragon ate cake.",
  },
  {
    audioData: [' ', ''],
    word: 'I mean',
    meaning: ['clarify/correct', 'actually'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['actually'],
    examples: ['Not bad, I mean good.', 'I mean, yes definitely.'],
    synonyms: ['actually'],
    antonyms: ['never mind'],
    shortStory: 'I mean, magic exists quietly.',
  },
  {
    audioData: [' ', ''],
    word: 'in business',
    meaning: ['commerce world', 'professional work'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['commerce'],
    examples: ['In business 20 years.', 'Secrets in business.'],
    synonyms: ['commerce'],
    antonyms: ['personal'],
    shortStory: 'In business honesty builds empires.',
  },
  {
    audioData: [' ', ''],
    word: 'in danger',
    meaning: ['threatened', 'at risk'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['threatened'],
    examples: ['Animals in danger.', 'In danger of failing.'],
    synonyms: ['at risk'],
    antonyms: ['safe'],
    shortStory: 'Heroes rescue those in danger.',
  },
  {
    audioData: [' ', ''],
    word: 'in history',
    meaning: ['historical record', 'past events'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['historical'],
    examples: ['Important in history.', 'Moment in history.'],
    synonyms: ['historical'],
    antonyms: ['future'],
    shortStory: 'Greatest discovery in history.',
  },
  {
    audioData: [' ', ''],
    word: 'in hospital',
    meaning: ['hospitalized', 'medical treatment'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['hospitalized'],
    examples: ["She's in hospital.", 'Visit him in hospital.'],
    synonyms: ['hospitalized'],
    antonyms: ['at home'],
    shortStory: 'Recovery begins in hospital beds.',
  },
  {
    audioData: [' ', ''],
    word: 'in love',
    meaning: ['romantic feelings', 'enamored'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['enamored'],
    examples: ['In love forever.', 'Clearly in love.'],
    synonyms: ['enamored'],
    antonyms: ['heartbroken'],
    shortStory: 'In love under moonlit skies.',
  },
  {
    audioData: [' ', ''],
    word: 'in prison',
    meaning: ['incarcerated', 'jailed'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['jailed'],
    examples: ["He's in prison.", 'Life in prison.'],
    synonyms: ['jailed'],
    antonyms: ['free'],
    shortStory: 'In prison minds sometimes escape.',
  },
  {
    audioData: [' ', ''],
    word: 'in some cases',
    meaning: ['sometimes', 'occasionally'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['sometimes'],
    examples: ['In some cases yes.', 'Works in some cases.'],
    synonyms: ['sometimes'],
    antonyms: ['always'],
    shortStory: 'Magic works in some cases.',
  },
  {
    audioData: [' ', ''],
    word: 'instead of',
    meaning: ['in place of', 'rather than'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['rather'],
    examples: ['Tea instead of coffee.', 'Walk instead of drive.'],
    synonyms: ['rather'],
    antonyms: ['as well as'],
    shortStory: 'Choose love instead of fear.',
  },
  {
    audioData: [' ', ''],
    word: 'in the air',
    meaning: ['atmosphere', 'floating'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['floating'],
    examples: ['Music in the air.', 'Tension in the air.'],
    synonyms: ['floating'],
    antonyms: ['on ground'],
    shortStory: 'Magic hangs in the air.',
  },
  {
    audioData: [' ', ''],
    word: 'in the end',
    meaning: ['finally', 'ultimately'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['finally'],
    examples: ['In the end, happy.', 'Won in the end.'],
    synonyms: ['finally'],
    antonyms: ['beginning'],
    shortStory: 'In the end, love always wins.',
  },
  {
    audioData: [' ', ''],
    word: 'in the middle',
    meaning: ['central position', 'center'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['center'],
    examples: ['In the middle of road.', 'Middle of night.'],
    synonyms: ['center'],
    antonyms: ['edge'],
    shortStory: 'Truth lies in the middle.',
  },
  {
    audioData: [' ', ''],
    word: 'in the same way',
    meaning: ['similarly', 'like that also'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['similarly'],
    examples: ['Works here; in the same way there.', 'Do it in the same way.'],
    synonyms: ['similarly'],
    antonyms: ['differently'],
    shortStory: 'Birds fly; fish swim in the same way.',
  },
  {
    audioData: [' ', ''],
    word: 'in this way',
    meaning: ['thus', 'by this method'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['thus'],
    examples: [
      'Study daily; succeed in this way.',
      'Solve problems in this way.',
    ],
    synonyms: ['thus'],
    antonyms: ['another way'],
    shortStory: 'Practice daily; master grows in this way.',
  },
  {
    audioData: [' ', ''],
    word: 'it depends',
    meaning: ['contingent on situation', 'not certain'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['maybe'],
    examples: ['Will you come? It depends.', 'Cost? It depends.'],
    synonyms: ['maybe'],
    antonyms: ['certain'],
    shortStory: 'Rain tomorrow? It depends on clouds.',
  },
  {
    audioData: [' ', ''],
    word: 'I think so',
    meaning: ['probably yes', 'believe true'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['probably'],
    examples: ['Will it rain? I think so.', 'Is he coming? I think so.'],
    synonyms: ['probably'],
    antonyms: ["I don't think so"],
    shortStory: 'Magic exists; I think so firmly.',
  },
  {
    audioData: [' ', ''],
    word: 'lead to sth',
    meaning: ['cause/result in', 'produce'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['cause'],
    examples: ['Study leads to success.', 'Laziness leads to failure.'],
    synonyms: ['cause'],
    antonyms: ['prevent'],
    shortStory: 'Kindness leads to warm friendships.',
  },
  {
    audioData: [' ', ''],
    word: 'less than…',
    meaning: ['smaller amount/number', 'under'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['under'],
    examples: ['Less than 10 people.', 'Less than $20.'],
    synonyms: ['under'],
    antonyms: ['more than'],
    shortStory: 'Less than perfect proves most beautiful.',
  },
  {
    audioData: [' ', ''],
    word: 'Let me…',
    meaning: ['allow me to', 'offer help'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['allow me'],
    examples: ['Let me help.', 'Let me explain.'],
    synonyms: ['allow me'],
    antonyms: ["don't"],
    shortStory: 'Let me carry that heavy load.',
  },
  {
    audioData: [' ', ''],
    word: 'let me know',
    meaning: ['tell me later', 'inform me'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['tell me'],
    examples: ['Decision made? Let me know.', 'Coming? Let me know.'],
    synonyms: ['tell me'],
    antonyms: ['keep secret'],
    shortStory: 'Found treasure? Let me know.',
  },
  {
    audioData: [' ', ''],
    word: 'look after sb/sth/yourself',
    meaning: ['care for/protect', 'take care'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['care for'],
    examples: ['Look after baby.', 'Look after yourself.'],
    synonyms: ['care for'],
    antonyms: ['neglect'],
    shortStory: 'Look after dreams tenderly daily.',
  },
  {
    audioData: [' ', ''],
    word: 'look back at sth',
    meaning: ['remember past', 'reflect'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['remember'],
    examples: ['Look back at childhood.', 'Look back at last year.'],
    synonyms: ['reflect'],
    antonyms: ['look forward'],
    shortStory: 'Look back reveals growth made.',
  },
  {
    audioData: [' ', ''],
    word: 'look sth up',
    meaning: ['search for information', 'research'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['research'],
    examples: ['Look up the word.', 'Look up train times.'],
    synonyms: ['research'],
    antonyms: ['ignore'],
    shortStory: 'Look up reveals hidden knowledge.',
  },
  {
    audioData: [' ', ''],
    word: 'make a mistake',
    meaning: ['do something wrong', 'error'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['error'],
    examples: ['Everyone makes mistakes.', 'I made a mistake.'],
    synonyms: ['err'],
    antonyms: ['correct'],
    shortStory: 'Make mistakes; learn from them.',
  },
  {
    audioData: [' ', ''],
    word: 'make money',
    meaning: ['earn income', 'profit'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['earn'],
    examples: ['Business makes money.', 'Work to make money.'],
    synonyms: ['earn'],
    antonyms: ['lose money'],
    shortStory: 'Make money through honest work.',
  },
  {
    audioData: [' ', ''],
    word: 'make sense',
    meaning: ['logical', 'understandable'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['logical'],
    examples: ['That makes sense.', 'Plan makes sense.'],
    synonyms: ['logical'],
    antonyms: ['nonsense'],
    shortStory: 'Truth always makes sense eventually.',
  },
  {
    audioData: [' ', ''],
    word: 'make sure',
    meaning: ['verify/confirm', 'check'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['check'],
    examples: ['Make sure door locked.', 'Make sure you understand.'],
    synonyms: ['verify'],
    antonyms: ['assume'],
    shortStory: 'Make sure before leaping forward.',
  },
  {
    audioData: [' ', ''],
    word: 'much better',
    meaning: ['significantly improved', 'greatly superior'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['greatly improved'],
    examples: ['Feeling much better.', 'Much better than before.'],
    synonyms: ['vastly improved'],
    antonyms: ['much worse'],
    shortStory: 'Practice makes much better results.',
  },
  {
    audioData: [' ', ''],
    word: 'not at all',
    meaning: ['no', 'not even slightly'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['no'],
    examples: ['Not at all tired.', 'Not at all, thank you.'],
    synonyms: ['no'],
    antonyms: ['yes'],
    shortStory: 'Not at all difficult for experts.',
  },
  {
    audioData: [' ', ''],
    word: 'no way',
    meaning: ['impossible', 'absolutely not'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['impossible'],
    examples: ["No way that's true.", "No way I'm doing that."],
    synonyms: ['impossible'],
    antonyms: ['possible'],
    shortStory: 'No way beats impossible odds.',
  },
  {
    audioData: [' ', ''],
    word: 'Oh dear',
    meaning: ['mild dismay/surprise', 'concern'],
    partOfSpeech: ['interjection'],
    simpleDefinition: ['oh no'],
    examples: ["Oh dear, it's late.", 'Oh dear, you forgot.'],
    synonyms: ['oh no'],
    antonyms: ['oh yes'],
    shortStory: 'Oh dear, the cake burned slightly.',
  },
  {
    audioData: [' ', ''],
    word: 'Oh well',
    meaning: ['acceptance/resignation', 'never mind'],
    partOfSpeech: ['interjection'],
    simpleDefinition: ['never mind'],
    examples: ['Oh well, next time.', 'Failed? Oh well.'],
    synonyms: ['never mind'],
    antonyms: ['oh great'],
    shortStory: 'Oh well, tomorrow brings new chances.',
  },
  {
    audioData: [' ', ''],
    word: 'on earth',
    meaning: ['in the world', 'ever'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['ever'],
    examples: ['Best on earth.', 'What on earth happened?'],
    synonyms: ['ever'],
    antonyms: ['in space'],
    shortStory: 'Happiest place on earth exists.',
  },
  {
    audioData: [' ', ''],
    word: 'on the ground',
    meaning: ['floor level', 'earth surface'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['floor'],
    examples: ['Sit on the ground.', 'Fallen on the ground.'],
    synonyms: ['floor level'],
    antonyms: ['in the air'],
    shortStory: 'Roots grow strong on the ground.',
  },
  {
    audioData: [' ', ''],
    word: 'on the other side',
    meaning: ['opposite location', 'across from'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['opposite'],
    examples: ['House on other side.', 'Friends on other side.'],
    synonyms: ['across'],
    antonyms: ['same side'],
    shortStory: 'Treasure waits on other side.',
  },
  {
    audioData: [' ', ''],
    word: 'on the wall',
    meaning: ['wall surface', 'hanging/mounted'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['wall'],
    examples: ['Picture on the wall.', 'Clock on wall.'],
    synonyms: ['mounted'],
    antonyms: ['on floor'],
    shortStory: 'Memories hang on the wall.',
  },
  {
    audioData: [' ', ''],
    word: 'on time',
    meaning: ['punctual', 'not late'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['punctual'],
    examples: ['Arrive on time.', 'Train on time.'],
    synonyms: ['punctual'],
    antonyms: ['late'],
    shortStory: 'On time catches every opportunity.',
  },
  {
    audioData: [' ', ''],
    word: 'on top of sth/sb',
    meaning: ['above/upon surface', 'uppermost'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['above'],
    examples: ['Book on top of table.', 'Snow on top of mountain.'],
    synonyms: ['atop'],
    antonyms: ['under'],
    shortStory: 'Stars shine on top of world.',
  },
  {
    audioData: [' ', ''],
    word: 'one or two',
    meaning: ['very few', 'a couple'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['few'],
    examples: ['One or two problems.', 'One or two friends.'],
    synonyms: ['a couple'],
    antonyms: ['many'],
    shortStory: 'One or two true friends matter.',
  },
  {
    audioData: [' ', ''],
    word: 'ordinary people',
    meaning: ['average citizens', 'common folk'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['average'],
    examples: ['Ordinary people achieve greatness.', 'Help ordinary people.'],
    synonyms: ['common folk'],
    antonyms: ['celebrities'],
    shortStory: 'Ordinary people change history quietly.',
  },
  {
    audioData: [' ', ''],
    word: 'pay attention',
    meaning: ['concentrate', 'listen carefully'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['concentrate'],
    examples: ['Pay attention in class.', 'Pay attention now.'],
    synonyms: ['listen'],
    antonyms: ['ignore'],
    shortStory: 'Pay attention reveals hidden wonders.',
  },
  {
    audioData: [' ', ''],
    word: 'per hour',
    meaning: ['hourly rate', 'each hour'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['hourly'],
    examples: ['$20 per hour.', 'Runs 10km per hour.'],
    synonyms: ['hourly'],
    antonyms: ['per day'],
    shortStory: 'Knowledge grows per hour steadily.',
  },
  {
    audioData: [' ', ''],
    word: 'pick sb/sth up',
    meaning: ['lift/collect', 'fetch or grab'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['collect'],
    examples: ['Pick up mail.', 'Pick up kids.'],
    synonyms: ['collect'],
    antonyms: ['drop'],
    shortStory: 'Pick up courage when it falls.',
  },
  {
    audioData: [' ', ''],
    word: 'police officer',
    meaning: ['law enforcement agent', 'cop'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['cop'],
    examples: ['Police officer helps.', 'Talk to police officer.'],
    synonyms: ['cop'],
    antonyms: ['criminal'],
    shortStory: 'Police officer saves the day.',
  },
  {
    audioData: [' ', ''],
    word: 'police station',
    meaning: ['police headquarters', 'station house'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['police HQ'],
    examples: ['Go to police station.', 'Lost items at police station.'],
    synonyms: ['station'],
    antonyms: ['home'],
    shortStory: 'Police station protects neighborhood.',
  },
  {
    audioData: [' ', ''],
    word: 'public transport',
    meaning: ['buses/trains', 'mass transit'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['bus/train'],
    examples: ['Use public transport.', 'Public transport delayed.'],
    synonyms: ['transit'],
    antonyms: ['car'],
    shortStory: 'Public transport connects communities.',
  },
  {
    audioData: [' ', ''],
    word: 'put sth on',
    meaning: ['wear clothing', 'dress'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['wear'],
    examples: ['Put on jacket.', 'Put on shoes.'],
    synonyms: ['wear'],
    antonyms: ['take off'],
    shortStory: 'Put on smile before leaving home.',
  },
  {
    audioData: [' ', ''],
    word: 'quite a lot',
    meaning: ['considerable amount', 'many/much'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['many'],
    examples: ['Quite a lot of rain.', 'Quite a lot of work.'],
    synonyms: ['plenty'],
    antonyms: ['a little'],
    shortStory: 'Quite a lot of courage needed.',
  },
  {
    audioData: [' ', ''],
    word: 'reasons why',
    meaning: ['explanations for cause', 'causes'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['causes'],
    examples: ['Reasons why it failed.', 'Main reasons why.'],
    synonyms: ['causes'],
    antonyms: ['results'],
    shortStory: 'Reasons why stars shine revealed.',
  },
  {
    audioData: [' ', ''],
    word: 'refer to sb/sth',
    meaning: ['mention/call by name', 'indicate'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['mention'],
    examples: ['Refer to the book.', 'Refer to teacher.'],
    synonyms: ['mention'],
    antonyms: ['ignore'],
    shortStory: 'Refer to wisdom of elders.',
  },
  {
    audioData: [' ', ''],
    word: 'report on sth',
    meaning: ['give account of', 'describe event'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['describe'],
    examples: ['Report on weather.', 'Report on progress.'],
    synonyms: ['describe'],
    antonyms: ['hide'],
    shortStory: 'Report on magical discoveries.',
  },
  {
    audioData: [' ', ''],
    word: 'respond to sth/sb',
    meaning: ['reply/react', 'answer'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['reply'],
    examples: ['Respond to email.', 'Respond to question.'],
    synonyms: ['reply'],
    antonyms: ['ignore'],
    shortStory: "Respond to heart's true calling.",
  },
  {
    audioData: [' ', ''],
    word: 'save money',
    meaning: ['keep for future', 'not spend'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['save'],
    examples: ['Save money monthly.', 'Save for vacation.'],
    synonyms: ['save'],
    antonyms: ['spend'],
    shortStory: 'Save money for dream journeys.',
  },
  {
    audioData: [' ', ''],
    word: 'science fiction',
    meaning: ['future/speculative stories', 'sci-fi'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['sci-fi'],
    examples: ['Love science fiction.', 'Science fiction movies.'],
    synonyms: ['sci-fi'],
    antonyms: ['reality'],
    shortStory: 'Science fiction predicts tomorrow.',
  },
  {
    audioData: [' ', ''],
    word: 'search for sth/sb',
    meaning: ['look actively', 'hunt'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['hunt'],
    examples: ['Search for keys.', 'Search for treasure.'],
    synonyms: ['hunt'],
    antonyms: ['find'],
    shortStory: 'Search for truth leads home.',
  },
  {
    audioData: [' ', ''],
    word: 'so that…',
    meaning: ['in order to/purpose', 'for this reason'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['purpose'],
    examples: ['Study so that you pass.', 'Save so that you travel.'],
    synonyms: ['to'],
    antonyms: ['although'],
    shortStory: 'Practice so that you master.',
  },
  {
    audioData: [' ', ''],
    word: 'solution to sth',
    meaning: ['answer to problem', 'fix'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['answer'],
    examples: ['Solution to math problem.', 'Solution to conflict.'],
    synonyms: ['fix'],
    antonyms: ['problem'],
    shortStory: 'Solution hides in plain sight.',
  },
  {
    audioData: [' ', ''],
    word: 'sort of sth',
    meaning: ['kind/type of', 'somewhat'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['kind'],
    examples: ['Sort of car.', 'Sort of person.'],
    synonyms: ['type'],
    antonyms: ['unique'],
    shortStory: 'Sort of magic changes everything.',
  },
  {
    audioData: [' ', ''],
    word: 'sound like sb/sth',
    meaning: ['resemble in sound', 'seem like'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['seem'],
    examples: ['Sounds like rain.', 'Sounds like trouble.'],
    synonyms: ['seem'],
    antonyms: ['unlike'],
    shortStory: 'Sounds like adventure calling.',
  },
];
