export const PageThreeOfPhrase = [
  {
    audioData: [' ', ''],
    word: 'start with sb/sth',
    meaning: ['begin using person/thing', 'commence with'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['begin'],
    examples: ['Start with basics.', 'Recipe starts with onions.'],
    synonyms: ['begin'],
    antonyms: ['end'],
    shortStory: 'Start with smile changes day.',
  },
  {
    audioData: [' ', ''],
    word: 'such a/an…',
    meaning: ['remarkable degree', 'so much'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['so much'],
    examples: ['Such a beautiful day.', 'Such an honor.'],
    synonyms: ['so'],
    antonyms: ['ordinary'],
    shortStory: 'Such a magical moment appeared.',
  },
  {
    audioData: [' ', ''],
    word: 'take care of sb/sth/yourself',
    meaning: ['look after/protect', 'care for'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['care for'],
    examples: ['Take care of baby.', 'Take care of yourself.'],
    synonyms: ['look after'],
    antonyms: ['neglect'],
    shortStory: 'Take care of dreams daily.',
  },
  {
    audioData: [' ', ''],
    word: 'take off',
    meaning: ['aircraft leave ground', 'remove clothing'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['fly/undress'],
    examples: ['Plane takes off.', 'Take off shoes.'],
    synonyms: ['depart'],
    antonyms: ['land'],
    shortStory: 'Dreams take off into sky.',
  },
  {
    audioData: [' ', ''],
    word: 'take sth off',
    meaning: ['remove clothing/item', 'deduct'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['remove'],
    examples: ['Take off jacket.', 'Take off price.'],
    synonyms: ['remove'],
    antonyms: ['put on'],
    shortStory: 'Take off worries; fly free.',
  },
  {
    audioData: [' ', ''],
    word: 'take part',
    meaning: ['participate/join', 'be involved'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['join'],
    examples: ['Take part in race.', 'Students take part.'],
    synonyms: ['participate'],
    antonyms: ['watch'],
    shortStory: 'Take part creates best memories.',
  },

  {
    audioData: [' ', ''],
    word: 'take place',
    meaning: ['happen/occur', 'event happens'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['happen'],
    examples: ['Party takes place Saturday.', 'Meeting takes place.'],
    synonyms: ['occur'],
    antonyms: ['cancelled'],
    shortStory: 'Magic takes place quietly.',
  },

  {
    audioData: [' ', ''],
    word: 'the best thing',
    meaning: ['most positive aspect', 'greatest advantage'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['greatest'],
    examples: ['Best thing about summer.', 'The best thing happened.'],
    synonyms: ['greatest'],
    antonyms: ['worst'],
    shortStory: 'The best thing: friendship found.',
  },

  {
    audioData: [' ', ''],
    word: 'the first thing',
    meaning: ['initial action', 'priority'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['first'],
    examples: ['First thing in morning.', 'The first thing to do.'],
    synonyms: ['priority'],
    antonyms: ['last'],
    shortStory: 'First thing: believe you can.',
  },

  {
    audioData: [' ', ''],
    word: 'the following…',
    meaning: ['what comes next', 'subsequently'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['next'],
    examples: ['The following day.', 'Read the following.'],
    synonyms: ['next'],
    antonyms: ['previous'],
    shortStory: 'The following dawn brings hope.',
  },

  {
    audioData: [' ', ''],
    word: 'the important thing',
    meaning: ['essential aspect', 'key point'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['essential'],
    examples: ['Important thing is safety.', 'The important thing first.'],
    synonyms: ['key'],
    antonyms: ['trivial'],
    shortStory: 'Important thing: never give up.',
  },

  {
    audioData: [' ', ''],
    word: 'the other side of sth',
    meaning: ['opposite aspect', 'alternative view'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['opposite'],
    examples: ['Other side of mountain.', 'Other side of story.'],
    synonyms: ['opposite'],
    antonyms: ['same'],
    shortStory: 'Other side holds the treasure.',
  },

  {
    audioData: [' ', ''],
    word: 'the rest of sth',
    meaning: ['remaining part', "what's left"],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['remaining'],
    examples: ['Rest of cake.', 'Rest of journey.'],
    synonyms: ['remainder'],
    antonyms: ['beginning'],
    shortStory: 'Rest of story proves magical.',
  },

  {
    audioData: [' ', ''],
    word: 'these days',
    meaning: ['currently', 'nowadays'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['now'],
    examples: ['These days busy.', 'People these days.'],
    synonyms: ['nowadays'],
    antonyms: ['before'],
    shortStory: 'These days dreams grow faster.',
  },

  {
    audioData: [' ', ''],
    word: 'they say…',
    meaning: ['common belief', 'rumor/general opinion'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['rumor'],
    examples: ["They say it's true.", 'They say rain coming.'],
    synonyms: ['rumor'],
    antonyms: ['fact'],
    shortStory: 'They say magic lives here.',
  },

  {
    audioData: [' ', ''],
    word: 'throw sth away',
    meaning: ['discard', 'get rid of'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['discard'],
    examples: ['Throw away trash.', "Don't throw away food."],
    synonyms: ['discard'],
    antonyms: ['keep'],
    shortStory: 'Throw away doubt; keep hope.',
  },

  {
    audioData: [' ', ''],
    word: 'turn sth off',
    meaning: ['stop device functioning', 'switch off'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['switch off'],
    examples: ['Turn off light.', 'Turn off computer.'],
    synonyms: ['switch off'],
    antonyms: ['turn on'],
    shortStory: 'Turn off worries; sleep peacefully.',
  },

  {
    audioData: [' ', ''],
    word: 'turn sth on',
    meaning: ['start device functioning', 'switch on'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['switch on'],
    examples: ['Turn on TV.', 'Turn on heater.'],
    synonyms: ['switch on'],
    antonyms: ['turn off'],
    shortStory: 'Turn on imagination; worlds appear.',
  },

  {
    audioData: [' ', ''],
    word: 'up and down',
    meaning: ['vertical movement', 'back and forth'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['vertical'],
    examples: ['Jump up and down.', 'Pacing up and down.'],
    synonyms: ['vertical'],
    antonyms: ['still'],
    shortStory: 'Heart beats up and down excitedly.',
  },

  {
    audioData: [' ', ''],
    word: 'Why not…?',
    meaning: ['suggestion', 'good idea'],
    partOfSpeech: ['question'],
    simpleDefinition: ['good idea'],
    examples: ['Why not try?', 'Why not go?'],
    synonyms: ["let's"],
    antonyms: ['no'],
    shortStory: 'Why not chase that rainbow?',
  },

  {
    audioData: [' ', ''],
    word: 'work out',
    meaning: ['exercise', 'solve problem'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['exercise/solve'],
    examples: ['Work out daily.', 'Problems work out.'],
    synonyms: ['exercise'],
    antonyms: ['give up'],
    shortStory: 'Plans work out perfectly.',
  },

  {
    audioData: [' ', ''],
    word: 'worried about sb/sth',
    meaning: ['anxious/concerned', 'nervous for'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['anxious'],
    examples: ['Worried about exam.', 'Worried about you.'],
    synonyms: ['anxious'],
    antonyms: ['calm'],
    shortStory: 'Worried about storm passing.',
  },

  {
    audioData: [' ', ''],
    word: 'would love to do sth',
    meaning: ['really want to', 'eager desire'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['really want'],
    examples: ['Would love to travel.', 'Would love to help.'],
    synonyms: ['love to'],
    antonyms: ['would hate'],
    shortStory: 'Would love to see stars fall.',
  },

  {
    audioData: [' ', ''],
    word: 'write sth down',
    meaning: ['record in writing', 'note'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['note'],
    examples: ['Write down address.', 'Write down ideas.'],
    synonyms: ['note'],
    antonyms: ['forget'],
    shortStory: 'Write down dreams before waking.',
  },

  {
    audioData: [' ', ''],
    word: 'a bit more',
    meaning: ['slightly additional', 'little extra'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['extra'],
    examples: ['A bit more time.', 'A bit more sugar.'],
    synonyms: ['extra'],
    antonyms: ['less'],
    shortStory: 'A bit more courage wins battles.',
  },

  {
    audioData: [' ', ''],
    word: 'a bit of sth',
    meaning: ['small amount', 'tiny portion'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['tiny bit'],
    examples: ['A bit of luck.', 'A bit of fun.'],
    synonyms: ['tiny bit'],
    antonyms: ['a lot'],
    shortStory: 'A bit of magic changes everything.',
  },

  {
    audioData: [' ', ''],
    word: 'access to sth',
    meaning: ['permission/ability to use', 'entry'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['entry'],
    examples: ['Access to internet.', 'Access to library.'],
    synonyms: ['entry'],
    antonyms: ['blocked'],
    shortStory: 'Access to wisdom opens doors.',
  },

  {
    audioData: [' ', ''],
    word: 'after all',
    meaning: ['considering circumstances', 'ultimately'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['ultimately'],
    examples: ["After all, you're right.", "It's true after all."],
    synonyms: ['ultimately'],
    antonyms: ['before'],
    shortStory: 'After all, love conquers fear.',
  },

  {
    audioData: [' ', ''],
    word: 'a great deal',
    meaning: ['large amount', 'considerably'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['much'],
    examples: ['A great deal of work.', 'Improved a great deal.'],
    synonyms: ['much'],
    antonyms: ['little'],
    shortStory: 'Learned a great deal daily.',
  },

  {
    audioData: [' ', ''],
    word: 'aim to do sth',
    meaning: ['intend/target', 'plan to achieve'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['intend'],
    examples: ['Aim to succeed.', 'Aim to finish today.'],
    synonyms: ['intend'],
    antonyms: ['avoid'],
    shortStory: 'Aim high; touch the stars.',
  },

  {
    audioData: [' ', ''],
    word: 'a kind of…',
    meaning: ['type/sort of', 'category'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['type'],
    examples: ['A kind of fruit.', 'A kind of magic.'],
    synonyms: ['type'],
    antonyms: ['specific'],
    shortStory: 'A kind of magic fills the air.',
  },

  {
    audioData: [' ', ''],
    word: 'a little bit',
    meaning: ['small amount', 'slightly'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['slightly'],
    examples: ['A little bit tired.', 'A little bit more.'],
    synonyms: ['slightly'],
    antonyms: ['a lot'],
    shortStory: 'A little bit of faith moves mountains.',
  },

  {
    audioData: [' ', ''],
    word: 'a little more',
    meaning: ['slightly additional', 'small extra'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['extra'],
    examples: ['A little more time.', 'A little more effort.'],
    synonyms: ['extra'],
    antonyms: ['less'],
    shortStory: 'A little more kindness heals wounds.',
  },

  {
    audioData: [' ', ''],
    word: 'along with sb/sth',
    meaning: ['together with', 'in addition'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['with'],
    examples: ['Coffee along with cake.', 'Friends along with family.'],
    synonyms: ['with'],
    antonyms: ['without'],
    shortStory: 'Journey along with good company.',
  },

  {
    audioData: [' ', ''],
    word: 'a lot more',
    meaning: ['much additional', 'considerably more'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['much more'],
    examples: ['A lot more work.', 'A lot more fun.'],
    synonyms: ['much more'],
    antonyms: ['less'],
    shortStory: 'A lot more stars appeared suddenly.',
  },

  {
    audioData: [' ', ''],
    word: 'alternative to sth',
    meaning: ['different option', 'substitute'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['option'],
    examples: ['Alternative to car.', 'Alternative to sugar.'],
    synonyms: ['option'],
    antonyms: ['only choice'],
    shortStory: 'Alternative paths lead to treasure.',
  },

  {
    audioData: [' ', ''],
    word: 'and so on',
    meaning: ['etcetera', 'and the rest'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['etc'],
    examples: ['Apples, oranges, and so on.', 'Books, pens, and so on.'],
    synonyms: ['etc'],
    antonyms: ['complete list'],
    shortStory: 'Dreams, hopes, and so on endlessly.',
  },

  {
    audioData: [' ', ''],
    word: 'apart from',
    meaning: ['except for', 'besides'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['except'],
    examples: ['Apart from rain, perfect.', 'All apart from John.'],
    synonyms: ['except'],
    antonyms: ['including'],
    shortStory: 'Perfect apart from one missing star.',
  },

  {
    audioData: [' ', ''],
    word: 'a range of sth',
    meaning: ['variety/selection', 'assortment'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['variety'],
    examples: ['A range of colors.', 'Range of options.'],
    synonyms: ['variety'],
    antonyms: ['one type'],
    shortStory: 'A range of possibilities opens.',
  },

  {
    audioData: [' ', ''],
    word: 'as if…',
    meaning: ['seems like', 'appears that'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['seems'],
    examples: ['Smiles as if happy.', 'Runs as if chased.'],
    synonyms: ['seems'],
    antonyms: ['definitely'],
    shortStory: 'Shines as if made of gold.',
  },

  {
    audioData: [' ', ''],
    word: 'as much as',
    meaning: ['equal amount', 'same degree'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['equal'],
    examples: ['Love as much as hate.', 'Eat as much as you want.'],
    synonyms: ['equal'],
    antonyms: ['less'],
    shortStory: 'Dream as much as you dare.',
  },

  {
    audioData: [' ', ''],
    word: 'as soon as possible',
    meaning: ['immediately', 'without delay'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['quickly'],
    examples: ['Come ASAP.', 'Reply as soon as possible.'],
    synonyms: ['quickly'],
    antonyms: ['later'],
    shortStory: 'Help arrives as soon as possible.',
  },

  {
    audioData: [' ', ''],
    word: 'at last',
    meaning: ['finally', 'after long wait'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['finally'],
    examples: ['At last we arrived.', 'Success at last.'],
    synonyms: ['finally'],
    antonyms: ['soon'],
    shortStory: 'At last, dreams become reality.',
  },

  {
    audioData: [' ', ''],
    word: 'at risk',
    meaning: ['in danger', 'threatened'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['endangered'],
    examples: ['Species at risk.', 'Job at risk.'],
    synonyms: ['endangered'],
    antonyms: ['safe'],
    shortStory: 'Heroes protect those at risk.',
  },

  {
    audioData: [' ', ''],
    word: 'at times',
    meaning: ['occasionally', 'sometimes'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['sometimes'],
    examples: ['Difficult at times.', 'Beautiful at times.'],
    synonyms: ['sometimes'],
    antonyms: ['always'],
    shortStory: 'Magic appears at times unexpectedly.',
  },

  {
    audioData: [' ', ''],
    word: 'attached to sb/sth',
    meaning: ['emotionally connected', 'fond of'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['fond of'],
    examples: ['Attached to old house.', 'Attached to childhood pet.'],
    synonyms: ['fond'],
    antonyms: ['detached'],
    shortStory: 'Attached to memories that linger.',
  },

  {
    audioData: [' ', ''],
    word: 'a variety of sth',
    meaning: ['different types/kinds', 'assortment'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['different kinds'],
    examples: ['Variety of fruits.', 'Variety of opinions.'],
    synonyms: ['assortment'],
    antonyms: ['same'],
    shortStory: 'Variety of colors paints life.',
  },

  {
    audioData: [' ', ''],
    word: 'be about to do sth',
    meaning: ['going to happen soon', 'imminent'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['soon'],
    examples: ['About to leave.', 'About to rain.'],
    synonyms: ['imminent'],
    antonyms: ['far off'],
    shortStory: 'About to discover hidden treasure.',
  },

  {
    audioData: [' ', ''],
    word: 'be going on',
    meaning: ['happening now', 'occurring'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['happening'],
    examples: ["What's going on?", "Something's going on."],
    synonyms: ['happening'],
    antonyms: ['finished'],
    shortStory: 'Magic going on behind curtains.',
  },

  {
    audioData: [' ', ''],
    word: 'be known as sb/sth',
    meaning: ['famous by name', 'called/referred'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['called'],
    examples: ['Known as Einstein.', 'Known as hero.'],
    synonyms: ['called'],
    antonyms: ['unknown'],
    shortStory: 'Known as the kindest soul.',
  },

  {
    audioData: [' ', ''],
    word: 'benefit from sth',
    meaning: ['gain advantage', 'profit by'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['gain'],
    examples: ['Benefit from exercise.', 'Benefit from advice.'],
    synonyms: ['profit'],
    antonyms: ['lose'],
    shortStory: 'Benefit from every kind word.',
  },

  {
    audioData: [' ', ''],
    word: 'be supposed to do sth',
    meaning: ['expected/obligated', 'should'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['should'],
    examples: ['Supposed to arrive.', 'Supposed to study.'],
    synonyms: ['should'],
    antonyms: ['not supposed'],
    shortStory: 'Supposed to follow your heart.',
  },

  {
    audioData: [' ', ''],
    word: 'break up',
    meaning: ['end relationship', 'separate'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['separate'],
    examples: ['They broke up.', 'Break up fight.'],
    synonyms: ['split'],
    antonyms: ['together'],
    shortStory: 'Break up; new beginnings await.',
  },

  {
    audioData: [' ', ''],
    word: 'by the time (that)…',
    meaning: ['when/after period', 'at that moment'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['when'],
    examples: ['By the time I arrive.', 'By time you read this.'],
    synonyms: ['when'],
    antonyms: ['before'],
    shortStory: 'By the time dawn breaks.',
  },

  {
    audioData: [' ', ''],
    word: "can't afford sth",
    meaning: ['lack money', 'too expensive'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['too expensive'],
    examples: ["Can't afford car.", "Can't afford vacation."],
    synonyms: ['too costly'],
    antonyms: ['can afford'],
    shortStory: "Can't afford doubt; invest hope.",
  },

  {
    audioData: [' ', ''],
    word: 'care for sb',
    meaning: ['love/protect', 'have affection'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['love'],
    examples: ['Care for family.', 'I care for you.'],
    synonyms: ['love'],
    antonyms: ['indifferent'],
    shortStory: 'Care for those who wander.',
  },

  {
    audioData: [' ', ''],
    word: 'caused by sth',
    meaning: ['result of cause', 'due to'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['due to'],
    examples: ['Caused by rain.', 'Caused by mistake.'],
    synonyms: ['due to'],
    antonyms: ['coincidence'],
    shortStory: 'Caused by one small kind act.',
  },

  {
    audioData: [' ', ''],
    word: 'check sb/sth out',
    meaning: ['examine/visit', 'investigate'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['examine'],
    examples: ['Check out new shop.', 'Check him out.'],
    synonyms: ['examine'],
    antonyms: ['ignore'],
    shortStory: 'Check out hidden waterfall path.',
  },

  {
    audioData: [' ', ''],
    word: 'choose to do sth',
    meaning: ['select/decide', 'opt for'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['decide'],
    examples: ['Choose to help.', 'Choose to succeed.'],
    synonyms: ['decide'],
    antonyms: ['forced'],
    shortStory: 'Choose to dance in the rain.',
  },

  {
    audioData: [' ', ''],
    word: 'clean up',
    meaning: ['tidy/make neat', 'remove mess'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['tidy'],
    examples: ['Clean up room.', 'Clean up after party.'],
    synonyms: ['tidy'],
    antonyms: ['mess up'],
    shortStory: 'Clean up reveals hidden treasures.',
  },

  {
    audioData: [' ', ''],
    word: 'click on sth',
    meaning: ['press computer button', 'select online'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['click'],
    examples: ['Click on link.', 'Click on button.'],
    synonyms: ['select'],
    antonyms: ['ignore'],
    shortStory: 'Click on adventure opens worlds.',
  },

  {
    audioData: [' ', ''],
    word: 'come up with sth',
    meaning: ['invent/find idea', 'think of'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['invent'],
    examples: ['Come up with plan.', 'Come up with solution.'],
    synonyms: ['invent'],
    antonyms: ['copy'],
    shortStory: 'Come up with magic spells daily.',
  },

  {
    audioData: [' ', ''],
    word: 'compared with sth',
    meaning: ['in comparison to', 'versus'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['vs'],
    examples: [
      'Better compared with last year.',
      'Tall compared with brother.',
    ],
    synonyms: ['vs'],
    antonyms: ['same'],
    shortStory: 'Shines brighter compared with others.',
  },

  {
    audioData: [' ', ''],
    word: 'concentrate on sth',
    meaning: ['focus attention', 'dedicate effort'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['focus'],
    examples: ['Concentrate on studies.', 'Concentrate on goal.'],
    synonyms: ['focus'],
    antonyms: ['distract'],
    shortStory: 'Concentrate on dreams materializes them.',
  },

  {
    audioData: [' ', ''],
    word: 'consist of sb/sth',
    meaning: ['made up of/composed', 'contains'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['made of'],
    examples: ['Team consists of players.', 'Cake consists of flour.'],
    synonyms: ['contains'],
    antonyms: ['lacks'],
    shortStory: 'Friendship consists of trust.',
  },

  {
    audioData: [' ', ''],
    word: 'decide on sth',
    meaning: ['choose/select', 'make choice'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['choose'],
    examples: ['Decide on dinner.', 'Decide on career.'],
    synonyms: ['choose'],
    antonyms: ['undecided'],
    shortStory: 'Decide on happiness every morning.',
  },

  {
    audioData: [' ', ''],
    word: 'depending on',
    meaning: ['contingent upon', 'varies by'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['varies'],
    examples: ['Depending on weather.', 'Cost depending on size.'],
    synonyms: ['varies'],
    antonyms: ['certain'],
    shortStory: 'Success depending on daily effort.',
  },

  {
    audioData: [' ', ''],
    word: 'developing countries',
    meaning: ['emerging economies', 'third world'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['emerging'],
    examples: [
      'Aid to developing countries.',
      'Growth in developing countries.',
    ],
    synonyms: ['emerging'],
    antonyms: ['developed'],
    shortStory: 'Developing countries rise steadily.',
  },

  {
    audioData: [' ', ''],
    word: 'due to sb/sth',
    meaning: ['caused by', 'because of'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['because'],
    examples: ['Late due to traffic.', 'Success due to hard work.'],
    synonyms: ['because'],
    antonyms: ['despite'],
    shortStory: 'Victory due to never quitting.',
  },

  {
    audioData: [' ', ''],
    word: 'economic growth',
    meaning: ['GDP increase', 'prosperity rise'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['prosperity'],
    examples: ['Strong economic growth.', 'Slow economic growth.'],
    synonyms: ['prosperity'],
    antonyms: ['recession'],
    shortStory: 'Economic growth lifts all boats.',
  },

  {
    audioData: [' ', ''],
    word: 'end up',
    meaning: ['finally become/result', 'ultimately'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['finally'],
    examples: ['End up happy.', 'End up lost.'],
    synonyms: ['finally'],
    antonyms: ['begin'],
    shortStory: 'End up where you belong.',
  },

  {
    audioData: [' ', ''],
    word: 'even if',
    meaning: ['despite/regardless', 'in spite of'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['despite'],
    examples: ['Help even if tired.', 'Try even if scared.'],
    synonyms: ['despite'],
    antonyms: ['only if'],
    shortStory: 'Fly even if wings tremble.',
  },

  {
    audioData: [' ', ''],
    word: 'even though',
    meaning: ['despite fact', 'although'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['although'],
    examples: [
      'Rained even though sunny forecast.',
      'Tired even though slept well.',
    ],
    synonyms: ['although'],
    antonyms: ['because'],
    shortStory: 'Continued even though path darkened.',
  },

  {
    audioData: [' ', ''],
    word: 'exactly the same',
    meaning: ['identical', 'no difference'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['identical'],
    examples: ['Same color exactly the same.', 'Twins look exactly the same.'],
    synonyms: ['identical'],
    antonyms: ['different'],
    shortStory: 'Hearts beat exactly the same.',
  },

  {
    audioData: [' ', ''],
    word: 'experience in sth',
    meaning: ['knowledge/skill from practice', 'expertise'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['expertise'],
    examples: ['Experience in teaching.', 'No experience in cooking.'],
    synonyms: ['expertise'],
    antonyms: ['beginner'],
    shortStory: 'Experience in storms builds strength.',
  },

  {
    audioData: [' ', ''],
    word: 'fail to do sth',
    meaning: ['not succeed', 'unsuccessful'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['unsuccessful'],
    examples: ['Fail to understand.', 'Fail to arrive on time.'],
    synonyms: ['unsuccessful'],
    antonyms: ['succeed'],
    shortStory: 'Fail to quit; rise again.',
  },

  {
    audioData: [' ', ''],
    word: 'fall asleep',
    meaning: ['begin sleeping', 'doze off'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['sleep'],
    examples: ['Fall asleep reading.', 'Fell asleep in class.'],
    synonyms: ['doze'],
    antonyms: ['wake up'],
    shortStory: 'Fall asleep to dream sweetly.',
  },

  {
    audioData: [' ', ''],
    word: 'far more',
    meaning: ['much greater amount', 'significantly more'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['much more'],
    examples: ['Far more beautiful.', 'Far more difficult.'],
    synonyms: ['much more'],
    antonyms: ['far less'],
    shortStory: 'Far more stars than eyes see.',
  },

  {
    audioData: [' ', ''],
    word: 'far too',
    meaning: ['excessively', 'way too much'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['excessive'],
    examples: ['Far too expensive.', 'Far too late.'],
    synonyms: ['way too'],
    antonyms: ['just right'],
    shortStory: 'Far too many worries carried.',
  },

  {
    audioData: [' ', ''],
    word: 'fed up',
    meaning: ['annoyed/frustrated', 'tired of'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['annoyed'],
    examples: ['Fed up with rain.', 'Fed up waiting.'],
    synonyms: ['frustrated'],
    antonyms: ['happy'],
    shortStory: 'Fed up; time for change.',
  },

  {
    audioData: [' ', ''],
    word: 'for a while',
    meaning: ['short time period', 'temporarily'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['temporarily'],
    examples: ['Wait for a while.', 'Lived there for a while.'],
    synonyms: ['temporarily'],
    antonyms: ['forever'],
    shortStory: 'Rest for a while; then continue.',
  },

  {
    audioData: [' ', ''],
    word: 'for free',
    meaning: ['no cost', 'gratis'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['free'],
    examples: ['Sample for free.', 'Advice for free.'],
    synonyms: ['gratis'],
    antonyms: ['paid'],
    shortStory: 'Best things come for free.',
  },

  {
    audioData: [' ', ''],
    word: 'for instance',
    meaning: ['example', 'such as'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['e.g.'],
    examples: ['Fruits, for instance apples.', 'Animals, for instance dogs.'],
    synonyms: ['e.g.'],
    antonyms: ['generally'],
    shortStory: 'Heroes, for instance everyday moms.',
  },

  {
    audioData: [' ', ''],
    word: 'for life',
    meaning: ['permanent/lifetime', 'forever'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['forever'],
    examples: ['Married for life.', 'Learn skill for life.'],
    synonyms: ['forever'],
    antonyms: ['temporary'],
    shortStory: 'True friends last for life.',
  },

  {
    audioData: [' ', ''],
    word: 'for long',
    meaning: ['extended time', 'long duration'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['long time'],
    examples: ["Won't take for long.", 'Not here for long.'],
    synonyms: ['long duration'],
    antonyms: ['briefly'],
    shortStory: 'Memories last not for long.',
  },

  {
    audioData: [' ', ''],
    word: 'for some time',
    meaning: ['extended period', 'considerable duration'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['some time'],
    examples: ['Worked there for some time.', 'Silent for some time.'],
    synonyms: ['awhile'],
    antonyms: ['briefly'],
    shortStory: 'Waited for some time patiently.',
  },

  {
    audioData: [' ', ''],
    word: 'get on with sb',
    meaning: ['have good relationship', 'get along'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['get along'],
    examples: ['Get on with colleagues.', "Doesn't get on with boss."],
    synonyms: ['get along'],
    antonyms: ['fight'],
    shortStory: 'Get on with everyone harmoniously.',
  },

  {
    audioData: [' ', ''],
    word: 'get to know sb',
    meaning: ['become familiar', 'learn about person'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['befriend'],
    examples: ['Get to know neighbors.', 'Got to know her well.'],
    synonyms: ['befriend'],
    antonyms: ['strangers'],
    shortStory: 'Get to know reveals true hearts.',
  },

  {
    audioData: [' ', ''],
    word: 'get used to sth',
    meaning: ['become accustomed', 'adapt'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['adapt'],
    examples: ['Get used to cold.', 'Used to new job.'],
    synonyms: ['adapt'],
    antonyms: ['resist'],
    shortStory: 'Get used to change gracefully.',
  },

  {
    audioData: [' ', ''],
    word: 'global warming',
    meaning: ['earth temperature rise', 'climate change'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['warming'],
    examples: ['Global warming melts ice.', 'Fight global warming.'],
    synonyms: ['climate change'],
    antonyms: ['cooling'],
    shortStory: 'Global warming wakes sleeping giants.',
  },

  {
    audioData: [' ', ''],
    word: 'go ahead',
    meaning: ['permission/proceed', 'start now'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['proceed'],
    examples: ['Go ahead, ask.', 'Project go ahead.'],
    synonyms: ['proceed'],
    antonyms: ['stop'],
    shortStory: 'Go ahead; greatness awaits.',
  },

  {
    audioData: [' ', ''],
    word: 'go wrong',
    meaning: ['fail/mistake', 'not as planned'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['fail'],
    examples: ['Plan went wrong.', 'What went wrong?'],
    synonyms: ['fail'],
    antonyms: ['go right'],
    shortStory: 'When plans go wrong, improvise.',
  },

  {
    audioData: [' ', ''],
    word: 'growth in sth',
    meaning: ['increase/development', 'expansion'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['increase'],
    examples: ['Growth in population.', 'Growth in business.'],
    synonyms: ['expansion'],
    antonyms: ['decline'],
    shortStory: 'Growth in kindness spreads widely.',
  },

  {
    audioData: [' ', ''],
    word: 'have no idea',
    meaning: ['completely unaware', "don't know"],
    partOfSpeech: ['phrase'],
    simpleDefinition: ["don't know"],
    examples: ['Have no idea where.', 'No idea how.'],
    synonyms: ['clueless'],
    antonyms: ['know'],
    shortStory: 'Have no idea magic exists.',
  },

  {
    audioData: [' ', ''],
    word: 'have sth in common',
    meaning: ['shared interests', 'similarities'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['similar'],
    examples: ['Have music in common.', 'Much in common.'],
    synonyms: ['similar'],
    antonyms: ['different'],
    shortStory: 'Have dreams in common bonds.',
  },

  {
    audioData: [' ', ''],
    word: 'hear of sb/sth',
    meaning: ['know about by hearsay', 'heard mention'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['heard of'],
    examples: ['Never heard of him.', 'Heard of that place.'],
    synonyms: ['heard mention'],
    antonyms: ['unknown'],
    shortStory: 'Heard of legendary lost city.',
  },

  {
    audioData: [' ', ''],
    word: 'heart disease',
    meaning: ['cardiac illness', 'heart problems'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['heart illness'],
    examples: ['Heart disease risk.', 'Prevent heart disease.'],
    synonyms: ['cardiac'],
    antonyms: ['healthy heart'],
    shortStory: 'Heart disease cured by love.',
  },

  {
    audioData: [' ', ''],
    word: 'high street',
    meaning: ['main shopping street', 'downtown shops'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['main street'],
    examples: ['Shops on high street.', 'High street closed.'],
    synonyms: ['main street'],
    antonyms: ['back street'],
    shortStory: 'High street buzzes with commerce.',
  },

  {
    audioData: [' ', ''],
    word: 'higher education',
    meaning: ['university/college', 'post-secondary'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['university'],
    examples: ['Higher education important.', 'Access higher education.'],
    synonyms: ['college'],
    antonyms: ['school'],
    shortStory: 'Higher education opens mind doors.',
  },

  {
    audioData: [' ', ''],
    word: 'if I were you',
    meaning: ['advice suggestion', 'my recommendation'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['advice'],
    examples: ["If I were you, I'd go.", 'If I were you, study.'],
    synonyms: ['advice'],
    antonyms: ["don't"],
    shortStory: "If I were you, I'd dream big.",
  },

  {
    audioData: [' ', ''],
    word: 'in addition',
    meaning: ['also', 'furthermore'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['also'],
    examples: ['Smart; in addition, kind.', 'Coffee in addition to tea.'],
    synonyms: ['also'],
    antonyms: ['however'],
    shortStory: 'Strength in addition to wisdom wins.',
  },

  {
    audioData: [' ', ''],
    word: 'in a way that...',
    meaning: ['manner/method', 'how'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['how'],
    examples: [
      'Works in a way that helps.',
      'Explains in a way that clarifies.',
    ],
    synonyms: ['how'],
    antonyms: ['differently'],
    shortStory: 'Shines in a way that warms hearts.',
  },

  {
    audioData: [' ', ''],
    word: 'in case…',
    meaning: ['if/precaution', 'just in case'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['if'],
    examples: ['Take umbrella in case rain.', 'Phone in case emergency.'],
    synonyms: ['if'],
    antonyms: ['certain'],
    shortStory: 'Hope in case dreams delay.',
  },

  {
    audioData: [' ', ''],
    word: 'in charge of sb/sth',
    meaning: ['responsible for', 'managing'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['responsible'],
    examples: ['In charge of team.', 'Teacher in charge of class.'],
    synonyms: ['responsible'],
    antonyms: ['follower'],
    shortStory: 'In charge of destiny boldly.',
  },

  {
    audioData: [' ', ''],
    word: 'in contrast',
    meaning: ['different/opposite', 'however'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['different'],
    examples: ['Rich; in contrast, poor.', 'Fast in contrast to slow.'],
    synonyms: ['however'],
    antonyms: ['similar'],
    shortStory: 'Dark in contrast to light reveals.',
  },

  {
    audioData: [' ', ''],
    word: 'in favour of sb/sth',
    meaning: ['supporting', 'preferring'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['support'],
    examples: ['Vote in favour of plan.', 'In favour of peace.'],
    synonyms: ['support'],
    antonyms: ['against'],
    shortStory: 'In favour of kindness always.',
  },

  {
    audioData: [' ', ''],
    word: 'in general',
    meaning: ['usually', 'overall'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['usually'],
    examples: ['In general, happy.', 'People in general kind.'],
    synonyms: ['usually'],
    antonyms: ['specifically'],
    shortStory: 'In general, good triumphs.',
  },

  {
    audioData: [' ', ''],
    word: 'in order of sth',
    meaning: ['sequence/arranged by', 'sorted'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['sorted'],
    examples: ['List in order of size.', 'Books in order of author.'],
    synonyms: ['sorted'],
    antonyms: ['random'],
    shortStory: 'Stars in order of brightness.',
  },

  {
    audioData: [' ', ''],
    word: 'in order to do sth',
    meaning: ['purpose', 'to'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['to'],
    examples: ['Study in order to pass.', 'Save in order to travel.'],
    synonyms: ['to'],
    antonyms: ['without reason'],
    shortStory: 'Practice in order to perfect.',
  },

  {
    audioData: [' ', ''],
    word: 'in other words',
    meaning: ['that is to say', 'meaning'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['meaning'],
    examples: [
      'Late; in other words, missed.',
      'Simple; in other words, easy.',
    ],
    synonyms: ['meaning'],
    antonyms: ['confusing'],
    shortStory: 'Magic; in other words, wonder.',
  },

  {
    audioData: [' ', ''],
    word: 'in particular',
    meaning: ['especially', 'specifically'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['especially'],
    examples: [
      'Likes fruit; apples in particular.',
      'Important; safety in particular.',
    ],
    synonyms: ['especially'],
    antonyms: ['generally'],
    shortStory: 'Stars; the North Star in particular.',
  },

  {
    audioData: [' ', ''],
    word: 'in public',
    meaning: ['not private', 'openly'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['openly'],
    examples: ['Speak in public.', "Don't cry in public."],
    synonyms: ['openly'],
    antonyms: ['privately'],
    shortStory: 'Heroes act in public courageously.',
  },

  {
    audioData: [' ', ''],
    word: 'in recent years',
    meaning: ['lately', 'recently'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['lately'],
    examples: ['In recent years, changed.', 'Technology in recent years.'],
    synonyms: ['lately'],
    antonyms: ['long ago'],
    shortStory: 'Magic returned in recent years.',
  },

  {
    audioData: [' ', ''],
    word: 'in response to sth',
    meaning: ['reply/reaction to', 'answering'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['reply'],
    examples: ['In response to question.', 'Action in response to crisis.'],
    synonyms: ['reply'],
    antonyms: ['ignore'],
    shortStory: 'Kindness in response to anger.',
  },

  {
    audioData: [' ', ''],
    word: 'in terms of sth',
    meaning: ['regarding/concerning', 'about'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['regarding'],
    examples: ['In terms of cost.', 'Success in terms of happiness.'],
    synonyms: ['regarding'],
    antonyms: ['regardless'],
    shortStory: 'Great in terms of heart.',
  },

  {
    audioData: [' ', ''],
    word: 'in the case of sth',
    meaning: ['regarding specific situation', 'for this instance'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['for this'],
    examples: ['In the case of rain.', 'In case of emergency.'],
    synonyms: ['for this'],
    antonyms: ['generally'],
    shortStory: 'In the case of true love, miracles happen.',
  },

  {
    audioData: [' ', ''],
    word: 'in the form of sb/sth',
    meaning: ['as type/shape', 'appearing as'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['as'],
    examples: ['Help in form of food.', 'Appeared in form of angel.'],
    synonyms: ['as'],
    antonyms: ['different form'],
    shortStory: 'Magic came in form of butterfly.',
  },

  {
    audioData: [' ', ''],
    word: 'in the way (that)…',
    meaning: ['manner/method', 'how'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['how'],
    examples: ['Works in way that helps.', 'Smiles in way that warms.'],
    synonyms: ['how'],
    antonyms: ['differently'],
    shortStory: 'Shines in way that inspires.',
  },

  {
    audioData: [' ', ''],
    word: 'in this case',
    meaning: ['for this situation', 'specifically now'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['now'],
    examples: ['In this case, yes.', 'Exception in this case.'],
    synonyms: ['now'],
    antonyms: ['generally'],
    shortStory: 'In this case, dreams come true.',
  },

  {
    audioData: [' ', ''],
    word: 'in time',
    meaning: ['before deadline', 'eventually'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['eventually'],
    examples: ['Arrived in time.', 'Learn in time.'],
    synonyms: ['eventually'],
    antonyms: ['too late'],
    shortStory: 'Truth reveals itself in time.',
  },

  {
    audioData: [' ', ''],
    word: 'in touch',
    meaning: ['contact/communication', 'connected'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['contact'],
    examples: ['Keep in touch.', 'Get back in touch.'],
    synonyms: ['contact'],
    antonyms: ['out of touch'],
    shortStory: 'Friends stay in touch forever.',
  },

  {
    audioData: [' ', ''],
    word: 'I wonder if…',
    meaning: ['curious thought', 'questioning'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['curious?'],
    examples: ['I wonder if it rains.', "Wonder if he's coming."],
    synonyms: ['curious?'],
    antonyms: ['certain'],
    shortStory: 'I wonder if stars have names.',
  },

  {
    audioData: [' ', ''],
    word: 'leave sb/sth out',
    meaning: ['exclude/omit', 'not include'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['exclude'],
    examples: ["Don't leave me out.", 'Left out ingredient.'],
    synonyms: ['exclude'],
    antonyms: ['include'],
    shortStory: 'Never leave kindness out.',
  },

  {
    audioData: [' ', ''],
    word: 'likely to do sth',
    meaning: ['probable', 'expected to'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['probable'],
    examples: ['Likely to rain.', 'Likely to succeed.'],
    synonyms: ['probable'],
    antonyms: ['unlikely'],
    shortStory: 'Likely to discover hidden talents.',
  },

  {
    audioData: [' ', ''],
    word: 'look forward to sth',
    meaning: ['anticipate happily', 'excited for'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['excited for'],
    examples: ['Look forward to vacation.', 'Look forward to meeting.'],
    synonyms: ['excited'],
    antonyms: ['dread'],
    shortStory: "Look forward to tomorrow's adventures.",
  },

  {
    audioData: [' ', ''],
    word: 'look out',
    meaning: ['be careful/watch', 'warning'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['watch out'],
    examples: ['Look out! Car coming.', 'Look out for dangers.'],
    synonyms: ['watch out'],
    antonyms: ['ignore'],
    shortStory: 'Look out reveals hidden blessings.',
  },

  {
    audioData: [' ', ''],
    word: 'make a difference',
    meaning: ['have impact/change', 'matter'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['matter'],
    examples: [
      'Small acts make a difference.',
      'Your vote makes a difference.',
    ],
    synonyms: ['matter'],
    antonyms: ['irrelevant'],
    shortStory: 'Kindness makes a difference daily.',
  },

  {
    audioData: [' ', ''],
    word: 'make sth up',
    meaning: ['invent/lie', 'create story'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['invent'],
    examples: ['Make up excuse.', 'Children make up stories.'],
    synonyms: ['invent'],
    antonyms: ['truth'],
    shortStory: 'Make up magical tales nightly.',
  },

  {
    audioData: [' ', ''],
    word: 'mean to do sth',
    meaning: ['intend/plan', 'supposed to'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['intend'],
    examples: ['I mean to finish.', "Didn't mean to hurt."],
    synonyms: ['intend'],
    antonyms: ['accident'],
    shortStory: 'Mean to chase every dream.',
  },

  {
    audioData: [' ', ''],
    word: 'more and more',
    meaning: ['increasingly', 'greater amounts'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['increasingly'],
    examples: ['More and more difficult.', 'More and more people.'],
    synonyms: ['increasingly'],
    antonyms: ['less and less'],
    shortStory: 'More and more stars appear.',
  },

  {
    audioData: [' ', ''],
    word: 'move on',
    meaning: ['progress/leave past', 'advance'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['advance'],
    examples: ['Time to move on.', 'Move on to next.'],
    synonyms: ['advance'],
    antonyms: ['stuck'],
    shortStory: 'Move on to brighter horizons.',
  },

  {
    audioData: [' ', ''],
    word: 'no longer',
    meaning: ['not anymore', 'stopped'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['not now'],
    examples: ['No longer friends.', 'No longer available.'],
    synonyms: ['not anymore'],
    antonyms: ['still'],
    shortStory: 'No longer afraid of dark.',
  },

  {
    audioData: [' ', ''],
    word: 'no more than…',
    meaning: ['only/just', 'maximum'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['only'],
    examples: ['No more than 5.', 'No more than expected.'],
    synonyms: ['only'],
    antonyms: ['more than'],
    shortStory: 'No more than a whisper needed.',
  },

  {
    audioData: [' ', ''],
    word: 'not even',
    meaning: ['not at all', 'barely'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['barely'],
    examples: ['Not even close.', 'Not even trying.'],
    synonyms: ['barely'],
    antonyms: ['completely'],
    shortStory: 'Not even wind could stop her.',
  },

  {
    audioData: [' ', ''],
    word: 'not necessarily',
    meaning: ['not always true', 'maybe not'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['maybe'],
    examples: ['Not necessarily true.', 'Not necessarily bad.'],
    synonyms: ['maybe'],
    antonyms: ['definitely'],
    shortStory: 'Not necessarily true; seek wisdom.',
  },

  {
    audioData: [' ', ''],
    word: 'not only… but also…',
    meaning: ['also/in addition', 'both'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['both'],
    examples: [
      'Not only smart but also kind.',
      'Not only rain but also thunder.',
    ],
    synonyms: ['both'],
    antonyms: ['either'],
    shortStory: 'Not only dreams but also action.',
  },

  {
    audioData: [' ', ''],
    word: 'on a regular basis',
    meaning: ['routinely', 'frequently/habitually'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['routinely'],
    examples: ['Exercise on regular basis.', 'Meet on regular basis.'],
    synonyms: ['routinely'],
    antonyms: ['occasionally'],
    shortStory: 'Practice on regular basis masters skills.',
  },

  {
    audioData: [' ', ''],
    word: 'on my own',
    meaning: ['alone/independently', 'solo'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['alone'],
    examples: ['Live on my own.', 'Did it on my own.'],
    synonyms: ['solo'],
    antonyms: ['with help'],
    shortStory: 'On my own discovers true strength.',
  },

  {
    audioData: [' ', ''],
    word: 'on the other hand',
    meaning: ['however/conversely', 'but'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['however'],
    examples: ['Smart; on other hand, lazy.', 'Cheap; on other hand, quality.'],
    synonyms: ['however'],
    antonyms: ['similarly'],
    shortStory: 'Bright; on other hand, challenging.',
  },

  {
    audioData: [' ', ''],
    word: 'on the street',
    meaning: ['outdoors/public road', 'homeless'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['outdoors'],
    examples: ['Buskers on street.', 'Sleeping on street.'],
    synonyms: ['outdoors'],
    antonyms: ['indoors'],
    shortStory: 'Stories heard on street corners.',
  },

  {
    audioData: [' ', ''],
    word: 'on the way',
    meaning: ['en route/coming', 'in transit'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['coming'],
    examples: ['Food on the way.', 'Stop on the way.'],
    synonyms: ['en route'],
    antonyms: ['arrived'],
    shortStory: 'Adventure waits on the way.',
  },

  {
    audioData: [' ', ''],
    word: 'or something',
    meaning: ['approximately/uncertain', 'or whatever'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['maybe'],
    examples: ['Seven or something.', 'Around five or something.'],
    synonyms: ['maybe'],
    antonyms: ['exactly'],
    shortStory: 'Magic or something wonderful.',
  },

  {
    audioData: [' ', ''],
    word: 'or two',
    meaning: ['a couple/few', 'small number'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['few'],
    examples: ['One or two things.', 'Day or two.'],
    synonyms: ['few'],
    antonyms: ['many'],
    shortStory: 'One or two true friends suffice.',
  },

  {
    audioData: [' ', ''],
    word: 'ought to',
    meaning: ['should/moral obligation', 'must'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['should'],
    examples: ['Ought to apologize.', 'You ought to know.'],
    synonyms: ['should'],
    antonyms: ["shouldn't"],
    shortStory: "Ought to follow heart's wisdom.",
  },

  {
    audioData: [' ', ''],
    word: 'out there',
    meaning: ['existing somewhere', 'available'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['exists'],
    examples: ['Answers out there.', 'Opportunities out there.'],
    synonyms: ['exists'],
    antonyms: ['gone'],
    shortStory: 'Magic still out there waiting.',
  },

  {
    audioData: [' ', ''],
    word: 'over the years',
    meaning: ['gradually/long term', 'with time'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['gradually'],
    examples: ['Over years, changed.', 'Learned over years.'],
    synonyms: ['gradually'],
    antonyms: ['suddenly'],
    shortStory: 'Friendship grows over years.',
  },

  {
    audioData: [' ', ''],
    word: 'over time',
    meaning: ['gradually/eventually', 'in the long run'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['gradually'],
    examples: ['Improve over time.', 'Truth emerges over time.'],
    synonyms: ['eventually'],
    antonyms: ['immediately'],
    shortStory: 'Strength builds over time steadily.',
  },

  {
    audioData: [' ', ''],
    word: 'participate in sth',
    meaning: ['take part/join', 'be involved'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['join'],
    examples: ['Participate in game.', 'Participate in discussion.'],
    synonyms: ['join'],
    antonyms: ['watch'],
    shortStory: "Participate in life's dance fully.",
  },

  {
    audioData: [' ', ''],
    word: 'point of view',
    meaning: ['perspective/opinion', 'viewpoint'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['opinion'],
    examples: ['From my point of view.', 'Different points of view.'],
    synonyms: ['viewpoint'],
    antonyms: ['fact'],
    shortStory: 'Point of view shapes reality.',
  },

  {
    audioData: [' ', ''],
    word: 'point out',
    meaning: ['indicate/show', 'highlight'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['show'],
    examples: ['Point out mistake.', 'Point out solution.'],
    synonyms: ['highlight'],
    antonyms: ['ignore'],
    shortStory: 'Point out stars in night sky.',
  },

  {
    audioData: [' ', ''],
    word: 'prepared to do sth',
    meaning: ['ready/willing', 'set to act'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['ready'],
    examples: ['Prepared to help.', 'Not prepared to wait.'],
    synonyms: ['ready'],
    antonyms: ['unwilling'],
    shortStory: 'Prepared to chase every dream.',
  },

  {
    audioData: [' ', ''],
    word: 'primary school',
    meaning: ['elementary school', 'first years'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['elementary'],
    examples: ['Primary school children.', 'Start primary school.'],
    synonyms: ['elementary'],
    antonyms: ['university'],
    shortStory: 'Primary school sparks curiosity.',
  },

  {
    audioData: [' ', ''],
    word: 'prime minister',
    meaning: ['head of government', 'PM'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['leader'],
    examples: ['Prime minister speaks.', 'Meet prime minister.'],
    synonyms: ['PM'],
    antonyms: ['citizen'],
    shortStory: 'Prime minister serves the people.',
  },

  {
    audioData: [' ', ''],
    word: 'put sth up',
    meaning: ['raise/display', 'hang/post'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['hang'],
    examples: ['Put up poster.', 'Put up shelf.'],
    synonyms: ['hang'],
    antonyms: ['take down'],
    shortStory: 'Put up dreams on vision board.',
  },

  {
    audioData: [' ', ''],
    word: 'quite a…',
    meaning: ['remarkable/surprising', 'considerable'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['remarkable'],
    examples: ['Quite a challenge.', 'Quite a view.'],
    synonyms: ['remarkable'],
    antonyms: ['ordinary'],
    shortStory: 'Quite a magical discovery made.',
  },

  {
    audioData: [' ', ''],
    word: 'raise money',
    meaning: ['collect funds', 'fundraise'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['fundraise'],
    examples: ['Raise money for charity.', 'Raise money online.'],
    synonyms: ['fundraise'],
    antonyms: ['spend'],
    shortStory: 'Raise money changes many lives.',
  },

  {
    audioData: [' ', ''],
    word: 'rather than',
    meaning: ['instead of/preferring', 'not'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['instead'],
    examples: ['Tea rather than coffee.', 'Walk rather than drive.'],
    synonyms: ['instead'],
    antonyms: ['as well as'],
    shortStory: 'Choose love rather than fear.',
  },

  {
    audioData: [' ', ''],
    word: 'reaction to sth',
    meaning: ['response/answer to', 'reply'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['response'],
    examples: ['Reaction to news.', 'Quick reaction to danger.'],
    synonyms: ['response'],
    antonyms: ['cause'],
    shortStory: 'Reaction to kindness spreads joy.',
  },

  {
    audioData: [' ', ''],
    word: 'relate to sth/sb',
    meaning: ['connect/understand', 'associate'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['connect'],
    examples: ['Relate to story.', "Can't relate to him."],
    synonyms: ['connect'],
    antonyms: ['ignore'],
    shortStory: 'Relate to dreams makes them real.',
  },

  {
    audioData: [' ', ''],
    word: 'related to sth/sb',
    meaning: ['connected/associate', 'linked'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['linked'],
    examples: ['Related to family.', 'Problems related to stress.'],
    synonyms: ['linked'],
    antonyms: ['unrelated'],
    shortStory: 'Related to purpose finds meaning.',
  },

  {
    audioData: [' ', ''],
    word: 'respect for sb/sth',
    meaning: ['admiration/esteem', 'honor'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['admiration'],
    examples: ['Respect for teacher.', 'Respect for nature.'],
    synonyms: ['honor'],
    antonyms: ['disrespect'],
    shortStory: 'Respect for others builds bridges.',
  },

  {
    audioData: [' ', ''],
    word: 'result in sth',
    meaning: ['cause/produce', 'lead to'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['cause'],
    examples: ['Hard work results in success.', 'Mistake resulted in delay.'],
    synonyms: ['cause'],
    antonyms: ['prevent'],
    shortStory: 'Effort results in golden harvests.',
  },

  {
    audioData: [' ', ''],
    word: 'rise in sth',
    meaning: ['increase/growth', 'go up'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['increase'],
    examples: ['Rise in prices.', 'Rise in temperature.'],
    synonyms: ['increase'],
    antonyms: ['fall'],
    shortStory: 'Rise in hope lifts spirits.',
  },

  {
    audioData: [' ', ''],
    word: 'run out',
    meaning: ['finish supply', 'deplete'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['finish'],
    examples: ['Time runs out.', 'Patience runs out.'],
    synonyms: ['deplete'],
    antonyms: ['have plenty'],
    shortStory: 'Sand runs out; act now.',
  },

  {
    audioData: [' ', ''],
    word: 'run out of sth',
    meaning: ['no more left', 'exhausted supply'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['no more'],
    examples: ['Run out of milk.', 'Ran out of time.'],
    synonyms: ['exhausted'],
    antonyms: ['stocked'],
    shortStory: 'Run out of excuses; try harder.',
  },

  {
    audioData: [' ', ''],
    word: 'search engine',
    meaning: ['internet search tool', 'Google/Bing'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['Google'],
    examples: ['Use search engine.', 'Best search engine.'],
    synonyms: ['Google'],
    antonyms: ['library'],
    shortStory: 'Search engine unlocks world knowledge.',
  },

  {
    audioData: [' ', ''],
    word: 'secondary school',
    meaning: ['high school', 'ages 11-18'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['high school'],
    examples: ['Secondary school students.', 'Start secondary school.'],
    synonyms: ['high school'],
    antonyms: ['primary'],
    shortStory: 'Secondary school shapes young minds.',
  },

  {
    audioData: [' ', ''],
    word: 'set sth up',
    meaning: ['arrange/organize', 'establish'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['organize'],
    examples: ['Set up meeting.', 'Set up business.'],
    synonyms: ['organize'],
    antonyms: ['cancel'],
    shortStory: 'Set up dreams for success.',
  },

  {
    audioData: [' ', ''],
    word: 'slow down',
    meaning: ['reduce speed', 'relax pace'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['relax'],
    examples: ['Slow down driving.', 'Life slow down.'],
    synonyms: ['relax'],
    antonyms: ['speed up'],
    shortStory: "Slow down reveals life's beauty.",
  },

  {
    audioData: [' ', ''],
    word: 'so far',
    meaning: ['until now', 'up to present'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['until now'],
    examples: ['So far so good.', 'Results so far.'],
    synonyms: ['thus far'],
    antonyms: ['future'],
    shortStory: 'So far, adventure continues.',
  },

  {
    audioData: [' ', ''],
    word: 'some kind of…',
    meaning: ['certain type', 'a type of'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['type'],
    examples: ['Some kind of magic.', 'Some kind of problem.'],
    synonyms: ['type'],
    antonyms: ['specific'],
    shortStory: 'Some kind of wonder appeared.',
  },

  {
    audioData: [' ', ''],
    word: 'succeed in doing sth',
    meaning: ['achieve goal', 'accomplish'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['achieve'],
    examples: ['Succeed in exam.', 'Succeed in business.'],
    synonyms: ['achieve'],
    antonyms: ['fail'],
    shortStory: 'Succeed in chasing every dream.',
  },

  {
    audioData: [' ', ''],
    word: 'suffer from sth',
    meaning: ['experience pain/illness', 'afflicted'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['illness'],
    examples: ['Suffer from cold.', 'Suffer from stress.'],
    synonyms: ['afflicted'],
    antonyms: ['healthy'],
    shortStory: 'Suffer from growth pains gracefully.',
  },

  {
    audioData: [' ', ''],
    word: 'sure to do sth',
    meaning: ['certain to happen', 'guaranteed'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['certain'],
    examples: ['Sure to rain today.', 'Sure to succeed.'],
    synonyms: ['certain'],
    antonyms: ['unlikely'],
    shortStory: 'Sure to find treasure with persistence.',
  },

  {
    audioData: [' ', ''],
    word: 'take sb/sth on',
    meaning: ['accept challenge/job', 'hire'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['accept'],
    examples: ['Take on new project.', 'Company takes on staff.'],
    synonyms: ['accept'],
    antonyms: ['refuse'],
    shortStory: 'Take on fears to conquer them.',
  },

  {
    audioData: [' ', ''],
    word: 'take up sth',
    meaning: ['start hobby/activity', 'begin'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['start'],
    examples: ['Take up painting.', 'Take up running.'],
    synonyms: ['begin'],
    antonyms: ['give up'],
    shortStory: 'Take up dancing frees the soul.',
  },

  {
    audioData: [' ', ''],
    word: 'take sth up',
    meaning: ['continue discussion', 'resume'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['continue'],
    examples: ['Take up where left off.', 'Take up the matter.'],
    synonyms: ['resume'],
    antonyms: ['drop'],
    shortStory: 'Take up dreams where paused.',
  },

  {
    audioData: [' ', ''],
    word: 'tell the truth',
    meaning: ['speak honestly', 'be truthful'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['honest'],
    examples: ['Always tell truth.', 'Promise to tell truth.'],
    synonyms: ['honest'],
    antonyms: ['lie'],
    shortStory: 'Tell truth builds lasting trust.',
  },

  {
    audioData: [' ', ''],
    word: 'tend to do sth',
    meaning: ['usually do', 'habitually'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['usually'],
    examples: ['Tend to forget names.', 'Tend to arrive late.'],
    synonyms: ['usually'],
    antonyms: ['rarely'],
    shortStory: 'Tend to dream big always.',
  },

  {
    audioData: [' ', ''],
    word: 'thanks to sb/sth',
    meaning: ['because of', 'due to help'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['because'],
    examples: ['Thanks to teacher, passed.', 'Thanks to rain, grew.'],
    synonyms: ['because'],
    antonyms: ['despite'],
    shortStory: 'Thanks to courage, mountains moved.',
  },

  {
    audioData: [' ', ''],
    word: "that's it",
    meaning: ['finished', 'exactly right'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['finished'],
    examples: ["Done! That's it.", "Perfect. That's it."],
    synonyms: ['done'],
    antonyms: ['continue'],
    shortStory: "That's it; victory achieved.",
  },

  {
    audioData: [' ', ''],
    word: 'the case',
    meaning: ['situation', 'circumstance'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['situation'],
    examples: ['In that case.', 'Is that the case?'],
    synonyms: ['situation'],
    antonyms: ['different'],
    shortStory: 'In that case, magic happens.',
  },

  {
    audioData: [' ', ''],
    word: 'the fact that…',
    meaning: ['reality that', 'truth is'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['truth'],
    examples: ['Fact that you tried.', 'Despite fact that raining.'],
    synonyms: ['truth'],
    antonyms: ['fiction'],
    shortStory: 'Fact that you persisted wins.',
  },

  {
    audioData: [' ', ''],
    word: 'those who…',
    meaning: ['people that', 'individuals who'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['people who'],
    examples: ['Those who dream.', 'Those who never quit.'],
    synonyms: ['people who'],
    antonyms: ["those who don't"],
    shortStory: 'Those who believe see miracles.',
  },

  {
    audioData: [' ', ''],
    word: 'to do with sb/sth',
    meaning: ['related to/concerning', 'about'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['about'],
    examples: ['Nothing to do with me.', 'Everything to do with effort.'],
    synonyms: ['about'],
    antonyms: ['unrelated'],
    shortStory: 'Everything to do with heart.',
  },

  {
    audioData: [' ', ''],
    word: 'together with',
    meaning: ['along with', 'in addition'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['with'],
    examples: ['Coffee together with cake.', 'Family together with friends.'],
    synonyms: ['with'],
    antonyms: ['without'],
    shortStory: 'Dreams together with action succeed.',
  },

  {
    audioData: [' ', ''],
    word: 'too bad',
    meaning: ['unfortunate', "that's a pity"],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['pity'],
    examples: ['Too bad you missed it.', "Too bad it's raining."],
    synonyms: ['pity'],
    antonyms: ['lucky'],
    shortStory: 'Too bad the cake burned slightly.',
  },

  {
    audioData: [' ', ''],
    word: 'try and…',
    meaning: ['attempt to', 'endeavor'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['attempt'],
    examples: ['Try and finish on time.', 'Try and be nice.'],
    synonyms: ['attempt'],
    antonyms: ['avoid'],
    shortStory: 'Try and reach for the stars.',
  },

  {
    audioData: [' ', ''],
    word: 'turn out',
    meaning: ['result/develop', 'end up'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['result'],
    examples: ['It turned out well.', 'How did it turn out?'],
    synonyms: ['result'],
    antonyms: ['plan'],
    shortStory: 'Everything turned out perfectly.',
  },

  {
    audioData: [' ', ''],
    word: 'turn sth up',
    meaning: ['increase volume', 'raise'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['raise'],
    examples: ['Turn up the music.', 'Turn volume up.'],
    synonyms: ['raise'],
    antonyms: ['turn down'],
    shortStory: 'Turn up joy to maximum.',
  },

  {
    audioData: [' ', ''],
    word: 'unable to do sth',
    meaning: ['cannot', 'incapable'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['cannot'],
    examples: ['Unable to attend.', 'Unable to help.'],
    synonyms: ['cannot'],
    antonyms: ['able'],
    shortStory: 'Unable to fly but dreams soar.',
  },

  {
    audioData: [' ', ''],
    word: 'up to sth',
    meaning: ['planning', 'about to do mischief'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['planning'],
    examples: ['Up to no good.', "What's he up to?"],
    synonyms: ['planning'],
    antonyms: ['innocent'],
    shortStory: 'Up to magical adventures again.',
  },

  {
    audioData: [' ', ''],
    word: 'way of life',
    meaning: ['lifestyle', 'manner of living'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['lifestyle'],
    examples: ['Healthy way of life.', 'Nomad way of life.'],
    synonyms: ['lifestyle'],
    antonyms: ['routine'],
    shortStory: 'Way of life shapes destiny.',
  },

  {
    audioData: [' ', ''],
    word: 'well known',
    meaning: ['famous', 'recognized'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['famous'],
    examples: ['Well known actor.', 'Well known fact.'],
    synonyms: ['famous'],
    antonyms: ['unknown'],
    shortStory: 'Well known for boundless kindness.',
  },

  {
    audioData: [' ', ''],
    word: 'work on sth',
    meaning: ['improve/develop', 'effort on'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['improve'],
    examples: ['Work on skills.', 'Work on project.'],
    synonyms: ['improve'],
    antonyms: ['ignore'],
    shortStory: 'Work on dreams brings reality.',
  },

  {
    audioData: [' ', ''],
    word: 'work sth out',
    meaning: ['solve/calculate', 'resolve'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['solve'],
    examples: ['Work out problem.', 'Work out math.'],
    synonyms: ['solve'],
    antonyms: ['confuse'],
    shortStory: 'Work out puzzles reveals treasure.',
  },

  {
    audioData: [' ', ''],
    word: 'wrong with sb/sth',
    meaning: ['problem/fault', 'issue'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['problem'],
    examples: ["What's wrong with car?", 'Something wrong with plan.'],
    synonyms: ['problem'],
    antonyms: ['fine'],
    shortStory: "What's wrong fixes with courage.",
  },

  {
    audioData: [' ', ''],
    word: 'you see',
    meaning: ['explanation', 'I mean'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['I mean'],
    examples: ["It's simple, you see.", 'Problem is, you see.'],
    synonyms: ['I mean'],
    antonyms: ['clear'],
    shortStory: 'Magic works, you see, quietly.',
  },
];
