export const PageFourOfPhrase = [
  {
    audioData: [' ', ''],
    word: 'a bit of a',
    meaning: ['somewhat/mild problem', 'slightly'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['slightly'],
    examples: ['A bit of a mess.', 'Bit of a problem.'],
    synonyms: ['somewhat'],
    antonyms: ['major'],
    shortStory: 'A bit of a challenge builds strength.',
  },

  {
    audioData: [' ', ''],
    word: 'account for sth',
    meaning: ['explain/represent', 'cause'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['explain'],
    examples: ['Account for absence.', 'Accounts for 50%.'],
    synonyms: ['explain'],
    antonyms: ['ignore'],
    shortStory: 'Account for success: daily effort.',
  },

  {
    audioData: [' ', ''],
    word: 'accused of sth',
    meaning: ['charged with crime', 'blamed'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['blamed'],
    examples: ['Accused of stealing.', 'Accused of lying.'],
    synonyms: ['charged'],
    antonyms: ['innocent'],
    shortStory: 'Accused wrongly; truth prevails.',
  },

  {
    audioData: [' ', ''],
    word: 'act as sth',
    meaning: ['function as/serve as', 'perform role'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['serve'],
    examples: ['Act as teacher.', 'Acts as bridge.'],
    synonyms: ['serve'],
    antonyms: ['prevent'],
    shortStory: 'Act as hero in daily life.',
  },

  {
    audioData: [' ', ''],
    word: 'aimed at sb',
    meaning: ['targeted toward person', 'intended for'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['targeted'],
    examples: ['Ad aimed at children.', 'Advice aimed at students.'],
    synonyms: ['targeted'],
    antonyms: ['general'],
    shortStory: 'Message aimed at dreamers.',
  },

  {
    audioData: [' ', ''],
    word: 'aimed at doing sth',
    meaning: ['intended to achieve', 'designed for'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['intended'],
    examples: ['Campaign aimed at reducing waste.', 'Plan aimed at success.'],
    synonyms: ['intended'],
    antonyms: ['random'],
    shortStory: 'Strategy aimed at winning hearts.',
  },

  {
    audioData: [' ', ''],
    word: 'all the way',
    meaning: ['completely/entire distance', 'fully'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['completely'],
    examples: ['Support all the way.', 'Walk all the way.'],
    synonyms: ['fully'],
    antonyms: ['partly'],
    shortStory: 'Friends stay all the way.',
  },

  {
    audioData: [' ', ''],
    word: 'a means of sth',
    meaning: ['method/way to achieve', 'tool for'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['method'],
    examples: ['Means of transport.', 'Means of communication.'],
    synonyms: ['method'],
    antonyms: ['end'],
    shortStory: 'A means of magic: pure imagination.',
  },

  {
    audioData: [' ', ''],
    word: 'appeal to sb',
    meaning: ['attract/interest person', 'persuade'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['attract'],
    examples: ['Idea appeals to me.', 'Ad appeals to youth.'],
    synonyms: ['attract'],
    antonyms: ['repel'],
    shortStory: 'Kindness appeals to every heart.',
  },

  {
    audioData: [' ', ''],
    word: 'apply to sb/sth',
    meaning: ['affect/concern person/thing', 'relevant'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['affect'],
    examples: ['Rule applies to all.', 'Offer applies to students.'],
    synonyms: ['affect'],
    antonyms: ['exempt'],
    shortStory: 'Wisdom applies to every situation.',
  },

  {
    audioData: [' ', ''],
    word: 'as a whole',
    meaning: ['completely/entirely', 'altogether'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['completely'],
    examples: ['Team as a whole.', 'World as a whole.'],
    synonyms: ['entirely'],
    antonyms: ['partly'],
    shortStory: 'Universe works as a whole perfectly.',
  },

  {
    audioData: [' ', ''],
    word: 'as far as I am concerned',
    meaning: ['my opinion', 'for me'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['my opinion'],
    examples: [
      "As far as I'm concerned, perfect.",
      'For me, as far as I am concerned.',
    ],
    synonyms: ['my opinion'],
    antonyms: ['objectively'],
    shortStory: "As far as I'm concerned, magic exists.",
  },

  {
    audioData: [' ', ''],
    word: 'as follows…',
    meaning: ['what comes next', 'listed below'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['next'],
    examples: ['Rules as follows.', 'Schedule as follows.'],
    synonyms: ['next'],
    antonyms: ['above'],
    shortStory: 'Adventure as follows: courage required.',
  },

  {
    audioData: [' ', ''],
    word: 'as for sb/sth',
    meaning: ['regarding/concerning', 'about'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['about'],
    examples: [
      'Everyone happy; as for me, tired.',
      'Plans good; as for money, lacking.',
    ],
    synonyms: ['about'],
    antonyms: ['regardless'],
    shortStory: 'Stars shine; as for moon, full.',
  },

  {
    audioData: [' ', ''],
    word: 'as long as…',
    meaning: ['provided that/if', 'on condition'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['if'],
    examples: ['Stay as long as you want.', 'Help as long as you need.'],
    synonyms: ['if'],
    antonyms: ['unless'],
    shortStory: 'Dream as long as heart desires.',
  },

  {
    audioData: [' ', ''],
    word: 'associated with sth',
    meaning: ['connected to', 'linked with'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['linked'],
    examples: ['Associated with success.', 'Disease associated with smoking.'],
    synonyms: ['linked'],
    antonyms: ['unrelated'],
    shortStory: 'Stars associated with dreams forever.',
  },

  {
    audioData: [' ', ''],
    word: 'as though…',
    meaning: ['as if', 'seemingly'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['as if'],
    examples: ['Looks as though raining.', 'Acts as though king.'],
    synonyms: ['as if'],
    antonyms: ['certainly'],
    shortStory: 'Felt as though flying high.',
  },

  {
    audioData: [' ', ''],
    word: 'at once',
    meaning: ['immediately', 'now'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['now'],
    examples: ['Come at once.', 'Do it at once.'],
    synonyms: ['immediately'],
    antonyms: ['later'],
    shortStory: 'Heroes act at once bravely.',
  },

  {
    audioData: [' ', ''],
    word: 'at present',
    meaning: ['currently', 'now'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['now'],
    examples: ['Busy at present.', 'Not available at present.'],
    synonyms: ['currently'],
    antonyms: ['formerly'],
    shortStory: 'Magic works at present perfectly.',
  },

  {
    audioData: [' ', ''],
    word: 'at some point',
    meaning: ['eventually', 'sometime'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['sometime'],
    examples: ['Will happen at some point.', 'Visit at some point.'],
    synonyms: ['sometime'],
    antonyms: ['never'],
    shortStory: 'Dreams come true at some point.',
  },

  {
    audioData: [' ', ''],
    word: 'at the end of the day',
    meaning: ['ultimately', 'basically'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['ultimately'],
    examples: [
      'At the end of the day, matters.',
      'Family counts at end of day.',
    ],
    synonyms: ['ultimately'],
    antonyms: ['initially'],
    shortStory: 'Love wins at end of day.',
  },

  {
    audioData: [' ', ''],
    word: 'at this point',
    meaning: ['now', 'currently'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['now'],
    examples: ['At this point, tired.', "Can't change at this point."],
    synonyms: ['now'],
    antonyms: ['before'],
    shortStory: 'Journey peaks at this point.',
  },

  {
    audioData: [' ', ''],
    word: 'at this stage',
    meaning: ['currently', 'now'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['now'],
    examples: ['Too late at this stage.', 'Decided at this stage.'],
    synonyms: ['currently'],
    antonyms: ['earlier'],
    shortStory: 'Magic reveals at this stage.',
  },

  {
    audioData: [' ', ''],
    word: 'awareness of sth',
    meaning: ['knowledge of', 'consciousness'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['knowledge'],
    examples: ['Awareness of danger.', 'Raise awareness of issues.'],
    synonyms: ['knowledge'],
    antonyms: ['ignorance'],
    shortStory: 'Awareness of beauty transforms lives.',
  },

  {
    audioData: [' ', ''],
    word: 'back sb/sth up',
    meaning: ['support', 'save data'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['support'],
    examples: ['Back up friend.', 'Back up files.'],
    synonyms: ['support'],
    antonyms: ['oppose'],
    shortStory: 'Friends back each other up always.',
  },

  {
    audioData: [' ', ''],
    word: 'be charged with sth',
    meaning: ['accused of crime', 'formally blamed'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['accused'],
    examples: ['Charged with theft.', 'Charged with murder.'],
    synonyms: ['accused'],
    antonyms: ['cleared'],
    shortStory: 'Charged wrongly; justice finds truth.',
  },

  {
    audioData: [' ', ''],
    word: 'be derived from sth',
    meaning: ['originate from', 'come from'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['come from'],
    examples: [
      'Language derived from ancient roots.',
      'Flavors derived from fresh herbs.',
    ],
    synonyms: ['originate'],
    antonyms: ['independent'],
    shortStory: 'Strength derived from quiet persistence.',
  },

  {
    audioData: [' ', ''],
    word: 'be expected to do sth',
    meaning: ['anticipated to perform', 'ought to'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['ought to'],
    examples: ['Expected to finish by noon.', 'Expected to behave properly.'],
    synonyms: ['ought'],
    antonyms: ['unexpected'],
    shortStory: 'Stars expected to light the night.',
  },

  {
    audioData: [' ', ''],
    word: 'be known to do sth',
    meaning: ['recognized for doing', 'famous for'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['famous for'],
    examples: ['Known to keep promises.', 'Known to share wisdom.'],
    synonyms: ['famous for'],
    antonyms: ['unknown'],
    shortStory: 'Eagles known to soar highest.',
  },

  {
    audioData: [' ', ''],
    word: 'be made up of sth',
    meaning: ['consist of', 'composed of'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['consist'],
    examples: [
      'Society made up of diverse people.',
      'Soup made up of vegetables.',
    ],
    synonyms: ['consist'],
    antonyms: ['separate'],
    shortStory: 'Harmony made up of different voices.',
  },

  {
    audioData: [' ', ''],
    word: 'be surrounded by sb/sth',
    meaning: ['encircled by people/things', 'enveloped'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['encircled'],
    examples: [
      'Surrounded by loving family.',
      'Surrounded by beautiful scenery.',
    ],
    synonyms: ['encircled'],
    antonyms: ['isolated'],
    shortStory: 'Garden surrounded by fragrant flowers.',
  },

  {
    audioData: [' ', ''],
    word: 'be to blame',
    meaning: ['responsible for fault', 'guilty'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['guilty'],
    examples: ["Don't be to blame.", 'Weather to blame for delay.'],
    synonyms: ['guilty'],
    antonyms: ['innocent'],
    shortStory: 'Mistakes happen; no one to blame.',
  },

  {
    audioData: [' ', ''],
    word: 'both sides',
    meaning: ['two perspectives', 'each party'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['each party'],
    examples: ['Hear both sides.', 'Both sides agree.'],
    synonyms: ['each party'],
    antonyms: ['one side'],
    shortStory: 'Wisdom sees both sides clearly.',
  },

  {
    audioData: [' ', ''],
    word: 'bound to do sth',
    meaning: ['certain to happen', 'inevitable'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['certain'],
    examples: ['Bound to rain soon.', 'Bound to succeed eventually.'],
    synonyms: ['certain'],
    antonyms: ['unlikely'],
    shortStory: 'Truth bound to emerge victorious.',
  },

  {
    audioData: [' ', ''],
    word: 'bring sb up',
    meaning: ['raise/educate child', 'mention'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['raise'],
    examples: ['Brought up in city.', 'Bring up old memories.'],
    synonyms: ['raise'],
    antonyms: ['neglect'],
    shortStory: 'Love brings children up strong.',
  },

  {
    audioData: [' ', ''],
    word: 'by now',
    meaning: ['at this time', 'already'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['already'],
    examples: ['Should be home by now.', 'Finished by now.'],
    synonyms: ['already'],
    antonyms: ['still'],
    shortStory: 'Journey complete by now.',
  },

  {
    audioData: [' ', ''],
    word: 'call for sth',
    meaning: ['demand/require', 'request'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['demand'],
    examples: ['Situation calls for caution.', 'Recipe calls for sugar.'],
    synonyms: ['demand'],
    antonyms: ['avoid'],
    shortStory: 'Crisis calls for brave hearts.',
  },

  {
    audioData: [' ', ''],
    word: 'case study',
    meaning: ['detailed analysis example', 'in-depth examination'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['example analysis'],
    examples: ['Business case study.', 'Medical case study.'],
    synonyms: ['example'],
    antonyms: ['generalization'],
    shortStory: 'Case study reveals hidden success secrets.',
  },

  {
    audioData: [' ', ''],
    word: 'come across sb/sth',
    meaning: ['meet/find by chance', 'encounter'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['find'],
    examples: ['Came across old friend.', 'Come across treasure map.'],
    synonyms: ['encounter'],
    antonyms: ['avoid'],
    shortStory: 'Came across magic door unexpectedly.',
  },

  {
    audioData: [' ', ''],
    word: 'come true',
    meaning: ['happen as wished', 'realize'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['happen'],
    examples: ['Dreams come true.', 'Wishes come true.'],
    synonyms: ['realize'],
    antonyms: ['fail'],
    shortStory: 'Childhood dreams finally come true.',
  },

  {
    audioData: [' ', ''],
    word: 'concerned about sth',
    meaning: ['worried about', 'caring'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['worried'],
    examples: ['Concerned about health.', 'Parents concerned about safety.'],
    synonyms: ['worried'],
    antonyms: ['indifferent'],
    shortStory: 'Friends concerned about lost traveler.',
  },

  {
    audioData: [' ', ''],
    word: 'concerned with sth',
    meaning: ['related to/dealing with', 'involved'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['related'],
    examples: [
      'Book concerned with history.',
      'Meeting concerned with budget.',
    ],
    synonyms: ['related'],
    antonyms: ['unrelated'],
    shortStory: 'Story concerned with courage triumphs.',
  },

  {
    audioData: [' ', ''],
    word: 'confidence in sb/sth',
    meaning: ['trust/belief in ability', 'faith'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['trust'],
    examples: ['Confidence in team.', 'Have confidence in plan.'],
    synonyms: ['trust'],
    antonyms: ['doubt'],
    shortStory: 'Confidence in wings makes eagles soar.',
  },

  {
    audioData: [' ', ''],
    word: 'contribute to sth',
    meaning: ['add/help cause', 'give to'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['help'],
    examples: ['Contribute to charity.', 'Ideas contribute to success.'],
    synonyms: ['help'],
    antonyms: ['hinder'],
    shortStory: 'Small drops contribute to mighty rivers.',
  },

  {
    audioData: [' ', ''],
    word: 'control over sb/sth',
    meaning: ['authority/power over', 'dominance'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['power'],
    examples: ['Control over emotions.', 'Parents control over children.'],
    synonyms: ['power'],
    antonyms: ['freedom'],
    shortStory: 'True control over fear brings peace.',
  },

  {
    audioData: [' ', ''],
    word: 'cope with sth',
    meaning: ['deal with/handle', 'manage'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['manage'],
    examples: ['Cope with stress.', 'Cope with change.'],
    synonyms: ['manage'],
    antonyms: ['fail'],
    shortStory: 'Warriors cope with greatest storms.',
  },

  {
    audioData: [' ', ''],
    word: 'decline in sth',
    meaning: ['decrease/drop', 'reduce'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['decrease'],
    examples: ['Decline in sales.', 'Decline in health.'],
    synonyms: ['decrease'],
    antonyms: ['increase'],
    shortStory: 'Decline in darkness brings dawn.',
  },

  {
    audioData: [' ', ''],
    word: 'dependent on sb/sth',
    meaning: ['relying on', 'needs'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['relies'],
    examples: ['Dependent on parents.', 'Success dependent on effort.'],
    synonyms: ['relies'],
    antonyms: ['independent'],
    shortStory: 'Plants dependent on sunlight thrive.',
  },

  {
    audioData: [' ', ''],
    word: 'despite the fact that…',
    meaning: ['although/even though', 'in spite of'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['although'],
    examples: [
      'Despite the fact that raining, went out.',
      'Despite the fact tired, continued.',
    ],
    synonyms: ['although'],
    antonyms: ['because'],
    shortStory: 'Despite the fact scared, faced fears.',
  },

  {
    audioData: [' ', ''],
    word: 'draw attention to sb/sth',
    meaning: ['highlight/point out', 'focus on'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['highlight'],
    examples: [
      'Draw attention to problem.',
      'Speech draws attention to issues.',
    ],
    synonyms: ['highlight'],
    antonyms: ['ignore'],
    shortStory: 'Lights draw attention to hidden beauty.',
  },

  {
    audioData: [' ', ''],
    word: 'engage in sth',
    meaning: ['participate/do', 'involve in'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['participate'],
    examples: ['Engage in conversation.', 'Engage in sports.'],
    synonyms: ['participate'],
    antonyms: ['avoid'],
    shortStory: 'Minds engage in creative wonders.',
  },

  {
    audioData: [' ', ''],
    word: 'engaged in sth',
    meaning: ['involved/busy with', 'occupied'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['busy'],
    examples: ['Engaged in work.', 'Engaged in discussion.'],
    synonyms: ['busy'],
    antonyms: ['free'],
    shortStory: 'Warriors engaged in noble battles.',
  },

  {
    audioData: [' ', ''],
    word: 'ever since(…)',
    meaning: ['from then until now', 'since'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['since'],
    examples: ['Ever since childhood.', 'Ever since accident, careful.'],
    synonyms: ['since'],
    antonyms: ['before'],
    shortStory: 'Ever since that day, dreams grew.',
  },

  {
    audioData: [' ', ''],
    word: 'exposure to sth',
    meaning: ['contact with/experience', 'familiarity'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['contact'],
    examples: ['Exposure to art.', 'Exposure to new ideas.'],
    synonyms: ['contact'],
    antonyms: ['protection'],
    shortStory: 'Exposure to wisdom sparks enlightenment.',
  },

  {
    audioData: [' ', ''],
    word: 'far from sth',
    meaning: ['not at all/not close', 'opposite'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['opposite'],
    examples: ['Far from perfect.', 'Far from home.'],
    synonyms: ['opposite'],
    antonyms: ['near'],
    shortStory: 'Far from ordinary, pure magic.',
  },

  {
    audioData: [' ', ''],
    word: 'figure sb/sth out',
    meaning: ['understand/solve', 'comprehend'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['understand'],
    examples: ['Figure out puzzle.', "Can't figure him out."],
    synonyms: ['solve'],
    antonyms: ['confuse'],
    shortStory: 'Figure out mystery reveals hidden truth.',
  },

  {
    audioData: [' ', ''],
    word: 'find yourself doing sth',
    meaning: ['unexpectedly doing', 'end up'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['end up'],
    examples: ['Found myself laughing.', 'Find yourself agreeing.'],
    synonyms: ['end up'],
    antonyms: ['avoid'],
    shortStory: 'Found myself soaring among clouds.',
  },

  {
    audioData: [' ', ''],
    word: 'get in',
    meaning: ['enter/arrive', 'gain access'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['enter'],
    examples: ['Get in car.', 'Train gets in late.'],
    synonyms: ['enter'],
    antonyms: ['get out'],
    shortStory: 'Heroes get in through secret door.',
  },

  {
    audioData: [' ', ''],
    word: 'get over sth/sb',
    meaning: ['recover from', 'move past'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['recover'],
    examples: ['Get over cold.', 'Get over breakup.'],
    synonyms: ['recover'],
    antonyms: ['stuck'],
    shortStory: 'Time helps get over deepest wounds.',
  },

  {
    audioData: [' ', ''],
    word: 'get rid of sb/sth',
    meaning: ['remove/eliminate', 'discard'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['remove'],
    examples: ['Get rid of junk.', 'Get rid of bad habits.'],
    synonyms: ['remove'],
    antonyms: ['keep'],
    shortStory: 'Get rid of fears unlocks potential.',
  },

  {
    audioData: [' ', ''],
    word: 'go off',
    meaning: ['explode/ring/start', 'leave'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['start'],
    examples: ['Alarm goes off.', 'Gun went off.'],
    synonyms: ['explode'],
    antonyms: ['stay'],
    shortStory: 'Fireworks go off in brilliant display.',
  },

  {
    audioData: [' ', ''],
    word: 'go on to do sth',
    meaning: ['continue/proceed', 'next do'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['continue'],
    examples: ['Go on to win.', 'Go on to fame.'],
    synonyms: ['continue'],
    antonyms: ['stop'],
    shortStory: 'Climbers go on to reach summit.',
  },

  {
    audioData: [' ', ''],
    word: 'go through sth',
    meaning: ['experience/suffer', 'examine'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['experience'],
    examples: ['Go through hard times.', 'Go through papers.'],
    synonyms: ['experience'],
    antonyms: ['avoid'],
    shortStory: 'Storms go through; rainbows follow.',
  },

  {
    audioData: [' ', ''],
    word: 'had better',
    meaning: ['should/ought to', 'advice'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['should'],
    examples: ['Had better leave.', "You'd better hurry."],
    synonyms: ['should'],
    antonyms: ["shouldn't"],
    shortStory: 'Had better prepare for great adventure.',
  },

  {
    audioData: [' ', ''],
    word: 'hang on',
    meaning: ['wait/hold tight', 'persevere'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['wait'],
    examples: ['Hang on a minute.', 'Hang on tight!'],
    synonyms: ['wait'],
    antonyms: ['let go'],
    shortStory: 'Hang on through storm; sun follows.',
  },

  {
    audioData: [' ', ''],
    word: 'human being',
    meaning: ['person', 'individual'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['person'],
    examples: ['Every human being matters.', 'Fellow human being.'],
    synonyms: ['person'],
    antonyms: ['animal'],
    shortStory: 'Every human being carries universe inside.',
  },

  {
    audioData: [' ', ''],
    word: 'human rights',
    meaning: ['basic freedoms', 'inalienable rights'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['freedoms'],
    examples: ['Protect human rights.', 'Universal human rights.'],
    synonyms: ['freedoms'],
    antonyms: ['oppression'],
    shortStory: 'Human rights light path to dignity.',
  },

  {
    audioData: [' ', ''],
    word: 'if only…',
    meaning: ['wish/I hope', 'regret'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['wish'],
    examples: ['If only I knew.', 'If only it would rain.'],
    synonyms: ['wish'],
    antonyms: ['glad'],
    shortStory: 'If only wings; skies await.',
  },

  {
    audioData: [' ', ''],
    word: 'I have to say…',
    meaning: ['honestly speaking', 'to be frank'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['frankly'],
    examples: ['I have to say, impressive.', 'I have to say, disappointed.'],
    synonyms: ['frankly'],
    antonyms: ['secretly'],
    shortStory: 'I have to say, magic truly exists.',
  },

  {
    audioData: [' ', ''],
    word: 'in action',
    meaning: ['working/operating', 'active'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['active'],
    examples: ['Machine in action.', 'Heroes in action.'],
    synonyms: ['active'],
    antonyms: ['inactive'],
    shortStory: 'Wheels in action create progress.',
  },

  {
    audioData: [' ', ''],
    word: 'in advance',
    meaning: ['beforehand', 'ahead of time'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['beforehand'],
    examples: ['Pay in advance.', 'Book in advance.'],
    synonyms: ['beforehand'],
    antonyms: ['late'],
    shortStory: 'Plan in advance wins battles.',
  },

  {
    audioData: [' ', ''],
    word: 'in an attempt to do sth',
    meaning: ['trying to achieve', 'to do'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['trying'],
    examples: ['Jumped in attempt to catch.', 'Studied in attempt to pass.'],
    synonyms: ['trying'],
    antonyms: ['without trying'],
    shortStory: 'Dove in attempt to save treasure.',
  },

  {
    audioData: [' ', ''],
    word: 'in part',
    meaning: ['partly/somewhat', 'to some extent'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['partly'],
    examples: ['True in part.', 'Success in part due to luck.'],
    synonyms: ['partly'],
    antonyms: ['completely'],
    shortStory: 'Journey in part guided by stars.',
  },

  {
    audioData: [' ', ''],
    word: 'in place',
    meaning: ['proper position', 'ready'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['ready'],
    examples: ['Everything in place.', 'Plan in place.'],
    synonyms: ['ready'],
    antonyms: ['disorder'],
    shortStory: 'Pieces in place; puzzle complete.',
  },

  {
    audioData: [' ', ''],
    word: 'in relation to sb/sth',
    meaning: ['regarding/concerning', 'about'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['about'],
    examples: ['In relation to budget.', 'Comments in relation to project.'],
    synonyms: ['about'],
    antonyms: ['unrelated'],
    shortStory: 'Stars in relation to dreams shine.',
  },

  {
    audioData: [' ', ''],
    word: 'in spite of sth',
    meaning: ['although/even though', 'despite'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['despite'],
    examples: ['In spite of rain, went.', 'Success in spite of obstacles.'],
    synonyms: ['despite'],
    antonyms: ['because of'],
    shortStory: 'In spite of darkness, light prevails.',
  },

  {
    audioData: [' ', ''],
    word: 'in the first place',
    meaning: ['originally', 'to begin with'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['originally'],
    examples: ['Why in first place?', 'Not there in first place.'],
    synonyms: ['originally'],
    antonyms: ['finally'],
    shortStory: 'Seeds planted in first place grow.',
  },

  {
    audioData: [' ', ''],
    word: 'in the near future',
    meaning: ['soon/shortly', 'upcoming'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['soon'],
    examples: ['Visit in near future.', 'Changes in near future.'],
    synonyms: ['soon'],
    antonyms: ['distant'],
    shortStory: 'Dreams arrive in near future.',
  },

  {
    audioData: [' ', ''],
    word: 'in turn',
    meaning: ['one after another', 'successively'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['successively'],
    examples: ['Each in turn spoke.', 'Actions in turn create results.'],
    synonyms: ['successively'],
    antonyms: ['simultaneously'],
    shortStory: 'Stars appear in turn nightly.',
  },

  {
    audioData: [' ', ''],
    word: 'investment in sth',
    meaning: ['money/time put into', 'stake'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['stake'],
    examples: ['Investment in education.', 'Investment in future.'],
    synonyms: ['stake'],
    antonyms: ['waste'],
    shortStory: 'Investment in kindness returns richest.',
  },

  {
    audioData: [' ', ''],
    word: 'I would say...',
    meaning: ['in my opinion', 'I think'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['opinion'],
    examples: ["I would say it's perfect.", 'I would say try harder.'],
    synonyms: ['opinion'],
    antonyms: ['fact'],
    shortStory: 'I would say magic fills the air.',
  },

  {
    audioData: [' ', ''],
    word: 'loads of sb/sth',
    meaning: ['lots of/many', 'plenty'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['lots'],
    examples: ['Loads of fun.', 'Loads of books.'],
    synonyms: ['plenty'],
    antonyms: ['few'],
    shortStory: 'Loads of stars light midnight sky.',
  },

  {
    audioData: [' ', ''],
    word: 'mental health',
    meaning: ['emotional well-being', 'mind health'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['mind health'],
    examples: ['Prioritize mental health.', 'Mental health awareness.'],
    synonyms: ['well-being'],
    antonyms: ['illness'],
    shortStory: 'Mental health blooms with gentle care.',
  },

  {
    audioData: [' ', ''],
    word: 'more or less',
    meaning: ['approximately', 'roughly'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['roughly'],
    examples: ['More or less ready.', 'About 100, more or less.'],
    synonyms: ['roughly'],
    antonyms: ['exactly'],
    shortStory: 'Journey more or less complete.',
  },

  {
    audioData: [' ', ''],
    word: 'no doubt',
    meaning: ['certainly/surely', 'undoubtedly'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['surely'],
    examples: ['No doubt about it.', 'Success, no doubt.'],
    synonyms: ['surely'],
    antonyms: ['maybe'],
    shortStory: 'Truth shines, no doubt forever.',
  },

  {
    audioData: [' ', ''],
    word: 'no matter…',
    meaning: ['regardless of/whether', 'anyway'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['regardless'],
    examples: ['No matter what.', 'No matter how hard.'],
    synonyms: ['regardless'],
    antonyms: ['depends'],
    shortStory: 'No matter storms, flowers still bloom.',
  },

  {
    audioData: [' ', ''],
    word: 'nothing but',
    meaning: ['only/just', 'merely'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['only'],
    examples: ['Nothing but trouble.', 'Nothing but love.'],
    synonyms: ['only'],
    antonyms: ['more'],
    shortStory: 'Nothing but pure imagination creates wonders.',
  },

  {
    audioData: [' ', ''],
    word: 'on board',
    meaning: ['agreeing/supporting', 'joined'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['agree'],
    examples: ["I'm on board.", 'Team on board.'],
    synonyms: ['agree'],
    antonyms: ['oppose'],
    shortStory: 'All on board for grand adventure.',
  },

  {
    audioData: [' ', ''],
    word: 'once again',
    meaning: ['again/one more time', 'repeatedly'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['again'],
    examples: ['Try once again.', 'Once again victorious.'],
    synonyms: ['again'],
    antonyms: ['first'],
    shortStory: 'Phoenix rises once again gloriously.',
  },

  {
    audioData: [' ', ''],
    word: 'one another',
    meaning: ['each other', 'mutually'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['each other'],
    examples: ['Help one another.', 'Love one another.'],
    synonyms: ['each other'],
    antonyms: ['alone'],
    shortStory: 'Stars guide one another through darkness.',
  },

  {
    audioData: [' ', ''],
    word: 'on the basis of sth',
    meaning: ['based on/using', 'according to'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['based on'],
    examples: ['Decision on basis of facts.', 'Chosen on basis of skill.'],
    synonyms: ['based on'],
    antonyms: ['randomly'],
    shortStory: 'Judged on basis of heart, not appearance.',
  },

  {
    audioData: [' ', ''],
    word: 'on the one hand',
    meaning: ['considering this side', 'first point'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['first side'],
    examples: [
      'On the one hand, expensive.',
      'On one hand good, on other bad.',
    ],
    synonyms: ['firstly'],
    antonyms: ['on the other hand'],
    shortStory: 'On one hand challenges build; other tests.',
  },

  {
    audioData: [' ', ''],
    word: 'opposed to sth',
    meaning: ['against/disagreeing', 'contrary'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['against'],
    examples: ['Opposed to violence.', 'Strongly opposed to plan.'],
    synonyms: ['against'],
    antonyms: ['for'],
    shortStory: 'Heroes opposed to darkness always.',
  },

  {
    audioData: [' ', ''],
    word: 'or so',
    meaning: ['approximately/about', 'roughly'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['about'],
    examples: ['100 or so people.', 'Ten minutes or so.'],
    synonyms: ['about'],
    antonyms: ['exactly'],
    shortStory: 'Stars number countless or so.',
  },

  {
    audioData: [' ', ''],
    word: 'other than',
    meaning: ['except/besides', 'apart from'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['except'],
    examples: ['Nothing other than truth.', 'All other than him.'],
    synonyms: ['except'],
    antonyms: ['including'],
    shortStory: 'Journey other than ordinary paths.',
  },

  {
    audioData: [' ', ''],
    word: 'potential for sth',
    meaning: ['possibility/capability', 'promise'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['possibility'],
    examples: ['Potential for growth.', 'Huge potential for success.'],
    synonyms: ['possibility'],
    antonyms: ['limit'],
    shortStory: 'Seeds hold potential for forests.',
  },

  {
    audioData: [' ', ''],
    word: 'pretty much',
    meaning: ['almost/nearly', 'basically'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['almost'],
    examples: ['Pretty much finished.', 'Pretty much everyone agrees.'],
    synonyms: ['almost'],
    antonyms: ['slightly'],
    shortStory: 'Pretty much magic in every moment.',
  },

  {
    audioData: [' ', ''],
    word: 'prior to',
    meaning: ['before/earlier than', 'preceding'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['before'],
    examples: ['Prior to meeting.', 'Prior to 2020.'],
    synonyms: ['before'],
    antonyms: ['after'],
    shortStory: "Dawn prior to sun's glorious rise.",
  },

  {
    audioData: [' ', ''],
    word: 'prove to be sth',
    meaning: ['turn out as', 'become'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['become'],
    examples: ['Proved to be true.', 'Proved to be challenge.'],
    synonyms: ['become'],
    antonyms: ['fail'],
    shortStory: 'Friend proved to be greatest treasure.',
  },

  {
    audioData: [' ', ''],
    word: 'put sth forward',
    meaning: ['propose/suggest', 'present'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['suggest'],
    examples: ['Put forward idea.', 'Put forward plan.'],
    synonyms: ['suggest'],
    antonyms: ['withdraw'],
    shortStory: 'Put forward dreams; world transforms.',
  },

  {
    audioData: [' ', ''],
    word: 'put sth together',
    meaning: ['assemble/build', 'organize'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['build'],
    examples: ['Put together puzzle.', 'Put together team.'],
    synonyms: ['assemble'],
    antonyms: ['take apart'],
    shortStory: 'Put together broken pieces; masterpiece.',
  },

  {
    audioData: [' ', ''],
    word: 'quality of life',
    meaning: ['living standard/well-being', 'comfort'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['well-being'],
    examples: ['Improve quality of life.', 'High quality of life.'],
    synonyms: ['well-being'],
    antonyms: ['poverty'],
    shortStory: 'Quality of life blooms from grateful heart.',
  },

  {
    audioData: [' ', ''],
    word: 'ranging from',
    meaning: ['varying between', 'from...to'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['varying'],
    examples: ['Ages ranging from 5-10.', 'Prices ranging from low to high.'],
    synonyms: ['varying'],
    antonyms: ['same'],
    shortStory: 'Colors ranging from dawn to dusk.',
  },

  {
    audioData: [' ', ''],
    word: 'regarded as sth',
    meaning: ['considered to be', 'viewed as'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['considered'],
    examples: ['Regarded as expert.', 'Regarded as hero.'],
    synonyms: ['considered'],
    antonyms: ['disregarded'],
    shortStory: 'Regarded as legend for timeless wisdom.',
  },

  {
    audioData: [' ', ''],
    word: 'relevant to sb/sth',
    meaning: ['related/applicable', 'pertinent'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['related'],
    examples: ['Relevant to discussion.', 'Information relevant to case.'],
    synonyms: ['related'],
    antonyms: ['irrelevant'],
    shortStory: 'Words relevant to hearts touch deeply.',
  },

  {
    audioData: [' ', ''],
    word: 'rely on sb/sth',
    meaning: ['depend/trust', 'count on'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['depend'],
    examples: ['Rely on friends.', 'Rely on facts.'],
    synonyms: ['depend'],
    antonyms: ['distrust'],
    shortStory: 'Stars rely on darkness to shine.',
  },

  {
    audioData: [' ', ''],
    word: 'role model',
    meaning: ['example to follow', 'inspiration'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['example'],
    examples: ['Great role model.', 'Be role model.'],
    synonyms: ['example'],
    antonyms: ['bad influence'],
    shortStory: 'Role model lights path for many.',
  },

  {
    audioData: [' ', ''],
    word: 'set out',
    meaning: ['start journey', 'begin'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['start'],
    examples: ['Set out early.', 'Set out to conquer.'],
    synonyms: ['begin'],
    antonyms: ['return'],
    shortStory: 'Adventurers set out at dawn bravely.',
  },

  {
    audioData: [' ', ''],
    word: 'short of sth',
    meaning: ['lacking/not enough', 'deficient'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['lacking'],
    examples: ['Short of cash.', 'Short of time.'],
    synonyms: ['lacking'],
    antonyms: ['plenty'],
    shortStory: 'Short of wings but heart soars.',
  },

  {
    audioData: [' ', ''],
    word: 'so as to do sth',
    meaning: ['in order to', 'to'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['to'],
    examples: ['Whisper so as to not wake.', 'Practice so as to improve.'],
    synonyms: ['to'],
    antonyms: ['prevent'],
    shortStory: 'Climbed so as to touch stars.',
  },

  {
    audioData: [' ', ''],
    word: 'something like…',
    meaning: ['approximately/similar to', 'about'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['about'],
    examples: ['Something like 50 people.', 'Something like magic.'],
    synonyms: ['about'],
    antonyms: ['exactly'],
    shortStory: 'Something like destiny guides gently.',
  },

  {
    audioData: [' ', ''],
    word: 'sort sb/sth/yourself out',
    meaning: ['organize/fix', 'resolve'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['fix'],
    examples: ['Sort out mess.', 'Sort yourself out.'],
    synonyms: ['fix'],
    antonyms: ['mess up'],
    shortStory: 'Sort out chaos; order emerges.',
  },

  {
    audioData: [' ', ''],
    word: 'stick to sth',
    meaning: ['continue/adhere', 'persist'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['continue'],
    examples: ['Stick to plan.', 'Stick to truth.'],
    synonyms: ['persist'],
    antonyms: ['quit'],
    shortStory: 'Stick to dreams; success follows.',
  },

  {
    audioData: [' ', ''],
    word: 'subject to sth',
    meaning: ['dependent on/conditional', 'under'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['conditional'],
    examples: ['Subject to change.', 'Subject to approval.'],
    synonyms: ['conditional'],
    antonyms: ['certain'],
    shortStory: 'Plans subject to winds of fate.',
  },

  {
    audioData: [' ', ''],
    word: 'sum up',
    meaning: ['summarize/conclude', 'in short'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['summarize'],
    examples: ['To sum up.', 'Sum up points.'],
    synonyms: ['summarize'],
    antonyms: ['expand'],
    shortStory: 'Sum up life: love conquers all.',
  },

  {
    audioData: [' ', ''],
    word: 'take advantage of sb/sth',
    meaning: ['use opportunity', 'exploit'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['use'],
    examples: ['Take advantage of sale.', 'Take advantage of weather.'],
    synonyms: ['exploit'],
    antonyms: ['miss'],
    shortStory: 'Take advantage of winds; sails fill.',
  },

  {
    audioData: [' ', ''],
    word: 'take sth into account',
    meaning: ['consider/include', 'factor in'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['consider'],
    examples: ['Take budget into account.', 'Take feelings into account.'],
    synonyms: ['consider'],
    antonyms: ['ignore'],
    shortStory: 'Take wisdom into account always.',
  },

  {
    audioData: [' ', ''],
    word: 'take over',
    meaning: ['assume control', 'replace'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['control'],
    examples: ['Take over business.', 'Take over driving.'],
    synonyms: ['control'],
    antonyms: ['give up'],
    shortStory: 'Heroes take over in darkest hour.',
  },

  {
    audioData: [' ', ''],
    word: 'that is',
    meaning: ['in other words', 'namely'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['namely'],
    examples: ['Fruit, that is apples.', 'Job, that is teaching.'],
    synonyms: ['namely'],
    antonyms: ['for example'],
    shortStory: 'Magic, that is pure imagination.',
  },

  {
    audioData: [' ', ''],
    word: 'the vast majority of sth',
    meaning: ['most/almost all', 'overwhelmingly'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['most'],
    examples: ['Vast majority agree.', 'Vast majority students.'],
    synonyms: ['most'],
    antonyms: ['minority'],
    shortStory: 'Vast majority stars remain unseen.',
  },

  {
    audioData: [' ', ''],
    word: 'turn into sth',
    meaning: ['become/change to', 'transform'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['become'],
    examples: ['Turn into butterfly.', 'Water turns into ice.'],
    synonyms: ['become'],
    antonyms: ['stay'],
    shortStory: 'Frogs turn into princes magically.',
  },

  {
    audioData: [' ', ''],
    word: 'up to sb',
    meaning: ['decision of person', 'your choice'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['choice'],
    examples: ['Up to you.', 'Up to manager.'],
    synonyms: ['choice'],
    antonyms: ['decided'],
    shortStory: 'Path up to brave hearts.',
  },

  {
    audioData: [' ', ''],
    word: 'when it comes to sth',
    meaning: ['regarding/concerning', 'about'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['about'],
    examples: ['When it comes to food.', 'When comes to truth.'],
    synonyms: ['about'],
    antonyms: ['regardless'],
    shortStory: 'When comes to dreams, never quit.',
  },

  {
    audioData: [' ', ''],
    word: 'whether or not…',
    meaning: ['regardless if', 'no matter'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['regardless'],
    examples: ['Whether or not raining.', 'Go whether or not ready.'],
    synonyms: ['regardless'],
    antonyms: ['depends'],
    shortStory: 'Shine whether or not applauded.',
  },

  {
    audioData: [' ', ''],
    word: 'would rather…',
    meaning: ['prefer to', 'like better'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['prefer'],
    examples: ['Would rather stay.', 'Would rather walk.'],
    synonyms: ['prefer'],
    antonyms: ["wouldn't"],
    shortStory: 'Would rather dream than sleep.',
  },

  {
    audioData: [' ', ''],
    word: 'above all',
    meaning: ['most importantly', 'primarily'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['most'],
    examples: ['Above all, be kind.', 'Above all else.'],
    synonyms: ['primarily'],
    antonyms: ['least'],
    shortStory: 'Above all, follow your heart.',
  },

  {
    audioData: [' ', ''],
    word: 'all but',
    meaning: ['almost/nearly', 'except'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['almost'],
    examples: ['All but finished.', 'All but one.'],
    synonyms: ['almost'],
    antonyms: ['completely'],
    shortStory: 'All but invisible, yet powerful.',
  },

  {
    audioData: [' ', ''],
    word: 'all the more',
    meaning: ['even more so', 'especially'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['especially'],
    examples: ['All the more reason.', 'Beautiful all the more.'],
    synonyms: ['especially'],
    antonyms: ['less'],
    shortStory: 'Challenges make victory all the more sweet.',
  },

  {
    audioData: [' ', ''],
    word: 'as far as sb/sth is concerned',
    meaning: ['in opinion of', 'for'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['opinion'],
    examples: ["As far as I'm concerned.", 'As far as team concerned.'],
    synonyms: ['opinion'],
    antonyms: ['generally'],
    shortStory: "As far as dreamers concerned, sky's limit.",
  },

  {
    audioData: [' ', ''],
    word: 'as of…',
    meaning: ['starting from', 'since'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['since'],
    examples: ['As of tomorrow.', 'As of now.'],
    synonyms: ['since'],
    antonyms: ['until'],
    shortStory: 'As of dawn, new beginnings sparkle.',
  },

  {
    audioData: [' ', ''],
    word: 'as opposed to',
    meaning: ['rather than', 'unlike'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['rather than'],
    examples: ['Walking as opposed to driving.', 'Peace as opposed to war.'],
    synonyms: ['rather than'],
    antonyms: ['same as'],
    shortStory: 'Love as opposed to fear heals.',
  },

  {
    audioData: [' ', ''],
    word: 'as such',
    meaning: ['therefore/in that capacity', 'thus'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['therefore'],
    examples: ['Not expert, as such.', 'President as such.'],
    synonyms: ['therefore'],
    antonyms: ['however'],
    shortStory: 'Stars as such guide lost travelers.',
  },

  {
    audioData: [' ', ''],
    word: 'as to sth',
    meaning: ['regarding/concerning', 'about'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['about'],
    examples: ['As to plans.', 'Question as to why.'],
    synonyms: ['about'],
    antonyms: ['regardless'],
    shortStory: 'As to magic, believe wholeheartedly.',
  },

  {
    audioData: [' ', ''],
    word: 'at the expense of sb/sth',
    meaning: ['harming/sacrificing', 'costing'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['costing'],
    examples: ['Success at expense of health.', 'Win at expense of friend.'],
    synonyms: ['costing'],
    antonyms: ['benefiting'],
    shortStory: 'Never glory at expense of truth.',
  },

  {
    audioData: [' ', ''],
    word: 'at the hands of sb',
    meaning: ['by/from person', 'done by'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['by'],
    examples: ['Defeated at hands of rival.', 'Saved at hands of hero.'],
    synonyms: ['by'],
    antonyms: ['self'],
    shortStory: 'Fame won at hands of destiny.',
  },

  {
    audioData: [' ', ''],
    word: 'back and forth',
    meaning: ['to and fro', 'repeatedly'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['repeatedly'],
    examples: ['Pacing back and forth.', 'Discuss back and forth.'],
    synonyms: ['repeatedly'],
    antonyms: ['once'],
    shortStory: 'Pendulum swings back and forth timelessly.',
  },

  {
    audioData: [' ', ''],
    word: 'bear sb/sth in mind',
    meaning: ['remember/consider', 'keep in mind'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['remember'],
    examples: ['Bear in mind deadline.', 'Bear my words in mind.'],
    synonyms: ['remember'],
    antonyms: ['forget'],
    shortStory: "Bear stars in mind; they'll guide.",
  },

  {
    audioData: [' ', ''],
    word: 'be attributed to sb',
    meaning: ['credited to person', 'assigned to'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['credited'],
    examples: [
      'Success attributed to teamwork.',
      'Invention attributed to genius.',
    ],
    synonyms: ['credited'],
    antonyms: ['disputed'],
    shortStory: 'Victory attributed to quiet courage.',
  },

  {
    audioData: [' ', ''],
    word: 'be entitled to sth',
    meaning: ['have right to', 'deserve'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['deserve'],
    examples: ['Entitled to vacation.', 'Entitled to respect.'],
    synonyms: ['deserve'],
    antonyms: ['forfeit'],
    shortStory: 'Heroes entitled to eternal glory.',
  },

  {
    audioData: [' ', ''],
    word: 'be found to do sth',
    meaning: ['discovered doing', 'proven to'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['discovered'],
    examples: ['Found to be innocent.', 'Found to contain errors.'],
    synonyms: ['discovered'],
    antonyms: ['hidden'],
    shortStory: 'Stars found to dance in harmony.',
  },

  {
    audioData: [' ', ''],
    word: 'be meant to do sth',
    meaning: ['intended/purposed', 'destined'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['destined'],
    examples: ['Meant to be together.', 'Meant to succeed.'],
    synonyms: ['destined'],
    antonyms: ['accidental'],
    shortStory: "Paths meant to cross at destiny's hour.",
  },

  {
    audioData: [' ', ''],
    word: 'be reported to be sth',
    meaning: ['said/alleged to be', 'rumored'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['rumored'],
    examples: ['Reported to be missing.', 'Reported to be recovering.'],
    synonyms: ['rumored'],
    antonyms: ['confirmed'],
    shortStory: 'Whispers reported to carry ancient magic.',
  },

  {
    audioData: [' ', ''],
    word: 'be said to be sth',
    meaning: ['believed/reputed', 'commonly thought'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['believed'],
    examples: ['Said to be haunted.', 'Said to be genius.'],
    synonyms: ['believed'],
    antonyms: ['disproven'],
    shortStory: 'Said to be impossible; done anyway.',
  },

  {
    audioData: [' ', ''],
    word: 'bring sth about',
    meaning: ['cause/make happen', 'achieve'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['cause'],
    examples: ['Bring about change.', 'Bring about peace.'],
    synonyms: ['cause'],
    antonyms: ['prevent'],
    shortStory: 'Kindness brings about greatest miracles.',
  },

  {
    audioData: [' ', ''],
    word: 'bring sth up',
    meaning: ['mention/raise topic', 'introduce'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['mention'],
    examples: ['Bring up concern.', 'Bring up old story.'],
    synonyms: ['mention'],
    antonyms: ['avoid'],
    shortStory: 'Bring up dreams; they take flight.',
  },

  {
    audioData: [' ', ''],
    word: 'by means of sth',
    meaning: ['using/through', 'with'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['using'],
    examples: ['By means of magic.', 'By means of hard work.'],
    synonyms: ['using'],
    antonyms: ['without'],
    shortStory: 'By means of courage, mountains move.',
  },

  {
    audioData: [' ', ''],
    word: 'by no means',
    meaning: ['not at all', 'definitely not'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['not'],
    examples: ['By no means easy.', 'By no means finished.'],
    synonyms: ['not'],
    antonyms: ['certainly'],
    shortStory: 'By no means ordinary; pure magic.',
  },

  {
    audioData: [' ', ''],
    word: 'call on sb',
    meaning: ['ask/visit person', 'request'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['ask'],
    examples: ['Call on expert.', 'Call on friend for help.'],
    synonyms: ['ask'],
    antonyms: ['ignore'],
    shortStory: 'Call on inner strength; conquer all.',
  },

  {
    audioData: [' ', ''],
    word: 'consistent with sth',
    meaning: ['agreeing with/matching', 'compatible'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['matching'],
    examples: ['Consistent with evidence.', 'Results consistent with theory.'],
    synonyms: ['matching'],
    antonyms: ['inconsistent'],
    shortStory: 'Actions consistent with heart shine true.',
  },

  {
    audioData: [' ', ''],
    word: 'dedicated to sth',
    meaning: ['devoted/committed', 'focused on'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['devoted'],
    examples: ['Dedicated to family.', 'Dedicated to excellence.'],
    synonyms: ['devoted'],
    antonyms: ['indifferent'],
    shortStory: 'Dedicated souls achieve greatest wonders.',
  },

  {
    audioData: [' ', ''],
    word: 'deprive sb/sth of sth',
    meaning: ['take away from', 'deny'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['deny'],
    examples: ['Deprive children of toys.', 'Deprive of freedom.'],
    synonyms: ['deny'],
    antonyms: ['give'],
    shortStory: 'Never deprive dreams of wings.',
  },

  {
    audioData: [' ', ''],
    word: 'dispose of sb/sth',
    meaning: ['get rid of/throw away', 'deal with'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['discard'],
    examples: ['Dispose of waste.', 'Dispose of problem.'],
    synonyms: ['discard'],
    antonyms: ['keep'],
    shortStory: 'Dispose of fears; embrace courage.',
  },

  {
    audioData: [' ', ''],
    word: 'follow sth up',
    meaning: ['pursue further/investigate', 'continue'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['investigate'],
    examples: ['Follow up email.', 'Follow up lead.'],
    synonyms: ['investigate'],
    antonyms: ['ignore'],
    shortStory: 'Follow up whispers of destiny.',
  },

  {
    audioData: [' ', ''],
    word: 'for that matter',
    meaning: ['also/similarly', 'likewise'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['also'],
    examples: [
      'Not me, for that matter anyone.',
      'Not today, for that matter tomorrow.',
    ],
    synonyms: ['also'],
    antonyms: ['except'],
    shortStory: 'Not just stars, for that matter moon.',
  },

  {
    audioData: [' ', ''],
    word: 'for the benefit of sb',
    meaning: ['to help person', 'for good of'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['to help'],
    examples: ['For benefit of all.', 'Changes for benefit of students.'],
    synonyms: ['to help'],
    antonyms: ['against'],
    shortStory: 'Sacrifices made for benefit of future.',
  },

  {
    audioData: [' ', ''],
    word: 'for the sake of sb/sth',
    meaning: ['to help/because of', 'on behalf'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['to help'],
    examples: ['For sake of peace.', "For children's sake."],
    synonyms: ['to help'],
    antonyms: ['despite'],
    shortStory: 'Journey for sake of distant horizons.',
  },

  {
    audioData: [' ', ''],
    word: 'get away with sth',
    meaning: ['escape punishment', 'do without consequence'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['escape'],
    examples: ['Get away with lie.', "Won't get away with it."],
    synonyms: ['escape'],
    antonyms: ['punished'],
    shortStory: 'Truth ensures none get away forever.',
  },

  {
    audioData: [' ', ''],
    word: 'given that…',
    meaning: ['considering/because', 'since'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['because'],
    examples: ['Given that raining, stay.', 'Given that tired, rest.'],
    synonyms: ['because'],
    antonyms: ['despite'],
    shortStory: 'Given that stars shine, night beautiful.',
  },

  {
    audioData: [' ', ''],
    word: 'have sb/sth in mind',
    meaning: ['thinking of/considering', 'planning'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['thinking'],
    examples: ['Have someone in mind.', 'Have plan in mind.'],
    synonyms: ['thinking'],
    antonyms: ['forget'],
    shortStory: 'Have greatness in mind always.',
  },

  {
    audioData: [' ', ''],
    word: 'have nothing to do with sb/sth',
    meaning: ['unrelated/not connected', 'no involvement'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['unrelated'],
    examples: [
      'Nothing to do with me.',
      'Irrelevant, nothing to do with topic.',
    ],
    synonyms: ['unrelated'],
    antonyms: ['connected'],
    shortStory: 'Shadows have nothing to do with light.',
  },

  {
    audioData: [' ', ''],
    word: 'in accordance with sth',
    meaning: ['following/according to', 'as per'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['following'],
    examples: ['In accordance with rules.', 'In accordance with plan.'],
    synonyms: ['following'],
    antonyms: ['against'],
    shortStory: 'In accordance with destiny, paths converge.',
  },

  {
    audioData: [' ', ''],
    word: 'in any case',
    meaning: ['anyway/regardless', 'regardless'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['anyway'],
    examples: ['In any case, try.', "Won't work, in any case."],
    synonyms: ['anyway'],
    antonyms: ['specifically'],
    shortStory: 'In any case, courage always wins.',
  },

  {
    audioData: [' ', ''],
    word: 'in a position to do sth',
    meaning: ['able/capable', 'qualified'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['able'],
    examples: ['Not in position to help.', 'In position to decide.'],
    synonyms: ['able'],
    antonyms: ['unable'],
    shortStory: 'In position to change world forever.',
  },

  {
    audioData: [' ', ''],
    word: 'in conjunction with sb/sth',
    meaning: ['together with/jointly', 'with'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['together'],
    examples: ['In conjunction with team.', 'In conjunction with efforts.'],
    synonyms: ['together'],
    antonyms: ['alone'],
    shortStory: 'In conjunction with stars, dreams manifest.',
  },

  {
    audioData: [' ', ''],
    word: 'in connection with sb/sth',
    meaning: ['related to/regarding', 'about'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['related'],
    examples: [
      'In connection with crime.',
      'Questions in connection with project.',
    ],
    synonyms: ['related'],
    antonyms: ['unrelated'],
    shortStory: 'In connection with magic, wonder unfolds.',
  },

  {
    audioData: [' ', ''],
    word: 'in effect',
    meaning: ['actually/essentially', 'practically'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['actually'],
    examples: ['In effect, same thing.', 'Rule in effect now.'],
    synonyms: ['actually'],
    antonyms: ['theoretically'],
    shortStory: 'In effect, love conquers everything.',
  },

  {
    audioData: [' ', ''],
    word: 'in full',
    meaning: ['completely/entirely', 'total'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['completely'],
    examples: ['Pay in full.', 'See picture in full.'],
    synonyms: ['completely'],
    antonyms: ['partly'],
    shortStory: 'In full bloom, flowers dazzle.',
  },

  {
    audioData: [' ', ''],
    word: 'in line with sth',
    meaning: ['consistent with/according to', 'matching'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['matching'],
    examples: ['In line with goals.', 'In line with expectations.'],
    synonyms: ['matching'],
    antonyms: ['against'],
    shortStory: 'In line with heart, true success.',
  },

  {
    audioData: [' ', ''],
    word: 'in practice',
    meaning: ['in reality/actually', 'real life'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['actually'],
    examples: ['Good in theory, not in practice.', 'Works in practice.'],
    synonyms: ['actually'],
    antonyms: ['theory'],
    shortStory: 'In practice, kindness transforms worlds.',
  },

  {
    audioData: [' ', ''],
    word: 'in respect of sth',
    meaning: ['regarding/concerning', 'about'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['about'],
    examples: ['In respect of payment.', 'In respect of quality.'],
    synonyms: ['about'],
    antonyms: ['regardless'],
    shortStory: 'In respect of dreams, never surrender.',
  },

  {
    audioData: [' ', ''],
    word: 'in such a way (that)…',
    meaning: ['so that/manner causing', 'resulting'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['so that'],
    examples: [
      'In such a way that everyone understands.',
      'Built in such way that lasts.',
    ],
    synonyms: ['so that'],
    antonyms: ['preventing'],
    shortStory: 'In such way that stars align perfectly.',
  },

  {
    audioData: [' ', ''],
    word: 'in the absence of sb/sth',
    meaning: ['without/not having', 'lacking'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['without'],
    examples: ['In absence of evidence.', 'In absence of leader.'],
    synonyms: ['without'],
    antonyms: ['with'],
    shortStory: 'In absence of fear, courage reigns.',
  },

  {
    audioData: [' ', ''],
    word: 'in the course of…',
    meaning: ['during/while', 'over time'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['during'],
    examples: ['In course of day.', 'In course of history.'],
    synonyms: ['during'],
    antonyms: ['outside'],
    shortStory: 'In course of journey, wisdom grows.',
  },

  {
    audioData: [' ', ''],
    word: 'in the event of sth',
    meaning: ['if/when happens', 'in case of'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['if'],
    examples: ['In event of rain, cancel.', 'Plan in event of emergency.'],
    synonyms: ['if'],
    antonyms: ['unless'],
    shortStory: 'In event of darkness, stars appear.',
  },

  {
    audioData: [' ', ''],
    word: 'in the face of sth',
    meaning: ['despite/confronting', 'against'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['despite'],
    examples: ['In face of danger.', 'Courage in face of fear.'],
    synonyms: ['despite'],
    antonyms: ['avoiding'],
    shortStory: 'In face of storms, heroes stand.',
  },

  {
    audioData: [' ', ''],
    word: 'in the hands of sb',
    meaning: ['controlled by/managed by', 'up to'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['controlled'],
    examples: ['Future in hands of youth.', 'Decision in hands of judge.'],
    synonyms: ['controlled'],
    antonyms: ['independent'],
    shortStory: 'Destiny in hands of dreamers.',
  },

  {
    audioData: [' ', ''],
    word: 'in the light of sth',
    meaning: ['considering/given', 'because of'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['considering'],
    examples: ['In light of new evidence.', 'In light of experience.'],
    synonyms: ['considering'],
    antonyms: ['ignoring'],
    shortStory: 'In light of truth, shadows vanish.',
  },

  {
    audioData: [' ', ''],
    word: 'in the meantime',
    meaning: ['for now/temporarily', 'meanwhile'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['meanwhile'],
    examples: ['Wait in meantime.', 'Work in meantime.'],
    synonyms: ['meanwhile'],
    antonyms: ['afterwards'],
    shortStory: 'In meantime, plant seeds of hope.',
  },

  {
    audioData: [' ', ''],
    word: 'in the midst of sth',
    meaning: ['during/among', 'surrounded by'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['during'],
    examples: ['In midst of chaos.', 'In midst of celebration.'],
    synonyms: ['during'],
    antonyms: ['outside'],
    shortStory: 'In midst of winter, spring waits.',
  },

  {
    audioData: [' ', ''],
    word: 'in the presence of sb',
    meaning: ['with/near person', 'before'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['with'],
    examples: ['In presence of king.', 'In presence of loved ones.'],
    synonyms: ['with'],
    antonyms: ['absence'],
    shortStory: 'In presence of love, miracles happen.',
  },

  {
    audioData: [' ', ''],
    word: 'in the wake of sb/sth',
    meaning: ['following/after', 'resulting from'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['after'],
    examples: ['In wake of storm.', 'In wake of victory.'],
    synonyms: ['after'],
    antonyms: ['before'],
    shortStory: 'In wake of courage, legends born.',
  },

  {
    audioData: [' ', ''],
    word: 'involvement in sth',
    meaning: ['participation/role', 'engagement'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['participation'],
    examples: ['Involvement in project.', 'Active involvement in community.'],
    synonyms: ['participation'],
    antonyms: ['detachment'],
    shortStory: 'Involvement in dreams creates reality.',
  },

  {
    audioData: [' ', ''],
    word: 'let alone',
    meaning: ['not to mention', 'far from'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['not even'],
    examples: [
      "Can't afford food, let alone car.",
      'No time to eat, let alone sleep.',
    ],
    synonyms: ['not even'],
    antonyms: ['as well as'],
    shortStory: "Can't see stars, let alone moon.",
  },

  {
    audioData: [' ', ''],
    word: 'little more than…',
    meaning: ['basically just', 'almost only'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['almost'],
    examples: ['Little more than child.', 'Little more than rumor.'],
    synonyms: ['almost'],
    antonyms: ['much more'],
    shortStory: 'Little more than spark ignites fire.',
  },

  {
    audioData: [' ', ''],
    word: 'live on sth',
    meaning: ['survive using', 'depend on'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['survive'],
    examples: ['Live on bread.', 'Live on $100 week.'],
    synonyms: ['survive'],
    antonyms: ['thrive'],
    shortStory: 'Live on hope through darkest nights.',
  },

  {
    audioData: [' ', ''],
    word: 'may well',
    meaning: ['probably/likely', 'quite possible'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['probably'],
    examples: ['May well rain.', 'May well be true.'],
    synonyms: ['probably'],
    antonyms: ['unlikely'],
    shortStory: 'May well find treasure beyond hill.',
  },

  {
    audioData: [' ', ''],
    word: 'nothing like',
    meaning: ['completely unlike', 'totally different'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['unlike'],
    examples: ['Nothing like home.', 'Nothing like summer.'],
    synonyms: ['unlike'],
    antonyms: ['just like'],
    shortStory: "Nothing like first love's pure magic.",
  },

  {
    audioData: [' ', ''],
    word: 'not to mention',
    meaning: ['and also', 'plus'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['plus'],
    examples: [
      'Expensive, not to mention heavy.',
      'Smart, not to mention kind.',
    ],
    synonyms: ['plus'],
    antonyms: ['let alone'],
    shortStory: 'Beautiful, not to mention enchanting.',
  },

  {
    audioData: [' ', ''],
    word: 'on behalf of sb',
    meaning: ['for/representing person', 'as agent'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['for'],
    examples: ['On behalf of team.', 'Speaking on behalf of all.'],
    synonyms: ['for'],
    antonyms: ['against'],
    shortStory: 'On behalf of dreamers, chase stars.',
  },

  {
    audioData: [' ', ''],
    word: 'on the part of sb',
    meaning: ['by/from person', 'done by'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['by'],
    examples: ['Mistake on my part.', 'Effort on their part.'],
    synonyms: ['by'],
    antonyms: ['automatic'],
    shortStory: 'Courage on part of ordinary souls.',
  },

  {
    audioData: [' ', ''],
    word: 'over the course of…',
    meaning: ['during/throughout', 'gradually'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['during'],
    examples: ['Over course of year.', 'Over course of time.'],
    synonyms: ['during'],
    antonyms: ['suddenly'],
    shortStory: 'Over course of seasons, wisdom grows.',
  },

  {
    audioData: [' ', ''],
    word: 'put it',
    meaning: ['express/say', 'phrase'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['say'],
    examples: ['Put it simply.', 'How to put it.'],
    synonyms: ['say'],
    antonyms: ['hide'],
    shortStory: 'Put it boldly: dreams never die.',
  },

  {
    audioData: [' ', ''],
    word: 'seek to do sth',
    meaning: ['try/aim to', 'attempt'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['try'],
    examples: ['Seek to understand.', 'Seek to improve.'],
    synonyms: ['try'],
    antonyms: ['avoid'],
    shortStory: 'Seek to touch the unreachable star.',
  },

  {
    audioData: [' ', ''],
    word: 'set to do sth',
    meaning: ['ready/prepared to', 'about to'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['ready'],
    examples: ['Set to begin.', 'Set to win race.'],
    synonyms: ['ready'],
    antonyms: ['unprepared'],
    shortStory: 'Set to conquer mountains at dawn.',
  },

  {
    audioData: [' ', ''],
    word: 'the extent to which…',
    meaning: ['degree/amount that', 'how much'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['how much'],
    examples: ['Extent to which helps.', 'Degree to which true.'],
    synonyms: ['how much'],
    antonyms: ['regardless'],
    shortStory: 'Extent to which hearts unite determines strength.',
  },

  {
    audioData: [' ', ''],
    word: 'to date',
    meaning: ['until now/so far', 'up to present'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['so far'],
    examples: ['Best to date.', 'Progress to date.'],
    synonyms: ['so far'],
    antonyms: ['from now'],
    shortStory: 'Greatest discoveries to date inspire tomorrow.',
  },

  {
    audioData: [' ', ''],
    word: 'up against sth',
    meaning: ['facing/confronting', 'challenged by'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['facing'],
    examples: ['Up against deadline.', 'Up against tough opponent.'],
    synonyms: ['facing'],
    antonyms: ['supported'],
    shortStory: 'Up against storms, ships prove strongest.',
  },

  {
    audioData: [' ', ''],
    word: 'with regard to sb/sth',
    meaning: ['regarding/concerning', 'about'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['about'],
    examples: ['With regard to plans.', 'Questions with regard to budget.'],
    synonyms: ['about'],
    antonyms: ['regardless'],
    shortStory: 'With regard to dreams, never compromise.',
  },

  {
    audioData: [' ', ''],
    word: 'with respect to sth',
    meaning: ['concerning/regarding', 'about'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['about'],
    examples: ['With respect to time.', 'Changes with respect to policy.'],
    synonyms: ['about'],
    antonyms: ['unrelated'],
    shortStory: 'With respect to truth, speak boldly.',
  },

  {
    audioData: [' ', ''],
    word: 'with the exception of sb/sth',
    meaning: ['except/but not', 'excluding'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['except'],
    examples: [
      'All with exception of one.',
      'Perfect with exception of color.',
    ],
    synonyms: ['except'],
    antonyms: ['including'],
    shortStory: 'Stars shine, with exception of cloudy nights.',
  },
];
