export const PageOneOfPhrase = [
  {
    audioData: [' ', ''],
    word: 'a few',
    meaning: ['a small number of', 'some (countable)'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['some', 'handful'],
    examples: ['A few students arrived early.', 'I have a few ideas to share.'],
    synonyms: ['some', 'several'],
    antonyms: ['few', 'many'],
    shortStory:
      'A few brave explorers ventured into the misty forest, discovering treasures hidden for centuries.',
  },
  {
    audioData: [' ', ''],
    word: 'a good idea',
    meaning: ['a sensible suggestion', 'a beneficial plan'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['smart plan'],
    examples: [
      'Sharing the workload is a good idea.',
      "Let's try that—it's a good idea.",
    ],
    synonyms: ['smart move', 'wise choice'],
    antonyms: ['bad idea', 'poor plan'],
    shortStory:
      'Calling a friend for advice proved a good idea, as her wisdom turned confusion into clear direction.',
  },
  {
    audioData: [' ', ''],
    word: 'agree with sb',
    meaning: ['have the same opinion as someone', "share a person's view"],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['same opinion'],
    examples: [
      'I agree with you completely.',
      'Do you agree with the teacher?',
    ],
    synonyms: ['side with', 'concur with'],
    antonyms: ['disagree with', 'oppose'],
    shortStory:
      'When tensions rose in the meeting, she chose to agree with her colleague, strengthening their united front against the challenge.',
  },
  {
    audioData: [' ', ''],
    word: 'a little',
    meaning: [
      'a small amount of something uncountable',
      'slightly or to a small degree',
    ],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['small amount', 'slightly'],
    examples: [
      'Add a little salt to the soup.',
      "I'm a little tired after the walk.",
    ],
    synonyms: ['a bit', 'some'],
    antonyms: ['a lot', 'much'],
    shortStory:
      "A little patience turned the tangled knot into neat loops, revealing the sailor's clever trick to the amazed crew.",
  },
  {
    audioData: [' ', ''],
    word: 'a lot',
    meaning: ['a large amount or number', 'very much'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['many', 'much'],
    examples: ['She has a lot of books.', 'I eat a lot during holidays.'],
    synonyms: ['plenty', 'tons'],
    antonyms: ['a little', 'few'],
    shortStory:
      'He practiced a lot before the big game, turning nervous energy into the winning goal that thrilled the crowd.',
  },
  {
    audioData: [' ', ''],
    word: 'a lot of sth',
    meaning: ['a large quantity of something', 'many or much of a thing'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['lots of something'],
    examples: [
      "There's a lot of traffic today.",
      'She bought a lot of clothes.',
    ],
    synonyms: ['lots of', 'plenty of'],
    antonyms: ['a little of', 'not much'],
    shortStory:
      'A lot of fresh snow covered the hills, inviting the children to build their grandest snowman yet.',
  },
  {
    audioData: [' ', ''],
    word: 'all day',
    meaning: ['the entire day', 'from morning until night'],
    partOfSpeech: ['adverbial phrase'],
    simpleDefinition: ['whole day'],
    examples: ["I've been working all day.", 'It rained all day long.'],
    synonyms: ['the whole day', 'throughout the day'],
    antonyms: ['a short time'],
    shortStory:
      'She waited all day by the window, her heart lifting when the familiar figure finally appeared at dusk.',
  },
  {
    audioData: [' ', ''],
    word: 'all over the world',
    meaning: ['everywhere on Earth', 'in every country'],
    partOfSpeech: ['adverbial phrase'],
    simpleDefinition: ['globally', 'worldwide'],
    examples: [
      'People all over the world celebrate New Year.',
      'The news spread all over the world.',
    ],
    synonyms: ['globally', 'worldwide'],
    antonyms: ['locally', 'in one place'],
    shortStory:
      'Musicians gathered all over the world for the grand concert, their harmonies uniting hearts across continents.',
  },
  {
    audioData: [' ', ''],
    word: 'anything else',
    meaning: ['is there more?', 'something additional?'],
    partOfSpeech: ['question phrase'],
    simpleDefinition: ['more?', 'else?'],
    examples: [
      'Is there anything else I can help with?',
      'Anything else to add?',
    ],
    synonyms: ['something more?', 'else?'],
    antonyms: ["that's all"],
    shortStory:
      "'Anything else?' the shopkeeper asked with a smile, as the child clutched the perfect toy and shook their head happily.",
  },

  {
    audioData: [' ', ''],
    word: 'a period of time',
    meaning: ['a length or duration', 'some amount of time'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['duration', 'while'],
    examples: [
      'It took a period of time to finish.',
      'After a period of time, she returned.',
    ],
    synonyms: ['some time', 'a while'],
    antonyms: ['instant', 'moment'],
    shortStory:
      'During a period of time in the quiet library, the old book revealed secrets long forgotten by modern readers.',
  },
  {
    audioData: [' ', ''],
    word: 'around the world',
    meaning: ['in many countries globally', 'everywhere on Earth'],
    partOfSpeech: ['adverbial phrase'],
    simpleDefinition: ['worldwide'],
    examples: [
      'Travelers come from around the world.',
      'News spreads around the world fast.',
    ],
    synonyms: ['globally', 'internationally'],
    antonyms: ['locally'],
    shortStory:
      "Adventurers journeyed around the world, collecting tales that wove the planet's diverse cultures into one grand tapestry.",
  },
  {
    audioData: [' ', ''],
    word: 'arrive at…',
    meaning: ['reach a specific place or point', 'get to a particular spot'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['reach place'],
    examples: [
      'We arrive at the station at 5 PM.',
      'Arrive at the correct answer.',
    ],
    synonyms: ['get to', 'reach'],
    antonyms: ['leave'],
    shortStory:
      'They arrive at the summit just as dawn broke, rewarded with a sunrise painting the peaks in golden light.',
  },
  {
    audioData: [' ', ''],
    word: 'arrive in…',
    meaning: ['reach a large area or country', 'enter a city or nation'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['enter area'],
    examples: ['We arrive in Paris tomorrow.', 'Arrive in town by noon.'],
    synonyms: ['get to', 'land in'],
    antonyms: ['depart from'],
    shortStory:
      'The ship would arrive in harbor after stormy seas, unloading weary sailors eager for solid ground.',
  },
  {
    audioData: [' ', ''],
    word: 'ask for sth',
    meaning: ['request something', 'demand or seek'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['request'],
    examples: ['Ask for help if needed.', "Don't ask for too much."],
    synonyms: ['request', 'seek'],
    antonyms: ['offer'],
    shortStory:
      'The beggar would ask for a coin, but received a warm meal that changed his entire day.',
  },
  {
    audioData: [' ', ''],
    word: 'at home',
    meaning: ["in one's house or residence", 'in a familiar place'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['home'],
    examples: ['Stay at home today.', 'She feels safe at home.'],
    synonyms: ['indoors', 'in the house'],
    antonyms: ['away'],
    shortStory:
      'Curled up at home by the fire, the family shared stories that warmed them more than the flames.',
  },
  {
    audioData: [' ', ''],
    word: 'at school',
    meaning: ['in the educational institution', 'during school time'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['school'],
    examples: ['Children are at school now.', 'Behave at school.'],
    synonyms: ['in class'],
    antonyms: ['at home'],
    shortStory:
      'At school, the shy student discovered painting, unleashing colors that spoke louder than words ever could.',
  },
  {
    audioData: [' ', ''],
    word: 'at the beginning of sth',
    meaning: ['start of something', 'early stage'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['start'],
    examples: [
      'At the beginning of class, take notes.',
      'At the beginning of summer.',
    ],
    synonyms: ['to start', 'initially'],
    antonyms: ['at the end'],
    shortStory:
      'At the beginning of the journey, doubts clouded their minds, but each step built unbreakable confidence.',
  },
  {
    audioData: [' ', ''],
    word: 'at the end',
    meaning: ['final part', 'conclusion'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['finish'],
    examples: ['At the end of the movie, cry.', 'Wait at the end.'],
    synonyms: ['finally'],
    antonyms: ['at the beginning'],
    shortStory:
      'At the end of the race, exhausted but triumphant, she crossed the line to cheers.',
  },
  {
    audioData: [' ', ''],
    word: 'at the end of sth',
    meaning: ['final part of something specific', 'after completion'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['after'],
    examples: ['At the end of the book.', 'At the end of the week.'],
    synonyms: ['finally'],
    antonyms: ['beginning'],
    shortStory:
      'At the end of the dark tunnel, light promised adventure beyond the shadows of fear.',
  },
  {
    audioData: [' ', ''],
    word: 'at the moment',
    meaning: ['right now', 'currently'],
    partOfSpeech: ['adverbial phrase'],
    simpleDefinition: ['now'],
    examples: ["I'm busy at the moment.", "At the moment, it's raining."],
    synonyms: ['currently', 'now'],
    antonyms: ['later'],
    shortStory:
      'At the moment the clock struck midnight, magic filled the air, transforming pumpkins into carriages.',
  },
  {
    audioData: [' ', ''],
    word: 'at the same time',
    meaning: ['simultaneously', 'together'],
    partOfSpeech: ['adverbial phrase'],
    simpleDefinition: ['together'],
    examples: ['Laugh and cry at the same time.', 'Study at the same time.'],
    synonyms: ['simultaneously', 'together'],
    antonyms: ['separately'],
    shortStory:
      'At the same time, hearts beat faster as rivals became friends in unexpected harmony.',
  },
  {
    audioData: [' ', ''],
    word: 'at the weekend',
    meaning: ['during Saturday and Sunday', 'on weekends'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['weekend'],
    examples: ['We relax at the weekend.', 'Party at the weekend.'],
    synonyms: ['on weekends'],
    antonyms: ['weekdays'],
    shortStory:
      'At the weekend, the town square buzzed with markets and music, drawing everyone outdoors.',
  },
  {
    audioData: [' ', ''],
    word: 'at university',
    meaning: ['during higher education', 'at college/university'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['college'],
    examples: ['Study at university.', 'She met him at university.'],
    synonyms: ['in college'],
    antonyms: ['at school'],
    shortStory:
      'At university, wide eyes drank in knowledge, friendships formed, and futures began to sparkle.',
  },
  {
    audioData: [' ', ''],
    word: 'at work',
    meaning: ['during employment hours', 'on the job'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['job'],
    examples: ["Don't call at work.", 'Busy at work.'],
    synonyms: ['on the job'],
    antonyms: ['at home'],
    shortStory:
      'At work, the quiet clerk uncovered a clever scheme, turning routine into heroic action.',
  },
  {
    audioData: [' ', ''],
    word: 'away from sb/sth',
    meaning: ['at a distance from someone or something', 'separated from'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['distant', 'apart'],
    examples: ['Stay away from the fire.', 'She moved away from home.'],
    synonyms: ['distant from', 'apart from'],
    antonyms: ['near to', 'close to'],
    shortStory:
      "The child ran away from the storm, finding shelter where rain couldn't reach.",
  },
  {
    audioData: [' ', ''],
    word: 'bad for sb/sth',
    meaning: ['harmful to someone or something', 'negative effect'],
    partOfSpeech: ['adjective phrase'],
    simpleDefinition: ['harmful'],
    examples: ['Sugar is bad for teeth.', 'Stress is bad for health.'],
    synonyms: ['harmful', 'unhealthy'],
    antonyms: ['good for'],
    shortStory:
      "Junk food seemed fun but proved bad for the team's energy during the big match.",
  },
  {
    audioData: [' ', ''],
    word: 'bad news',
    meaning: ['unpleasant information', 'negative update'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['sad info'],
    examples: ["I'm sorry, that's bad news.", 'Breaking bad news gently.'],
    synonyms: ['sad tidings', 'ill tidings'],
    antonyms: ['good news'],
    shortStory:
      'The bad news of the canceled trip crushed dreams, but sparked a backyard adventure instead.',
  },
  {
    audioData: [' ', ''],
    word: 'bad thing',
    meaning: ['something negative', 'unpleasant event'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['negative event'],
    examples: ['Losing keys is a bad thing.', 'Not the worst bad thing.'],
    synonyms: ['negative', 'misfortune'],
    antonyms: ['good thing'],
    shortStory:
      'What seemed a bad thing—the broken bike—taught him to fix it himself with pride.',
  },
  {
    audioData: [' ', ''],
    word: 'because of',
    meaning: ['due to a reason', 'on account of'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['due to'],
    examples: ['Late because of traffic.', 'Success because of hard work.'],
    synonyms: ['due to', 'owing to'],
    antonyms: ['despite'],
    shortStory:
      "Because of the kind stranger's map, the lost hiker found the path home before dark.",
  },
  {
    audioData: [' ', ''],
    word: 'begin with sth',
    meaning: ['start with something', 'commence using'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['start'],
    examples: ["Let's begin with introductions.", 'Recipe begins with onions.'],
    synonyms: ['start with', 'commence'],
    antonyms: ['end with'],
    shortStory:
      'Stories begin with a single spark of imagination, growing into worlds of wonder.',
  },
  {
    audioData: [' ', ''],
    word: 'be going to do sth',
    meaning: ['plan or intend to do', 'future intention'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['will do'],
    examples: ["I'm going to call her.", "It's going to rain."],
    synonyms: ['plan to', 'intend to'],
    antonyms: ["won't"],
    shortStory:
      'She was going to quit, but one more try led to unexpected victory.',
  },
  {
    audioData: [' ', ''],
    word: 'best friend',
    meaning: ['closest companion', 'most trusted pal'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['closest pal'],
    examples: [
      'My best friend understands me.',
      'Tell your best friend first.',
    ],
    synonyms: ['bosom buddy', 'soulmate'],
    antonyms: ['stranger', 'enemy'],
    shortStory:
      'Her best friend shared every secret, turning ordinary days into treasured memories.',
  },
  {
    audioData: [' ', ''],
    word: 'black and white',
    meaning: ['monochrome', 'clear and simple'],
    partOfSpeech: ['adjective phrase'],
    simpleDefinition: ['no color', 'clear'],
    examples: ['Black and white photo.', "Life isn't black and white."],
    synonyms: ['monochrome', 'straightforward'],
    antonyms: ['color', 'gray area'],
    shortStory:
      'The old black and white film captured emotions more vividly than modern colors ever could.',
  },
  {
    audioData: [' ', ''],
    word: 'car park',
    meaning: ['parking lot', 'area for vehicles'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['parking lot'],
    examples: ['Park in the car park.', 'Full car park ahead.'],
    synonyms: ['parking lot'],
    antonyms: ['no parking'],
    shortStory:
      'In the crowded car park, he found the last spot, just in time for the show.',
  },
  {
    audioData: [' ', ''],
    word: 'cell phone',
    meaning: ['mobile telephone', 'handheld device'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['mobile'],
    examples: ['Lost my cell phone.', 'Check your cell phone.'],
    synonyms: ['mobile phone', 'smartphone'],
    antonyms: ['landline'],
    shortStory:
      'Her cell phone buzzed with a message that changed the course of her entire day.',
  },
  {
    audioData: [' ', ''],
    word: 'city centre',
    meaning: ['downtown area', 'central urban district'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['downtown'],
    examples: ['Shops in the city centre.', 'Traffic in city centre.'],
    synonyms: ['downtown', 'central business district'],
    antonyms: ['suburbs'],
    shortStory:
      'The city centre pulsed with life, where street performers wove magic amid bustling crowds.',
  },
  {
    audioData: [' ', ''],
    word: 'come from…',
    meaning: ['originate from a place or source', 'be born or made in'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['from origin'],
    examples: ['I come from Dhaka.', 'Coffee comes from beans.'],
    synonyms: ['originate', 'hail from'],
    antonyms: ['go to'],
    shortStory:
      'She comes from a mountain village where stories flow like rivers, carrying wisdom through generations.',
  },
  {
    audioData: [' ', ''],
    word: 'come into sth',
    meaning: ['inherit money or property', 'receive unexpectedly'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['inherit'],
    examples: ['He came into a fortune.', 'She came into family land.'],
    synonyms: ['inherit', 'receive'],
    antonyms: ['give away'],
    shortStory:
      'When he came into the old mansion, dusty portraits whispered family secrets long hidden.',
  },
  {
    audioData: [' ', ''],
    word: 'differences between A and B',
    meaning: ['ways A and B are not the same', 'comparison points'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['how different'],
    examples: [
      'What are the differences between cats and dogs?',
      'Note the differences between A and B.',
    ],
    synonyms: ['contrast', 'dissimilarities'],
    antonyms: ['similarities'],
    shortStory:
      'Exploring differences between the ancient maps revealed the true path to the lost treasure.',
  },
  {
    audioData: [' ', ''],
    word: 'difficult for sb',
    meaning: ['hard or challenging for someone', 'problematic for'],
    partOfSpeech: ['adjective phrase'],
    simpleDefinition: ['hard for'],
    examples: [
      'Math is difficult for me.',
      'The task was difficult for beginners.',
    ],
    synonyms: ['hard', 'challenging'],
    antonyms: ['easy for'],
    shortStory:
      'Public speaking was difficult for the shy boy, until one passionate speech changed everything.',
  },

  {
    audioData: [' ', ''],
    word: 'each other',
    meaning: ['mutual action between two or more', 'reciprocally'],
    partOfSpeech: ['reciprocal pronoun'],
    simpleDefinition: ['mutually'],
    examples: ['They love each other.', 'Help each other study.'],
    synonyms: ['one another'],
    antonyms: ['alone'],
    shortStory:
      "The twins finished each other's sentences, their unbreakable bond amazing everyone around them.",
  },
  {
    audioData: [' ', ''],
    word: 'end in sth',
    meaning: ['result or finish with something', 'conclude with'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['finish with'],
    examples: ['Most diets end in failure.', 'The story ends in happiness.'],
    synonyms: ['result in', 'conclude'],
    antonyms: ['begin with'],
    shortStory:
      'What began as a simple argument would end in laughter when they realized the silly misunderstanding.',
  },
  {
    audioData: [' ', ''],
    word: 'every day',
    meaning: ['each day', 'daily routine'],
    partOfSpeech: ['adverbial phrase'],
    simpleDefinition: ['daily'],
    examples: ['I exercise every day.', 'She calls every day.'],
    synonyms: ['daily'],
    antonyms: ['never'],
    shortStory:
      "Every day at dawn, the fisherman cast his nets, patient for the day's unexpected bounty.",
  },
  {
    audioData: [' ', ''],
    word: 'excuse me',
    meaning: ['polite interruption', 'sorry for attention'],
    partOfSpeech: ['interjection'],
    simpleDefinition: ['sorry'],
    examples: ["Excuse me, where's the station?", 'Excuse me, pardon.'],
    synonyms: ['pardon', 'sorry'],
    antonyms: ['ignore'],
    shortStory:
      "'Excuse me,' whispered the child, politely gaining the librarian's help to reach the top shelf.",
  },
  {
    audioData: [' ', ''],
    word: 'family member',
    meaning: ['relative or kin', 'part of family'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['relative'],
    examples: ['My family member visited.', 'Close family member.'],
    synonyms: ['relative', 'kin'],
    antonyms: ['stranger'],
    shortStory:
      'The lost family member returned home after years, embraced by tears and joyful reunion.',
  },
  {
    audioData: [' ', ''],
    word: 'find out',
    meaning: ['discover information', 'learn or uncover'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['discover'],
    examples: ['Find out the truth.', 'I found out later.'],
    synonyms: ['discover', 'learn'],
    antonyms: ['hide'],
    shortStory:
      "Curious detectives would find out the thief's clever disguise through careful observation.",
  },
  {
    audioData: [' ', ''],
    word: 'for a long time',
    meaning: ['during an extended period', 'over many moments'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['long while'],
    examples: [
      "I've waited for a long time.",
      "They've known each other for a long time.",
    ],
    synonyms: ['for ages', 'over a long period'],
    antonyms: ['for a short time'],
    shortStory:
      'She practiced piano for a long time, transforming clumsy fingers into masterful melodies.',
  },
  {
    audioData: [' ', ''],
    word: 'for a moment',
    meaning: ['briefly', 'for a very short time'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['briefly'],
    examples: ['Wait for a moment.', 'He paused for a moment.'],
    synonyms: ['briefly', 'a second'],
    antonyms: ['for a long time'],
    shortStory:
      'For a moment, time froze as their eyes met across the crowded room, sparking instant connection.',
  },
  {
    audioData: [' ', ''],
    word: 'for example',
    meaning: ['to illustrate a point', 'such as'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['e.g.'],
    examples: ['Fruits, for example, apples.', 'For example, see this case.'],
    synonyms: ['such as', 'e.g.'],
    antonyms: ['for instance (negative)'],
    shortStory:
      'For example, the tiny seed grew into a mighty tree, proving patience yields wonders.',
  },
  {
    audioData: [' ', ''],
    word: 'for lunch',
    meaning: ['during midday meal', 'at lunchtime'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['lunchtime'],
    examples: ['Meet for lunch at noon.', "What's for lunch today?"],
    synonyms: ['at lunchtime'],
    antonyms: ['for breakfast'],
    shortStory:
      'They shared stories for lunch, turning a simple meal into cherished friendship moments.',
  },
  {
    audioData: [' ', ''],
    word: 'for many years',
    meaning: ['over a long duration', 'extended period'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['long time'],
    examples: ['Lived here for many years.', 'Worked for many years.'],
    synonyms: ['for years', 'over decades'],
    antonyms: ['for a short time'],
    shortStory:
      'The old bridge stood for many years, witness to generations crossing its sturdy span.',
  },
  {
    audioData: [' ', ''],
    word: 'for the first time',
    meaning: ['initial experience', 'never before'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['first'],
    examples: [
      'Saw snow for the first time.',
      'Trying sushi for the first time.',
    ],
    synonyms: ['initially', 'firstly'],
    antonyms: ['again'],
    shortStory:
      'For the first time, she flew solo, soaring above clouds with newfound freedom.',
  },
  {
    audioData: [' ', ''],
    word: 'get home',
    meaning: ['arrive at residence', 'return home'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['return home'],
    examples: ["I'll get home late.", 'Safe to get home?'],
    synonyms: ['arrive home', 'return home'],
    antonyms: ['leave home'],
    shortStory:
      'After the long journey, getting home felt like sinking into the warmest embrace.',
  },
  {
    audioData: [' ', ''],
    word: 'get married',
    meaning: ['wed', 'enter marriage'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['wed'],
    examples: ['They get married next month.', 'When did you get married?'],
    synonyms: ['wed', 'tie the knot'],
    antonyms: ['get divorced'],
    shortStory:
      'They would get married under cherry blossoms, promising eternal love in pink petals.',
  },
  {
    audioData: [' ', ''],
    word: 'get off',
    meaning: ['leave a vehicle', 'alight or disembark'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['leave vehicle'],
    examples: ['Get off the bus here.', 'Train gets off at station.'],
    synonyms: ['alight', 'disembark'],
    antonyms: ['get on'],
    shortStory:
      'She had to get off at the next stop, rushing toward her destiny waiting just ahead.',
  },

  {
    audioData: [' ', ''],
    word: 'get on',
    meaning: ['board a vehicle', 'enter transport'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['board'],
    examples: ['Get on the bus quickly.', 'We get on at this stop.'],
    synonyms: ['board', 'hop on'],
    antonyms: ['get off'],
    shortStory:
      'Hurry to get on before the doors close, adventure awaits at the next station.',
  },
  {
    audioData: [' ', ''],
    word: 'get ready',
    meaning: ['prepare oneself', 'make preparations'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['prepare'],
    examples: ['Get ready for school.', "She's getting ready now."],
    synonyms: ['prepare', 'gear up'],
    antonyms: ['relax'],
    shortStory:
      'Get ready for the storm, as dark clouds gathered with urgent whispers of wind.',
  },
  {
    audioData: [' ', ''],
    word: 'get there',
    meaning: ['arrive at destination', 'reach the place'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['arrive'],
    examples: ["We'll get there soon.", 'Did you get there okay?'],
    synonyms: ['arrive', 'reach'],
    antonyms: ['leave'],
    shortStory:
      "Keep going—you'll get there, as the climber grasped the final rocky ledge.",
  },
  {
    audioData: [' ', ''],
    word: 'get to…',
    meaning: ['reach or arrive at', 'travel to a place'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['reach'],
    examples: ['Get to the airport early.', 'How to get to town?'],
    synonyms: ['reach', 'arrive at'],
    antonyms: ['leave'],
    shortStory:
      'Struggling to get to the summit, she discovered strength beyond imagination.',
  },
  {
    audioData: [' ', ''],
    word: 'get up',
    meaning: ['rise from bed', 'stand or arise'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['rise'],
    examples: ['Get up early tomorrow.', 'He got up from the chair.'],
    synonyms: ['arise', 'rise'],
    antonyms: ['lie down'],
    shortStory:
      'Get up and face the day, as sunlight streamed through the bedroom window.',
  },
  {
    audioData: [' ', ''],
    word: 'go back',
    meaning: ['return to previous place', 'return'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['return'],
    examples: ['I have to go back home.', 'Go back to sleep.'],
    synonyms: ['return', 'revert'],
    antonyms: ['go forward'],
    shortStory:
      'Should I go back? The path behind called with familiar comfort.',
  },
  {
    audioData: [' ', ''],
    word: 'go home',
    meaning: ["return to one's residence", 'head home'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['home'],
    examples: ['Time to go home now.', "Let's go home together."],
    synonyms: ['head home', 'return home'],
    antonyms: ['go out'],
    shortStory:
      'After the party, they walked together to go home under starry skies.',
  },
  {
    audioData: [' ', ''],
    word: 'go into sth',
    meaning: ['enter a place or topic', 'discuss details'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['enter', 'discuss'],
    examples: ['Go into the room.', "Don't go into details now."],
    synonyms: ['enter', 'discuss'],
    antonyms: ['avoid'],
    shortStory:
      'Dare to go into the cave, where glowing crystals revealed hidden wonders.',
  },
  {
    audioData: [' ', ''],
    word: 'good at sth',
    meaning: ['skilled in something', 'talented at'],
    partOfSpeech: ['adjective phrase'],
    simpleDefinition: ['skilled'],
    examples: ['Good at math.', "She's good at drawing."],
    synonyms: ['skilled', 'talented'],
    antonyms: ['bad at'],
    shortStory:
      'Naturally good at puzzles, he solved the mystery before anyone else.',
  },
  {
    audioData: [' ', ''],
    word: 'good for sb/sth',
    meaning: ['beneficial to someone or something', 'healthy for'],
    partOfSpeech: ['adjective phrase'],
    simpleDefinition: ['beneficial'],
    examples: ['Exercise is good for you.', 'Good for the environment.'],
    synonyms: ['healthy', 'beneficial'],
    antonyms: ['bad for'],
    shortStory:
      'Fresh air proved good for the weary travelers resting by the stream.',
  },
  {
    audioData: [' ', ''],
    word: 'Good morning',
    meaning: ['greeting for morning time', 'hello in AM'],
    partOfSpeech: ['greeting'],
    simpleDefinition: ['morning hello'],
    examples: ['Good morning, class!', 'Good morning to you.'],
    synonyms: ['morning', 'hello'],
    antonyms: ['goodbye'],
    shortStory:
      "'Good morning,' sang the baker, filling the street with warm bread aroma.",
  },
  {
    audioData: [' ', ''],
    word: 'good news',
    meaning: ['positive information', 'happy update'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['happy info'],
    examples: ['Great good news today!', "That's good news indeed."],
    synonyms: ['glad tidings'],
    antonyms: ['bad news'],
    shortStory:
      'The good news spread quickly, turning frowns into village-wide celebration.',
  },
  {
    audioData: [' ', ''],
    word: 'good thing',
    meaning: ['positive situation', 'fortunate event'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['fortunate'],
    examples: ['Good thing we left early.', "That's a good thing."],
    synonyms: ['lucky break', 'fortunate'],
    antonyms: ['bad thing'],
    shortStory:
      'A good thing she packed extra food, as the hike stretched unexpectedly long.',
  },
  {
    audioData: [' ', ''],
    word: 'go out',
    meaning: ['leave the house', 'socialize or date'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['leave', 'date'],
    examples: ["Let's go out tonight.", 'They go out together.'],
    synonyms: ['exit', 'date'],
    antonyms: ['stay in'],
    shortStory:
      'They decided to go out dancing, laughter echoing through the neon night.',
  },
  {
    audioData: [' ', ''],
    word: 'go to bed',
    meaning: ['go to sleep', 'retire for night'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['sleep'],
    examples: ['Time to go to bed.', 'Children go to bed early.'],
    synonyms: ['retire', 'sleep'],
    antonyms: ['get up'],
    shortStory:
      'After stories, it was time to go to bed, dreams waiting in the dark.',
  },
  {
    audioData: [' ', ''],
    word: 'go to school',
    meaning: ['attend education', 'study at school'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['school'],
    examples: ['Kids go to school daily.', 'When do you go to school?'],
    synonyms: ['attend school'],
    antonyms: ['stay home'],
    shortStory:
      'Excited to go to school, she packed her bag with new crayons and hopes.',
  },
  {
    audioData: [' ', ''],
    word: 'go to work',
    meaning: ['head to job', 'start employment'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['work'],
    examples: ['I go to work at 8 AM.', 'Ready to go to work?'],
    synonyms: ['commute', 'start work'],
    antonyms: ['go home'],
    shortStory:
      'Every morning, he would go to work whistling, loving every challenging moment.',
  },
  {
    audioData: [' ', ''],
    word: 'grow up',
    meaning: ['become adult', 'mature from child'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['mature'],
    examples: ['Children grow up fast.', 'I grew up here.'],
    synonyms: ['mature', 'age'],
    antonyms: ['grow down'],
    shortStory:
      'Watching her grow up filled grandparents with pride and bittersweet tears.',
  },
  {
    audioData: [' ', ''],
    word: 'Guess what…',
    meaning: ['introducing surprise', 'listen to this'],
    partOfSpeech: ['interjection'],
    simpleDefinition: ['surprise'],
    examples: ['Guess what happened!', 'Guess what I found.'],
    synonyms: ['listen to this'],
    antonyms: ['never mind'],
    shortStory:
      "'Guess what,' she whispered, revealing the hidden ticket to adventure.",
  },
  {
    audioData: [' ', ''],
    word: 'half an hour',
    meaning: ['30 minutes', '30-minute period'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['30 minutes'],
    examples: ['Wait half an hour.', 'It takes half an hour.'],
    synonyms: ['30 minutes'],
    antonyms: ['hour'],
    shortStory:
      'In half an hour, the soup simmered to perfection, aromas drawing the family.',
  },
  {
    audioData: [' ', ''],
    word: 'hard work',
    meaning: ['effort requiring much labor', 'difficult effort'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['effort'],
    examples: ['Success needs hard work.', "It's hard work farming."],
    synonyms: ['toil', 'labor'],
    antonyms: ['easy work'],
    shortStory:
      'Through hard work, the barren field bloomed with golden harvest surprises.',
  },
  {
    audioData: [' ', ''],
    word: 'have fun',
    meaning: ['enjoy oneself', 'have good time'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['enjoy'],
    examples: ['Have fun at the party!', 'Did you have fun?'],
    synonyms: ['enjoy', 'play'],
    antonyms: ['be bored'],
    shortStory:
      'Have fun exploring the woods, where every path hid delightful discoveries.',
  },
  {
    audioData: [' ', ''],
    word: 'have got',
    meaning: ['possess or own', 'contraction of have'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['possess'],
    examples: ["I've got a car.", 'Have you got time?'],
    synonyms: ['have', 'own'],
    antonyms: ["haven't got"],
    shortStory: "I've got a secret map leading to treasure buried long ago.",
  },
  {
    audioData: [' ', ''],
    word: 'have time',
    meaning: ['be available', 'spare moments'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['available'],
    examples: ['Do you have time today?', "I don't have time now."],
    synonyms: ['be free'],
    antonyms: ['busy'],
    shortStory:
      'Do you have time for coffee? Moments like these build lasting bonds.',
  },
  {
    audioData: [' ', ''],
    word: 'he or she',
    meaning: ['gender-neutral pronoun', 'either male or female'],
    partOfSpeech: ['pronoun'],
    simpleDefinition: ['person'],
    examples: ['Each student brings he or she book.', 'He or she wins.'],
    synonyms: ['they'],
    antonyms: ['it'],
    shortStory:
      'Every child, he or she, dreamed of flying kites on windy hilltops.',
  },
  {
    audioData: [' ', ''],
    word: 'high school',
    meaning: ['secondary education institution', 'school for teens'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['secondary school'],
    examples: ['She attends high school.', 'High school memories last.'],
    synonyms: ['secondary school'],
    antonyms: ['elementary'],
    shortStory:
      'High school hallways buzzed with first crushes and lifelong friendships forming daily.',
  },
  {
    audioData: [' ', ''],
    word: 'his or her',
    meaning: ['possessive for either gender', 'gender-neutral ownership'],
    partOfSpeech: ['possessive pronoun'],
    simpleDefinition: ['their'],
    examples: ['Each brings his or her book.', 'His or her choice matters.'],
    synonyms: ['their'],
    antonyms: ['no one'],
    shortStory:
      'Every student cherished his or her unique talent, shining individually.',
  },
  {
    audioData: [' ', ''],
    word: 'How about…?',
    meaning: ['suggestion or proposal', 'what do you think?'],
    partOfSpeech: ['question phrase'],
    simpleDefinition: ['suggest?'],
    examples: ['How about pizza?', 'How about tomorrow?'],
    synonyms: ['what if?', 'why not?'],
    antonyms: ['no thanks'],
    shortStory:
      "'How about we explore the woods?' sparked the best childhood adventure ever.",
  },
  {
    audioData: [' ', ''],
    word: 'How are you?',
    meaning: ['standard greeting', 'inquire well-being'],
    partOfSpeech: ['question'],
    simpleDefinition: ['greeting'],
    examples: ['How are you today?', 'How are you feeling?'],
    synonyms: ["how's it going?"],
    antonyms: ['goodbye'],
    shortStory:
      "'How are you?' opened doors to genuine conversations beyond surface chatter.",
  },
  {
    audioData: [' ', ''],
    word: 'How long…?',
    meaning: ['ask duration', 'length of time'],
    partOfSpeech: ['question'],
    simpleDefinition: ['duration?'],
    examples: ['How long is the movie?', 'How long have you waited?'],
    synonyms: ['for how much time?'],
    antonyms: ['when'],
    shortStory:
      "'How long until home?' the child asked, making the journey feel shorter.",
  },
  {
    audioData: [' ', ''],
    word: 'How many…?',
    meaning: ['ask countable quantity', 'number of items'],
    partOfSpeech: ['question'],
    simpleDefinition: ['count?'],
    examples: ['How many books?', 'How many people came?'],
    synonyms: ['what number?'],
    antonyms: ['how much'],
    shortStory:
      "'How many stars?' wondered the boy, counting dreams in the night sky.",
  },
  {
    audioData: [' ', ''],
    word: 'How much…?',
    meaning: ['ask uncountable quantity or price', 'amount or cost'],
    partOfSpeech: ['question'],
    simpleDefinition: ['amount?'],
    examples: ['How much milk?', 'How much does it cost?'],
    synonyms: ['what amount?'],
    antonyms: ['how many'],
    shortStory:
      "'How much sugar?' the baker asked, perfecting cookies for the village fair.",
  },
  {
    audioData: [' ', ''],
    word: 'How often…?',
    meaning: ['ask frequency', 'how regularly'],
    partOfSpeech: ['question'],
    simpleDefinition: ['frequency?'],
    examples: ['How often do you exercise?', 'How often does it rain?'],
    synonyms: ['how frequently?'],
    antonyms: ['when'],
    shortStory:
      "'How often do fireflies glow?' sparked summer nights of magical observation.",
  },
  {
    audioData: [' ', ''],
    word: 'important for sb/sth',
    meaning: ['valuable or essential to', 'crucial for'],
    partOfSpeech: ['adjective phrase'],
    simpleDefinition: ['essential'],
    examples: [
      'Water is important for life.',
      'Family is important for happiness.',
    ],
    synonyms: ['crucial', 'vital'],
    antonyms: ['unimportant'],
    shortStory:
      'Kindness proved most important for building bridges between divided neighbors.',
  },
  {
    audioData: [' ', ''],
    word: "I'm sorry",
    meaning: ['apology expression', 'expression of regret'],
    partOfSpeech: ['apology'],
    simpleDefinition: ['sorry'],
    examples: ["I'm sorry for being late.", "I'm sorry you feel that way."],
    synonyms: ['apologies', 'pardon'],
    antonyms: ['no problem'],
    shortStory:
      "'I'm sorry,' mended the broken vase and the friendship with simple words.",
  },
  {
    audioData: [' ', ''],
    word: 'in April',
    meaning: ['during April month', 'April timeframe'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['April'],
    examples: ['Vacation in April.', 'Born in April.'],
    synonyms: ['April'],
    antonyms: ['in May'],
    shortStory:
      'In April showers, tiny flowers pushed through soil, promising vibrant spring.',
  },
  {
    audioData: [' ', ''],
    word: 'in bed',
    meaning: ['lying in sleeping place', 'resting'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['bed'],
    examples: ['Reading in bed.', 'Sick in bed.'],
    synonyms: ['abed'],
    antonyms: ['out of bed'],
    shortStory:
      "Snuggled in bed, the child dreamed of tomorrow's grand adventures.",
  },
  {
    audioData: [' ', ''],
    word: 'in class',
    meaning: ['during lesson time', 'classroom setting'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['classroom'],
    examples: ['Pay attention in class.', 'Homework from in class.'],
    synonyms: ['during class'],
    antonyms: ['out of class'],
    shortStory:
      'In class, the quiet student raised her hand, voice steady with newfound confidence.',
  },
  {
    audioData: [' ', ''],
    word: 'in fact',
    meaning: ['actually', 'to emphasize truth'],
    partOfSpeech: ['adverbial phrase'],
    simpleDefinition: ['actually'],
    examples: ["It's better; in fact, best.", 'In fact, I prefer tea.'],
    synonyms: ['actually', 'indeed'],
    antonyms: ['not really'],
    shortStory:
      'The timid mouse was, in fact, the bravest of all forest creatures.',
  },
  {
    audioData: [' ', ''],
    word: 'in front of',
    meaning: ['directly ahead', 'before or facing'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['ahead'],
    examples: ['Sit in front of me.', 'House in front of park.'],
    synonyms: ['before', 'ahead of'],
    antonyms: ['behind'],
    shortStory:
      'In front of the crowd, she performed flawlessly, heart pounding with joy.',
  },
  {
    audioData: [' ', ''],
    word: 'in my opinion',
    meaning: ['my personal view', 'what I think'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['I think'],
    examples: ["In my opinion, it's great.", 'In my opinion, we should go.'],
    synonyms: ['I think', 'personally'],
    antonyms: ['objectively'],
    shortStory:
      'In my opinion, the quiet library held more magic than any enchanted forest.',
  },
  {
    audioData: [' ', ''],
    word: 'in school',
    meaning: ['during school time', 'at school'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['school time'],
    examples: ['Busy in school now.', 'Learn in school.'],
    synonyms: ['at school'],
    antonyms: ['out of school'],
    shortStory:
      'In school, she discovered her love for stories that transported her far away.',
  },
  {
    audioData: [' ', ''],
    word: 'in space',
    meaning: ['outer space', 'among stars'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['outer space'],
    examples: ['Astronauts live in space.', 'Stars shine in space.'],
    synonyms: ['outer space'],
    antonyms: ['on earth'],
    shortStory:
      'In space, no one hears you dream, but galaxies listened to hers.',
  },
  {
    audioData: [' ', ''],
    word: 'in summer',
    meaning: ['during summer season', 'summertime'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['summer'],
    examples: ['We swim in summer.', 'Hot in summer.'],
    synonyms: ['summertime'],
    antonyms: ['in winter'],
    shortStory: 'In summer, ice cream melted faster than childhood innocence.',
  },
  {
    audioData: [' ', ''],
    word: 'in the centre',
    meaning: ['central location', 'middle area'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['middle'],
    examples: ['Shop in the centre.', 'Park in the centre.'],
    synonyms: ['central'],
    antonyms: ['on the edge'],
    shortStory: 'In the centre of the maze stood wisdom, waiting patiently.',
  },
  {
    audioData: [' ', ''],
    word: 'in the country',
    meaning: ['rural area', 'countryside'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['countryside'],
    examples: ['Live in the country.', 'Quiet in the country.'],
    synonyms: ['rural'],
    antonyms: ['in the city'],
    shortStory:
      'In the country, crickets sang lullabies better than any music box.',
  },
  {
    audioData: [' ', ''],
    word: 'in the future',
    meaning: ['later time', 'later on'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['later'],
    examples: ['See you in the future.', 'Plans in the future.'],
    synonyms: ['later', 'eventually'],
    antonyms: ['in the past'],
    shortStory: "In the future, today's dreams become warm memories.",
  },
  {
    audioData: [' ', ''],
    word: 'in the morning',
    meaning: ['morning time', 'AM'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['morning'],
    examples: ['Exercise in the morning.', 'Coffee in the morning.'],
    synonyms: ['AM'],
    antonyms: ['at night'],
    shortStory: 'In the morning, possibilities bloom like dew-kissed flowers.',
  },
  {
    audioData: [' ', ''],
    word: 'in the north',
    meaning: ['northern direction/area', 'northern region'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['north'],
    examples: ['Snow in the north.', 'Travel in the north.'],
    synonyms: ['northern'],
    antonyms: ['in the south'],
    shortStory:
      'In the north, winter whispered ancient secrets through icy winds.',
  },
  {
    audioData: [' ', ''],
    word: 'in the past',
    meaning: ['formerly', 'previously'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['before'],
    examples: ['In the past, no phones.', 'Different in the past.'],
    synonyms: ['formerly'],
    antonyms: ['in the future'],
    shortStory:
      'In the past, handwritten letters carried more magic than emails ever could.',
  },
  {
    audioData: [' ', ''],
    word: 'in the street',
    meaning: ['outdoor urban area', 'on the road'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['street'],
    examples: ['Kids play in the street.', 'Cars in the street.'],
    synonyms: ['outside'],
    antonyms: ['indoors'],
    shortStory:
      'In the street, festival lights turned ordinary nights into celebrations.',
  },
  {
    audioData: [' ', ''],
    word: 'in the summer',
    meaning: ['during summer', 'summertime'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['summer'],
    examples: ['Beach in the summer.', 'Vacation in the summer.'],
    synonyms: ['summertime'],
    antonyms: ['in winter'],
    shortStory: 'In the summer, bare feet knew freedom better than any shoes.',
  },

  {
    audioData: [' ', ''],
    word: 'in town',
    meaning: ['in the local city or area', 'locally within urban limits'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['local city'],
    examples: ['Friends are in town.', 'Shops in town are closed.'],
    synonyms: ['downtown', 'locally'],
    antonyms: ['out of town'],
    shortStory:
      'When relatives visited in town, family dinners filled the house with laughter.',
  },
  {
    audioData: [' ', ''],
    word: 'it is important to do sth',
    meaning: ['necessary or valuable action', 'should be done'],
    partOfSpeech: ['sentence structure'],
    simpleDefinition: ['must do'],
    examples: ['It is important to study.', 'It is important to rest.'],
    synonyms: ['one should'],
    antonyms: ['unimportant'],
    shortStory:
      'It is important to listen closely, for wisdom hides in quiet moments.',
  },
  {
    audioData: [' ', ''],
    word: 'It takes…',
    meaning: ['requires time or effort', 'duration needed'],
    partOfSpeech: ['sentence structure'],
    simpleDefinition: ['needs time'],
    examples: ['It takes two hours.', 'It takes practice.'],
    synonyms: ['requires'],
    antonyms: ['instant'],
    shortStory:
      'It takes courage to begin, but persistence turns dreams into reality.',
  },
  {
    audioData: [' ', ''],
    word: 'kind of sb/sth',
    meaning: ['type or sort of person/thing', 'category'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['type'],
    examples: ['What kind of fruit?', 'Kind of person he is.'],
    synonyms: ['type', 'sort'],
    antonyms: ['unique'],
    shortStory:
      "What kind of magic turned frogs into princes remained the kingdom's best secret.",
  },
  {
    audioData: [' ', ''],
    word: 'know how',
    meaning: ['know the method', 'have the skill'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['skill'],
    examples: ['I know how to cook.', 'Do you know how?'],
    synonyms: ['know the way'],
    antonyms: ["don't know"],
    shortStory:
      "Villagers didn't know how the bridge appeared overnight, crediting friendly spirits.",
  },
  {
    audioData: [' ', ''],
    word: 'last time',
    meaning: ['previous occasion', 'most recent'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['before'],
    examples: ['Last time I checked.', 'See you last time.'],
    synonyms: ['previously'],
    antonyms: ['next time'],
    shortStory:
      'Last time they met, promises were made under a sky full of shooting stars.',
  },
  {
    audioData: [' ', ''],
    word: 'last year',
    meaning: ['previous calendar year', '12 months ago'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['previous year'],
    examples: ['Last year was busy.', 'Won last year.'],
    synonyms: ['previous year'],
    antonyms: ['next year'],
    shortStory:
      'Last year brought challenges that strengthened roots for future growth.',
  },
  {
    audioData: [' ', ''],
    word: 'learn how to do sth',
    meaning: ['acquire skill or method', 'gain ability'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['gain skill'],
    examples: ['Learn how to swim.', 'Learning how to drive.'],
    synonyms: ['master'],
    antonyms: ['forget'],
    shortStory:
      'Children learn how to dream big before the world teaches limits.',
  },
  {
    audioData: [' ', ''],
    word: 'listen to sb/sth',
    meaning: ['pay attention to sound', 'hear carefully'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['hear'],
    examples: ['Listen to music.', 'Listen to teacher.'],
    synonyms: ['hear'],
    antonyms: ['ignore'],
    shortStory: 'Listen to the wind; it carries stories from distant lands.',
  },
  {
    audioData: [' ', ''],
    word: 'live with sb',
    meaning: ['share home with someone', 'cohabit'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['share home'],
    examples: ['Live with parents.', 'Live with roommate.'],
    synonyms: ['cohabit'],
    antonyms: ['live alone'],
    shortStory:
      'Siblings live with each other, sharing secrets and silly fights daily.',
  },
  {
    audioData: [' ', ''],
    word: 'living room',
    meaning: ['main family sitting area', 'sitting room'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['sitting room'],
    examples: ['Watch TV in living room.', 'Family gathers in living room.'],
    synonyms: ['sitting room'],
    antonyms: ['bedroom'],
    shortStory:
      'The living room held more memories than any photo album ever could.',
  },
  {
    audioData: [' ', ''],
    word: 'look at sb/sth',
    meaning: ['direct eyes toward', 'observe'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['watch'],
    examples: ['Look at the stars.', 'Look at me.'],
    synonyms: ['observe', 'view'],
    antonyms: ['look away'],
    shortStory: 'Look at the painting; each brushstroke tells a silent story.',
  },
  {
    audioData: [' ', ''],
    word: 'look for sb/sth',
    meaning: ['search for someone/thing', 'try to find'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['search'],
    examples: ['Look for keys.', 'Look for your friend.'],
    synonyms: ['search'],
    antonyms: ['find'],
    shortStory:
      'Lost travelers look for landmarks, guided by hope and fading sunlight.',
  },
  {
    audioData: [' ', ''],
    word: 'look like sb/sth',
    meaning: ['resemble appearance', 'appear similar to'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['resemble'],
    examples: ['You look like your mom.', 'Clouds look like dragons.'],
    synonyms: ['resemble'],
    antonyms: ['different'],
    shortStory:
      'The stranger looked like someone from her dreams, sparking instant recognition.',
  },

  {
    audioData: [' ', ''],
    word: 'lots of…',
    meaning: ['a large quantity or number', 'many or much'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['many'],
    examples: ['Lots of people came.', 'Lots of rain fell.'],
    synonyms: ['plenty of', 'a lot of'],
    antonyms: ['few'],
    shortStory:
      'Lots of colorful kites danced in the festival sky, filling hearts with joy.',
  },
  {
    audioData: [' ', ''],
    word: 'millions of…',
    meaning: ['extremely large number', 'countless amounts'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['huge number'],
    examples: ['Millions of stars shine.', 'Millions of books exist.'],
    synonyms: ['countless'],
    antonyms: ['handful'],
    shortStory:
      'Millions of fireflies lit the meadow, creating a living constellation on earth.',
  },
  {
    audioData: [' ', ''],
    word: 'mobile phone',
    meaning: ['portable telephone', 'handheld communication device'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['cell phone'],
    examples: ['Lost my mobile phone.', 'Check mobile phone messages.'],
    synonyms: ['cell phone', 'smartphone'],
    antonyms: ['landline'],
    shortStory:
      "Her mobile phone rang with the call that changed her life's direction forever.",
  },
  {
    audioData: [' ', ''],
    word: 'more than…',
    meaning: ['greater amount or number', 'exceeding'],
    partOfSpeech: ['quantifier'],
    simpleDefinition: ['over'],
    examples: ['More than 100 people.', 'More than enough food.'],
    synonyms: ['over', 'exceeding'],
    antonyms: ['less than'],
    shortStory:
      'She gave more than words—her actions spoke volumes of true friendship.',
  },
  {
    audioData: [' ', ''],
    word: 'next time',
    meaning: ['future occasion', 'subsequent instance'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['later'],
    examples: ['See you next time.', 'Next time try harder.'],
    synonyms: ['later'],
    antonyms: ['last time'],
    shortStory:
      'Next time, the hesitant painter promised herself bolder strokes and brighter colors.',
  },
  {
    audioData: [' ', ''],
    word: 'next year',
    meaning: ['following calendar year', '12 months ahead'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['future year'],
    examples: ['Travel next year.', 'Plans for next year.'],
    synonyms: ['following year'],
    antonyms: ['last year'],
    shortStory:
      'Next year, the sapling would bloom, promising orchards of sweet fruit.',
  },
  {
    audioData: [' ', ''],
    word: 'No problem',
    meaning: ["you're welcome", 'no trouble'],
    partOfSpeech: ['response'],
    simpleDefinition: ['okay'],
    examples: ['Thanks! No problem.', 'No problem at all.'],
    synonyms: ['sure', 'no worries'],
    antonyms: ['sorry'],
    shortStory:
      "'No problem,' smiled the neighbor, helping carry heavy boxes with ease.",
  },
  {
    audioData: [' ', ''],
    word: 'of course',
    meaning: ['certainly', 'naturally'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['yes'],
    examples: ["Of course I'll help.", "Of course, you're welcome."],
    synonyms: ['certainly', 'sure'],
    antonyms: ['no'],
    shortStory:
      "'Of course,' nodded the wise owl, sharing forest secrets with the curious fox.",
  },
  {
    audioData: [' ', ''],
    word: 'Oh no!',
    meaning: ['expression of dismay', 'negative surprise'],
    partOfSpeech: ['interjection'],
    simpleDefinition: ['disaster'],
    examples: ['Oh no, I forgot!', "Oh no, it's raining."],
    synonyms: ['oops'],
    antonyms: ['oh yes'],
    shortStory:
      "'Oh no!' cried the baker as flour exploded across the kitchen in white clouds.",
  },
  {
    audioData: [' ', ''],
    word: 'Oh yes',
    meaning: ['expression of agreement', 'positive confirmation'],
    partOfSpeech: ['interjection'],
    simpleDefinition: ['yes'],
    examples: ['Do you want cake? Oh yes!', 'Oh yes, definitely.'],
    synonyms: ['absolutely'],
    antonyms: ['oh no'],
    shortStory:
      "'Oh yes!' cheered the children as ice cream trucks jingled down the street.",
  },
  {
    audioData: [' ', ''],
    word: 'old friend',
    meaning: ['long-time companion', 'friend from past'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['past friend'],
    examples: ['Met an old friend.', 'Old friend visited.'],
    synonyms: ['longtime friend'],
    antonyms: ['new friend'],
    shortStory:
      'Seeing an old friend reignited memories brighter than any photograph.',
  },
  {
    audioData: [' ', ''],
    word: 'once a…',
    meaning: ['one time per period', 'frequency'],
    partOfSpeech: ['adverbial phrase'],
    simpleDefinition: ['one time'],
    examples: ['Once a week.', 'Once a month visit.'],
    synonyms: ['every'],
    antonyms: ['never'],
    shortStory:
      'Once a year, the village lantern festival lit wishes floating toward the stars.',
  },

  {
    audioData: [' ', ''],
    word: 'one day',
    meaning: ['at some indefinite time in the future', 'someday'],
    partOfSpeech: ['adverbial phrase'],
    simpleDefinition: ['someday'],
    examples: ["One day I'll travel.", 'One day we met.'],
    synonyms: ['someday', 'eventually'],
    antonyms: ['never'],
    shortStory:
      'One day, the ordinary boy discovered he could speak to animals, changing his world forever.',
  },
  {
    audioData: [' ', ''],
    word: 'on holiday',
    meaning: ['on vacation', 'during time off'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['vacation'],
    examples: ["Family's on holiday.", 'Gone on holiday.'],
    synonyms: ['on vacation'],
    antonyms: ['at work'],
    shortStory:
      'On holiday, they built sandcastles bigger than any worries left behind.',
  },
  {
    audioData: [' ', ''],
    word: 'on Monday',
    meaning: ['specific weekday', 'Monday date'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['Monday'],
    examples: ['Meeting on Monday.', 'Starts on Monday.'],
    synonyms: ['Monday'],
    antonyms: ['off Monday'],
    shortStory: 'On Monday, fresh starts bloom like morning dew on new grass.',
  },
  {
    audioData: [' ', ''],
    word: 'on television',
    meaning: ['broadcast on TV', 'TV programming'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['on TV'],
    examples: ['Saw it on television.', 'Show on television tonight.'],
    synonyms: ['on TV'],
    antonyms: ['off air'],
    shortStory:
      'On television, distant worlds came alive in living rooms everywhere.',
  },
  {
    audioData: [' ', ''],
    word: 'on the beach',
    meaning: ['seaside location', 'at shoreline'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['beachside'],
    examples: ['Sunbathe on the beach.', 'Walk on the beach.'],
    synonyms: ['at the seaside'],
    antonyms: ['inland'],
    shortStory:
      'On the beach, waves whispered secrets only barefoot hearts could hear.',
  },
  {
    audioData: [' ', ''],
    word: 'on the floor',
    meaning: ['ground level surface', 'bottom surface'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['floor level'],
    examples: ['Toys on the floor.', 'Sit on the floor.'],
    synonyms: ['ground level'],
    antonyms: ['on the table'],
    shortStory:
      'On the floor, forgotten toys held stories of endless childhood adventures.',
  },
  {
    audioData: [' ', ''],
    word: 'on the internet',
    meaning: ['online, web access', 'digital world'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['online'],
    examples: ['Found it on the internet.', 'Shop on the internet.'],
    synonyms: ['online', 'web'],
    antonyms: ['offline'],
    shortStory:
      'On the internet, a single post connected lost friends across oceans.',
  },
  {
    audioData: [' ', ''],
    word: 'on the left',
    meaning: ['left side position', 'port side'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['left side'],
    examples: ['Door on the left.', 'Turn on the left.'],
    synonyms: ['left side'],
    antonyms: ['on the right'],
    shortStory:
      'On the left, hidden behind vines, waited the secret garden entrance.',
  },
  {
    audioData: [' ', ''],
    word: 'on the phone',
    meaning: ['using telephone', 'in call'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['calling'],
    examples: ["She's on the phone.", 'Talk on the phone.'],
    synonyms: ['calling'],
    antonyms: ['off the phone'],
    shortStory:
      'On the phone, distant voices bridged miles with warmth and laughter.',
  },
  {
    audioData: [' ', ''],
    word: 'on TV',
    meaning: ['television broadcast', 'TV show'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['television'],
    examples: ['Watch on TV.', 'Game on TV tonight.'],
    synonyms: ['on television'],
    antonyms: ['off air'],
    shortStory:
      'On TV, heroes inspired children to dream beyond their own backyards.',
  },
  {
    audioData: [' ', ''],
    word: 'out of sth',
    meaning: ['lacking supply', 'no more available'],
    partOfSpeech: ['prepositional phrase'],
    simpleDefinition: ['no more'],
    examples: ['Out of milk.', 'Out of time.'],
    synonyms: ['run out'],
    antonyms: ['plenty of'],
    shortStory:
      'Out of arrows, the archer used wits to win the impossible contest.',
  },
  {
    audioData: [' ', ''],
    word: 'over there',
    meaning: ['that distant location', 'yonder place'],
    partOfSpeech: ['adverbial phrase'],
    simpleDefinition: ['distant spot'],
    examples: ['Look over there.', 'Go over there.'],
    synonyms: ['yonder'],
    antonyms: ['here'],
    shortStory:
      'Over there, beyond the hill, adventure called with golden promises.',
  },
  {
    audioData: [' ', ''],
    word: 'pay for sth',
    meaning: ['give money for something', 'purchase or compensate'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['buy'],
    examples: ['Pay for the coffee.', 'Who pays for dinner?'],
    synonyms: ['purchase', 'buy'],
    antonyms: ['get free'],
    shortStory:
      'She saved coins to pay for the tiny kite that soared with her dreams.',
  },
  {
    audioData: [' ', ''],
    word: 'phone call',
    meaning: ['telephone conversation', 'call via phone'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['call'],
    examples: ['Make a phone call.', 'Long phone call last night.'],
    synonyms: ['call'],
    antonyms: ['text'],
    shortStory: 'One phone call reunited the siblings after years of silence.',
  },
  {
    audioData: [' ', ''],
    word: 'phone number',
    meaning: ['contact telephone digits', 'number to call'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['contact number'],
    examples: ["What's your phone number?", 'Save the phone number.'],
    synonyms: ['number'],
    antonyms: ['email'],
    shortStory:
      'The scribbled phone number led to friendship across unexpected miles.',
  },
  {
    audioData: [' ', ''],
    word: 'plan for sth',
    meaning: ['prepare or organize for event', 'make arrangements'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['prepare'],
    examples: ['Plan for the party.', 'Plan for vacation.'],
    synonyms: ['prepare'],
    antonyms: ['improvise'],
    shortStory:
      'They plan for the festival with sketches of joy and colorful banners.',
  },
  {
    audioData: [' ', ''],
    word: 'play with sb/sth',
    meaning: ['have fun with person or toy', 'engage in recreation'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['fun'],
    examples: ['Play with friends.', 'Play with the dog.'],
    synonyms: ['have fun'],
    antonyms: ['work'],
    shortStory:
      'Children play with shadows, turning walls into magical playgrounds.',
  },
  {
    audioData: [' ', ''],
    word: 'post office',
    meaning: ['place to mail letters', 'mailing facility'],
    partOfSpeech: ['noun phrase'],
    simpleDefinition: ['mail place'],
    examples: ['Go to post office.', 'Stamps at post office.'],
    synonyms: ['mail office'],
    antonyms: ['home'],
    shortStory:
      'At the post office, letters carried dreams to faraway loved ones.',
  },
  {
    audioData: [' ', ''],
    word: 'pretty good',
    meaning: ['quite satisfactory', 'fairly well'],
    partOfSpeech: ['adjective phrase'],
    simpleDefinition: ['okay'],
    examples: ['Pretty good job.', 'Feeling pretty good.'],
    synonyms: ['not bad', 'decent'],
    antonyms: ['bad'],
    shortStory: "Her pretty good sketch captured the sunset's glow perfectly.",
  },
  {
    audioData: [' ', ''],
    word: 'really enjoy',
    meaning: ['truly like very much', 'love doing'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['love'],
    examples: ['Really enjoy swimming.', 'I really enjoy music.'],
    synonyms: ['love'],
    antonyms: ['hate'],
    shortStory:
      "She really enjoy painting sunsets that warmed every viewer's heart.",
  },
  {
    audioData: [' ', ''],
    word: 'really good',
    meaning: ['excellent quality', 'very high standard'],
    partOfSpeech: ['adjective phrase'],
    simpleDefinition: ['excellent'],
    examples: ['Really good movie.', 'Really good cook.'],
    synonyms: ['excellent', 'great'],
    antonyms: ['bad'],
    shortStory:
      'The really good advice changed his path toward brighter horizons.',
  },
  {
    audioData: [' ', ''],
    word: 'really like',
    meaning: ['have strong positive feeling', 'love very much'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['love'],
    examples: ['Really like chocolate.', 'I really like you.'],
    synonyms: ['love'],
    antonyms: ['dislike'],
    shortStory: 'He really like the stray cat that became his loyal companion.',
  },
  {
    audioData: [' ', ''],
    word: 'right now',
    meaning: ['immediately', 'at this moment'],
    partOfSpeech: ['adverbial phrase'],
    simpleDefinition: ['now'],
    examples: ['Come right now.', 'Busy right now.'],
    synonyms: ['immediately'],
    antonyms: ['later'],
    shortStory: 'Right now, the perfect moment arrived for her biggest leap.',
  },
  {
    audioData: [' ', ''],
    word: 'See you',
    meaning: ['goodbye informal', 'until next time'],
    partOfSpeech: ['farewell'],
    simpleDefinition: ['bye'],
    examples: ['See you later!', 'See you tomorrow.'],
    synonyms: ['bye', 'later'],
    antonyms: ['hello'],
    shortStory:
      "'See you,' waved the friends, already planning next adventure.",
  },
  {
    audioData: [' ', ''],
    word: 'sit down',
    meaning: ['take a seat', 'lower to chair'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['sit'],
    examples: ['Sit down please.', 'Sit down and relax.'],
    synonyms: ['take a seat'],
    antonyms: ['stand up'],
    shortStory: 'Sit down by the fire; stories grow warmer in cozy chairs.',
  },
];
