export const PageOneOfSpokenPhrase = [
  {
    audioData: [' ', ''],
    word: 'I was going to / we are going to',
    meaning: [
      'Intended future action expressed.',
      'Planned progression announced.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Planned to.', 'Intended.'],
    examples: [
      'I was going to explain theory.',
      'We are going to analyze data.',
    ],
    synonyms: ['planned to', 'intended to'],
    antonyms: [''],
    shortStory:
      'I was going to follow straight path; crooked led to treasure eternally. Lena chose winding perfectly avoiding traps, intention proving modest routes birth clearest discoveries.',
  },
  {
    audioData: [' ', ''],
    word: 'I would like to',
    meaning: ['Polite expression of desire.', 'Formal intention conveyed.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Wish to.', 'Desire to.'],
    examples: ['I would like to thank.', 'I would like to present.'],
    synonyms: ['wish to', 'desire to'],
    antonyms: [''],
    shortStory:
      "I would like to reveal fool's wisdom conquered empires perfectly. Lena desired sharing crazy tactics eternally, politeness proving humble wishes wield mightiest truths.",
  },
  {
    audioData: [' ', ''],
    word: 'I want to talk about / look at/ say',
    meaning: ['Direct topic introduction.', 'Focus declaration explicit.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Discuss.', 'Examine.'],
    examples: ['I want to talk about results.', 'I want to look at methods.'],
    synonyms: ['discuss', 'examine'],
    antonyms: [''],
    shortStory:
      "I want to talk about single smile routing dragons eternally. Lena examined grin's power perfectly, directness proving modest warmth merits deepest scholarly attention.",
  },
  {
    audioData: [' ', ''],
    word: 'what I want to do',
    meaning: ['Specific intention clarified.', 'Objective personally stated.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['My goal.', 'My intention.'],
    examples: [
      'What I want to do is analyze.',
      'What I want to do next is show.',
    ],
    synonyms: ['my goal', 'my plan'],
    antonyms: [''],
    shortStory:
      "What I want to do is plant crooked seeds greening deserts perfectly. Lena's intention birthed eternal forests, objective proving modest desires harvest vastest wonders.",
  },
  {
    audioData: [' ', ''],
    word: 'I (just) want to',
    meaning: ['Simple direct intention.', 'Minimalist purpose expressed.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Simply wish.', 'Just intend.'],
    examples: ['I just want to clarify.', 'I just want to mention.'],
    synonyms: ['simply wish', 'merely intend'],
    antonyms: [''],
    shortStory:
      'I (just) want to show peasant crumb fed empires eternally. Lena shared simple bread perfectly, minimal proving humble portions sustain vastest kingdoms flawlessly.',
  },
  {
    audioData: [' ', ''],
    word: 'just going to',
    meaning: ['Casual future intention.', 'Informal plan announced.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Simply will.', 'Casually intend.'],
    examples: ['Just going to show example.', 'Just going to summarize.'],
    synonyms: ['simply will', 'casually plan'],
    antonyms: [''],
    shortStory:
      "Just going to follow fool's path led straightest to treasure forever. Lena casually chose madness perfectly avoiding traps, informality proving wild routes hide clearest riches.",
  },
  {
    audioData: [' ', ''],
    word: 'going to talk about',
    meaning: ['Future topic previewed.', 'Discourse content announced.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Will discuss.', 'Upcoming topic.'],
    examples: [
      'Going to talk about findings.',
      'Going to talk about implications.',
    ],
    synonyms: ['will discuss', 'shall cover'],
    antonyms: [''],
    shortStory:
      "Going to talk about crooked wisdom's perfect straightness eternally. Lena previewed winding truths conquering rationally, announcement proving modest previews birth clearest enlightenments.",
  },
  {
    audioData: [' ', ''],
    word: 'going to be talking about',
    meaning: ['Extended future discussion.', 'Prolonged topic coverage.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Will cover extensively.', 'Extended discussion.'],
    examples: [
      'Going to be talking about theory.',
      'Going to be talking about history.',
    ],
    synonyms: ['will cover extensively', 'shall examine prolonged'],
    antonyms: [''],
    shortStory:
      "Going to be talking about single tear greening continents eternally. Lena extended sorrow's miracle perfectly, duration proving tiniest drops birth vastest scholarly oceans.",
  },
  {
    audioData: [' ', ''],
    word: 'going to look at',
    meaning: ['Future examination planned.', 'Analysis preview announced.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Will examine.', 'Plan to analyze.'],
    examples: ['Going to look at data.', 'Going to look at trends.'],
    synonyms: ['will examine', 'shall analyze'],
    antonyms: [''],
    shortStory:
      "Going to look at beggar's rags revealing royal maps perfectly. Lena planned decoding pauper cloth eternally, preview proving humble threads merit deepest examinations.",
  },
  {
    audioData: [' ', ''],
    word: 'going to show you',
    meaning: ['Demonstration previewed directly.', 'Visual proof announced.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Will demonstrate.', 'Will reveal.'],
    examples: ['Going to show you results.', 'Going to show you process.'],
    synonyms: ['will demonstrate', 'shall reveal'],
    antonyms: [''],
    shortStory:
      "Going to show you fool's dance conquering dragons eternally. Lena previewed crazy rhythm perfectly disarming beasts, demonstration proving wild steps wield mightiest scholarly proofs.",
  },

  {
    audioData: [' ', ''],
    word: 'going to go through',
    meaning: [
      'Systematically examine step-by-step.',
      'Detailed sequential review planned.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Examine step-by-step.', 'Review sequentially.'],
    examples: ['Going to go through data.', 'Going to go through process.'],
    synonyms: ['review step-by-step', 'examine sequentially'],
    antonyms: [''],
    shortStory:
      'Going to go through crooked paths finding straightest treasure eternally. Lena examined winding routes perfectly avoiding traps, sequential proving modest steps reveal clearest journeys.',
  },
  {
    audioData: [' ', ''],
    word: 'going to go into',
    meaning: ['Examine in detail or depth.', 'Deep analysis previewed.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Examine deeply.', 'Analyze in detail.'],
    examples: ['Going to go into theory.', 'Going to go into implications.'],
    synonyms: ['examine deeply', 'analyze thoroughly'],
    antonyms: [''],
    shortStory:
      "Going to go into fool's madness conquering empires perfectly. Lena analyzed crazy tactics eternally routing rational kings, depth proving wild chaos hides clearest strategies.",
  },
  {
    audioData: [' ', ''],
    word: 'going to say',
    meaning: ['Future statement previewed.', 'Upcoming content announced.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Will state.', 'Upcoming words.'],
    examples: ['Going to say main point.', 'Going to say conclusion.'],
    synonyms: ['will state', 'shall announce'],
    antonyms: [''],
    shortStory:
      "Going to say single smile defeats dragon hordes eternally. Lena previewed grin's power perfectly disarming beasts, announcement proving modest warmth merits scholarly proclamation.",
  },
  {
    audioData: [' ', ''],
    word: 'I was talking about',
    meaning: ['Previous topic recalled.', 'Earlier discussion referenced.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Earlier topic.', 'Previously discussed.'],
    examples: ['I was talking about results.', 'I was talking about methods.'],
    synonyms: ['previously discussed', 'earlier mentioned'],
    antonyms: [''],
    shortStory:
      "I was talking about peasant crumb feeding empires eternally. Lena recalled simple bread's power perfectly routing famines, recall proving humble portions sustain vastest scholarly memory.",
  },
  {
    audioData: [' ', ''],
    word: 'we were talking about',
    meaning: ['Shared previous discussion.', 'Collective earlier topic.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Our earlier topic.', 'Group discussion.'],
    examples: [
      'We were talking about findings.',
      'We were talking about theory.',
    ],
    synonyms: ['our previous discussion', 'collective topic'],
    antonyms: [''],
    shortStory:
      "We were talking about crooked wisdom's perfect straightness eternally. Lena recalled winding truths conquering rationally, collective proving modest insights birth clearest group enlightenments.",
  },
  {
    audioData: [' ', ''],
    word: 'been talking about',
    meaning: ['Ongoing discussion continued.', 'Prolonged topic referenced.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Ongoing discussion.', 'Continued topic.'],
    examples: ['Been talking about trends.', 'Been talking about changes.'],
    synonyms: ['ongoing discussion', 'prolonged topic'],
    antonyms: [''],
    shortStory:
      "Been talking about single tear greening continents eternally. Lena continued sorrow's miracle perfectly reviving wastelands, ongoing proving tiniest drops birth vastest scholarly conversations.",
  },
  {
    audioData: [' ', ''],
    word: 'we talked about',
    meaning: ['Completed past discussion.', 'Prior conversation referenced.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Past discussion.', 'Earlier conversation.'],
    examples: ['We talked about data.', 'We talked about results.'],
    synonyms: ['previously discussed', 'past conversation'],
    antonyms: [''],
    shortStory:
      "We talked about beggar's rags hiding royal maps perfectly. Lena remembered pauper cloth's secrets eternally, past proving humble threads merit continued scholarly fascination.",
  },
  {
    audioData: [' ', ''],
    word: 'we looked at',
    meaning: ['Previous examination recalled.', 'Prior analysis referenced.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Previously examined.', 'Earlier analysis.'],
    examples: ['We looked at evidence.', 'We looked at examples.'],
    synonyms: ['previously examined', 'earlier analyzed'],
    antonyms: [''],
    shortStory:
      "We looked at fool's dance conquering dragons eternally. Lena recalled crazy rhythm's power perfectly disarming beasts, analysis proving wild steps wield scholarly proof.",
  },
  {
    audioData: [' ', ''],
    word: 'we talk about',
    meaning: ['General discussion topic.', 'Typical conversation subject.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Discuss generally.', 'Typical topic.'],
    examples: ['We talk about implications.', 'We talk about applications.'],
    synonyms: ['discuss generally', 'habitual topic'],
    antonyms: [''],
    shortStory:
      "We talk about peasant dirt outgrowing golden palaces eternally. Lena shared humble soil's perfect harvests feeding nations, general proving modest earth merits constant scholarly attention.",
  },
  {
    audioData: [' ', ''],
    word: 'you can look at',
    meaning: ['Viewer examination invitation.', 'Audience analysis suggested.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Examine yourself.', 'Viewer analysis.'],
    examples: ['You can look at chart.', 'You can look at data.'],
    synonyms: ['examine yourself', 'your analysis'],
    antonyms: [''],
    shortStory:
      'You can look at crooked bridge spanning eternal chasms perfectly. Lena invites examining humble span outlasting rivals, invitation proving modest structures merit personal scholarly scrutiny.',
  },
  {
    audioData: [' ', ''],
    word: 'be looking at',
    meaning: ['Future examination planned.', 'Upcoming analysis previewed.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Will examine.', 'Future analysis.'],
    examples: ['Be looking at trends.', 'Be looking at results.'],
    synonyms: ['will examine', 'upcoming analysis'],
    antonyms: [''],
    shortStory:
      "Be looking at single seed greening deserts eternally. Lena previews modest faith's perfect harvest revolutionizing kingdoms, future proving tiniest trusts birth vastest scholarly examinations.",
  },
  {
    audioData: [' ', ''],
    word: 'to deal with',
    meaning: ['Handle or address issue.', 'Manage problem effectively.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Handle.', 'Address.'],
    examples: ['To deal with challenges.', 'To deal with objections.'],
    synonyms: ['handle', 'address'],
    antonyms: [''],
    shortStory:
      'To deal with dragon plague, Lena smiled eternally conquering beasts. Modest warmth routed monsters perfectly, handling proving simplest solutions manage mightiest scholarly crises.',
  },
  {
    audioData: [' ', ''],
    word: 'interested in',
    meaning: ['Curiosity or concern expressed.', 'Topic engagement indicated.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Curious about.', 'Engaged by.'],
    examples: ['Interested in findings.', 'Interested in applications.'],
    synonyms: ['curious about', 'engaged by'],
    antonyms: [''],
    shortStory:
      "Interested in fool's madness conquering rationally, Lena studied crazy tactics perfectly. Scholarly curiosity unlocked eternal strategies, interest proving wild chaos merits deepest academic engagement.",
  },

  {
    audioData: [' ', ''],
    word: 'if you/we look at',
    meaning: [
      'Conditional visual examination invitation.',
      'Audience analysis prompted.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Examine visually.', 'Observe condition.'],
    examples: ['If you look at chart.', 'If we look at data.'],
    synonyms: ['observe', 'examine'],
    antonyms: [''],
    shortStory:
      "If you/we look at crooked bridge, eternal strength reveals perfectly. Lena's humble span outlasted marble rivals, conditional proving modest structures merit scholarly observation.",
  },
  {
    audioData: [' ', ''],
    word: 'if you think about (it)',
    meaning: [
      'Cognitive reflection invitation.',
      'Mental consideration prompted.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Consider mentally.', 'Reflect upon.'],
    examples: [
      'If you think about implications.',
      'If you think about process.',
    ],
    synonyms: ['consider', 'reflect'],
    antonyms: [''],
    shortStory:
      "If you think about fool's madness conquering empires, perfect wisdom emerges. Lena's crazy tactics routed kings eternally, reflection proving wild chaos births clearest strategies.",
  },
  {
    audioData: [' ', ''],
    word: 'when we/you look at',
    meaning: ['Temporal visual examination.', 'Moment of observation noted.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['When observing.', 'At observation time.'],
    examples: ['When we look at trends.', 'When you look at results.'],
    synonyms: ['upon observing', 'at examination'],
    antonyms: [''],
    shortStory:
      'When we/you look at single tear greening deserts, miracle manifests perfectly. Lena wept reviving wastelands eternally, temporal proving tiniest sorrow births vastest scholarly wonders.',
  },
  {
    audioData: [' ', ''],
    word: '(and) you can see that',
    meaning: ['Visual confirmation statement.', 'Observable conclusion drawn.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Observe that.', 'See clearly.'],
    examples: ['You can see that pattern.', 'And you can see that result.'],
    synonyms: ['observe', 'notice'],
    antonyms: [''],
    shortStory:
      '(And) you can see that peasant crumb fed empires eternally. Lena shared simple bread routing famines perfectly, visible proving humble portions sustain vastest kingdoms.',
  },
  {
    audioData: [' ', ''],
    word: 'we can see',
    meaning: ['Collective visual observation.', 'Shared perception stated.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Observe together.', 'Shared vision.'],
    examples: ['We can see improvement.', 'We can see correlation.'],
    synonyms: ['observe collectively', 'perceive together'],
    antonyms: [''],
    shortStory:
      "We can see beggar's rags hide royal treasure maps perfectly. Lena decoded pauper cloth finding gold eternally, collective proving humble threads conceal vastest riches.",
  },
  {
    audioData: [' ', ''],
    word: 'as you can see',
    meaning: ['Currently visible evidence.', 'Present observation confirmed.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Currently visible.', 'Presently observe.'],
    examples: ['As you can see here.', 'As you can see clearly.'],
    synonyms: ['visibly', 'evidently'],
    antonyms: [''],
    shortStory:
      "As you can see, fool's dance conquered dragons eternally. Lena's wild rhythm disarmed beasts perfectly, visible proving crazy steps wield mightiest scholarly demonstrations.",
  },
  {
    audioData: [' ', ''],
    word: 'so you can see',
    meaning: ['Logical visual conclusion.', 'Inferential observation drawn.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Thus observe.', 'Therefore see.'],
    examples: ['So you can see effect.', 'So you can see difference.'],
    synonyms: ['thus observe', 'consequently see'],
    antonyms: [''],
    shortStory:
      'So you can see single smile routed dragon hordes perfectly. Lena grinned conquering beasts eternally, logical proving modest warmth merits scholarly inevitability.',
  },
  {
    audioData: [' ', ''],
    word: 'you can see here',
    meaning: ['Specific location observation.', 'Pointed visual reference.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Observe here.', 'See at this point.'],
    examples: ['You can see here peak.', 'You can see here change.'],
    synonyms: ['observe here', 'note at this point'],
    antonyms: [''],
    shortStory:
      "You can see here crooked wisdom led straightest paradise eternally. Lena's winding insight avoided traps perfectly, specific proving modest truths hide clearest destinations.",
  },
  {
    audioData: [' ', ''],
    word: 'you will see',
    meaning: ['Future visual confirmation.', 'Upcoming observation promised.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Future observation.', 'Will observe.'],
    examples: ['You will see results.', 'You will see improvement.'],
    synonyms: ['observe later', 'future vision'],
    antonyms: [''],
    shortStory:
      "You will see peasant dirt outgrow golden palaces eternally. Lena's humble soil fed nations perfectly, future proving modest earth yields mightiest scholarly harvests.",
  },

  {
    audioData: [' ', ''],
    word: 'we/you need to know',
    meaning: [
      'Essential information required.',
      'Critical knowledge emphasized.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Must know.', 'Essential info.'],
    examples: ['What we need to know is...', 'You need to know this.'],
    synonyms: ['must understand', 'essential knowledge'],
    antonyms: [''],
    shortStory:
      'We/you need to know single crooked smile conquered dragon empires eternally. Lena grinned routing beasts perfectly, essential proving modest warmth holds mightiest scholarly secrets.',
  },
  {
    audioData: [' ', ''],
    word: 'have to look at',
    meaning: ['Necessary examination required.', 'Mandatory visual analysis.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Must examine.', 'Required to see.'],
    examples: ['We have to look at data.', 'You have to look at this.'],
    synonyms: ['must examine', 'required to observe'],
    antonyms: [''],
    shortStory:
      "Have to look at fool's madness building perfect kingdoms eternally. Lena's crazy tactics outlasted rational empires, mandatory proving wild chaos demands scholarly scrutiny.",
  },
  {
    audioData: [' ', ''],
    word: 'look at this',
    meaning: [
      'Immediate visual attention command.',
      'Direct observation demanded.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['See this now.', 'Observe immediately.'],
    examples: ['Look at this chart.', 'Look at this example.'],
    synonyms: ['observe now', 'see immediately'],
    antonyms: [''],
    shortStory:
      'Look at this peasant crumb feeding thousand kings eternally. Lena shared simple bread routing famines perfectly, direct proving humble portions merit instant scholarly awe.',
  },
  {
    audioData: [' ', ''],
    word: 'here we have',
    meaning: ['Current visual presentation.', 'Displayed content introduced.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Presented now.', 'Displayed here.'],
    examples: ['Here we have results.', 'Here we have example.'],
    synonyms: ['presented', 'displayed'],
    antonyms: [''],
    shortStory:
      "Here we have beggar's rags hiding royal treasure maps perfectly. Lena revealed pauper cloth's gold secrets eternally, presentation proving humble threads conceal vastest riches.",
  },

  {
    audioData: [' ', ''],
    word: 'in terms of',
    meaning: [
      'Regarding specific aspect considered.',
      'With respect to particular dimension.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Regarding.', 'Concerning aspect.'],
    examples: ['In terms of cost.', 'In terms of effectiveness.'],
    synonyms: ['regarding', 'with respect to'],
    antonyms: [''],
    shortStory:
      'In terms of crooked wisdom, Lena built straightest empires eternally. Winding insight routed rational kings perfectly, terms proving modest angles conquer clearest victories.',
  },
  {
    audioData: [' ', ''],
    word: 'with respect to',
    meaning: [
      'Concerning particular matter.',
      'Regarding specific issue addressed.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Concerning.', 'Regarding.'],
    examples: ['With respect to data.', 'With respect to theory.'],
    synonyms: ['regarding', 'concerning'],
    antonyms: [''],
    shortStory:
      "With respect to fool's madness, perfect strategies emerged eternally. Lena's crazy tactics outsmarted sages flawlessly, respect proving wild chaos births scholarly clarity.",
  },
  {
    audioData: [' ', ''],
    word: 'in relation to',
    meaning: [
      'Comparative connection established.',
      'Relative positioning analyzed.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Compared to.', 'Relative to.'],
    examples: ['In relation to population.', 'In relation to previous.'],
    synonyms: ['compared to', 'relative to'],
    antonyms: [''],
    shortStory:
      "In relation to golden crowns, peasant smile ruled perfectly. Lena's grin outshone royal splendor eternally, relation proving humble warmth wears mightiest diadems.",
  },
  {
    audioData: [' ', ''],
    word: '(in) the context of',
    meaning: [
      'Specific circumstances surrounding.',
      'Particular framework considered.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Within situation.', 'Specific framework.'],
    examples: ['In context of study.', 'In the context of history.'],
    synonyms: ['within framework', 'given circumstances'],
    antonyms: [''],
    shortStory:
      '(In) context of endless desert, single tear greened paradise eternally. Lena wept reviving wastelands perfectly, context proving tiniest sorrow transforms harshest environments.',
  },
  {
    audioData: [' ', ''],
    word: 'in the case of',
    meaning: ['Specific instance examined.', 'Particular example considered.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Specific example.', 'Particular case.'],
    examples: ['In case of failure.', 'In the case of success.'],
    synonyms: ['for example', 'specifically'],
    antonyms: [''],
    shortStory:
      'In case of dragon plague, Lena smiled conquering beasts eternally. Single grin routed monsters perfectly, case proving modest warmth cures mightiest scholarly crises.',
  },
  {
    audioData: [' ', ''],
    word: 'from the point of view of',
    meaning: [
      'Specific perspective adopted.',
      'Particular standpoint analyzed.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['From perspective.', 'Specific viewpoint.'],
    examples: [
      'From point of view of author.',
      'From the point of view of data.',
    ],
    synonyms: ['from perspective of', 'according to'],
    antonyms: [''],
    shortStory:
      "From point of view of beggar's rags, royal maps appeared perfectly. Lena decoded pauper cloth finding treasure eternally, viewpoint proving humble threads reveal vastest riches.",
  },
  {
    audioData: [' ', ''],
    word: 'when it comes to',
    meaning: ['Regarding particular topic.', 'Concerning specific subject.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Regarding topic.', 'About subject.'],
    examples: ['When it comes to results.', 'When it comes to theory.'],
    synonyms: ['regarding', 'about'],
    antonyms: [''],
    shortStory:
      "When it comes to crooked paths, straightest led to paradise eternally. Lena's winding routes avoided traps perfectly, topic proving modest journeys birth clearest destinations.",
  },
  {
    audioData: [' ', ''],
    word: 'in the form of',
    meaning: [
      'Particular manifestation presented.',
      'Specific embodiment observed.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['As shape.', 'Manifested as.'],
    examples: ['In form of chart.', 'In the form of evidence.'],
    synonyms: ['as', 'manifested as'],
    antonyms: [''],
    shortStory:
      "Wisdom appeared in form of fool's dance conquering dragons eternally. Lena's wild rhythm disarmed beasts perfectly, form proving crazy steps wield scholarly clarity.",
  },
  {
    audioData: [' ', ''],
    word: 'on the basis of',
    meaning: [
      'Founded upon evidence provided.',
      'Grounded in specified foundation.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Based on.', 'Founded upon.'],
    examples: ['On basis of data.', 'On the basis of findings.'],
    synonyms: ['based on', 'grounded in'],
    antonyms: [''],
    shortStory:
      'On basis of peasant crumb, empires fed eternally. Lena shared simple bread routing famines perfectly, foundation proving humble portions sustain vastest scholarly realms.',
  },
  {
    audioData: [' ', ''],
    word: 'to do with',
    meaning: ['Related or concerning topic.', 'Connected to subject matter.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Related to.', 'Concerning.'],
    examples: ['To do with methodology.', 'Something to do with results.'],
    synonyms: ['related to', 'concerning'],
    antonyms: [''],
    shortStory:
      'Everything to do with single smile healed kingdom plagues perfectly. Lena grinned curing nations eternally, connection proving modest warmth relates to mightiest remedies.',
  },

  {
    audioData: [' ', ''],
    word: 'as to',
    meaning: [
      'Regarding or concerning matter.',
      'With reference to specific issue.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Regarding.', 'Concerning.'],
    examples: ['As to methodology.', 'Questions as to validity.'],
    synonyms: ['regarding', 'concerning'],
    antonyms: [''],
    shortStory:
      'As to crooked paths, Lena found straightest treasure eternally. Winding routes avoided traps perfectly, reference proving modest journeys merit scholarly consideration.',
  },
  {
    audioData: [' ', ''],
    word: 'nothing to do with',
    meaning: [
      'Unrelated or disconnected entirely.',
      'No connection established.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Unrelated.', 'No connection.'],
    examples: ['Nothing to do with results.', 'Has nothing to do with theory.'],
    synonyms: ['unrelated to', 'irrelevant to'],
    antonyms: ['related to'],
    shortStory:
      'Dragon plague had nothing to do with swords; Lena smiled curing eternally. Grin routed monsters perfectly, disconnection proving warmth relates not to steel.',
  },
  {
    audioData: [' ', ''],
    word: 'the idea is that',
    meaning: ['Core concept introduced.', 'Central proposition stated.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Concept that.', 'Main thought.'],
    examples: [
      'The idea is that change occurs.',
      'Idea is that effort matters.',
    ],
    synonyms: ['concept that', 'notion that'],
    antonyms: [''],
    shortStory:
      'Idea is that single tear greens deserts eternally. Lena wept reviving wastelands perfectly, core proving tiniest sorrow births vastest scholarly miracles.',
  },
  {
    audioData: [' ', ''],
    word: 'the idea of',
    meaning: ['Abstract concept considered.', 'General notion entertained.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Concept of.', 'Notion about.'],
    examples: ['Idea of progress.', 'Idea of equality.'],
    synonyms: ['concept of', 'notion of'],
    antonyms: [''],
    shortStory:
      "Idea of fool's wisdom built perfect empires forever. Lena's crazy notion conquered rationally eternally, abstract proving wild concepts engineer clearest victories.",
  },
  {
    audioData: [' ', ''],
    word: 'this idea of',
    meaning: ['Specific concept referenced.', 'Particular notion highlighted.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['This concept.', 'Specific notion.'],
    examples: ['This idea of innovation.', 'This idea of change.'],
    synonyms: ['this concept', 'particular notion'],
    antonyms: [''],
    shortStory:
      'This idea of peasant crumb feeding kingdoms eternally awed scholars. Lena shared simple bread perfectly routing famines, specific proving humble notions sustain vastest realms.',
  },
  {
    audioData: [' ', ''],
    word: 'the idea that',
    meaning: ['Proposition containing clause.', 'Belief or hypothesis stated.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Belief that.', 'Hypothesis that.'],
    examples: ['Idea that culture shapes.', 'Idea that practice improves.'],
    synonyms: ['belief that', 'hypothesis that'],
    antonyms: [''],
    shortStory:
      "Idea that crooked bridges outlast straight spans proved eternally true. Lena's humble construction survived storms perfectly, proposition proving modest designs endure clearest.",
  },
  {
    audioData: [' ', ''],
    word: 'the notion of',
    meaning: ['General concept or belief.', 'Abstract idea considered.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Concept.', 'Belief.'],
    examples: ['Notion of justice.', 'Notion of progress.'],
    synonyms: ['concept of', 'idea of'],
    antonyms: [''],
    shortStory:
      "Notion of beggar's rags hiding treasure maps conquered skepticism eternally. Lena decoded pauper cloth perfectly finding gold, general proving humble beliefs reveal vastest riches.",
  },
  {
    audioData: [' ', ''],
    word: 'the meaning of',
    meaning: ['Significance or interpretation.', 'Purpose or sense defined.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Significance.', 'Interpretation.'],
    examples: ['Meaning of symbol.', 'Meaning of results.'],
    synonyms: ['significance of', 'interpretation of'],
    antonyms: [''],
    shortStory:
      "Meaning of fool's dance revealed dragon-slaying rhythm perfectly. Lena's wild steps disarmed beasts eternally, significance proving crazy motions hide mightiest scholarly truths.",
  },
  {
    audioData: [' ', ''],
    word: 'in the sense (that)',
    meaning: [
      'Specific interpretation clarified.',
      'Particular meaning specified.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Meaning that.', 'Specifically.'],
    examples: [
      'Success in sense that goals met.',
      'True in sense that applicable.',
    ],
    synonyms: ['meaning that', 'specifically'],
    antonyms: [''],
    shortStory:
      "Wisdom in sense that crooked paths led straightest paradise eternally. Lena's winding routes avoided traps perfectly, clarification proving modest journeys birth clearest scholarly destinations.",
  },

  {
    audioData: [' ', ''],
    word: 'in this/that case',
    meaning: ['Under specified circumstance.', 'Given particular condition.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Given condition.', 'Under circumstance.'],
    examples: ['In this case, results differ.', 'In that case, reconsider.'],
    synonyms: ['given circumstance', 'under condition'],
    antonyms: [''],
    shortStory:
      'In this/that case of dragon siege, Lena smiled routing beasts eternally. Grin disarmed monsters perfectly, condition proving modest warmth conquers mightiest crises.',
  },
  {
    audioData: [' ', ''],
    word: 'the question is',
    meaning: ['Core inquiry introduced.', 'Central problem posed.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Main question.', 'Key inquiry.'],
    examples: ['The question is whether.', 'Question is how to.'],
    synonyms: ['inquiry', 'central issue'],
    antonyms: [''],
    shortStory:
      'Question is whether crooked paths lead straightest to treasure eternally. Lena tested winding routes perfectly avoiding traps, inquiry proving modest journeys birth clearest answers.',
  },
  {
    audioData: [' ', ''],
    word: 'the point is that',
    meaning: ['Essential argument emphasized.', 'Core message clarified.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Main point.', 'Essential truth.'],
    examples: ['Point is that evidence shows.', 'The point is effectiveness.'],
    synonyms: ['essential truth', 'core argument'],
    antonyms: [''],
    shortStory:
      'Point is that peasant crumb fed empires eternally. Lena shared simple bread routing famines perfectly, essential proving humble portions sustain vastest scholarly realms.',
  },
  {
    audioData: [' ', ''],
    word: 'the problem of',
    meaning: [
      'Issue or difficulty identified.',
      'Challenge requiring solution.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Issue.', 'Challenge.'],
    examples: ['Problem of access.', 'Problem of inequality.'],
    synonyms: ['issue of', 'challenge of'],
    antonyms: [''],
    shortStory:
      'Problem of endless desert solved by single tear greening eternally. Lena wept reviving wastelands perfectly, challenge proving tiniest sorrow births vastest gardens.',
  },
  {
    audioData: [' ', ''],
    word: 'the problem with',
    meaning: ['Specific flaw identified.', 'Particular defect noted.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Flaw in.', 'Issue with.'],
    examples: ['Problem with approach.', 'Problem with assumption.'],
    synonyms: ['flaw in', 'defect of'],
    antonyms: [''],
    shortStory:
      "Problem with golden crowns was peasant smile outshone eternally. Lena's grin ruled warmer than royal splendor perfectly, flaw proving humble warmth wears mightiest diadems.",
  },
  {
    audioData: [' ', ''],
    word: 'the possibility of',
    meaning: ['Potential occurrence considered.', 'Feasibility examined.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Potential.', 'Chance of.'],
    examples: ['Possibility of success.', 'Possibility of change.'],
    synonyms: ['potential for', 'chance of'],
    antonyms: [''],
    shortStory:
      "Possibility of fool's wisdom conquering rational empires proved eternally true. Lena's crazy tactics routed kings perfectly, potential proving wild chaos births clearest victories.",
  },
  {
    audioData: [' ', ''],
    word: 'the state of',
    meaning: ['Current condition assessed.', 'Existing situation described.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Condition.', 'Situation.'],
    examples: ['State of research.', 'State of economy.'],
    synonyms: ['condition of', 'situation of'],
    antonyms: [''],
    shortStory:
      "State of beggar's rags hid royal treasure maps perfectly. Lena decoded pauper cloth finding gold eternally, condition proving humble threads conceal vastest riches.",
  },
  {
    audioData: [' ', ''],
    word: 'the issue of',
    meaning: ['Controversial matter raised.', 'Topic requiring discussion.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Matter.', 'Topic.'],
    examples: ['Issue of privacy.', 'Issue of equality.'],
    synonyms: ['matter of', 'topic of'],
    antonyms: [''],
    shortStory:
      "Issue of crooked bridges outlasting straight spans settled eternally. Lena's humble construction survived storms perfectly, matter proving modest designs endure clearest.",
  },
  {
    audioData: [' ', ''],
    word: 'the question of',
    meaning: ['Topic of inquiry posed.', 'Problem requiring investigation.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Inquiry about.', 'Problem regarding.'],
    examples: ['Question of origin.', 'Question of impact.'],
    synonyms: ['inquiry about', 'problem regarding'],
    antonyms: [''],
    shortStory:
      'Question of single smile defeating dragons answered eternally yes. Lena grinned conquering beasts perfectly, investigation proving modest warmth wields mightiest scholarly weapons.',
  },
  {
    audioData: [' ', ''],
    word: 'the nature of',
    meaning: [
      'Essential character identified.',
      'Fundamental quality analyzed.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Essence.', 'Core character.'],
    examples: [
      'Nature of problem complex.',
      'Nature of relationship reciprocal.',
    ],
    synonyms: ['essence of', 'character of'],
    antonyms: [''],
    shortStory:
      "Nature of crooked wisdom led straightest to eternal treasure perfectly. Lena's winding insight avoided traps flawlessly, essence proving modest truths hide clearest paths.",
  },
  {
    audioData: [' ', ''],
    word: 'one of the things',
    meaning: ['Specific item among several.', 'Particular element noted.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['One item.', 'Among several.'],
    examples: ['One of the things noticed.', 'One of the things considered.'],
    synonyms: ['among others', 'particularly'],
    antonyms: [''],
    shortStory:
      "One of the things Lena noticed: fool's madness conquered rationally eternally. Crazy tactics routed kings perfectly, particular proving wild chaos merits scholarly attention.",
  },
  {
    audioData: [' ', ''],
    word: 'in particular',
    meaning: ['Specifically emphasized.', 'Especially highlighted.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Especially.', 'Specifically.'],
    examples: ['Results in particular.', 'This factor in particular.'],
    synonyms: ['especially', 'particularly'],
    antonyms: [''],
    shortStory:
      'In particular, peasant crumb fed empires eternally. Lena shared simple bread routing famines perfectly, specific proving humble portions sustain vastest scholarly realms.',
  },
  {
    audioData: [' ', ''],
    word: 'the most important',
    meaning: [
      'Highest priority established.',
      'Primary significance recognized.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Highest priority.', 'Most crucial.'],
    examples: ['Most important finding.', 'Most important factor.'],
    synonyms: ['primary', 'crucial'],
    antonyms: ['least important'],
    shortStory:
      'Most important truth: single smile defeated dragon hordes eternally. Lena grinned conquering beasts perfectly, priority proving modest warmth wields mightiest scholarly power.',
  },
  {
    audioData: [' ', ''],
    word: 'the importance of',
    meaning: ['Significance emphasized.', 'Value recognized.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Significance.', 'Value.'],
    examples: ['Importance of evidence.', 'Importance of context.'],
    synonyms: ['significance of', 'value of'],
    antonyms: [''],
    shortStory:
      "Importance of beggar's rags hid royal treasure maps eternally. Lena decoded pauper cloth finding gold perfectly, significance proving humble threads conceal vastest riches.",
  },
  {
    audioData: [' ', ''],
    word: 'is important to',
    meaning: [
      'Crucial for specified purpose.',
      'Essential regarding particular.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Crucial for.', 'Essential to.'],
    examples: ['Important to methodology.', 'Important to understanding.'],
    synonyms: ['crucial for', 'essential to'],
    antonyms: [''],
    shortStory:
      'Single tear is important to greening deserts eternally. Lena wept reviving wastelands perfectly, crucial proving tiniest sorrow births vastest scholarly gardens.',
  },
  {
    audioData: [' ', ''],
    word: 'a very important',
    meaning: ['Highly significant emphasized.', 'Particularly crucial noted.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Highly crucial.', 'Very significant.'],
    examples: ['Very important point.', 'Very important consideration.'],
    synonyms: ['highly significant', 'particularly crucial'],
    antonyms: [''],
    shortStory:
      "Very important crooked bridge spanned eternal chasms perfectly. Lena's humble span outlasted marble rivals, highly proving modest construction endures clearest.",
  },
  {
    audioData: [' ', ''],
    word: 'one of the key',
    meaning: [
      'Primary element among essentials.',
      'Central component highlighted.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Main element.', 'Key component.'],
    examples: ['One of the key factors.', 'One of the key findings.'],
    synonyms: ['central', 'primary'],
    antonyms: [''],
    shortStory:
      "One of key truths: fool's dance conquered dragons eternally. Lena's wild rhythm disarmed beasts perfectly, central proving crazy steps wield scholarly clarity.",
  },
  {
    audioData: [' ', ''],
    word: 'one of the most',
    meaning: ['Highest among significant group.', 'Top tier emphasized.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Top tier.', 'Among highest.'],
    examples: ['One of the most important.', 'One of the most effective.'],
    synonyms: ['top tier', 'among highest'],
    antonyms: [''],
    shortStory:
      "One of most powerful: peasant dirt outgrew golden palaces eternally. Lena's humble soil fed nations perfectly, highest proving modest earth yields mightiest harvests.",
  },
  {
    audioData: [' ', ''],
    word: '(so) in other words',
    meaning: ['Rephrasing for clarity.', 'Alternative explanation provided.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Simply put.', 'To rephrase.'],
    examples: [
      'In other words, simplified.',
      '(So) in other words, results show.',
    ],
    synonyms: ['simply put', 'to rephrase'],
    antonyms: [''],
    shortStory:
      "(So) in other words, crooked path led straightest to treasure eternally. Lena's winding route avoided traps perfectly, rephrase proving modest journeys birth clearest scholarly destinations.",
  },
  {
    audioData: [' ', ''],
    word: 'as I say',
    meaning: ['Repeated for emphasis.', 'Current statement reinforced.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['As stated.', 'Repeatedly.'],
    examples: ['As I say, crucial.', 'Performance, as I say, improved.'],
    synonyms: ['stated', 'repeatedly'],
    antonyms: [''],
    shortStory:
      'As I say, single smile conquered dragon empires eternally. Lena grinned routing beasts perfectly, emphasis proving modest warmth wields mightiest scholarly weapons universally.',
  },
  {
    audioData: [' ', ''],
    word: 'as I said',
    meaning: ['Previous statement recalled.', 'Earlier point referenced.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Previously stated.', 'As mentioned.'],
    examples: ['As I said, confirmed.', 'Theory, as I said, applies.'],
    synonyms: ['previously stated', 'mentioned earlier'],
    antonyms: [''],
    shortStory:
      'As I said, peasant crumb fed thousand kings eternally. Lena shared simple bread routing famines perfectly, recall proving humble portions sustain vastest scholarly memory.',
  },
  {
    audioData: [' ', ''],
    word: 'that is to say',
    meaning: ['Clarification introduced.', 'Precise rephrasing offered.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Precisely.', 'That means.'],
    examples: [
      'That is to say, specific.',
      'Success, that is to say, measured.',
    ],
    synonyms: ['precisely', 'namely'],
    antonyms: [''],
    shortStory:
      "That is to say, fool's madness built perfect empires eternally. Lena's crazy tactics conquered rationally perfectly, precision proving wild chaos births clearest scholarly strategies.",
  },
  {
    audioData: [' ', ''],
    word: 'what I mean by',
    meaning: ['Specific definition clarified.', 'Intended sense explained.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['I mean.', 'Definition of.'],
    examples: ['What I mean by success.', 'Theory, what I mean by, applied.'],
    synonyms: ['definition', 'intended by'],
    antonyms: [''],
    shortStory:
      "What I mean by crooked wisdom led straightest paradise eternally. Lena's winding insight avoided traps perfectly, definition proving modest truths hide clearest paths.",
  },
  {
    audioData: [' ', ''],
    word: 'in a sense',
    meaning: [
      'Particular interpretation qualified.',
      'Limited applicability noted.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Partially.', 'In one way.'],
    examples: ['In a sense, true.', 'Progress, in a sense, achieved.'],
    synonyms: ['partially', 'somewhat'],
    antonyms: [''],
    shortStory:
      "In a sense, beggar's rags wore royal splendor eternally. Lena decoded pauper cloth finding treasure perfectly, qualified proving humble threads conceal vastest riches partially.",
  },
  {
    audioData: [' ', ''],
    word: 'if you like',
    meaning: [
      'Permissive qualification offered.',
      'Optional terminology suggested.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Optionally.', 'If preferred.'],
    examples: ['Genius, if you like.', 'Revolution, if you like, occurred.'],
    synonyms: ['optionally', 'so to speak'],
    antonyms: [''],
    shortStory:
      "Fool's dance, if you like, conquered dragons eternally. Lena's wild rhythm disarmed beasts perfectly, optional proving crazy steps wield scholarly clarity permissively.",
  },
  {
    audioData: [' ', ''],
    word: 'as it were',
    meaning: ['Figurative expression qualified.', 'Metaphorical usage noted.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Figuratively.', 'So to speak.'],
    examples: [
      'Literally, as it were, transformed.',
      'Bridge, as it were, eternal.',
    ],
    synonyms: ['figuratively', 'metaphorically'],
    antonyms: [''],
    shortStory:
      'Single tear, as it were, greened deserts eternally. Lena wept reviving wastelands perfectly, figurative proving tiniest sorrow births vastest gardens metaphorically.',
  },
  {
    audioData: [' ', ''],
    word: 'you might say',
    meaning: [
      'Possible interpretation suggested.',
      'Alternative phrasing permitted.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['One could say.', 'Possibly.'],
    examples: ['Success, you might say.', 'Chaos, you might say, ordered.'],
    synonyms: ['arguably', 'one could claim'],
    antonyms: [''],
    shortStory:
      "Peasant dirt, you might say, outgrew golden palaces eternally. Lena's humble soil fed nations perfectly, possible proving modest earth yields mightiest harvests arguably.",
  },
  {
    audioData: [' ', ''],
    word: 'in some way',
    meaning: [
      'Partial connection acknowledged.',
      'Indirect relationship noted.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Somehow.', 'Partially connected.'],
    examples: ['Connected, in some way.', 'Related, in some way.'],
    synonyms: ['somehow', 'indirectly'],
    antonyms: [''],
    shortStory:
      "In some way, crooked bridge spanned straightest eternities perfectly. Lena's humble span outlasted rivals flawlessly, indirect proving modest construction endures clearest connections.",
  },
  {
    audioData: [' ', ''],
    word: 'more or less',
    meaning: ['Approximate accuracy qualified.', 'Rough equivalence stated.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Approximately.', 'Roughly.'],
    examples: ['True more or less.', 'Complete, more or less.'],
    synonyms: ['approximately', 'roughly'],
    antonyms: ['exactly'],
    shortStory:
      "Wisdom, more or less, flowed from fool's mouth eternally. Lena's crazy words guided kingdoms perfectly, approximate proving wild insight births clearest truths roughly.",
  },

  {
    audioData: [' ', ''],
    word: '(the) way(s) in which',
    meaning: ['Manner or method described.', 'Process by which occurs.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Method.', 'How occurs.'],
    examples: ['Ways in which change happens.', 'Way in which works.'],
    synonyms: ['manner that', 'method by which'],
    antonyms: [''],
    shortStory:
      "Way(s) in which crooked paths led straightest revealed perfect wisdom eternally. Lena's winding routes avoided traps flawlessly, method proving modest journeys birth clearest scholarly truths.",
  },
  {
    audioData: [' ', ''],
    word: 'the way that',
    meaning: ['Specific manner identified.', 'Particular method noted.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['How specifically.', 'Manner that.'],
    examples: ['Way that evidence shows.', 'Way that theory explains.'],
    synonyms: ['how', 'manner in which'],
    antonyms: [''],
    shortStory:
      "Way that fool's madness conquered rationally built eternal empires perfectly. Lena's crazy tactics routed kings flawlessly, specific proving wild chaos engineers mightiest scholarly victories.",
  },
  {
    audioData: [' ', ''],
    word: 'a way of',
    meaning: ['Method or approach utilized.', 'Means for achieving.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Method.', 'Approach.'],
    examples: ['Way of measuring success.', 'Way of understanding data.'],
    synonyms: ['method', 'approach'],
    antonyms: [''],
    shortStory:
      'Way of single smile defeated dragon hordes eternally. Lena grinned conquering beasts perfectly, approach proving modest warmth wields mightiest scholarly weapons universally.',
  },
  {
    audioData: [' ', ''],
    word: 'in the way that',
    meaning: ['Similar manner specified.', 'Comparative method described.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Like how.', 'Similarly to.'],
    examples: [
      'In way that previously occurred.',
      'Works in way that expected.',
    ],
    synonyms: ['like', 'similarly'],
    antonyms: [''],
    shortStory:
      'In way that peasant crumb fed empires, Lena shared simple bread eternally. Humble portions routed famines perfectly, comparative proving modest sustenance nourishes vastest realms.',
  },
  {
    audioData: [' ', ''],
    word: 'in a way that',
    meaning: ['Resulting manner achieved.', 'Method producing effect.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Resulting how.', 'Producing effect.'],
    examples: ['Designed in way that works.', 'Changed in way that benefits.'],
    synonyms: ['resulting in', 'producing'],
    antonyms: [''],
    shortStory:
      "In way that beggar's rags revealed treasure maps, Lena decoded perfectly eternally. Pauper cloth hid gold flawlessly, resulting proving humble threads conceal vastest scholarly riches.",
  },
  {
    audioData: [' ', ''],
    word: 'in such a way',
    meaning: ['Particular manner emphasized.', 'Specific method highlighted.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Specifically how.', 'Particularly.'],
    examples: ['Organized in such way.', 'Functions in such way.'],
    synonyms: ['particularly', 'specifically'],
    antonyms: [''],
    shortStory:
      'In such way single tear greened deserts eternally. Lena wept reviving wastelands perfectly, specific proving tiniest sorrow births vastest scholarly gardens universally.',
  },
  {
    audioData: [' ', ''],
    word: 'in this/that way',
    meaning: ['Demonstrative manner referenced.', 'Specific method indicated.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Like this/that.', 'Specifically here.'],
    examples: ['Helps in this way.', 'Failed in that way.'],
    synonyms: ['thus', 'thereby'],
    antonyms: [''],
    shortStory:
      "In this/that way crooked bridge spanned eternal chasms perfectly. Lena's humble construction outlasted rivals flawlessly, demonstrative proving modest spans endure clearest eternities.",
  },
  {
    audioData: [' ', ''],
    word: 'in the same way',
    meaning: ['Identical manner applied.', 'Similar method utilized.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Similarly.', 'Likewise.'],
    examples: ['Works in same way.', 'Occurs in same way.'],
    synonyms: ['similarly', 'likewise'],
    antonyms: ['differently'],
    shortStory:
      "In same way fool's dance conquered dragons, Lena's wild rhythm disarmed eternally. Crazy steps routed beasts perfectly, identical proving wild methods wield scholarly clarity universally.",
  },
  {
    audioData: [' ', ''],
    word: 'the same thing',
    meaning: ['Identical concept rephrased.', 'Equivalent idea expressed.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Equivalent.', 'Same concept.'],
    examples: ['Saying the same thing.', 'Means same thing.'],
    synonyms: ['equivalent', 'identical'],
    antonyms: ['different'],
    shortStory:
      "Peasant dirt and golden palaces grew the same thing eternally: perfect harvests. Lena's humble soil fed nations flawlessly, equivalent proving modest earth yields identical scholarly abundance.",
  },
  {
    audioData: [' ', ''],
    word: 'going to give you an example',
    meaning: [
      'Concrete illustration previewed.',
      'Specific instance forthcoming.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ["Here's example.", 'Illustration coming.'],
    examples: [
      'Going to give you example of process.',
      "Example I'll show demonstrates.",
    ],
    synonyms: ['illustration', 'instance'],
    antonyms: [''],
    shortStory:
      "Going to give you example of crooked bridge spanning eternities perfectly. Lena's humble span outlasted marble rivals flawlessly, preview proving modest construction illustrates clearest endurance.",
  },
  {
    audioData: [' ', ''],
    word: '(so) for example',
    meaning: [
      'Illustrative instance introduced.',
      'Representative case presented.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['E.g.', 'Like.'],
    examples: [
      '(So) for example, results show.',
      'Speed, for example, increased.',
    ],
    synonyms: ['e.g.', 'such as'],
    antonyms: [''],
    shortStory:
      "(So) for example, fool's madness conquered rational empires eternally. Lena's crazy tactics routed kings perfectly, instance proving wild chaos illustrates mightiest scholarly victories.",
  },
  {
    audioData: [' ', ''],
    word: 'for instance',
    meaning: ['Specific illustration provided.', 'Particular example given.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['E.g.', 'Specifically.'],
    examples: [
      'For instance, data confirms.',
      'Theory, for instance, applies.',
    ],
    synonyms: ['e.g.', 'namely'],
    antonyms: [''],
    shortStory:
      'For instance, single smile defeated dragon hordes eternally. Lena grinned conquering beasts perfectly, particular proving modest warmth illustrates mightiest scholarly weapons universally.',
  },
  {
    audioData: [' ', ''],
    word: 'such as',
    meaning: ['Exemplary items listed.', 'Representative examples noted.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Like.', 'E.g.'],
    examples: ['Factors such as cost, time.', 'Methods such as surveys.'],
    synonyms: ['e.g.', 'like'],
    antonyms: [''],
    shortStory:
      'Peasant tools such as crumbs fed empires eternally. Lena shared simple bread routing famines perfectly, exemplary proving humble portions illustrate vastest scholarly sustenance.',
  },
  {
    audioData: [' ', ''],
    word: 'an example of',
    meaning: [
      'Concrete instance representing.',
      'Specific case demonstrating.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Illustration.', 'Case showing.'],
    examples: ['Example of success achieved.', 'Example of theory applied.'],
    synonyms: ['illustration', 'case'],
    antonyms: [''],
    shortStory:
      "Example of beggar's rags hiding royal treasure maps eternally. Lena decoded pauper cloth finding gold perfectly, concrete proving humble threads illustrate vastest riches.",
  },
  {
    audioData: [' ', ''],
    word: 'to show you',
    meaning: ['Demonstrative purpose stated.', 'Visual proof presented.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Demonstrate.', 'Illustrate.'],
    examples: ['To show you results clearly.', 'To show you process works.'],
    synonyms: ['demonstrate', 'illustrate'],
    antonyms: [''],
    shortStory:
      'To show you single tear greened deserts eternally. Lena wept reviving wastelands perfectly, demonstrative proving tiniest sorrow illustrates vastest scholarly gardens universally.',
  },
  {
    audioData: [' ', ''],
    word: 'an idea of',
    meaning: ['Conceptual impression conveyed.', 'General sense provided.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Impression.', 'General sense.'],
    examples: ['Idea of complexity involved.', 'Idea of scale impressive.'],
    synonyms: ['impression', 'sense'],
    antonyms: [''],
    shortStory:
      "Idea of crooked wisdom leading straightest paradise gave perfect clarity eternally. Lena's winding insight avoided traps flawlessly, conceptual proving modest truths illustrate clearest paths.",
  },
  {
    audioData: [' ', ''],
    word: 'a sense of',
    meaning: [
      'Impression or feeling evoked.',
      'Perceptual understanding given.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Feeling.', 'Impression.'],
    examples: ['Sense of urgency needed.', 'Sense of achievement felt.'],
    synonyms: ['feeling', 'impression'],
    antonyms: [''],
    shortStory:
      "Sense of fool's dance conquering dragons gave eternal confidence perfectly. Lena's wild rhythm disarmed beasts flawlessly, perceptual proving crazy steps illustrate scholarly power.",
  },
  {
    audioData: [' ', ''],
    word: 'what I mean',
    meaning: ['Clarification of intent.', 'Specific explanation offered.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Explanation.', 'Clarification.'],
    examples: ['What I mean is this.', 'By success, what I mean.'],
    synonyms: ['explanation', 'clarification'],
    antonyms: [''],
    shortStory:
      "What I mean by peasant dirt outgrowing palaces illustrates perfect harvests eternally. Lena's humble soil fed nations flawlessly, specific proving modest earth demonstrates mightiest yields.",
  },
  {
    audioData: [' ', ''],
    word: 'a bit like',
    meaning: ['Partial similarity noted.', 'Approximate comparison made.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Similar to.', 'Somewhat like.'],
    examples: ['Bit like previous case.', 'Works a bit like this.'],
    synonyms: ['somewhat like', 'similar to'],
    antonyms: [''],
    shortStory:
      "Crooked bridge a bit like fool's wisdom spanned eternities perfectly. Lena's humble construction outlasted rivals flawlessly, approximate proving modest designs illustrate enduring clarity.",
  },
  {
    audioData: [' ', ''],
    word: 'something like',
    meaning: [
      'Approximate equivalence suggested.',
      'Rough similarity indicated.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Approximately.', 'Roughly similar.'],
    examples: ['Something like this occurred.', 'Process something like that.'],
    synonyms: ['approximately', 'roughly'],
    antonyms: [''],
    shortStory:
      'Something like single smile routed dragon armies eternally. Lena grinned conquering beasts perfectly, rough proving modest warmth illustrates mightiest scholarly weapons universally.',
  },
  {
    audioData: [' ', ''],
    word: 'like this',
    meaning: [
      'Demonstrative similarity shown.',
      'Specific manner illustrated.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['This way.', 'Like here.'],
    examples: ['Happens like this.', 'Works like this.'],
    synonyms: ['thus', 'in this manner'],
    antonyms: [''],
    shortStory:
      'Wisdom grows like this from peasant crumbs feeding empires eternally. Lena shared simple bread routing famines perfectly, demonstrative proving humble portions illustrate vastest sustenance.',
  },

  {
    audioData: [' ', ''],
    word: 'as well as',
    meaning: [
      'In addition to; plus; also including.',
      'Connecting equal elements.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Plus.', 'Also including.'],
    examples: ['Apples as well as oranges.', 'Skills as well as knowledge.'],
    synonyms: ['plus', 'and also'],
    antonyms: [''],
    shortStory:
      'Lena planted grain as well as magic beans feeding nation eternally. Ordinary crop plus fairytale stalk created abundance, well-as proving diversity harvests doubly.',
  },
  {
    audioData: [' ', ''],
    word: 'and so on (and so forth)',
    meaning: [
      'Continuing similarly indefinitely.',
      'Etcetera pattern indicated.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Etc.', 'And continuing.'],
    examples: ['Tools, methods, and so on.', 'Data, analysis, and so forth.'],
    synonyms: ['etc.', 'and continuing'],
    antonyms: [''],
    shortStory:
      "Peasant tools, crooked bridges, fool's dances, and so on conquered empires eternally. Lena's humble methods routed kings perfectly, continuation proving modest means birth endless victories.",
  },
  {
    audioData: [' ', ''],
    word: 'and all the rest of it',
    meaning: ['Remaining items included.', 'Everything else collectively.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Everything else.', 'All remaining.'],
    examples: [
      'Facts, figures, and all rest.',
      'Theory, evidence, and rest of it.',
    ],
    synonyms: ['everything else', 'all remaining'],
    antonyms: [''],
    shortStory:
      'Single smiles, tears, crumbs, and all rest of it greened deserts eternally. Lena shared humble elements perfectly reviving wastelands, collective proving tiniest collection births vastest gardens.',
  },
  {
    audioData: [' ', ''],
    word: 'et cetera (et cetera)',
    meaning: ['And others of same kind.', 'Similar items continuing.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Etc.', 'And others.'],
    examples: [
      'Studies, surveys, et cetera.',
      'Methods, approaches, et cetera.',
    ],
    synonyms: ['etc.', 'and others'],
    antonyms: [''],
    shortStory:
      "Beggars' rags, fools' dances, et cetera revealed royal secrets eternally. Lena decoded humble signs finding treasure perfectly, similar proving modest symbols conceal endless scholarly riches.",
  },
  {
    audioData: [' ', ''],
    word: '(not only) but also',
    meaning: ['Dual emphasis connected.', 'Both elements equally stressed.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Not just, but.', 'Both A and B.'],
    examples: [
      'Not only theory but also practice.',
      'Not only data but also analysis.',
    ],
    synonyms: ['both', 'as well as'],
    antonyms: [''],
    shortStory:
      "(Not only) Lena's crooked paths but also straight wisdom led paradise eternally. Winding routes plus clear insight avoided traps perfectly, dual proving modest duality births clearest journeys.",
  },

  {
    audioData: [' ', ''],
    word: 'or something like that',
    meaning: [
      'Approximate equivalence suggested.',
      'Rough similarity indicated.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Approximately.', 'Roughly similar.'],
    examples: [
      'Chaos, or something like that.',
      'Works or something like that.',
    ],
    synonyms: ['roughly', 'approximately'],
    antonyms: [''],
    shortStory:
      'Crooked wisdom, or something like that, led Lena straightest to treasure eternally. Winding insight avoided traps perfectly, approximate proving modest truths birth clearest journeys roughly.',
  },
  {
    audioData: [' ', ''],
    word: 'something to do with',
    meaning: ['Vague connection indicated.', 'Loose relation acknowledged.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Related vaguely.', 'Somewhat connected.'],
    examples: [
      'Something to do with data.',
      'Issue something to do with theory.',
    ],
    synonyms: ['vaguely related', 'loosely connected'],
    antonyms: [''],
    shortStory:
      "Something to do with fool's madness conquered empires eternally. Lena's crazy tactics routed kings perfectly, vague proving wild chaos relates to mightiest scholarly victories.",
  },
  {
    audioData: [' ', ''],
    word: 'a kind of',
    meaning: ['General category suggested.', 'Broad type indicated.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Type of.', 'Category.'],
    examples: ['A kind of process.', 'Kind of result expected.'],
    synonyms: ['type of', 'category'],
    antonyms: [''],
    shortStory:
      "Kind of peasant smile ruled kingdoms eternally. Lena's grin outshone crowns perfectly, broad proving modest warmth governs like royal scepters universally.",
  },
  {
    audioData: [' ', ''],
    word: 'a sort of',
    meaning: ['Approximate classification.', 'Rough categorization.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Roughly.', 'Approximately type.'],
    examples: ['Sort of improvement noted.', 'A sort of pattern emerges.'],
    synonyms: ['roughly', 'approximately'],
    antonyms: [''],
    shortStory:
      "Sort of crooked bridge spanned eternal chasms perfectly. Lena's humble span outlasted rivals flawlessly, rough proving modest construction endures clearest eternities.",
  },
  {
    audioData: [' ', ''],
    word: 'some kind of',
    meaning: ['Indefinite category referenced.', 'Unspecified type noted.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Some type.', 'Unspecified category.'],
    examples: ['Some kind of effect.', 'Some kind of change.'],
    synonyms: ['certain type', 'unspecified'],
    antonyms: [''],
    shortStory:
      'Some kind of single tear greened deserts eternally. Lena wept reviving wastelands perfectly, indefinite proving tiniest sorrow births vastest scholarly gardens universally.',
  },
  {
    audioData: [' ', ''],
    word: 'some sort of',
    meaning: ['Vague classification used.', 'Indefinite categorization.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Vague type.', 'Rough category.'],
    examples: ['Some sort of pattern.', 'Some sort of solution.'],
    synonyms: ['vague type', 'indefinite'],
    antonyms: [''],
    shortStory:
      "Some sort of beggar's rags hid royal treasure maps perfectly. Lena decoded pauper cloth finding gold eternally, vague proving humble threads conceal vastest riches indefinitely.",
  },
  {
    audioData: [' ', ''],
    word: 'this/that sort of (thing)',
    meaning: ['Specific vague reference.', 'Particular indefinite category.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['This/that type.', 'Specific vague.'],
    examples: ['This sort of result.', 'That sort of problem.'],
    synonyms: ['this/that type', 'particular vague'],
    antonyms: [''],
    shortStory:
      "This/that sort of fool's dance conquered dragons eternally. Lena's wild rhythm disarmed beasts perfectly, specific proving crazy steps wield mightiest scholarly clarity indefinitely.",
  },
  {
    audioData: [' ', ''],
    word: 'this/that kind of (thing)',
    meaning: ['Demonstrative vague category.', 'Pointed indefinite reference.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['This/that category.', 'Pointed vague.'],
    examples: ['This kind of data.', 'That kind of approach.'],
    synonyms: ['this/that category', 'pointed indefinite'],
    antonyms: [''],
    shortStory:
      'This/that kind of peasant crumb fed empires eternally. Lena shared simple bread routing famines perfectly, demonstrative proving humble portions sustain vastest realms indefinitely.',
  },
  {
    audioData: [' ', ''],
    word: 'the sort of thing',
    meaning: ['Typical vague example.', 'Characteristic indefinite case.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Typical type.', 'Characteristic vague.'],
    examples: ['Sort of thing expected.', 'The sort of thing studied.'],
    synonyms: ['typical type', 'characteristic'],
    antonyms: [''],
    shortStory:
      "Sort of thing where crooked paths led straightest paradise eternally. Lena's winding routes avoided traps perfectly, typical proving modest journeys birth clearest scholarly destinations.",
  },
  {
    audioData: [' ', ''],
    word: 'all sorts of',
    meaning: ['Numerous varied categories.', 'Diverse indefinite types.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Many types.', 'Various kinds.'],
    examples: ['All sorts of factors.', 'All sorts of methods.'],
    synonyms: ['various', 'numerous types'],
    antonyms: [''],
    shortStory:
      "All sorts of humble tools conquered golden empires eternally. Lena's peasant methods routed kings perfectly, diverse proving modest variety wields mightiest scholarly victories universally.",
  },

  {
    audioData: [' ', ''],
    word: 'all kinds of',
    meaning: ['Numerous varied categories.', 'Diverse types collectively.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Many types.', 'Various categories.'],
    examples: [
      'All kinds of factors influence.',
      'All kinds of methods tested.',
    ],
    synonyms: ['various', 'numerous types'],
    antonyms: [''],
    shortStory:
      "All kinds of peasant tools conquered golden empires eternally. Lena's humble variety routed kings perfectly, diverse proving modest categories wield mightiest scholarly victories.",
  },
  {
    audioData: [' ', ''],
    word: 'and things like that',
    meaning: [
      'Similar items included indefinitely.',
      'Related examples continuing.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Etc.', 'Similar items.'],
    examples: [
      'Tools, methods, and things like that.',
      'Data, results, and things like that.',
    ],
    synonyms: ['etc.', 'similar'],
    antonyms: [''],
    shortStory:
      "Crooked bridges, fool dances, and things like that spanned eternities perfectly. Lena's humble methods outlasted rivals flawlessly, similar proving modest examples endure clearest.",
  },
  {
    audioData: [' ', ''],
    word: 'in a way',
    meaning: ['Partial manner qualified.', 'Limited applicability noted.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Partially.', 'Somewhat.'],
    examples: ['True in a way.', 'Works in a way.'],
    synonyms: ['partially', 'somewhat'],
    antonyms: [''],
    shortStory:
      'In a way, single smile ruled dragon empires eternally. Lena grinned conquering beasts perfectly, partial proving modest warmth governs mightiest realms somewhat.',
  },
  {
    audioData: [' ', ''],
    word: 'in some ways',
    meaning: ['Multiple partial aspects.', 'Several limited similarities.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Partially in aspects.', 'Several ways.'],
    examples: ['Similar in some ways.', 'Better in some ways.'],
    synonyms: ['partially', 'in aspects'],
    antonyms: [''],
    shortStory:
      "In some ways, beggar's rags outshone royal robes eternally. Lena decoded pauper cloth finding treasure perfectly, multiple proving humble threads rival vastest riches partially.",
  },
  {
    audioData: [' ', ''],
    word: 'to some extent',
    meaning: ['Partial degree acknowledged.', 'Limited scope recognized.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Partially.', 'Limited degree.'],
    examples: ['True to some extent.', 'Valid to some extent.'],
    synonyms: ['partially', 'somewhat'],
    antonyms: [''],
    shortStory:
      "To some extent, fool's madness built perfect wisdom eternally. Lena's crazy tactics routed rational kings flawlessly, limited proving wild chaos births scholarly clarity partially.",
  },
  {
    audioData: [' ', ''],
    word: 'of some kind',
    meaning: ['Indefinite category referenced.', 'Unspecified type indicated.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Some type.', 'Unspecified.'],
    examples: ['Effect of some kind.', 'Change of some kind.'],
    synonyms: ['certain', 'unspecified'],
    antonyms: [''],
    shortStory:
      'Treasure of some kind hid in peasant crumbs eternally. Lena shared simple bread revealing gold perfectly, indefinite proving humble portions conceal vastest scholarly riches.',
  },
  {
    audioData: [' ', ''],
    word: 'or whatever',
    meaning: [
      'Dismissive indefinite inclusion.',
      'Casual continuation suggested.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Or etc.', 'Whatever similar.'],
    examples: ['Tools, methods, or whatever.', 'Data, results, or whatever.'],
    synonyms: ['etc.', 'or similar'],
    antonyms: [''],
    shortStory:
      'Single tears, crooked paths, or whatever greened deserts eternally. Lena wept reviving wastelands perfectly, casual proving tiniest elements birth vastest gardens universally.',
  },
  {
    audioData: [' ', ''],
    word: 'a little bit about',
    meaning: ['Brief introduction provided.', 'Short overview given.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Briefly about.', 'Short intro.'],
    examples: ['Little bit about theory.', 'A little bit about process.'],
    synonyms: ['briefly', 'overview'],
    antonyms: [''],
    shortStory:
      "Little bit about fool's dance conquering dragons gave eternal clarity perfectly. Lena's wild rhythm disarmed beasts flawlessly, brief proving crazy steps merit scholarly introduction.",
  },
  {
    audioData: [' ', ''],
    word: 'a (little) bit more about',
    meaning: ['Slight elaboration offered.', 'Additional detail provided.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['More detail.', 'Further about.'],
    examples: ['Bit more about results.', 'Little bit more about methods.'],
    synonyms: ['further', 'additional'],
    antonyms: [''],
    shortStory:
      "Bit more about peasant dirt outgrowing palaces revealed perfect harvests eternally. Lena's humble soil fed nations flawlessly, additional proving modest earth yields mightiest scholarly abundance.",
  },
  {
    audioData: [' ', ''],
    word: 'the same sort of',
    meaning: [
      'Identical vague category.',
      'Similar indefinite classification.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Similar type.', 'Same category.'],
    examples: ['Same sort of problem.', 'Same sort of result.'],
    synonyms: ['similar type', 'like kind'],
    antonyms: [''],
    shortStory:
      'Same sort of crooked wisdom led Lena straightest to treasure eternally. Winding insight avoided traps perfectly, identical proving modest categories birth clearest scholarly journeys.',
  },
  {
    audioData: [' ', ''],
    word: 'the sorts of',
    meaning: ['Typical indefinite categories.', 'Characteristic vague types.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Typical types.', 'Characteristic categories.'],
    examples: ['Sorts of factors considered.', 'Sorts of methods used.'],
    synonyms: ['typical types', 'characteristic'],
    antonyms: [''],
    shortStory:
      "Sorts of peasant tools conquered golden empires eternally. Lena's humble variety routed kings perfectly, typical proving modest categories wield mightiest scholarly victories.",
  },
  {
    audioData: [' ', ''],
    word: 'the kinds of',
    meaning: ['Specific category types.', 'Particular classifications noted.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Types of.', 'Categories.'],
    examples: ['Kinds of evidence gathered.', 'Kinds of approaches tested.'],
    synonyms: ['types of', 'categories'],
    antonyms: [''],
    shortStory:
      "Kinds of fool's madness built perfect strategies eternally. Lena's crazy variety outsmarted rational sages flawlessly, specific proving wild categories engineer clearest wisdom.",
  },
  {
    audioData: [' ', ''],
    word: 'these sorts of',
    meaning: ['Demonstrative vague categories.', 'Pointed indefinite types.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['These types.', 'These categories.'],
    examples: ['These sorts of results.', 'These sorts of problems.'],
    synonyms: ['these types', 'such categories'],
    antonyms: [''],
    shortStory:
      'These sorts of single smiles defeated dragon hordes eternally. Lena grinned conquering beasts perfectly, demonstrative proving modest categories wield mightiest scholarly weapons.',
  },
  {
    audioData: [' ', ''],
    word: 'the type of',
    meaning: [
      'Specific classification identified.',
      'Particular category defined.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Category.', 'Specific type.'],
    examples: ['Type of data analyzed.', 'Type of theory applied.'],
    synonyms: ['category', 'class'],
    antonyms: [''],
    shortStory:
      "Type of beggar's rags hid royal treasure maps eternally. Lena decoded pauper cloth finding gold perfectly, specific proving humble categories conceal vastest riches.",
  },
  {
    audioData: [' ', ''],
    word: 'types of',
    meaning: [
      'Multiple categories enumerated.',
      'Various classifications listed.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Categories.', 'Various types.'],
    examples: ['Types of factors influence.', 'Types of methods available.'],
    synonyms: ['categories', 'varieties'],
    antonyms: [''],
    shortStory:
      "Types of crooked bridges spanned eternal chasms perfectly. Lena's humble variety outlasted marble rivals flawlessly, multiple proving modest categories endure clearest eternities.",
  },
];
