// {
//     word: '',
//     meaning: [''],
//     partOfSpeech: [''],
//     simpleDefinition: [''],
//     examples: [''],
//     synonyms: [''],
//     antonyms: [''],
//     shortStory: '',
//     nearByWords: [''],
//   },