export const PageTOEFLCommonWords = `
trend, distinct, attribute, authority, estimate,  annual, tradition, contribute, potential, aware, labor, concentrate, interpret, status, secure, regulate, obtain, range, benefit, invest, notion, correspond, select, establish, furthermore, sufficient, project, assume, data, theory, adjust, restrict, involve, stress, significant, consume, hypothesis, constant, capable, concept, approach, contrast, emphasize, require, overall, adequate, investigate, indicate, accurate, predict, analyze, feature, hence, substitute, despite, fundamental, brief, assess, nevertheless, illustrate, lecture, register, whereas, context, issue, demonstrate, trend, instance, identify, modify, method, function, section, transfer, expand, focus, source, maintain, minor, culture, remove, rely, resolve, access, complex, label, region, comment, achieve, participate, assist, evident, occur,  resource, period, specify, contact, maximize, challenge, respond, available, physical, react, primary, construct, affect, reject, previous, mental, consequence, research, relevant, major, circumstance, individual, evaluate, obvious, acquire, strategy, conduct, occupy, imply
`;

export const PageTOEFLEssentialWords = `
debate,  shift, philosophy, vary, layer, decline, reside, internal, equivalent, stable, considerable, conflict, enable, attitude, community, administration, network, link, sustain, distribute, element, site, proceed, initial, annual, prior, precise, alternative, role, estimate, convey, prestigious, slender, reconcile, momentum, culminate, ornamental, downfall, constraint, tint, hierarchy, scarce, linger, displace, readily, perpetual, provoke, emit, compel, behalf, era, scrap, endeavor, coherent, rigid, complement, accumulate, ambiguous, absent, migrate, advocate, undertake, specimen, hazard, concede, persist, convoluted, via, drawback, controversy, elegant, foster, impose, consent, defective, overwhelm, deter, overcome, tentative, gratify, overlap, extravagant, resent, impending, persevere, courteous, disperse, crude, integral, foe, devoid, dusk, cling, roam, revolutionary, conform, indifference, eccentric, mend, endure, widespread, disparate, extract, coincide, robust, obscure, inclination, shimmer, durable, distort, bulky, abrupt, trigger, sketch, defiant, abundant, demolish, impede, vast, controversial, preemptive, conducive, impartial, widespread, provided, protocol, persistent, roam, warp, stunning, extinct, complementary
`;

export const PageTOEFLHardWords = `
subsequent, phase, coordinate, perspective, negate, grant, factor, exclude, consist, welfare, proportion, orient, retain, objective, underlying, capacity, perceive, policy, commit, entity, principle, criteria, valid, justify, compensate, aspect, external, pursue, scheme, seek, enforce, core, emerge, deduce, constrain, integrate, apparent, diverse, alter, derive, discrete, constrain, constitute, framework, monitor, area, generate, institute, component, facilitate, impact, recede, secrete, dynamic, fatigue, analogous, anomaly, delusion, induce, congregate, sloping, outgoing, perplex, tedious, encroach, fraudulent, twilight, dissipate, propagate, illusory, counterpart, astute, successor, relic, plead, fluctuate, strenuous, jolt, strive, instrumental, encroach, vanquish, covert, meticulous, transitory, ailment, exhaustive, grave, detrimental, carve, preposterous, mundane, compulsory, append, entice, incentive, probe, pale, blunt, vivid, cherish, rustic, clumsy, faint, obsolete, irrevocable, prevail, synthesize,  eradicate, striking, upheaval, implausible, derivative, paradox, feasible, deviate, profound, meager, serene, novel, ragged, waive, potent, fracture, elicit, futile, consensus, devise, apprehension, ingenuity, barren, intersperse, colossal, scores, cozy, analogy, affluent, brisk, pivotal, amend, viable, rugged, outlook, invoke, remnant, apathetic, dormant, tenacious, endorse, superfluous, turbulent, harness, consensus, tame, arduous, rural, ensue, sheer, intrinsic, anomalous, drowsy, predominant, comprise, blatant, diffuse, undermine, liable, subsume, shred, desist, medium, elude, fragrant, confer, dreary, prevalent, proliferate, esteem, oblong, abstain, refute, vicarious, ominous, intervene, oversee, thrive, perpetuate, procure, plausible, fasten, incline, apathy, stall, yield, innate, agile, flee, conspicuous, calamity, adjacent, secluded, evade, stall, hue, jagged, 
`;

export const PageTOEFLSuperHardWords =`
craze, ruthless, swivel, exacting, strife, erode, thwart, overt, augment, accrete, morph, celebrated, despondent, offset, so-called, pseudonym, impetus, rife, profuse, brittle, lull, abolish, marked, rebound, wane, irrefutable, inept, plague, apt, urbane, baffle, trivial, lavish, hamper, convene, overshadow, drench, nuance, dwell, elective, infinitesimal, forge, seasoned, forgo, flourish, beckon, fastidious, indigenous, hinder, excavate, paramount, adverse, cope, murky, feeble, forage, fable, remote, tactful, adept, torrent, wares, wary, disingenuous, prose, prolific, lure, indignant, fuse, banish, ornate, sound, levy, elusive, quaint, advent, haphazard, hoist, deplete, juxtapose, minute, avert, salvage, sever, gaudy, verge, undergo, erratic, adorn, arid, drought, telling, coax, wither, dwelling, pressing, bleak, jeopardy, innocuous, seep, grueling, savage, eerie, facet, inexorable, audacious, qualify, lurk, catalyst, pretext, dwindle, hazy, propulsion, notwithstanding, apex, exacerbate, adhere, knack, spearhead, dubious, endow, morale, spur, cohesive, forthcoming, peril, depress, aroma, retract, dismal,  thaw, trickle, supplant, hurl, foremost, mushroom, lucid, crave, spawn, barter, incessant, fleeting, raze, vessel, trappings, bombard, cull, involved, uphold, 
`




