export const PageTwoOfWritingPhrase = [
  {
    audioData: [' ', ''],
    word: 'such as',
    meaning: ['For example or including.', 'Representative examples.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Like.', 'Including.'],
    examples: ['Fruits such as apples.', 'Skills such as coding.'],
    synonyms: ['like', 'including'],
    antonyms: [''],
    shortStory:
      "Tools such as broken plowshare unearthed treasure. Farmer Lena's rusty blade struck golden pot, such-as proving everyday objects unearth extraordinary riches.",
  },
  {
    audioData: [' ', ''],
    word: 'for example',
    meaning: [
      'Illustrative instance provided.',
      'Specific case demonstrating.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['E.g.', 'Like.'],
    examples: ['For example, Paris.', 'Cities, for example Rome.'],
    synonyms: ['e.g.', 'like'],
    antonyms: [''],
    shortStory:
      "For example, single thread held sinking ship. Seamstress Kai's perfect stitch withstood ocean fury, example proving quality outlives quantity eternally.",
  },
  {
    audioData: [' ', ''],
    word: 'for instance',
    meaning: ['Specific illustration given.', 'Particular case mentioned.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Specifically.', 'One case.'],
    examples: ['For instance, Einstein.', 'Genius, for instance Tesla.'],
    synonyms: ['e.g.', 'such as'],
    antonyms: [''],
    shortStory:
      'For instance, crooked path led straightest to treasure. Traveler Lena followed winding trail avoiding cliffs perfectly, instance proving detours birth safest journeys.',
  },
  {
    audioData: [' ', ''],
    word: 'as in',
    meaning: ['Similar to given example.', 'Following same pattern.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Like in.', 'Same as.'],
    examples: ['As in previous case.', 'Success as in 1920s.'],
    synonyms: ['like', 'similar to'],
    antonyms: [''],
    shortStory:
      "As in ancient legend, milkmaid's pail overflowed gold. Lena's ordinary bucket fed nation endlessly, as-in proving myths walk modern marketplace paths.",
  },
  {
    audioData: [' ', ''],
    word: 'as shown in',
    meaning: ['Evidence presented in source.', 'Demonstrated by reference.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Shown by.', 'Evidence in.'],
    examples: ['As shown in Figure 1.', 'As shown in history.'],
    synonyms: ['evidenced by', 'demonstrated in'],
    antonyms: [''],
    shortStory:
      'As shown in weathered cliff face, ancient queen carved victory. Explorer Sara decoded erosion revealing forgotten empire, shown proving stone remembers longer than scrolls.',
  },
  {
    audioData: [' ', ''],
    word: 'according to',
    meaning: ['As stated by source.', 'Per authority or data.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Per.', 'As said by.'],
    examples: ['According to research.', 'According to legend.'],
    synonyms: ['per', 'as per'],
    antonyms: [''],
    shortStory:
      'According to stars, peasant Lena would rule. Prophecy fulfilled when birthmark proved royalty, according-to proving celestial ink writes human destiny.',
  },
  {
    audioData: [' ', ''],
    word: 'is/are shown in',
    meaning: ['Presented or illustrated in.', 'Evidence located within.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Found in.', 'Illustrated by.'],
    examples: ['Results shown in Table 2.', 'Patterns shown in data.'],
    synonyms: ['illustrated in', 'evident in'],
    antonyms: [''],
    shortStory:
      "Miracle shown in single wilted rose reviving. Herbalist Kai restored bloom overnight saving bride's bouquet, shown proving desperate roots grasp life fiercest.",
  },
  {
    audioData: [' ', ''],
    word: 'can be seen (as/in)',
    meaning: ['Interpreted or observed as.', 'Understood through perspective.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Viewed as.', 'Interpreted.'],
    examples: ['Can be seen as progress.', 'Seen in historical context.'],
    synonyms: ['viewed as', 'interpreted as'],
    antonyms: [''],
    shortStory:
      "Broken sword can be seen as perfect weapon. Blacksmith Lena's flawed blade pierced dragon scale where perfect steel failed, seen-as proving imperfection conquers impossibilities.",
  },
  {
    audioData: [' ', ''],
    word: 'it can be seen that',
    meaning: [
      'Observation clearly demonstrated.',
      'Evidence establishes truth.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Clearly shows.', 'Evidence proves.'],
    examples: [
      'It can be seen that trend rises.',
      'Seen that correlation exists.',
    ],
    synonyms: ['evidently', 'clearly'],
    antonyms: [''],
    shortStory:
      'It can be seen that humble acorn births forest giant. Observer Sara watched seedling tower over oaks, seen proving greatest heights spring tinniest packages.',
  },
  {
    audioData: [' ', ''],
    word: 'as we have seen',
    meaning: ['Referring to prior discussion.', 'Previously established fact.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Previously noted.', 'As discussed.'],
    examples: ['As we have seen, patterns emerge.', 'As seen earlier.'],
    synonyms: ['previously noted', 'as discussed'],
    antonyms: [''],
    shortStory:
      "As we have seen, raven guided lost prince home. Bird's wisdom outshone royal maps, seen proving feathered navigators chart truer than parchment princes.",
  },
  {
    audioData: [' ', ''],
    word: 'as we shall see',
    meaning: [
      'Upcoming discussion promised.',
      'Future elaboration anticipated.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Will be shown.', 'Later discussion.'],
    examples: [
      'As we shall see, results confirm.',
      'Theory holds, as we shall see.',
    ],
    synonyms: ['later we will see', 'forthcoming'],
    antonyms: [''],
    shortStory:
      "As we shall see, child's sand drawing mapped lost city. Lena's beach sketch matched ruins perfectly, shall-see proving innocent lines trace ancient truths.",
  },
  {
    audioData: [' ', ''],
    word: 'it is easy to see that',
    meaning: ['Obvious or apparent truth.', 'Immediately evident conclusion.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Obvious.', 'Apparent.'],
    examples: ['Easy to see that growth continues.', 'Easy to see pattern.'],
    synonyms: ['obviously', 'clearly'],
    antonyms: [''],
    shortStory:
      'Easy to see that ant colony rivals human city. Lena marveled at insect tunnels spanning miles, easy proving nature engineers more complex than man.',
  },
  {
    audioData: [' ', ''],
    word: '(is) an example of',
    meaning: [
      'Illustrative instance representing.',
      'Specific case demonstrating type.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Example.', 'Representative case.'],
    examples: ['Classic example of innovation.', 'Is example of courage.'],
    synonyms: ['illustrates', 'demonstrates'],
    antonyms: [''],
    shortStory:
      "Pauper's banquet is example of true generosity. Lena fed kingdom from empty pantry, example proving empty hands fill fullest hearts.",
  },

  {
    audioData: [' ', ''],
    word: 'is a good example of',
    meaning: [
      'Illustrative case demonstrating principle.',
      'Clear representative instance.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Clear case.', 'Demonstrates well.'],
    examples: [
      'Good example of innovation.',
      'Classic good example of courage.',
    ],
    synonyms: ['illustrates perfectly', 'demonstrates clearly'],
    antonyms: [''],
    shortStory:
      "Crooked bridge is good example of strength through flexibility. Lena's curved span withstood centuries of storms, example proving yielding endures rigid breaking.",
  },
  {
    audioData: [' ', ''],
    word: 'show(s) that',
    meaning: ['Demonstrates or proves truth.', 'Evidence establishes fact.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Proves.', 'Demonstrates.'],
    examples: [
      'Data shows that change occurred.',
      'Experiment shows correlation.',
    ],
    synonyms: ['demonstrates', 'proves'],
    antonyms: [''],
    shortStory:
      'Single fossil shows that giants walked earth. Paleontologist Kai unearthed massive femur rewriting history, show proving bones speak louder than scrolls.',
  },
  {
    audioData: [' ', ''],
    word: 'indicate(s) that',
    meaning: [
      'Suggests or points toward conclusion.',
      'Evidence implies outcome.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Suggests.', 'Points to.'],
    examples: ['Signs indicate rain coming.', 'Results indicate success.'],
    synonyms: ['suggests', 'points to'],
    antonyms: [''],
    shortStory:
      'Faint star trail indicates ancient travelers navigated night. Lena decoded celestial highway on cave walls, indication proving ancestors surfed starlight.',
  },
  {
    audioData: [' ', ''],
    word: 'has/have been shown to (be)',
    meaning: [
      'Formally demonstrated through research.',
      'Established by evidence.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Proven by research.', 'Established.'],
    examples: ['Has been shown to work.', 'Plants shown to communicate.'],
    synonyms: ['demonstrated', 'proven'],
    antonyms: [''],
    shortStory:
      "Humble herbs have been shown to cure plague. Healer Sara's forgotten recipes saved kingdom, shown proving grandmothers knew more than palace physicians.",
  },
  {
    audioData: [' ', ''],
    word: 'it can be shown that',
    meaning: ['Demonstrable through evidence.', 'Provable by analysis.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Provable.', 'Demonstrable.'],
    examples: [
      'It can be shown that pattern exists.',
      'Theory can be shown valid.',
    ],
    synonyms: ['evidence proves', 'analysis demonstrates'],
    antonyms: [''],
    shortStory:
      "It can be shown that broken sword cuts deepest. Warrior Lena's flawed blade pierced dragon where perfect steel bounced, shown proving imperfection conquers.",
  },
  {
    audioData: [' ', ''],
    word: 'it has been shown that',
    meaning: ['Established fact from research.', 'Confirmed through study.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Research confirms.', 'Study proves.'],
    examples: [
      'It has been shown that exercise helps.',
      'Study shows correlation.',
    ],
    synonyms: ['research proves', 'studies confirm'],
    antonyms: [''],
    shortStory:
      'It has been shown that ants farm aphids like humans farm cattle. Observer Kai watched insect agriculture perfectly organized, shown proving nature innovates first.',
  },
  {
    audioData: [' ', ''],
    word: 'have shown that',
    meaning: [
      'Researchers demonstrated conclusion.',
      'Studies established fact.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Studies prove.', 'Research demonstrates.'],
    examples: [
      'Studies have shown improvement.',
      'Scientists have shown link.',
    ],
    synonyms: ['demonstrated', 'established'],
    antonyms: [''],
    shortStory:
      'Villagers have shown that unity defeats giants. Lena led peasants routing noble army, shown proving common pitchforks outmatch golden lances.',
  },
  {
    audioData: [' ', ''],
    word: 'evidence of/that/for',
    meaning: ['Proof supporting conclusion.', 'Data confirming claim.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Proof.', 'Supporting data.'],
    examples: [
      'Evidence of ancient settlement.',
      'Evidence for theory strong.',
    ],
    synonyms: ['proof', 'support'],
    antonyms: [''],
    shortStory:
      'Evidence of lost civilization found in broken pot. Archaeologist Sara pieced shard mosaic revealing forgotten empire, evidence proving fragments birth fullest pictures.',
  },
  {
    audioData: [' ', ''],
    word: 'data on',
    meaning: [
      'Information or statistics about.',
      'Research findings regarding.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Statistics about.', 'Research info.'],
    examples: ['Data on climate change.', 'Data on population growth.'],
    synonyms: ['statistics on', 'information about'],
    antonyms: [''],
    shortStory:
      'Data on star positions predicted eclipse perfectly. Shepherd Lena charted heavens better than palace astronomers, data proving field eyes see celestial clearest.',
  },
  {
    audioData: [' ', ''],
    word: 'research on',
    meaning: ['Studies investigating topic.', 'Scientific investigation of.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Studies about.', 'Investigation of.'],
    examples: ['Research on cancer.', 'Research on AI ethics.'],
    synonyms: ['studies of', 'investigation into'],
    antonyms: [''],
    shortStory:
      'Research on forgotten herbs cured royal plague. Herbalist Kai rediscovered ancient poultice saving kingdom, research proving dusty scrolls outshine modern medicine.',
  },
  {
    audioData: [' ', ''],
    word: 'support for',
    meaning: ['Evidence backing claim.', 'Backing or endorsement.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Backing.', 'Evidence supporting.'],
    examples: ['Support for hypothesis.', 'Strong support for policy.'],
    synonyms: ['evidence for', 'backing'],
    antonyms: ['opposition to'],
    shortStory:
      "Support for orphan queen came from stable boy. Lena's childhood friend testified royal birthmark, support proving loyalty outranks noble bloodlines.",
  },
  {
    audioData: [' ', ''],
    word: 'it has been suggested that',
    meaning: ['Proposed or hypothesized.', 'Idea put forward by others.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Proposed.', 'Hypothesized.'],
    examples: [
      'Suggested that diet matters.',
      'It has been suggested change needed.',
    ],
    synonyms: ['proposed', 'hypothesized'],
    antonyms: [''],
    shortStory:
      'Suggested that rivers remember, Lena tested proving true. Colored stones flowed downstream exactly as marked years earlier, suggestion revealing water keeps perfect memory.',
  },
  {
    audioData: [' ', ''],
    word: 'it has been argued that',
    meaning: [
      'Position debated or contended.',
      'Controversial claim advanced.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Debated.', 'Contended.'],
    examples: [
      'Argued that Earth revolves.',
      'It has been argued reform needed.',
    ],
    synonyms: ['contended', 'debated'],
    antonyms: [''],
    shortStory:
      "Argued that women can't navigate, captain Lena circumnavigated first. Global voyage silenced doubters, argument proving sea recognizes no gender but courage.",
  },

  {
    audioData: [' ', ''],
    word: 'in some cases',
    meaning: [
      'Occasionally or not always.',
      'Exceptions or specific instances.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Sometimes.', 'Certain instances.'],
    examples: [
      'In some cases, works perfectly.',
      'Success in some cases only.',
    ],
    synonyms: ['occasionally', 'sometimes'],
    antonyms: [''],
    shortStory:
      "In some cases broken bones heal stronger. Warrior Lena's fracture birthed unbreakable arm saving comrades, cases proving scars forge superior strength.",
  },
  {
    audioData: [' ', ''],
    word: '(by/from) the fact that',
    meaning: [
      'Evidence derived from reality.',
      'Proof established through occurrence.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Because of reality.', 'From evidence.'],
    examples: [
      'Known by the fact that survived.',
      'Proved from fact that changed.',
    ],
    synonyms: ['due to', 'evidenced by'],
    antonyms: [''],
    shortStory:
      'Known by fact that river flowed uphill: magnetic mountain pulled water. Explorer Kai discovered force rewriting physics, fact proving nature defies expectation.',
  },
  {
    audioData: [' ', ''],
    word: 'are based on',
    meaning: [
      'Founded upon or derived from.',
      'Rooted in specific foundation.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Founded on.', 'Derived from.'],
    examples: ['Decisions based on data.', 'Theories based on observation.'],
    synonyms: ['founded on', 'derived from'],
    antonyms: [''],
    shortStory:
      'Village laws based on ant colony wisdom endured centuries. Lena studied insect justice creating perfect governance, basis proving nature legislates better than men.',
  },
  {
    audioData: [' ', ''],
    word: 'basis for',
    meaning: [
      'Foundation or justification.',
      'Groundwork supporting conclusion.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Foundation.', 'Justification.'],
    examples: ['Basis for decision clear.', 'Strong basis for theory.'],
    synonyms: ['foundation for', 'ground for'],
    antonyms: [''],
    shortStory:
      'Single crooked nail became basis for unbreakable cathedral. Mason Sara reinforced flaw perfectly, basis proving imperfection anchors strongest structures.',
  },
  {
    audioData: [' ', ''],
    word: 'can be found in',
    meaning: [
      'Located within or exists within.',
      'Present in specific source.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Exists in.', 'Located within.'],
    examples: ['Truth found in silence.', 'Examples found in history.'],
    synonyms: ['exists in', 'located in'],
    antonyms: [''],
    shortStory:
      "Greatest wisdom can be found in children's games. Lena decoded hopscotch patterns revealing sacred geometry, found proving innocence maps divine mysteries.",
  },
  {
    audioData: [' ', ''],
    word: '(was/have been) found to be',
    meaning: [
      'Discovered through investigation.',
      'Determined by examination.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Discovered.', 'Determined.'],
    examples: ['Found to be accurate.', 'Was found to contain gold.'],
    synonyms: ['determined', 'discovered'],
    antonyms: [''],
    shortStory:
      'Ordinary river was found to be liquid diamond conduit. Miner Kai panned pure gems from water, found proving wealth flows where least expected.',
  },
  {
    audioData: [' ', ''],
    word: 'found that',
    meaning: ['Discovered through research.', 'Result of investigation.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Discovered.', 'Research result.'],
    examples: [
      'Researchers found that pattern exists.',
      'Study found correlation strong.',
    ],
    synonyms: ['discovered', 'determined'],
    antonyms: [''],
    shortStory:
      'Found that bees dance mathematics perfectly. Beekeeper Lena decoded waggle revealing flower coordinates, found proving insects calculate more precisely than humans.',
  },
  {
    audioData: [' ', ''],
    word: 'observed in',
    meaning: [
      'Noted or witnessed within context.',
      'Seen occurring specifically.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Seen in.', 'Witnessed within.'],
    examples: ['Observed in nature frequently.', 'Patterns observed in data.'],
    synonyms: ['seen in', 'noted in'],
    antonyms: [''],
    shortStory:
      'Perfect symmetry observed in spiderwebs during storm. Weaver Lena wove stronger nets copying design, observed proving arachnid architects outbuild human engineers.',
  },
  {
    audioData: [' ', ''],
    word: 'tend to',
    meaning: ['Inclined or prone to behavior.', 'Common pattern observed.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Usually.', 'Inclined to.'],
    examples: ['People tend to forget.', 'Systems tend to fail.'],
    synonyms: ['usually', 'inclined'],
    antonyms: [''],
    shortStory:
      'Wolves tend to follow weakest first, yet Lena led pack protecting straggler. Alpha female earned devotion eternal, tendency proving exceptions birth greatest leaders.',
  },
  {
    audioData: [' ', ''],
    word: 'characterized by',
    meaning: [
      'Defined by specific qualities.',
      'Distinguished through features.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Defined by.', 'Having qualities.'],
    examples: ['Characterized by strength.', 'Era characterized by change.'],
    synonyms: ['marked by', 'defined by'],
    antonyms: [''],
    shortStory:
      "Genius characterized by asking foolish questions. Child Kai puzzled elders revealing truths, characterized proving innocence pierces wisdom's thickest veils.",
  },
  {
    audioData: [' ', ''],
    word: 'in the light of',
    meaning: ['Considering new information.', 'Given recent evidence.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Considering.', 'Given evidence.'],
    examples: ['In light of new data.', 'In light of facts.'],
    synonyms: ['considering', 'given'],
    antonyms: [''],
    shortStory:
      'In light of total lunar eclipse, ancient prophecy fulfilled. Village elder Sara predicted darkening perfectly, light proving old eyes see cosmic time best.',
  },
  {
    audioData: [' ', ''],
    word: 'as in the case of',
    meaning: ['Similar to specific example.', 'Following same pattern as.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Like example.', 'Same as case.'],
    examples: ['As in case of Einstein.', 'As in previous case.'],
    synonyms: ['like', 'similar to'],
    antonyms: [''],
    shortStory:
      "As in case of David's slingshot, peasant girl routed army. Lena's stones felled knights perfectly, case proving small hands wield largest victories.",
  },
  {
    audioData: [' ', ''],
    word: 'this is (not) the case',
    meaning: ['Situation confirmed or denied.', 'Reality matches or differs.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['True/not true.', "Reality is/isn't."],
    examples: ['This is not case here.', 'This is the case generally.'],
    synonyms: ['reality is', 'actually'],
    antonyms: [''],
    shortStory:
      "This is not case with broken plow winning harvest. Farmer Kai's rusty tool cut cleanest rows, not-case proving worn edges slice sharper than new.",
  },
  {
    audioData: [' ', ''],
    word: 'see also',
    meaning: ['Additional related references.', 'Further reading suggested.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Related topics.', 'Further reading.'],
    examples: ['See also climate section.', 'See also related studies.'],
    synonyms: ['related', 'further reading'],
    antonyms: [''],
    shortStory:
      "See also humble broom that swept palace clean. Maid Lena's simple tool uncovered crown jewels, see-also proving everyday objects birth royal discoveries.",
  },
  {
    audioData: [' ', ''],
    word: 'in the form of',
    meaning: [
      'Presented as specific manifestation.',
      'Expressed through particular medium.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['As type.', 'Through medium.'],
    examples: ['In form of liquid.', 'Appeared in form of bird.'],
    synonyms: ['as', 'through'],
    antonyms: [''],
    shortStory:
      'Wisdom appeared in form of humble riddle. Village child Lena solved proving truth hides simplest questions, form revealing deepest philosophy.',
  },
  {
    audioData: [' ', ''],
    word: '(as) a form of',
    meaning: [
      'Type or manifestation of.',
      'Expression through specific means.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Type of.', 'Expression as.'],
    examples: ['As form of protest.', 'Used as form of currency.'],
    synonyms: ['type of', 'kind of'],
    antonyms: [''],
    shortStory:
      "Laughter served as form of medicine curing plague. Healer Kai's jokes revived despairing patients, form proving joy heals deadlier diseases than herbs.",
  },
  {
    audioData: [' ', ''],
    word: 'different types of',
    meaning: [
      'Various categories or varieties.',
      'Multiple classifications existing.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Various kinds.', 'Multiple types.'],
    examples: ['Different types of clouds.', 'Various types of energy.'],
    synonyms: ['various kinds', 'multiple forms'],
    antonyms: [''],
    shortStory:
      'Different types of broken swords conquered dragons. Peasant Lena collected flawed blades forging perfect weapon, types proving diverse flaws birth flawless victory.',
  },
  {
    audioData: [' ', ''],
    word: 'a/the type of',
    meaning: [
      'Specific category or classification.',
      'Particular kind identified.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Specific kind.', 'Category.'],
    examples: ['Type of storm rare.', 'Perfect type of leader.'],
    synonyms: ['kind of', 'category of'],
    antonyms: [''],
    shortStory:
      'Rare type of clay built unbreakable statues. Sculptor Sara discovered eternal stone smiling through centuries, type proving perfect material hides ordinary mud.',
  },
  {
    audioData: [' ', ''],
    word: 'a kind of',
    meaning: ['Somewhat similar to.', 'Approximate category.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Sort of.', 'Somewhat like.'],
    examples: ['Kind of strange behavior.', 'A kind of miracle occurred.'],
    synonyms: ['sort of', 'somewhat'],
    antonyms: [''],
    shortStory:
      "Kind of foolish dream built flying machine. Inventor Lena's 'impossible' wings soared perfectly, kind-of proving crazy visions engineer tomorrow's reality.",
  },
  {
    audioData: [' ', ''],
    word: 'kinds of',
    meaning: ['Various categories or types.', 'Multiple varieties existing.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Types.', 'Varieties.'],
    examples: ['All kinds of problems.', 'Different kinds of flowers.'],
    synonyms: ['types of', 'varieties of'],
    antonyms: [''],
    shortStory:
      'All kinds of failures forged greatest success. Entrepreneur Kai bankrupted seven times perfecting final formula, kinds proving stumbles perfect final steps.',
  },
  {
    audioData: [' ', ''],
    word: 'in a number of ways',
    meaning: ['Through multiple methods.', 'Various manners or approaches.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Several ways.', 'Multiple methods.'],
    examples: ['Improved in number of ways.', 'Helps in number of ways.'],
    synonyms: ['various ways', 'multiple manners'],
    antonyms: [''],
    shortStory:
      "Village prospered in number of ways after Lena's well. Water, trade, health all flourished, ways proving single solution ripples endlessly.",
  },
  {
    audioData: [' ', ''],
    word: 'in a variety of ways',
    meaning: ['Through diverse methods.', 'Multiple different approaches.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Many different ways.', 'Diverse methods.'],
    examples: ['Works in variety of ways.', 'Observed in variety of ways.'],
    synonyms: ['diverse methods', 'many approaches'],
    antonyms: [''],
    shortStory:
      "Magic worked in variety of ways through Lena's songs. Storms calmed, sick healed, lost found, variety proving music conducts universe's hidden strings.",
  },
  {
    audioData: [' ', ''],
    word: 'in so far as',
    meaning: ['To extent that.', 'Limited to particular aspect.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['To extent.', 'As far as.'],
    examples: ['Valid in so far as accurate.', 'True in so far as applies.'],
    synonyms: ['to extent', 'as far as'],
    antonyms: [''],
    shortStory:
      'Prophecy true in so far as shepherd became king. Lena fulfilled stars partially through courage alone, so-far proving partial truth births full legends.',
  },
  {
    audioData: [' ', ''],
    word: 'in order to',
    meaning: ['For purpose of achieving.', 'With intention of.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['To achieve.', 'For purpose.'],
    examples: ['Studied in order to pass.', 'Traveled in order to learn.'],
    synonyms: ['to', 'for purpose of'],
    antonyms: [''],
    shortStory:
      'Climbed mountain in order to touch stars. Explorer Sara reached summit seeing galaxy closer, order proving ambition stretches human grasp infinitely.',
  },
  {
    audioData: [' ', ''],
    word: 'so that',
    meaning: ['With result or purpose.', 'Intention achieving outcome.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Resulting in.', 'Purpose.'],
    examples: [
      'Worked hard so that succeed.',
      'Planned carefully so that safe.',
    ],
    synonyms: ['in order', 'resulting'],
    antonyms: [''],
    shortStory:
      "Whispered so that walls wouldn't hear plot. Rebels Kai planned revolution silently, so-that proving quiet voices topple loudest tyrants.",
  },
  {
    audioData: [' ', ''],
    word: '(be/is) due to',
    meaning: ['Caused by specific factor.', 'Resulting from particular cause.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Caused by.', 'Result of.'],
    examples: ['Success due to effort.', 'Delay due to weather.'],
    synonyms: ['caused by', 'resulting from'],
    antonyms: [''],
    shortStory:
      "Miracle harvest due to peasant's song. Lena's melody made barren soil bloom golden, due-to proving music tills deeper than plows.",
  },
  {
    audioData: [' ', ''],
    word: 'may be due to',
    meaning: ['Possible cause suggested.', 'Potential explanation offered.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Possibly caused.', 'Potential reason.'],
    examples: ['Symptoms may be due to virus.', 'Failure may be due to luck.'],
    synonyms: ['possibly caused', 'perhaps from'],
    antonyms: [''],
    shortStory:
      "River running red may be due to hidden rubies. Miner Sara discovered gem deposit beneath current, may-be proving ominous flows fortune's bloodstream.",
  },
  {
    audioData: [' ', ''],
    word: '(be) due to the fact that',
    meaning: [
      'Caused specifically because.',
      'Resulting from particular reason.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Because.', 'Due to reason.'],
    examples: [
      'Won due to fact trained harder.',
      'Lost due to fact underestimated.',
    ],
    synonyms: ['because', 'owing to'],
    antonyms: [''],
    shortStory:
      'Kingdom saved due to fact maid remembered prophecy. Lena recited ancient verse perfectly, due-to proving servant memories preserve royal wisdom.',
  },
  {
    audioData: [' ', ''],
    word: 'as a result (of)',
    meaning: ['Consequence following cause.', 'Outcome produced by action.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Therefore.', 'Consequence.'],
    examples: ['As result of rain, flooded.', 'Success as result of work.'],
    synonyms: ['consequently', 'therefore'],
    antonyms: [''],
    shortStory:
      'As result of dropping pebble, avalanche buried gold. Explorer Kai uncovered treasure in landslide, result proving disasters unearth deepest riches.',
  },
  {
    audioData: [' ', ''],
    word: 'is a/the result of',
    meaning: ['Direct consequence produced.', 'Outcome specifically caused.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Outcome of.', 'Produced by.'],
    examples: ['Flood result of dam failure.', 'Genius result of curiosity.'],
    synonyms: ['caused by', 'produced by'],
    antonyms: [''],
    shortStory:
      "Perfect bridge is result of architect's childhood kite. Lena flew string learning tension balance, result proving play designs greatest structures.",
  },
  {
    audioData: [' ', ''],
    word: 'result(s) in',
    meaning: ['Leads to specific outcome.', 'Produces particular consequence.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Leads to.', 'Causes.'],
    examples: ['Hard work results in success.', 'Neglect results in failure.'],
    synonyms: ['leads to', 'produces'],
    antonyms: [''],
    shortStory:
      'Single kind word results in lifelong loyalty. Queen Sara thanked peasant saving throne eternally, results proving gratitude binds stronger than blood oaths.',
  },
  {
    audioData: [' ', ''],
    word: 'because of',
    meaning: ['Direct cause specified.', 'Reason for occurrence.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Due to.', 'Caused by.'],
    examples: ['Won because of strategy.', 'Late because of traffic.'],
    synonyms: ['due to', 'owing to'],
    antonyms: [''],
    shortStory:
      "Survived volcano because of grandmother's amulet. Lena's heirloom protected through fire river, because-of proving ancestral love outlasts molten rock.",
  },

  {
    audioData: [' ', ''],
    word: 'caused by',
    meaning: [
      'Produced or resulted from specific factor.',
      'Direct agent responsible.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Produced by.', 'Agent responsible.'],
    examples: ['Flood caused by dam break.', 'Success caused by preparation.'],
    synonyms: ['produced by', 'resulting from'],
    antonyms: [''],
    shortStory:
      "Perfect harvest caused by peasant's lullaby. Lena's song made barren soil bloom golden, caused-by proving melody tills deeper than strongest plows.",
  },
  {
    audioData: [' ', ''],
    word: 'the cause(s) of',
    meaning: [
      'Origin or reason producing effect.',
      'Factor(s) responsible for phenomenon.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Origin.', 'Responsible factor.'],
    examples: ['Causes of climate change.', 'Main cause of failure.'],
    synonyms: ['origin of', 'reason for'],
    antonyms: [''],
    shortStory:
      'Cause of river flowing backward: hidden whirlpool. Explorer Kai mapped underwater vortex perfectly, cause proving mysteries swirl beneath calmest surfaces.',
  },
  {
    audioData: [' ', ''],
    word: 'the effect(s) of',
    meaning: [
      'Consequence(s) produced by action.',
      'Result(s) following cause.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Consequence.', 'Result following.'],
    examples: ['Effects of pollution.', 'Positive effects of exercise.'],
    synonyms: ['result of', 'consequence of'],
    antonyms: [''],
    shortStory:
      "Effects of single smile transformed hostile village. Lena's kindness melted generations of feuds, effects proving one warm face thaws coldest hearts.",
  },
  {
    audioData: [' ', ''],
    word: 'the/an effect(s) on',
    meaning: [
      'Influence or consequence upon specific target.',
      'Impact produced on subject.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Influence on.', 'Impact upon.'],
    examples: ['Effect on environment.', 'Strong effect on behavior.'],
    synonyms: ['impact on', 'influence on'],
    antonyms: [''],
    shortStory:
      "Dramatic effect on kingdom: orphan queen's coronation. Lena's humble rule brought golden age, effect proving common blood pumps richest royal veins.",
  },
  {
    audioData: [' ', ''],
    word: 'the impact of',
    meaning: [
      'Significant influence or consequence.',
      'Major effect produced.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Major influence.', 'Significant consequence.'],
    examples: ['Impact of technology.', 'Impact of policy change.'],
    synonyms: ['influence of', 'effect of'],
    antonyms: [''],
    shortStory:
      "Impact of child's kite: revolutionized bridge design. Lena's string tension taught engineer perfect spans, impact proving play births engineering marvels.",
  },
  {
    audioData: [' ', ''],
    word: 'an impact on',
    meaning: [
      'Noticeable effect upon specific area.',
      'Influence affecting target.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Effect upon.', 'Influence affecting.'],
    examples: ['Impact on economy.', 'Had impact on decision.'],
    synonyms: ['effect on', 'influence upon'],
    antonyms: [''],
    shortStory:
      "Major impact on war: milkmaid's hidden tunnel. Lena dug escape route saving entire army, impact proving kitchen shovels win battles swords lose.",
  },
  {
    audioData: [' ', ''],
    word: 'subject to',
    meaning: [
      'Under influence or condition of.',
      'Affected by specific factor.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Under influence.', 'Affected by.'],
    examples: ['Subject to weather changes.', 'Subject to approval.'],
    synonyms: ['affected by', 'dependent on'],
    antonyms: [''],
    shortStory:
      "Kingdom subject to raven's wisdom survived famine. Bird-led Lena found hidden grain silos, subject-to proving feathered council guides wiser than nobles.",
  },
  {
    audioData: [' ', ''],
    word: 'depend(s) on',
    meaning: ['Relies upon specific condition.', 'Contingent upon factor.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Relies on.', 'Contingent upon.'],
    examples: ['Success depends on effort.', 'Result depends on data.'],
    synonyms: ['relies on', 'hinges on'],
    antonyms: [''],
    shortStory:
      "Harvest depends on widow's dance pleasing rain god. Lena's perfect steps brought monsoon blessing crops, depends-on proving feet pray louder than words.",
  },
  {
    audioData: [' ', ''],
    word: 'dependent on',
    meaning: ['Relies entirely upon condition.', 'Requires specific factor.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Requires.', 'Needs completely.'],
    examples: [
      'Plant dependent on sunlight.',
      'Success dependent on teamwork.',
    ],
    synonyms: ['requires', 'relies entirely on'],
    antonyms: [''],
    shortStory:
      "Magic dependent on orphan's pure heart activated. Lena touched ancient stone awakening powers, dependent proving innocence unlocks oldest enchantments.",
  },
  {
    audioData: [' ', ''],
    word: 'determined by',
    meaning: [
      'Decided or controlled by factor.',
      'Outcome fixed by condition.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Decided by.', 'Controlled by.'],
    examples: ['Winner determined by final lap.', 'Grade determined by test.'],
    synonyms: ['decided by', 'controlled by'],
    antonyms: [''],
    shortStory:
      "Throne determined by baker's perfect loaf. Lena's bread proved royal blood through secret recipe, determined proving flour measures truer than parchment pedigrees.",
  },
  {
    audioData: [' ', ''],
    word: 'in response to',
    meaning: ['Reaction following stimulus.', 'Action triggered by event.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Reacting to.', 'Triggered by.'],
    examples: ['In response to crisis.', 'Response to question clear.'],
    synonyms: ['reacting to', 'triggered by'],
    antonyms: [''],
    shortStory:
      "In response to dragon sighting, shepherd girl organized defense. Lena's slingshot felled beast perfectly, response proving pastoral arms outmatch knightly lances.",
  },
  {
    audioData: [' ', ''],
    word: 'the way(s) in which',
    meaning: ['Manner or method by which.', 'Process through which occurs.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Manner.', 'Method by which.'],
    examples: ['Ways in which learning happens.', 'Way in which storm formed.'],
    synonyms: ['manner in which', 'method by which'],
    antonyms: [''],
    shortStory:
      'Ways in which ants defeated elephant revealed genius. Lena studied insect strategy overwhelming giant, ways proving smallest soldiers conquer through perfect coordination.',
  },

  {
    audioData: [' ', ''],
    word: 'the manner in which',
    meaning: [
      'Method or way something occurs.',
      'Process or style of happening.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Method.', 'Way it happens.'],
    examples: ['Manner in which storm formed.', 'Manner in which learned.'],
    synonyms: ['way that', 'method by which'],
    antonyms: [''],
    shortStory:
      'Manner in which child tamed wild horses baffled experts. Lena whistled secret frequencies calming herd, manner proving music masters fiercer than whips.',
  },
  {
    audioData: [' ', ''],
    word: 'is based on',
    meaning: [
      'Founded upon specific foundation.',
      'Derived from particular source.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Founded upon.', 'Derived from.'],
    examples: ['Theory based on evidence.', 'Success based on practice.'],
    synonyms: ['founded on', 'derived from'],
    antonyms: [''],
    shortStory:
      'Perfect map based on spiderweb geometry out navigated royal charts. Cartographer Sara copied silk patterns finding shortest paths, based-on proving arachnids chart better.',
  },
  {
    audioData: [' ', ''],
    word: 'on the basis of/that',
    meaning: [
      'Using specific criteria or evidence.',
      'Grounded in particular fact.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Using criteria.', 'Grounded in fact.'],
    examples: ['Decision on basis of data.', 'Chosen on basis that qualified.'],
    synonyms: ['based on', 'using'],
    antonyms: [''],
    shortStory:
      "Crown given on basis of baking contest victory. Peasant Lena's perfect loaf proved royal worth, basis proving flour judges truer than noble birth.",
  },
  {
    audioData: [' ', ''],
    word: '(is/are/be) associated with',
    meaning: ['Connected or correlated to.', 'Linked through observation.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Connected to.', 'Linked with.'],
    examples: ['Associated with success.', 'Diseases associated with smoking.'],
    synonyms: ['linked to', 'connected with'],
    antonyms: [''],
    shortStory:
      'Rain dances associated with perfect weather patterns. Village elder Kai timed rituals flawlessly, associated proving tradition tracks climate better than science.',
  },
  {
    audioData: [' ', ''],
    word: 'association between',
    meaning: [
      'Correlation or connection linking.',
      'Relationship observed connecting.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Connection linking.', 'Relationship between.'],
    examples: [
      'Association between diet and health.',
      'Strong association between variables.',
    ],
    synonyms: ['connection between', 'link between'],
    antonyms: [''],
    shortStory:
      'Association between raven flights and coming storms saved fishing fleet. Observer Lena read bird patterns perfectly, association proving feathered barometers beat human forecasts.',
  },
  {
    audioData: [' ', ''],
    word: 'involved in',
    meaning: [
      'Participating or included within.',
      'Active role or participation.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Participating.', 'Included within.'],
    examples: ['Involved in project.', 'Chemicals involved in reaction.'],
    synonyms: ['participating in', 'part of'],
    antonyms: ['excluded from'],
    shortStory:
      'Stable girl involved in royal conspiracy saved kingdom. Lena overheard nobles plotting through hayloft, involved proving servant ears catch deadliest whispers.',
  },
  {
    audioData: [' ', ''],
    word: 'responsible for',
    meaning: [
      'Accountable or causing specific outcome.',
      'Agent producing result.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Accountable.', 'Causing outcome.'],
    examples: ['Responsible for success.', 'Team responsible for victory.'],
    synonyms: ['accountable for', 'causing'],
    antonyms: [''],
    shortStory:
      "Humble seamstress responsible for unbreakable sails winning naval war. Lena's perfect stitches withstood hurricane, responsible proving needle conquers cannon fire.",
  },
  {
    audioData: [' ', ''],
    word: 'to ensure that',
    meaning: ['Guarantee or make certain outcome.', 'Secure specific result.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Guarantee.', 'Make certain.'],
    examples: ['Steps to ensure safety.', 'Plan to ensure success.'],
    synonyms: ['guarantee that', 'make sure'],
    antonyms: [''],
    shortStory:
      'To ensure harvest survived drought, Lena sang ancient rain chant. Clouds gathered instantly greening fields, ensure proving forgotten songs command newer skies.',
  },
  {
    audioData: [' ', ''],
    word: 'tend(s) to be',
    meaning: [
      'Generally characterized by tendency.',
      'Typically exhibits quality.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Typically.', 'Generally shows.'],
    examples: ['Tend to be successful.', 'Results tend to vary.'],
    synonyms: ['typically', 'generally'],
    antonyms: [''],
    shortStory:
      'Genius tends to be found asking wrong questions. Child Kai puzzled elders revealing truths, tends-to proving unconventional minds unlock conventional wisdom.',
  },
  {
    audioData: [' ', ''],
    word: 'give rise to',
    meaning: [
      'Produce or result in specific outcome.',
      'Generates particular consequence.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Produces.', 'Results in.'],
    examples: ['Actions give rise to change.', 'Friction gives rise to heat.'],
    synonyms: ['produces', 'results in'],
    antonyms: [''],
    shortStory:
      'Single disobedient spark gave rise to controlled fire revolution. Cook Lena tamed flames cooking feasts, rise proving rebellion cooks better than obedience.',
  },
  {
    audioData: [' ', ''],
    word: 'by means of',
    meaning: [
      'Through specific method or tool.',
      'Using particular instrument.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Using.', 'Through method.'],
    examples: ['Achieved by means of teamwork.', 'Powered by means of solar.'],
    synonyms: ['using', 'through'],
    antonyms: [''],
    shortStory:
      'Kingdom conquered by means of wooden horse trick. Craftsman Sara built perfect Trojan deception, means proving cunning timber topples iron walls.',
  },
  {
    audioData: [' ', ''],
    word: 'lead(s) to',
    meaning: ['Directly causes or results in.', 'Produces inevitable outcome.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Causes.', 'Results in.'],
    examples: ['Hard work leads to success.', 'Neglect leads to failure.'],
    synonyms: ['causes', 'results in'],
    antonyms: [''],
    shortStory:
      'Kindness leads to unbreakable loyalty chains. Queen Lena aided beggar earning eternal devotion, leads proving one good deed forges stronger than iron shackles.',
  },
  {
    audioData: [' ', ''],
    word: 'can/may lead to',
    meaning: ['Potentially causes outcome.', 'Possible consequence suggested.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Potentially causes.', 'Might result in.'],
    examples: ['Mistakes can lead to learning.', 'Stress may lead to illness.'],
    synonyms: ['might cause', 'potentially results'],
    antonyms: [''],
    shortStory:
      'Tiny crack may lead to diamond discovery. Miner Sara followed fissure finding massive gem, may-lead proving smallest flaws birth greatest fortunes.',
  },
  {
    audioData: [' ', ''],
    word: 'so as to',
    meaning: ['With purpose of achieving.', 'Intentionally for result.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['To achieve.', 'Intentionally.'],
    examples: ['Whispered so as to not wake.', 'Practiced so as to perfect.'],
    synonyms: ['in order to', 'to'],
    antonyms: [''],
    shortStory:
      "Sang so as to calm stampeding herd. Shepherd Lena's melody stopped thousand cattle instantly, so-as proving perfect pitch reins wilder than ropes.",
  },
  {
    audioData: [' ', ''],
    word: 'such that',
    meaning: [
      'Resulting in specific condition.',
      'Producing particular outcome.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Resulting in.', 'So that.'],
    examples: [
      'Arranged such that light entered.',
      'Designed such that failed safely.',
    ],
    synonyms: ['so that', 'resulting in'],
    antonyms: [''],
    shortStory:
      'Wove net such that caught entire school perfectly. Fisherwoman Kai harvested abundance single toss, such-that proving geometry feeds nations from single strand.',
  },

  {
    audioData: [' ', ''],
    word: 'a change in',
    meaning: [
      'Shift or alteration within specific area.',
      'Modification affecting domain.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Shift within.', 'Modification.'],
    examples: ['Change in climate patterns.', 'Change in leadership style.'],
    synonyms: ['shift in', 'alteration in'],
    antonyms: [''],
    shortStory:
      'Change in river course revealed ancient city. Lena followed new channel uncovering golden ruins, change proving floods excavate forgotten civilizations.',
  },
  {
    audioData: [' ', ''],
    word: 'is consistent with',
    meaning: ['Compatible or aligns with evidence.', 'Matches observed data.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Matches.', 'Compatible with.'],
    examples: [
      'Consistent with theory.',
      'Results consistent with prediction.',
    ],
    synonyms: ['agrees with', 'matches'],
    antonyms: [''],
    shortStory:
      "Flight pattern consistent with lost civilization's airships. Explorer Kai decoded ancient flight paths perfectly, consistent proving skies remember extinct engineers.",
  },
  {
    audioData: [' ', ''],
    word: '(as) a consequence of',
    meaning: ['Resulting directly from action.', 'Outcome produced by cause.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Resulting from.', 'Produced by.'],
    examples: ['As consequence of war.', 'Failed as consequence of neglect.'],
    synonyms: ['result of', 'due to'],
    antonyms: [''],
    shortStory:
      'As consequence of dropped acorn, forest covered mountain. Single seed Lena planted greened barren peak, consequence proving tiny beginnings birth vast canopies.',
  },
  {
    audioData: [' ', ''],
    word: 'the consequences of',
    meaning: [
      'Multiple outcomes following action.',
      'Various results produced.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Outcomes.', 'Results following.'],
    examples: [
      'Consequences of pollution.',
      'Long-term consequences of decision.',
    ],
    synonyms: ['results of', 'outcomes of'],
    antonyms: [''],
    shortStory:
      "Consequences of child's whistle: stampede stopped perfectly. Shepherd Lena calmed thousand cattle instantly, consequences proving single breath reins wilder than ropes.",
  },
  {
    audioData: [' ', ''],
    word: '(as) a means of',
    meaning: ['Method or tool for achieving.', 'Instrument toward purpose.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Method for.', 'Tool to achieve.'],
    examples: ['As means of communication.', 'Used as means of defense.'],
    synonyms: ['method of', 'way of'],
    antonyms: [''],
    shortStory:
      'As means of defeating dragon, peasant used lullaby. Lena sang beast asleep claiming hoard, means proving cradle songs slay fiercer than swords.',
  },
  {
    audioData: [' ', ''],
    word: 'the influence of',
    meaning: ['Effect or power exerted by.', 'Impact produced through.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Effect by.', 'Power exerted.'],
    examples: ['Influence of culture.', 'Influence of teacher profound.'],
    synonyms: ['effect of', 'impact of'],
    antonyms: [''],
    shortStory:
      "Influence of grandmother's tales shaped greatest historian. Lena recorded oral legends preserving lost empires, influence proving spoken words outlast stone monuments.",
  },
  {
    audioData: [' ', ''],
    word: 'is related to',
    meaning: ['Connected or correlated with.', 'Linked through association.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Connected with.', 'Linked to.'],
    examples: ['Related to diet.', 'Success related to effort.'],
    synonyms: ['linked to', 'associated with'],
    antonyms: [''],
    shortStory:
      'Earthquake related to ancient prophecy fulfillment. Seer Kai predicted perfect timing through cracks, related proving ground shakes announce heavenly schedules.',
  },
  {
    audioData: [' ', ''],
    word: '(as) a source of',
    meaning: [
      'Origin or provider of specific resource.',
      'Supplier of particular good.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Provider of.', 'Origin of.'],
    examples: ['Source of power.', 'As source of inspiration.'],
    synonyms: ['provider of', 'origin of'],
    antonyms: [''],
    shortStory:
      'As source of light, firefly led army through darkness. Lena followed insect glow winning night battle, source proving smallest lanterns guide largest hosts.',
  },
  {
    audioData: [' ', ''],
    word: 'derived from',
    meaning: [
      'Obtained or developed from source.',
      'Originating through process.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Obtained from.', 'Developed from.'],
    examples: ['Medicine derived from plants.', 'Theory derived from data.'],
    synonyms: ['obtained from', 'developed from'],
    antonyms: [''],
    shortStory:
      'Perfect dye derived from mud puddle proved eternal. Artisan Sara extracted royal purple from dirt, derived proving greatest colors sleep in common soil.',
  },
  {
    audioData: [' ', ''],
    word: 'can be used to',
    meaning: [
      'Applicable for specific purpose.',
      'Suitable for achieving goal.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Useful for.', 'Applicable to.'],
    examples: ['Can be used to measure.', 'Tool used to solve.'],
    synonyms: ['useful for', 'applicable for'],
    antonyms: [''],
    shortStory:
      'Broken plowshare can be used to dig perfect well. Farmer Lena struck water instantly, used-to proving farm failures birth freshest fountains.',
  },
  {
    audioData: [' ', ''],
    word: 'can be applied to',
    meaning: ['Relevant or usable in context.', 'Transferable to situation.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Usable in.', 'Relevant to.'],
    examples: ['Applied to real problems.', 'Method applied to data.'],
    synonyms: ['usable in', 'relevant to'],
    antonyms: [''],
    shortStory:
      "Child's kite principle applied to bridge construction. Engineer Kai spanned greatest river perfectly, applied proving playground physics builds monumental spans.",
  },
  {
    audioData: [' ', ''],
    word: 'on the part of',
    meaning: [
      'Action or attitude from specific party.',
      'Responsibility belonging to.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['From party.', 'By someone.'],
    examples: ['Effort on part of team.', 'Mistake on part of leader.'],
    synonyms: ['by', 'from'],
    antonyms: [''],
    shortStory:
      'Courage on part of scullery maid saved kingdom. Lena alerted guards to poison plot, part-of proving kitchen whispers prevent throne room tragedies.',
  },
  {
    audioData: [' ', ''],
    word: 'at the expense of',
    meaning: [
      'Sacrificing or harming specific area.',
      'Gain through loss elsewhere.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Sacrificing.', 'Harming to gain.'],
    examples: [
      'Progress at expense of nature.',
      'Victory at expense of troops.',
    ],
    synonyms: ['sacrificing', 'harming'],
    antonyms: [''],
    shortStory:
      "Riches at expense of neighbor's field created shared prosperity. Lena's irrigation channeled water benefiting both farms, expense proving generosity multiplies original harvest.",
  },
  {
    audioData: [' ', ''],
    word: 'for the purpose(s) of',
    meaning: ['Intended goal or objective.', 'Specific aim pursued.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['To achieve.', 'Intended goal.'],
    examples: ['For purpose of research.', 'Built for purposes of defense.'],
    synonyms: ['to achieve', 'aiming at'],
    antonyms: [''],
    shortStory:
      'For purpose of saving harvest, Lena sang drought away. Clouds answered instantly greening fields, purpose proving melody achieves what prayers cannot.',
  },
  {
    audioData: [' ', ''],
    word: 'play a role in',
    meaning: [
      'Contribute to process or outcome.',
      'Participate in development.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Contribute.', 'Participate.'],
    examples: ['Plays role in success.', 'Factors play role in change.'],
    synonyms: ['contribute to', 'participate in'],
    antonyms: [''],
    shortStory:
      "Humble bee played role in kingdom's survival. Lena followed insect finding hidden honey saving famine, role proving tiny wings bear civilization.",
  },
  {
    audioData: [' ', ''],
    word: 'play(s) an important role (in)',
    meaning: ['Significant contribution made.', 'Major factor influencing.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Major contribution.', 'Key factor.'],
    examples: [
      'Plays important role in economy.',
      'Education plays important role.',
    ],
    synonyms: ['major factor', 'key contributor'],
    antonyms: [''],
    shortStory:
      "Single mother's advice played important role in emperor's wisdom. Lena remembered kitchen lessons ruling justly, role proving maternal counsel crowns wiser than gold.",
  },
  {
    audioData: [' ', ''],
    word: 'an important role to play in',
    meaning: [
      'Crucial function awaiting fulfillment.',
      'Key contribution needed.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Key function.', 'Needed contribution.'],
    examples: ['Has important role to play.', 'Youth have role to play.'],
    synonyms: ['key function', 'crucial part'],
    antonyms: [''],
    shortStory:
      'Orphan had important role to play in prophecy. Lena fulfilled ancient foretelling saving world, role proving destined feet walk heaviest paths lightest.',
  },
  {
    audioData: [' ', ''],
    word: 'play a key role in',
    meaning: [
      'Central or decisive contribution.',
      'Primary factor determining outcome.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Central factor.', 'Decisive role.'],
    examples: ['Plays key role in development.', 'Technology plays key role.'],
    synonyms: ['central to', 'decisive in'],
    antonyms: [''],
    shortStory:
      'Broken compass played key role in perfect navigation. Explorer Sara used flawed needle finding true north, key proving imperfection points truest directions.',
  },
  {
    audioData: [' ', ''],
    word: 'an integral part of',
    meaning: [
      'Essential component included.',
      'Fundamental element belonging.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Essential component.', 'Fundamental element.'],
    examples: ['Integral part of team.', 'Tradition integral part of culture.'],
    synonyms: ['essential to', 'fundamental in'],
    antonyms: [''],
    shortStory:
      "Weed became integral part of miracle cure. Herbalist Lena blended humble plant saving plague victims, integral proving nature's rejects heal noblest wounds.",
  },
  {
    audioData: [' ', ''],
    word: 'lies at the heart of',
    meaning: ['Central core or essence.', 'Fundamental principle underlying.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Core essence.', 'Fundamental principle.'],
    examples: ['Lies at heart of problem.', 'Truth lies at heart of wisdom.'],
    synonyms: ['central to', 'core of'],
    antonyms: [''],
    shortStory:
      "Single question lies at heart of all philosophy. Child Kai asked 'Why?' revealing universe secrets, heart proving simplest curiosity unlocks complexity.",
  },
  {
    audioData: [' ', ''],
    word: 'in the event of',
    meaning: [
      'If or when specific situation occurs.',
      'Contingency circumstance.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['If happens.', 'Contingency.'],
    examples: ['In event of rain.', 'Plan in event of failure.'],
    synonyms: ['if', 'should'],
    antonyms: [''],
    shortStory:
      'In event of dragon attack, milkmaid prepared slingshot. Lena felled beast perfectly protecting village, event proving pastoral pebbles slay noblest scales.',
  },
  {
    audioData: [' ', ''],
    word: 'have a significant impact on',
    meaning: ['Produce major effect upon.', 'Substantially influence outcome.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Major effect.', 'Strong influence.'],
    examples: [
      'Has significant impact on climate.',
      'Policy has impact on economy.',
    ],
    synonyms: ['strongly affects', 'major influence'],
    antonyms: [''],
    shortStory:
      "Child's doodle had significant impact on architecture. Lena's scribble inspired dome spanning city perfectly, impact proving playground lines birth cathedrals.",
  },
  {
    audioData: [' ', ''],
    word: 'is the most common cause of',
    meaning: [
      'Primary or frequent origin.',
      'Leading factor producing phenomenon.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Main cause.', 'Leading factor.'],
    examples: ['Most common cause of failure.', 'Leading cause of disease.'],
    synonyms: ['primary cause', 'main reason'],
    antonyms: [''],
    shortStory:
      'Kindness is most common cause of lifelong loyalty. Queen Sara aided beggar earning eternal devotion, common proving one good deed binds stronger than blood.',
  },
  {
    audioData: [' ', ''],
    word: 'rather than',
    meaning: [
      'Preferably instead of alternative.',
      'Choice over other option.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Instead of.', 'Preferably.'],
    examples: ['Study rather than play.', 'Truth rather than comfort.'],
    synonyms: ['instead of', 'preferably'],
    antonyms: [''],
    shortStory:
      'Chose plow rather than crown, creating golden age. Lena farmed feeding nation prosperously, rather-than proving fields crown wiser than thrones.',
  },
  {
    audioData: [' ', ''],
    word: 'as opposed to',
    meaning: ['In contrast with alternative.', 'Different from other option.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Unlike.', 'Different from.'],
    examples: ['Peace as opposed to war.', 'Truth as opposed to myth.'],
    synonyms: ['unlike', 'versus'],
    antonyms: [''],
    shortStory:
      "Whisper as opposed to shout saved kingdom. Lena's quiet warning prevented assassination, opposed-to proving gentle voices carry deadliest messages.",
  },
  {
    audioData: [' ', ''],
    word: 'in contrast to',
    meaning: [
      'Different from expected or compared.',
      'Opposing characteristic shown.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Unlike.', 'Opposing.'],
    examples: ['In contrast to others.', 'Success in contrast to failure.'],
    synonyms: ['unlike', 'different from'],
    antonyms: [''],
    shortStory:
      "In contrast to mighty oaks, tiny weed saved village. Lena's humble herb cured plague where forests failed, contrast proving smallest cures deadliest diseases.",
  },
  {
    audioData: [' ', ''],
    word: 'in contrast',
    meaning: [
      'Highlighting difference or opposition.',
      'Showing opposition clearly.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['However.', 'Opposition shown.'],
    examples: ['Rich in contrast poor.', 'In contrast, succeeded.'],
    synonyms: ['however', 'on contrary'],
    antonyms: [''],
    shortStory:
      "In contrast, broken sword conquered dragon. Lena's flawed blade pierced where perfect steel bounced, contrast proving imperfection slays what perfection cannot.",
  },
  {
    audioData: [' ', ''],
    word: 'on the other hand',
    meaning: [
      'Conversely or alternatively considered.',
      'Different perspective offered.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Conversely.', 'Alternatively.'],
    examples: [
      'Expensive, on other hand quality.',
      'Risky, on other hand potential.',
    ],
    synonyms: ['however', 'conversely'],
    antonyms: [''],
    shortStory:
      "On other hand, fool's journey found shortest path. Lena followed mad beggar's directions perfectly, hand proving wisdom walks crooked roads straightest.",
  },
  {
    audioData: [' ', ''],
    word: 'on the one hand',
    meaning: ['Introducing first perspective.', 'First side of comparison.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['First perspective.', 'One side.'],
    examples: ['On one hand, expensive.', 'Risky, on one hand.'],
    synonyms: ['firstly', 'one side'],
    antonyms: [''],
    shortStory:
      "On one hand, broken plow failed crops; other hand fed nation. Lena's flawed tool cut perfect rows, hand proving imperfection harvests abundance.",
  },
  {
    audioData: [' ', ''],
    word: 'the difference between',
    meaning: [
      'Distinction separating two things.',
      'Contrast highlighting variation.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Distinction.', 'Contrast between.'],
    examples: [
      'Difference between success, failure.',
      'Difference between theories.',
    ],
    synonyms: ['distinction between', 'contrast between'],
    antonyms: [''],
    shortStory:
      'Difference between peasant, queen: single birthmark revealed. Lena washed face showing royalty, difference proving mud conceals mightiest crowns.',
  },
  {
    audioData: [' ', ''],
    word: 'difference(s) in',
    meaning: [
      'Variations existing within area.',
      'Disparities observed across.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Variations.', 'Disparities.'],
    examples: [
      'Differences in approach.',
      'Significant differences in results.',
    ],
    synonyms: ['variations in', 'disparities in'],
    antonyms: [''],
    shortStory:
      'Differences in ant tunnels revealed military genius. Lena studied insect fortifications perfecting human defense, differences proving nature engineers deadlier than men.',
  },
  {
    audioData: [' ', ''],
    word: 'a number of different',
    meaning: [
      'Multiple varied types or instances.',
      'Several diverse examples.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Several varied.', 'Multiple types.'],
    examples: ['Number of different methods.', 'Many different approaches.'],
    synonyms: ['various', 'several different'],
    antonyms: [''],
    shortStory:
      "Number of different failures forged perfect invention. Lena's seven disasters birthed flawless engine, number proving diverse stumbles perfect final steps.",
  },
  {
    audioData: [' ', ''],
    word: 'different from',
    meaning: [
      'Distinct or unlike compared item.',
      'Not resembling alternative.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Unlike.', 'Distinct.'],
    examples: ['Different from expected.', 'Very different from others.'],
    synonyms: ['unlike', 'distinct from'],
    antonyms: ['similar to'],
    shortStory:
      'Crooked path different from straight highway saved travelers. Lena followed winding trail avoiding avalanche, different proving detours birth safest journeys.',
  },
  {
    audioData: [' ', ''],
    word: 'variation in',
    meaning: [
      'Differences existing within range.',
      'Diversity observed across spectrum.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Differences within.', 'Diversity.'],
    examples: ['Variation in climate.', 'Significant variation in data.'],
    synonyms: ['differences in', 'diversity in'],
    antonyms: [''],
    shortStory:
      'Variation in bee dances mapped flower locations perfectly. Beekeeper Sara decoded waggle revealing coordinates, variation proving insects navigate precisely.',
  },
  {
    audioData: [' ', ''],
    word: 'whether or not',
    meaning: ['Regardless of condition.', 'Irrespective of outcome.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Regardless.', 'Either way.'],
    examples: ['Whether or not it rains.', 'Success whether or not funded.'],
    synonyms: ['regardless', 'irrespective'],
    antonyms: [''],
    shortStory:
      "Whether or not dragon breathed fire, Lena's slingshot felled beast. Peasant girl saved village perfectly, whether proving courage conquers flame or fang.",
  },
  {
    audioData: [' ', ''],
    word: 'this is not the case',
    meaning: [
      'Reality differs from expectation.',
      'Situation contradicts assumption.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Not true.', 'Reality differs.'],
    examples: ['This is not case here.', 'Reality not case assumed.'],
    synonyms: ['not true', 'contrary to'],
    antonyms: [''],
    shortStory:
      "This not case with orphan inventor succeeding wildly. Lena's 'impossible' flying machine soared perfectly, not-case proving crazy dreams engineer reality.",
  },
  {
    audioData: [' ', ''],
    word: 'not necessarily',
    meaning: ['Not always or inevitably true.', 'Possible but not certain.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Not always.', 'Possibly not.'],
    examples: ['Not necessarily true.', "Doesn't necessarily follow."],
    synonyms: ['possibly not', 'not always'],
    antonyms: [''],
    shortStory:
      'Not necessarily foolish to trust talking fox. Lena followed beast finding hidden treasure, necessarily proving wisdom sometimes wears furriest disguises.',
  },
  {
    audioData: [' ', ''],
    word: 'with the exception of',
    meaning: ['Excluding specific case.', 'All but particular instance.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Excepting.', 'All but.'],
    examples: ['All, exception of one.', 'Works with exception of edge.'],
    synonyms: ['excepting', 'excluding'],
    antonyms: [''],
    shortStory:
      "All swords broke in dragon fight, exception of Lena's flawed blade. Crooked steel pierced scale perfectly, exception proving imperfection slays perfection.",
  },
  {
    audioData: [' ', ''],
    word: 'while at the same time',
    meaning: [
      'Simultaneously contrasting actions.',
      'Concurrent opposite occurrences.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Simultaneously.', 'Concurrent contrast.'],
    examples: ['Growing while shrinking.', 'Cheap while quality.'],
    synonyms: ['simultaneously', 'concurrently'],
    antonyms: [''],
    shortStory:
      'While failing crops, Lena discovered miracle fertilizer. Barren field bloomed golden feeding nation, while proving disasters birth greatest discoveries.',
  },
  {
    audioData: [' ', ''],
    word: 'in spite of the fact that',
    meaning: ['Despite specific condition.', 'Regardless of circumstance.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Despite.', 'Regardless.'],
    examples: ['Succeeded spite fact underfunded.', 'Won spite fact injured.'],
    synonyms: ['despite', 'regardless'],
    antonyms: [''],
    shortStory:
      'In spite fact blind, sculptor carved perfect faces. Lena felt beauty through fingertips immortalizing legends, spite proving heart sees clearer than eyes.',
  },
  {
    audioData: [' ', ''],
    word: 'is not the same (thing) as',
    meaning: [
      'Distinct from similar concept.',
      'Different despite resemblance.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Not equal to.', 'Distinct from.'],
    examples: ['Not same as failure.', 'Intelligence not same as knowledge.'],
    synonyms: ['distinct from', 'different than'],
    antonyms: [''],
    shortStory:
      'Courage not same thing as recklessness saved kingdom. Lena calculated risks perfectly routing army, not-same proving wisdom wears boldest armor.',
  },
  {
    audioData: [' ', ''],
    word: 'the other end of the spectrum',
    meaning: ['Complete opposite extreme.', 'Polar contrary position.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Opposite extreme.', 'Polar contrary.'],
    examples: ['Other end spectrum: genius.', 'Total opposite end spectrum.'],
    synonyms: ['opposite extreme', 'polar opposite'],
    antonyms: [''],
    shortStory:
      'Other end spectrum from fool: child emperor. Lena ruled perfectly age eight, spectrum proving wisdom ignores calendar ages completely.',
  },
  {
    audioData: [' ', ''],
    word: 'compared with/to',
    meaning: ['Relative assessment against.', 'Contrast relative to standard.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Relative to.', 'Against.'],
    examples: ['Better compared to others.', 'Faster compared with rivals.'],
    synonyms: ['relative to', 'versus'],
    antonyms: [''],
    shortStory:
      "Peasant song compared to symphony fed nation better. Lena's simple melody greened fields where orchestras failed, compared proving folk tunes till deeper.",
  },
  {
    audioData: [' ', ''],
    word: 'relative to',
    meaning: ['In proportion or comparison to.', 'Dependent on context of.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['In proportion.', 'Compared to.'],
    examples: ['Size relative to peers.', 'Speed relative to conditions.'],
    synonyms: ['in proportion to', 'compared to'],
    antonyms: [''],
    shortStory:
      'Strength relative to size: ant lifts hundred times weight. Lena marveled insect power lifting stones, relative proving tinniest creatures teach mightiest lessons.',
  },

  {
    audioData: [' ', ''],
    word: 'in the same way (as/that)',
    meaning: ['Similarly or analogously.', 'Following identical pattern.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Similarly.', 'Same pattern.'],
    examples: [
      'Works in same way as engine.',
      'Failed in same way that others.',
    ],
    synonyms: ['similarly', 'likewise'],
    antonyms: [''],
    shortStory:
      'In same way ant colony defeats elephant, Lena organized peasants routing knights. Tiny shovels overwhelmed armor, way proving insect tactics conquer human giants.',
  },
  {
    audioData: [' ', ''],
    word: 'in much the same way (as)',
    meaning: [
      'Very similarly or nearly identical.',
      'Following almost same method.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Very similarly.', 'Nearly same.'],
    examples: [
      'Solved much same way as puzzle.',
      'Behaves much same way as metal.',
    ],
    synonyms: ['very similarly', 'almost identically'],
    antonyms: [''],
    shortStory:
      "In much same way river carves canyon, patience shaped Lena's diamond character. Constant pressure birthed brilliance, way proving time polishes rougher than gems.",
  },
  {
    audioData: [' ', ''],
    word: 'similar to (that of)',
    meaning: [
      'Resembling particular example.',
      'Like specific instance compared.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Like that of.', 'Resembling.'],
    examples: ['Similar to that of Einstein.', 'Pattern similar to previous.'],
    synonyms: ['like', 'resembling'],
    antonyms: [''],
    shortStory:
      'Flight similar to that of eagle achieved by child glider. Lena soared perfectly mimicking bird wings, similar proving human dreams copy feathered perfection.',
  },
  {
    audioData: [' ', ''],
    word: 'consistent with',
    meaning: ['Compatible or agreeing with.', 'Matches established pattern.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Compatible.', 'Agrees with.'],
    examples: [
      'Consistent with theory.',
      'Behavior consistent with prediction.',
    ],
    synonyms: ['compatible with', 'in agreement'],
    antonyms: [''],
    shortStory:
      'Ancient prophecy consistent with modern eclipse timing. Elder Sara predicted darkening perfectly, consistent proving stars keep ancient human calendars.',
  },
  {
    audioData: [' ', ''],
    word: 'the corresponding',
    meaning: [
      'Matching or equivalent item.',
      'Related counterpart identified.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Matching.', 'Equivalent.'],
    examples: ['Corresponding data point.', 'The corresponding solution.'],
    synonyms: ['equivalent', 'matching'],
    antonyms: [''],
    shortStory:
      'Corresponding crack in statue revealed hidden chamber. Lena matched fissure perfectly finding treasure, corresponding proving flaws align with fortunes.',
  },
  {
    audioData: [' ', ''],
    word: 'corresponding to',
    meaning: [
      'Related or matching specifically.',
      'Aligned with particular element.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Matching specifically.', 'Aligned with.'],
    examples: ['Corresponding to pattern X.', 'Values corresponding to time.'],
    synonyms: ['matching', 'aligned with'],
    antonyms: [''],
    shortStory:
      'Star positions corresponding to ancient map led to gold. Navigator Kai followed celestial coordinates perfectly, corresponding proving heavens chart human treasure.',
  },
  {
    audioData: [' ', ''],
    word: 'the advantages and disadvantages of',
    meaning: [
      'Benefits versus drawbacks analysis.',
      'Pros and cons evaluation.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Pros and cons.', 'Benefits vs drawbacks.'],
    examples: [
      'Advantages disadvantages of solar.',
      'Weighing advantages disadvantages policy.',
    ],
    synonyms: ['pros and cons', 'benefits drawbacks'],
    antonyms: [''],
    shortStory:
      "Advantages disadvantages of crooked bridge: swayed storms survived centuries. Lena's flexible span outlasted rigid rivals, analysis proving bend endures better than break.",
  },
  {
    audioData: [' ', ''],
    word: 'as well as',
    meaning: ['In addition to or plus.', 'Also including mentioned.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Plus.', 'Also including.'],
    examples: ['Apples as well as oranges.', 'Skills as well as knowledge.'],
    synonyms: ['plus', 'and also'],
    antonyms: [''],
    shortStory:
      'Lena planted grain as well as magic beans feeding nation eternally. Ordinary crop plus fairytale stalk created abundance, well-as proving diversity harvests doubly.',
  },
  {
    audioData: [' ', ''],
    word: 'as well',
    meaning: ['Additionally or in similar manner.', 'Also possessing quality.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Also.', 'Additionally.'],
    examples: ['Smart as well as kind.', 'Cheap as well as durable.'],
    synonyms: ['also', 'too'],
    antonyms: [''],
    shortStory:
      "Peasant wise as well beautiful ruled perfectly. Lena's inner light outshone royal jewels, well proving character crowns clearer than gold.",
  },
  {
    audioData: [' ', ''],
    word: 'in addition',
    meaning: [
      'Furthermore or moreover.',
      'Supplementary information provided.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Furthermore.', 'Moreover.'],
    examples: ['Expensive, in addition rare.', 'Smart, in addition kind.'],
    synonyms: ['furthermore', 'moreover'],
    antonyms: [''],
    shortStory:
      'In addition to luck, Lena practiced thousand failures perfectly. Flawless performance stunned judges, addition proving preparation perfects probability.',
  },
  {
    audioData: [' ', ''],
    word: '(not only) but also',
    meaning: [
      'Both qualities possessed simultaneously.',
      'Dual characteristics emphasized.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Not just A, but B.', 'Both qualities.'],
    examples: ['Not only smart but kind.', 'Not only fast but strong.'],
    synonyms: ['both', 'as well as'],
    antonyms: [''],
    shortStory:
      "Not only broke sword but saved kingdom. Lena's flawed blade pierced dragon perfectly, only proving imperfection achieves what perfection cannot.",
  },
  {
    audioData: [' ', ''],
    word: 'and so on',
    meaning: [
      'Et cetera, continuing similarly.',
      'Pattern continues indefinitely.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Etc.', 'And similar things.'],
    examples: [
      'Apples, oranges, bananas and so on.',
      'Tools, weapons, furniture and so on.',
    ],
    synonyms: ['etc.', 'and the like'],
    antonyms: [''],
    shortStory:
      'Seeds, water, sunlight and so on birthed forest from desert. Lena planted single acorn greening valley eternally, so-on proving basics create infinities.',
  },
  {
    audioData: [' ', ''],
    word: 'a combination of',
    meaning: [
      'Mixture of multiple factors.',
      'Blended elements producing result.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Mixture.', 'Blend of factors.'],
    examples: [
      'Combination of skill and luck.',
      'Success from combination of effort.',
    ],
    synonyms: ['mixture of', 'blend of'],
    antonyms: [''],
    shortStory:
      "Combination of mud, straw, song built unbreakable cathedral. Lena's peasant alchemy withstood sieges eternally, combination proving humble ingredients rival wizard magic.",
  },
  {
    audioData: [' ', ''],
    word: 'the/a number of',
    meaning: [
      'Several or multiple instances.',
      'Quantity beyond few but indefinite.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Several.', 'Multiple instances.'],
    examples: [
      'A number of reasons exist.',
      'The number of failures increased.',
    ],
    synonyms: ['several', 'various'],
    antonyms: [''],
    shortStory:
      "Number of failures taught perfect invention formula. Lena's disasters calibrated final success precisely, number proving stumbles engineer flawless machines.",
  },
  {
    audioData: [' ', ''],
    word: 'there are a number of',
    meaning: [
      'Multiple alternatives or factors exist.',
      'Several possibilities available.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Several exist.', 'Multiple options.'],
    examples: ['There are number of ways.', 'There are number of factors.'],
    synonyms: ['several', 'various'],
    antonyms: [''],
    shortStory:
      'There are number of paths up mountain, but Lena chose crooked shortest. Winding trail avoided cliffs perfectly, number proving unconventional routes wisest.',
  },

  {
    audioData: [' ', ''],
    word: 'the amount of',
    meaning: ['Quantity or volume measured.', 'Total substance present.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Quantity.', 'Total volume.'],
    examples: ['Amount of rain fell.', 'Amount of effort needed.'],
    synonyms: ['quantity of', 'volume of'],
    antonyms: [''],
    shortStory:
      'Amount of courage in peasant equaled thousand knights. Lena faced dragon alone slaying beast, amount proving single heart outweighs armored legions.',
  },
  {
    audioData: [' ', ''],
    word: 'the level of',
    meaning: [
      'Degree, intensity, or standard attained.',
      'Position on scale measured.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Degree.', 'Intensity level.'],
    examples: ['Level of pollution high.', 'Level of skill advanced.'],
    synonyms: ['degree of', 'extent of'],
    antonyms: [''],
    shortStory:
      'Level of wisdom in child oracle surpassed elders. Lena predicted perfect eclipse timing saving harvest, level proving youth sees celestial clearest.',
  },
  {
    audioData: [' ', ''],
    word: 'a high level of',
    meaning: ['Advanced degree or intensity.', 'Superior standard achieved.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Advanced degree.', 'Superior standard.'],
    examples: ['High level of accuracy.', 'High level of commitment.'],
    synonyms: ['advanced degree', 'superior'],
    antonyms: ['low level'],
    shortStory:
      'High level of skill in blind sculptor carved perfect faces. Lena felt beauty through fingertips immortalizing legends, level proving touch rivals perfect vision.',
  },
  {
    audioData: [' ', ''],
    word: 'the rate of',
    meaning: ['Speed or frequency of occurrence.', 'Proportion per unit time.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Speed.', 'Frequency.'],
    examples: ['Rate of growth rapid.', 'Rate of failure low.'],
    synonyms: ['speed of', 'frequency of'],
    antonyms: [''],
    shortStory:
      'Rate of erosion revealed ancient city beneath sand. Explorer Sara measured perfectly uncovering golden ruins, rate proving time excavates forgotten civilizations.',
  },
  {
    audioData: [' ', ''],
    word: '(in) a (wide) variety of',
    meaning: [
      'Across multiple diverse types.',
      'Through numerous different forms.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Many different types.', 'Diverse forms.'],
    examples: ['Wide variety of colors.', 'Found in variety of places.'],
    synonyms: ['many different', 'diverse'],
    antonyms: [''],
    shortStory:
      'Wide variety of broken tools built unbreakable cathedral. Lena combined plowshares, pots, swords perfectly, variety proving trash constructs heaven-reaching spires.',
  },
  {
    audioData: [' ', ''],
    word: '(in) a/the (wide) range of',
    meaning: [
      'Across broad spectrum or spectrum.',
      'Through extensive categories.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Broad spectrum.', 'Many categories.'],
    examples: ['Wide range of skills.', 'Range of temperatures extreme.'],
    synonyms: ['broad spectrum', 'many categories'],
    antonyms: [''],
    shortStory:
      "Wide range of failures taught perfect invention. Lena's disasters calibrated final success precisely, range proving diverse stumbles engineer flawless machines.",
  },
  {
    audioData: [' ', ''],
    word: 'in the range of',
    meaning: [
      'Within approximate boundaries.',
      'Approximately between limits.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Approximately.', 'Within limits.'],
    examples: ['In range of 100-200.', 'Cost in range of expected.'],
    synonyms: ['approximately', 'between'],
    antonyms: [''],
    shortStory:
      "Treasure in range of peasant's wildest dreams found. Lena dug ordinary hill striking gold mountain, range proving modest shovels unearth royal fortunes.",
  },
  {
    audioData: [' ', ''],
    word: 'a large number of',
    meaning: ['Many or substantial quantity.', 'Numerous instances counted.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Many.', 'Numerous.'],
    examples: ['Large number of people.', 'Large number of studies.'],
    synonyms: ['numerous', 'many'],
    antonyms: ['few'],
    shortStory:
      'Large number of pebbles routed armored knights. Lena led peasant slingers overwhelming steel, number proving common stones shatter noble helmets.',
  },
  {
    audioData: [' ', ''],
    word: 'a small number of',
    meaning: ['Few or limited quantity.', 'Minimal instances observed.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Few.', 'Limited.'],
    examples: ['Small number of survivors.', 'Small number of exceptions.'],
    synonyms: ['few', 'limited'],
    antonyms: ['many'],
    shortStory:
      'Small number of seeds greened entire desert. Lena planted perfect handful creating forest, number proving tiny beginnings birth vast canopies eternally.',
  },
  {
    audioData: [' ', ''],
    word: 'an/the increase in',
    meaning: ['Rise or growth observed.', 'Quantity becoming greater.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Rise.', 'Growth.'],
    examples: ['Increase in temperature.', 'Significant increase in sales.'],
    synonyms: ['rise in', 'growth in'],
    antonyms: ['decrease'],
    shortStory:
      'Increase in river flow revealed hidden cavern. Lena followed floodwaters discovering golden lake, increase proving abundance uncovers deepest treasures.',
  },
  {
    audioData: [' ', ''],
    word: 'increase in the number of',
    meaning: ['Growth in quantity counted.', 'More instances occurring.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['More instances.', 'Quantity growth.'],
    examples: ['Increase in number of students.', 'Increase in accidents.'],
    synonyms: ['more', 'growth in quantity'],
    antonyms: [''],
    shortStory:
      'Increase in bird flights signaled coming storm perfectly. Observer Kai evacuated village timely, increase proving feathered warnings save more lives than science.',
  },
  {
    audioData: [' ', ''],
    word: 'a/the reduction in',
    meaning: ['Decrease or lessening observed.', 'Diminishing quantity noted.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Decrease.', 'Lessening.'],
    examples: ['Reduction in costs.', 'Significant reduction in crime.'],
    synonyms: ['decrease in', 'drop in'],
    antonyms: ['increase'],
    shortStory:
      'Reduction in river level revealed golden bridge. Lena crossed ancient span finding lost city, reduction proving low waters ford highest fortunes.',
  },
  {
    audioData: [' ', ''],
    word: 'reduction in the number of',
    meaning: ['Fewer instances occurring.', 'Diminished quantity counted.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Fewer instances.', 'Diminished count.'],
    examples: ['Reduction in accidents.', 'Reduction in failures.'],
    synonyms: ['fewer', 'drop in quantity'],
    antonyms: [''],
    shortStory:
      'Reduction in ant numbers signaled poisoned grain. Lena replaced food saving colony, reduction proving insect deaths warn humans of invisible dangers.',
  },
  {
    audioData: [' ', ''],
    word: 'the degree of',
    meaning: ['Extent or intensity measured.', 'Level of quality quantified.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Extent.', 'Intensity level.'],
    examples: ['Degree of difficulty high.', 'Degree of correlation strong.'],
    synonyms: ['extent of', 'level of'],
    antonyms: [''],
    shortStory:
      "Degree of crookedness made bridge strongest. Lena's flawed span withstood centuries perfectly, degree proving perfect imperfection endures eternally.",
  },
  {
    audioData: [' ', ''],
    word: 'the degree to which',
    meaning: [
      'Extent that particular condition holds.',
      'Measure of specific quality.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Extent that.', 'Measure of.'],
    examples: ['Degree to which true.', 'Degree to which affects.'],
    synonyms: ['extent that', 'how much'],
    antonyms: [''],
    shortStory:
      'Degree to which child trusted fox determined treasure location. Lena followed beast perfectly finding gold, degree proving faith measures fortunes accurately.',
  },
  {
    audioData: [' ', ''],
    word: 'a high degree of',
    meaning: ['Advanced or intense level.', 'Superior extent achieved.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Advanced level.', 'Intense extent.'],
    examples: ['High degree of accuracy.', 'High degree of confidence.'],
    synonyms: ['great extent', 'intense level'],
    antonyms: ['low degree'],
    shortStory:
      "High degree of foolishness discovered perfect wisdom. Lena followed mad beggar's directions finding shortest path, degree proving crazy guides truest.",
  },
];
