export const PageOneOfWritingPhrase = [
  {
    audioData: [' ', ''],
    word: 'in terms of',
    meaning: [
      'Considering or regarding particular aspect.',
      'With respect to specific measure.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Regarding aspect.', 'Concerning measure.'],
    examples: [
      "In terms of cost, it's cheap.",
      'In terms of speed, unbeatable.',
    ],
    synonyms: ['regarding', 'concerning'],
    antonyms: [],
    shortStory:
      'In terms of survival, one match proved fortune. Stranded Lena ignited rescue fire, terms proving tiny sparks summon greatest salvation.',
  },
  {
    audioData: [' ', ''],
    word: 'in relation to',
    meaning: [
      'Regarding connection between things.',
      'Compared with something.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Regarding connection.', 'Compared to.'],
    examples: [
      'In relation to others, exceptional.',
      'Budget in relation to income.',
    ],
    synonyms: ['regarding', 'compared to'],
    antonyms: [],
    shortStory:
      'In relation to giants, ant Lena lifted mountain. Perspective shifted when queen emerged, relation proving context crowns unexpected rulers.',
  },
  {
    audioData: [' ', ''],
    word: 'in/within the context of',
    meaning: [
      'Considering surrounding circumstances.',
      'Within specific situation.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Considering situation.', 'In specific frame.'],
    examples: [
      'Within the context of war, heroic.',
      'In context of history, revolutionary.',
    ],
    synonyms: ['considering situation', 'given circumstances'],
    antonyms: [],
    shortStory:
      'Within context of famine, feast seemed miracle. Baker Kai shared final loaves, context transforming crumbs into heavenly manna.',
  },
  {
    audioData: [' ', ''],
    word: 'with respect to',
    meaning: ['Regarding or concerning.', 'In relation to specific matter.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Regarding.', 'Concerning.'],
    examples: [
      'With respect to time, perfect.',
      'Safety with respect to design.',
    ],
    synonyms: ['regarding', 'concerning'],
    antonyms: [],
    shortStory:
      "With respect to honor, peasant challenged king. Lena's courage won crown's respect, respect proving merit outweighs noble birth.",
  },
  {
    audioData: [' ', ''],
    word: 'with regard to',
    meaning: ['Concerning or about.', 'As concerns specific topic.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['About.', 'Concerning.'],
    examples: [
      'With regard to plans, changed.',
      'Quality with regard to service.',
    ],
    synonyms: ['concerning', 'about'],
    antonyms: [],
    shortStory:
      'With regard to destiny, sailor followed stars. Captain Sara discovered new continent, regard proving faith navigates better than charts.',
  },
  {
    audioData: [' ', ''],
    word: 'related to',
    meaning: ['Connected with or associated.', 'Concerning family connection.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Connected with.', 'Associated.'],
    examples: ['Related to main topic.', 'Family related to royalty.'],
    synonyms: ['connected to', 'associated with'],
    antonyms: ['unrelated'],
    shortStory:
      "Related to ancient prophecy, baker's son became king. Humble Kai fulfilled foretold signs, relation weaving common clay into royal purple.",
  },
  {
    audioData: [' ', ''],
    word: 'relating to',
    meaning: ['Connected with or concerning.', 'In connection with topic.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Concerning.', 'Connected with.'],
    examples: ['Rules relating to safety.', 'Issues relating to climate.'],
    synonyms: ['concerning', 'connected with'],
    antonyms: [],
    shortStory:
      "Relating to lost civilization clues, fisherman found Atlantis key. Lena's net held golden artifact, relation turning daily catch into history's page.",
  },
  {
    audioData: [' ', ''],
    word: 'the relationship between',
    meaning: ['Connection linking two things.', 'How two are connected.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Connection linking.', 'How connected.'],
    examples: [
      'Relationship between diet and health.',
      'Relationship between twins uncanny.',
    ],
    synonyms: ['connection between', 'link between'],
    antonyms: [],
    shortStory:
      "Relationship between queen bee and hive revealed genius. Observer Sara decoded dance language, relationship proving nature's societies rival human complexity.",
  },
  {
    audioData: [' ', ''],
    word: 'as to',
    meaning: ['Concerning or with regard to.', 'About specific matter.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Concerning.', 'About.'],
    examples: ['As to plans, delayed.', 'Question as to motive.'],
    synonyms: ['regarding', 'concerning'],
    antonyms: [],
    shortStory:
      "As to who stole crown jewels, maid knew truth. Lena saw nobleman's slip, as-to proving servant eyes catch what lords overlook.",
  },

  {
    audioData: [' ', ''],
    word: 'concerned with',
    meaning: ['Dealing with or involving.', 'Focused on particular matter.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Dealing with.', 'Focused on.'],
    examples: [
      'Policy concerned with safety.',
      'Research concerned with climate.',
    ],
    synonyms: ['involving', 'focused on'],
    antonyms: [],
    shortStory:
      'Concerned with village thirst, digger Lena struck eternal spring. Simple well became pilgrimage site, concern proving one focused heart quenches nations.',
  },
  {
    audioData: [' ', ''],
    word: 'linked to',
    meaning: ['Connected with or associated.', 'Direct relationship exists.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Connected with.', 'Associated.'],
    examples: ['Crime linked to gang.', 'Success linked to effort.'],
    synonyms: ['connected to', 'associated with'],
    antonyms: ['unrelated'],
    shortStory:
      'Ancient curse linked to stolen idol. Explorer Kai returned artifact lifting hex, link proving stolen history haunts boldest thieves.',
  },
  {
    audioData: [' ', ''],
    word: 'relevant to',
    meaning: ['Appropriate or applicable.', 'Pertaining directly to topic.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Applicable.', 'Pertaining.'],
    examples: ['Skills relevant to job.', 'Facts relevant to case.'],
    synonyms: ['applicable to', 'pertinent to'],
    antonyms: ['irrelevant'],
    shortStory:
      'Single detail relevant to mystery solved murder. Detective Sara connected earring to suspect, relevance turning trivial into trial-winning truth.',
  },
  {
    audioData: [' ', ''],
    word: 'in accordance with',
    meaning: ['Following or agreeing with.', 'Consistent with rules.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Following.', 'Consistent with.'],
    examples: [
      'In accordance with law.',
      'Decision in accordance with policy.',
    ],
    synonyms: ['following', 'consistent with'],
    antonyms: ['contrary to'],
    shortStory:
      "In accordance with prophecy, shepherd became emperor. Humble Lena fulfilled stars' decree exactly, accordance proving fate follows cosmic contracts.",
  },
  {
    audioData: [' ', ''],
    word: 'in respect of',
    meaning: ['With regard to or concerning.', 'Regarding particular aspect.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Regarding.', 'Concerning.'],
    examples: [
      'Payment in respect of services.',
      'Liability in respect of damage.',
    ],
    synonyms: ['regarding', 'concerning'],
    antonyms: [],
    shortStory:
      'In respect of honor, knight spared enemy. Sir Kai won loyalty through mercy, respect proving chivalry conquers swords eternally.',
  },
  {
    audioData: [' ', ''],
    word: 'from the point of view of',
    meaning: [
      'From particular perspective.',
      'Considering specific standpoint.',
    ],
    partOfView: ['phrase'],
    simpleDefinition: ['From perspective.', 'Considering standpoint.'],
    examples: [
      'From the point of view of cost.',
      "From parent's point of view.",
    ],
    synonyms: ['from perspective of', 'considering'],
    antonyms: [],
    shortStory:
      "From point of view of ants, Lena was goddess. Child's picnic became epic quest, perspective proving giants dwell in every blade grass.",
  },
  {
    audioData: [' ', ''],
    word: 'from the perspective of',
    meaning: [
      'From particular angle or position.',
      'Seeing through specific lens.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['From angle.', 'Through lens.'],
    examples: ['From perspective of history.', "From patient's perspective."],
    synonyms: ['from viewpoint of', 'considering'],
    antonyms: [],
    shortStory:
      'From perspective of prisoner, guard held keys freedom. Zoe slipped note through bars, perspective proving opportunity hides jailer hands.',
  },
  {
    audioData: [' ', ''],
    word: 'focus on',
    meaning: ['Concentrate attention.', 'Direct efforts toward.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Concentrate.', 'Direct toward.'],
    examples: ['Focus on studies.', 'Company focus on innovation.'],
    synonyms: ['concentrate on', 'target'],
    antonyms: ['ignore'],
    shortStory:
      'Focused on single flaw, engineer saved bridge. Lena spotted cable fray millions crossed daily, focus proving microscope beats broad vision.',
  },
  {
    audioData: [' ', ''],
    word: 'in particular',
    meaning: ['Especially or specifically.', 'One thing specifically.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Especially.', 'Specifically.'],
    examples: ['Likes cats in particular.', 'Problem in particular noted.'],
    synonyms: ['especially', 'specifically'],
    antonyms: ['generally'],
    shortStory:
      'In particular one crooked nail doomed ship. Shipwright Sara spotted defect pre-launch, particular proving tiny faults sink greatest vessels.',
  },
  {
    audioData: [' ', ''],
    word: 'in question',
    meaning: ['Being discussed or considered.', 'The specific one mentioned.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Being discussed.', 'Specific one.'],
    examples: ['The item in question.', 'Issue in question resolved.'],
    synonyms: ['under discussion', 'specific'],
    antonyms: [],
    shortStory:
      'Artifact in question proved biblical ark. Archaeologist Lena authenticated wood through radiocarbon, question settled rewriting sacred history pages.',
  },

  {
    audioData: [' ', ''],
    word: 'as part of',
    meaning: ['Included within larger whole.', 'Component of bigger process.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Included in.', 'Component of.'],
    examples: ['As part of training.', 'As part of tradition.'],
    synonyms: ['included in', 'component of'],
    antonyms: [],
    shortStory:
      'As part of daily chores, milkmaid Lena found magic cow. Simple bucket filled gold endlessly, part proving routine hides greatest wonders.',
  },
  {
    audioData: [' ', ''],
    word: 'the question of (whether or not)',
    meaning: ['Issue requiring decision.', 'Debate about existence or truth.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Issue to decide.', 'Debate existence.'],
    examples: [
      'The question of whether to go.',
      "Question of whether it's true.",
    ],
    synonyms: ['issue of', 'debate about'],
    antonyms: [],
    shortStory:
      'Question of whether gods exist answered by lightning strike. Shepherd Kai survived bolt revealing divine tattoo, question proving heavens mark chosen.',
  },
  {
    audioData: [' ', ''],
    word: 'the concept of',
    meaning: ['Abstract idea or general notion.', 'Theoretical understanding.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Abstract idea.', 'General notion.'],
    examples: ['The concept of justice.', 'Concept of infinity.'],
    synonyms: ['idea of', 'notion of'],
    antonyms: [],
    shortStory:
      'Concept of zero revolutionized math. Scholar Lena introduced nothingness as number, concept proving empty space births infinite possibility.',
  },
  {
    audioData: [' ', ''],
    word: 'the idea of',
    meaning: ['Particular thought or suggestion.', 'Proposed concept.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Thought.', 'Suggestion.'],
    examples: ['The idea of flying.', 'Idea of democracy.'],
    synonyms: ['notion of', 'concept of'],
    antonyms: [],
    shortStory:
      'Idea of round earth mocked until proven. Sailor Sara circumnavigated globe, idea transforming flat worldview into spherical reality.',
  },
  {
    audioData: [' ', ''],
    word: 'the notion of',
    meaning: ['Belief or opinion about something.', 'General concept.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Belief.', 'General idea.'],
    examples: ['Notion of fate.', 'Notion of equality.'],
    synonyms: ['idea of', 'concept of'],
    antonyms: [],
    shortStory:
      'Notion of talking animals proved true. Child Lena understood wolf howls perfectly, notion revealing nature speaks to pure hearts.',
  },
  {
    audioData: [' ', ''],
    word: 'the problem of',
    meaning: ['Issue needing solution.', 'Difficulty faced.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Issue.', 'Difficulty.'],
    examples: ['The problem of hunger.', 'Problem of pollution.'],
    synonyms: ['issue of', 'challenge of'],
    antonyms: [],
    shortStory:
      'Problem of endless drought solved by child. Zoe dug exactly where spring bubbled, problem proving intuition trumps engineering.',
  },
  {
    audioData: [' ', ''],
    word: 'the issue of',
    meaning: ['Topic of concern or debate.', 'Problem under discussion.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Concern.', 'Debate topic.'],
    examples: ['The issue of climate.', 'Issue of poverty.'],
    synonyms: ['problem of', 'question of'],
    antonyms: [],
    shortStory:
      'Issue of succession solved by forgotten daughter. Princess Lena revealed royal birthmark, issue proving blood speaks louder than parchment.',
  },
  {
    audioData: [' ', ''],
    word: 'the idea that',
    meaning: ['Belief or proposition.', 'Thought introduced.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Belief.', 'Proposition.'],
    examples: ['The idea that Earth revolves.', 'Idea that dreams predict.'],
    synonyms: ['notion that', 'belief that'],
    antonyms: [],
    shortStory:
      'Idea that music heals proved true. Harper Kai cured plague through melody, idea transforming deadly epidemic into harmonious recovery.',
  },
  {
    audioData: [' ', ''],
    word: 'in the field of',
    meaning: ['Within specific discipline.', 'Area of study or work.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Within discipline.', 'Study area.'],
    examples: ['In the field of physics.', 'Field of medicine.'],
    synonyms: ['within discipline of', 'area of'],
    antonyms: [],
    shortStory:
      'In field of astronomy, peasant saw comet first. Lena predicted eclipse timing perfectly, field proving visionaries rise from humblest observatories.',
  },
  {
    audioData: [' ', ''],
    word: 'in the area of',
    meaning: ['Within particular domain.', 'Specific sphere of activity.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Within domain.', 'Specific sphere.'],
    examples: ['In the area of education.', 'Area of technology.'],
    synonyms: ['within field of', 'domain of'],
    antonyms: [],
    shortStory:
      'In area of cryptography, barmaid cracked royal code. Sara decoded invasion plans over ale mugs, area proving genius pours from every tap.',
  },
  {
    audioData: [' ', ''],
    word: 'in the study of',
    meaning: ['Academic discipline.', 'Research area.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Academic discipline.', 'Research area.'],
    examples: ['In the study of history.', 'Study of biology.'],
    synonyms: ['within discipline of', 'field of'],
    antonyms: [],
    shortStory:
      'In study of ancient languages, baker translated prophecy. Lena read scroll flour-dusted hands revealed apocalypse timing, study proving wisdom seasons every trade.',
  },

  {
    audioData: [' ', ''],
    word: 'our understanding of',
    meaning: [
      'Current collective knowledge about.',
      'Shared comprehension regarding.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Shared knowledge.', 'Collective comprehension.'],
    examples: [
      'Our understanding of gravity changed.',
      'Our understanding of history evolves.',
    ],
    synonyms: ['knowledge about', 'comprehension of'],
    antonyms: [],
    shortStory:
      'Our understanding of stars transformed when shepherd Lena mapped constellations accurately. Village wisdom outshone palace astronomers, understanding proving clearest from humble fields.',
  },
  {
    audioData: [' ', ''],
    word: 'an understanding of',
    meaning: [
      'Grasp or comprehension about.',
      'Knowledge regarding specific topic.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Grasp about.', 'Knowledge regarding.'],
    examples: [
      'An understanding of physics required.',
      'An understanding of culture helps.',
    ],
    synonyms: ['knowledge of', 'awareness of'],
    antonyms: [],
    shortStory:
      'An understanding of wolf language saved trapper Kai. Howls warned avalanche perfectly, understanding bridging beast and man through primal whispers.',
  },
  {
    audioData: [' ', ''],
    word: 'a better understanding of',
    meaning: ['Improved or deeper comprehension.', 'Enhanced knowledge about.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Deeper grasp.', 'Improved knowledge.'],
    examples: [
      'A better understanding of climate.',
      'Leads to better understanding.',
    ],
    synonyms: ['deeper knowledge', 'improved comprehension'],
    antonyms: [],
    shortStory:
      "A better understanding of ancient script unlocked pyramid secrets. Scribe Sara decoded wall carvings revealing pharaoh's hidden tomb, understanding illuminating darkness.",
  },
  {
    audioData: [' ', ''],
    word: 'the assumption that',
    meaning: [
      'Belief taken as true without proof.',
      'Premise accepted for argument.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Belief without proof.', 'Accepted premise.'],
    examples: [
      'The assumption that Earth is flat.',
      'Under the assumption that.',
    ],
    synonyms: ['belief that', 'premise that'],
    antonyms: [],
    shortStory:
      'The assumption that gods controlled weather shattered when farmer Lena irrigated drought. Human effort watered fields, assumption proving clouds obey plows too.',
  },
  {
    audioData: [' ', ''],
    word: 'the aim/purpose of this study/chapter/article',
    meaning: [
      'Objective or intention of work.',
      'Goal stated for research/writing.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Objective of work.', 'Goal of research.'],
    examples: ['The aim of this study is...', 'Purpose of this chapter.'],
    synonyms: ['objective of', 'goal of'],
    antonyms: [],
    shortStory:
      'The aim of this humble diary changed kingdom fate. Maid Kai chronicled corruption perfectly, purpose transforming servant scribbles into revolutionary manifesto.',
  },
  {
    audioData: [' ', ''],
    word: 'beyond the scope of (this book/article/chapter)',
    meaning: ['Outside boundaries of discussion.', 'Not covered by this work.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Outside boundaries.', 'Not covered here.'],
    examples: ['Beyond the scope of this book.', 'This is beyond our scope.'],
    synonyms: ['outside scope of', 'not covered by'],
    antonyms: [],
    shortStory:
      'Beyond scope of village tales lay dragon truth. Storyteller Lena revealed beast sightings real, scope expanding from myth to monstrous reality.',
  },
  {
    audioData: [' ', ''],
    word: 'will be discussed in more detail',
    meaning: [
      'Subject covered more thoroughly later.',
      'Further elaboration promised.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Covered later.', 'More detail coming.'],
    examples: [
      'This will be discussed in more detail.',
      'Examined in more detail later.',
    ],
    synonyms: ['covered later', 'elaborated further'],
    antonyms: [],
    shortStory:
      'Village secret will be discussed in more detail at moonrise. Elder Sara revealed ancient pact with forest spirits, discussion unveiling generations-hidden magic.',
  },

  {
    audioData: [' ', ''],
    word: 'it is important (to)',
    meaning: [
      'Stresses necessity or significance.',
      'Highlights essential action.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Necessary.', 'Essential.'],
    examples: ['It is important to study.', 'It is important to listen.'],
    synonyms: ['crucial to', 'vital to'],
    antonyms: [],
    shortStory:
      'It is important to look beyond appearances, peasant Lena advised king. Hidden noble birth saved realm, importance proving wisdom flows from humblest lips.',
  },
  {
    audioData: [' ', ''],
    word: 'it should be noted that',
    meaning: [
      'Draws attention to key fact.',
      'Highlights observation formally.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Note that.', 'Observe.'],
    examples: [
      'It should be noted that results vary.',
      'It should be noted that context matters.',
    ],
    synonyms: ['observe that', 'mention that'],
    antonyms: [],
    shortStory:
      'It should be noted that tiny seed contains forest, botanist Kai warned. Single acorn greened desert, notation proving potential hides microscopic packages.',
  },
  {
    audioData: [' ', ''],
    word: 'it is important to note that',
    meaning: ['Emphasizes critical observation.', 'Stresses noteworthy fact.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Stress observation.', 'Key fact.'],
    examples: [
      'It is important to note that exceptions exist.',
      'Important to note the limitations.',
    ],
    synonyms: ['crucial to observe', 'vital to mention'],
    antonyms: [],
    shortStory:
      "It is important to note that silence speaks loudest. Judge Sara read defendant's trembling hands perfectly, notation revealing truth words conceal.",
  },
  {
    audioData: [' ', ''],
    word: 'it is interesting to note that',
    meaning: [
      'Highlights curious or surprising fact.',
      'Points out noteworthy observation.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Curious fact.', 'Surprising observation.'],
    examples: [
      'It is interesting to note that ancient cultures knew.',
      'Interesting to note the pattern.',
    ],
    synonyms: ['curious that', 'noteworthy that'],
    antonyms: [],
    shortStory:
      "It is interesting to note that broken sword won battle. Blacksmith Lena's flawed blade shattered enemy armor, interest proving imperfection cuts deepest.",
  },
  {
    audioData: [' ', ''],
    word: 'it is worth noting that',
    meaning: [
      'Highlights valuable observation.',
      'Points out significant detail.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Valuable note.', 'Significant detail.'],
    examples: [
      'It is worth noting that early intervention helps.',
      'Worth noting the historical context.',
    ],
    synonyms: ['noteworthy that', 'significant that'],
    antonyms: [],
    shortStory:
      'It is worth noting that forgotten well held treasure. Villager Kai rediscovered spring gold, worth proving lost knowledge shines brightest.',
  },
  {
    audioData: [' ', ''],
    word: 'it is important to remember that',
    meaning: ['Stresses crucial recollection.', 'Emphasizes key past fact.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ["Don't forget.", 'Key recollection.'],
    examples: [
      'It is important to remember that mistakes teach.',
      'Remember that context changes meaning.',
    ],
    synonyms: ['crucial to recall', 'vital to remember'],
    antonyms: [],
    shortStory:
      'It is important to remember that dragons fear mice. Knight Sara routed beast with rodent army, remembrance proving ancient wisdom survives.',
  },
  {
    audioData: [' ', ''],
    word: 'it is important to realize that',
    meaning: [
      'Stresses essential awareness.',
      'Highlights critical understanding.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Essential awareness.', 'Critical understanding.'],
    examples: [
      'It is important to realize that perception varies.',
      'Realize that assumptions mislead.',
    ],
    synonyms: ['crucial to understand', 'vital to recognize'],
    antonyms: [],
    shortStory:
      'It is important to realize that shadows hold light. Artist Lena painted masterpiece from darkness, realization proving contrast births greatest beauty.',
  },
  {
    audioData: [' ', ''],
    word: 'it is important to understand',
    meaning: [
      'Emphasizes necessity of comprehension.',
      'Stresses grasping concept fully.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Must comprehend.', 'Grasp fully.'],
    examples: [
      'It is important to understand the theory.',
      'Understand the historical context.',
    ],
    synonyms: ['crucial to grasp', 'essential to comprehend'],
    antonyms: [],
    shortStory:
      'It is important to understand that rivers carve canyons. Explorer Kai followed water through stone, understanding proving patience shapes hardest rock.',
  },
  {
    audioData: [' ', ''],
    word: 'it is important to recognize/be aware of/ bear in mind',
    meaning: [
      'Stresses conscious acknowledgment.',
      'Highlights need for awareness.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Be aware.', 'Conscious acknowledgment.'],
    examples: ['Important to recognize bias.', 'Bear in mind the limitations.'],
    synonyms: ['acknowledge', 'be conscious of'],
    antonyms: [],
    shortStory:
      'It is important to recognize that stars guide sailors. Captain Lena navigated storm using constellations, recognition proving heavens chart human destiny.',
  },
  {
    audioData: [' ', ''],
    word: 'in the case of',
    meaning: ['Regarding specific instance.', 'Concerning particular example.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Specific instance.', 'Particular example.'],
    examples: ['In the case of emergencies.', 'In the case of John.'],
    synonyms: ['regarding', 'concerning'],
    antonyms: [],
    shortStory:
      'In the case of lost princess, baker revealed truth. Lena recognized royal birthmark through flour dust, case proving royalty hides plainest aprons.',
  },

  {
    audioData: [' ', ''],
    word: 'in this case',
    meaning: [
      'Regarding this specific situation.',
      'For this particular instance.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['This situation.', 'Particular instance.'],
    examples: [
      'In this case, exception applies.',
      'Solution works in this case.',
    ],
    synonyms: ['for this instance', 'regarding this'],
    antonyms: [],
    shortStory:
      "In this case, broken sword saved kingdom. Blacksmith Lena's flawed blade pierced dragon scale, case proving imperfection slays perfect monsters.",
  },
  {
    audioData: [' ', ''],
    word: 'the importance of',
    meaning: [
      'Significance or value of something.',
      'Crucial nature regarding.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Significance.', 'Crucial nature.'],
    examples: ['The importance of education.', 'Importance of preparation.'],
    synonyms: ['significance of', 'value of'],
    antonyms: [],
    shortStory:
      "The importance of one kind word transformed orphan into emperor. Peasant Kai remembered beggar's smile, importance proving tiny seeds grow mightiest crowns.",
  },
  {
    audioData: [' ', ''],
    word: '(one of) the most important',
    meaning: [
      'Among highest priority or value.',
      'Primary or crucial element.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Highest priority.', 'Primary element.'],
    examples: [
      'One of the most important factors.',
      'Most important consideration.',
    ],
    synonyms: ['crucial', 'primary'],
    antonyms: ['least important'],
    shortStory:
      "One of most important discoveries came from child's sandcastle. Lena unearthed ancient coin proving lost city real, importance hiding beneath playful waves.",
  },
  {
    audioData: [' ', ''],
    word: 'it is not surprising that',
    meaning: [
      'Expected or predictable outcome.',
      'Logical consequence observed.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Expected outcome.', 'Logical result.'],
    examples: [
      'It is not surprising that he won.',
      'Not surprising that it failed.',
    ],
    synonyms: ['predictably', 'expectedly'],
    antonyms: ['surprisingly'],
    shortStory:
      "It is not surprising that humble roots bore greatest fruit. Farmer Sara's simple soil grew miracle crop, unsurprising proving fertility favors purity.",
  },
  {
    audioData: [' ', ''],
    word: 'the need for/to',
    meaning: ['Requirement or necessity.', 'Essential action required.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Requirement.', 'Must do.'],
    examples: ['The need for change.', 'Need to prepare now.'],
    synonyms: ['necessity for', 'requirement to'],
    antonyms: [],
    shortStory:
      'The need to forgive freed chained kingdom. Queen Lena pardoned assassin publicly, need proving mercy unlocks heavier shackles than iron.',
  },
  {
    audioData: [' ', ''],
    word: 'there is a need for/to',
    meaning: ['Exists requirement or necessity.', 'Situation demands action.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Must have.', 'Situation demands.'],
    examples: ['There is a need for volunteers.', 'Need to act quickly.'],
    synonyms: ['requires', 'demands'],
    antonyms: [],
    shortStory:
      "There is a need for heroes when dragons circle. Village girl Kai climbed beast's back taming it, need birthing legends from trembling hands.",
  },
  {
    audioData: [' ', ''],
    word: 'the significance of',
    meaning: ['Importance or deeper meaning.', 'Profound impact or value.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Deeper meaning.', 'Profound impact.'],
    examples: [
      'The significance of this finding.',
      'Significance of the event.',
    ],
    synonyms: ['importance of', 'meaning of'],
    antonyms: [],
    shortStory:
      "The significance of single crooked branch saved avalanche victims. Climber Lena tied rope perfectly, significance proving nature's flaws guide human salvation.",
  },
  {
    audioData: [' ', ''],
    word: 'it is necessary to',
    meaning: ['Must or required action.', 'Essential step needed.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Must do.', 'Required step.'],
    examples: ['It is necessary to verify.', 'Necessary to prepare.'],
    synonyms: ['must', 'essential to'],
    antonyms: [],
    shortStory:
      'It is necessary to listen when winds whisper warnings. Sailor Sara heard storm signals dodging disaster, necessity proving ears trump compasses.',
  },
  {
    audioData: [' ', ''],
    word: 'it is useful to',
    meaning: ['Beneficial or helpful action.', 'Practical advantage gained.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Helpful.', 'Practical benefit.'],
    examples: ['It is useful to plan ahead.', 'Useful to know basics.'],
    synonyms: ['helpful to', 'beneficial to'],
    antonyms: [],
    shortStory:
      'It is useful to know raven speech when lost. Traveler Lena followed bird calls to safety, usefulness proving animal tongues chart human trails.',
  },
  {
    audioData: [' ', ''],
    word: '(to) take into account',
    meaning: ['Consider or include factor.', 'Factor in consideration.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Consider factor.', 'Include.'],
    examples: ['Take into account weather.', 'Must take into account age.'],
    synonyms: ['consider', 'factor in'],
    antonyms: ['ignore'],
    shortStory:
      "Take into account the river's bend saved flotilla. Captain Kai timed crossing perfectly, accounting proving foresight steers safer than strongest oars.",
  },
  {
    audioData: [' ', ''],
    word: '(to/should/need to) be taken into account',
    meaning: ['Must be considered.', 'Factor requiring inclusion.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Must consider.', 'Include factor.'],
    examples: [
      'Should be taken into account.',
      'Needs to be taken into account.',
    ],
    synonyms: ['must consider', 'factor in'],
    antonyms: ['overlook'],
    shortStory:
      "Needs to be taken into account: owl's night vision. Hunter Lena tracked prey through darkness perfectly, accounting proving night belongs to wise eyes.",
  },

  {
    audioData: [' ', ''],
    word: 'to take account of',
    meaning: ['To consider or include factor.', 'Factor into decision-making.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Consider factor.', 'Include.'],
    examples: ['To take account of risks.', 'Must take account of time.'],
    synonyms: ['consider', 'factor in'],
    antonyms: ['ignore'],
    shortStory:
      "To take account of tidal pull saved fishing fleet. Captain Lena timed departure perfectly, accounting proving moon's grip steers safer than human charts.",
  },
  {
    audioData: [' ', ''],
    word: 'to be aware of',
    meaning: [
      'To have knowledge or notice.',
      'Conscious recognition required.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Notice.', 'Know about.'],
    examples: ['To be aware of dangers.', 'Be aware of changes.'],
    synonyms: ['notice', 'recognize'],
    antonyms: ['ignorant of'],
    shortStory:
      'To be aware of falcon cries warned avalanche. Mountaineer Kai evacuated camp timely, awareness proving bird voices shout louder than silent snow.',
  },
  {
    audioData: [' ', ''],
    word: 'it is difficult to',
    meaning: [
      'Challenging or hard to accomplish.',
      'Requires significant effort.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Hard to.', 'Challenging.'],
    examples: ['It is difficult to predict.', 'Difficult to understand fully.'],
    synonyms: ['hard to', 'challenging to'],
    antonyms: ['easy to'],
    shortStory:
      'It is difficult to forgive betrayer, yet Lena freed kingdom through mercy. Royal pardon healed civil war, difficulty proving hardest paths birth deepest peace.',
  },
  {
    audioData: [' ', ''],
    word: 'the purposes of',
    meaning: ['Intended goals or objectives.', 'Reasons for action taken.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Goals.', 'Objectives.'],
    examples: ['For the purposes of research.', 'Purposes of this meeting.'],
    synonyms: ['goals of', 'objectives of'],
    antonyms: [],
    shortStory:
      'For purposes of village defense, child Kai dug perfect moat. Tiny shovel routed invaders, purpose proving innocent hands build mightiest fortresses.',
  },
  {
    audioData: [' ', ''],
    word: 'the benefits of',
    meaning: [
      'Advantages gained from something.',
      'Positive outcomes or gains.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Advantages.', 'Gains.'],
    examples: ['The benefits of exercise.', 'Benefits of early planning.'],
    synonyms: ['advantages of', 'gains from'],
    antonyms: ['drawbacks of'],
    shortStory:
      "The benefits of shared suffering forged unbreakable tribe. Survivor Lena led through famine, benefits proving adversity welds stronger than prosperity's gold.",
  },
  {
    audioData: [' ', ''],
    word: '(to) note that',
    meaning: [
      'Observe or mention important fact.',
      'Highlight key observation.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Observe.', 'Mention fact.'],
    examples: ['Note that exceptions exist.', 'Important to note trends.'],
    synonyms: ['observe that', 'mention that'],
    antonyms: [],
    shortStory:
      '(To) note that crooked path led straightest taught cartographer Sara. Winding trail avoided cliffs perfectly, notation proving detours chart safest routes.',
  },
  {
    audioData: [' ', ''],
    word: 'an important role in',
    meaning: [
      'Significant function or contribution.',
      'Key participation within.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Key function.', 'Major contribution.'],
    examples: ['Plays an important role in.', 'Important role in development.'],
    synonyms: ['key function in', 'vital part of'],
    antonyms: [],
    shortStory:
      'An important role in revolution played by laundress. Lena washed coded messages in sheets, role proving humble soap hides rebel fire.',
  },
  {
    audioData: [' ', ''],
    word: 'at the heart of',
    meaning: ['Central or essential element.', 'Core or fundamental aspect.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Central.', 'Core element.'],
    examples: ['At the heart of problem.', 'At heart of solution.'],
    synonyms: ['central to', 'core of'],
    antonyms: ['on periphery of'],
    shortStory:
      "At heart of ancient tree beat village's pulse. Elder Kai heard wisdom rings, heart proving oldest wood whispers newest truths.",
  },
  {
    audioData: [' ', ''],
    word: 'if and only if',
    meaning: ['Exclusive condition required.', 'Both directions necessary.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Exactly when.', 'Both ways.'],
    examples: [
      'True if and only if conditions met.',
      'Works if and only if powered.',
    ],
    synonyms: ['exactly when', 'precisely when'],
    antonyms: [],
    shortStory:
      'Lock opens if and only if moon aligns with gem. Thief Lena timed heist perfectly, condition proving celestial math cracks human iron.',
  },
  {
    audioData: [' ', ''],
    word: 'in fact',
    meaning: ['Actually or in reality.', 'Truth contrary to appearance.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Actually.', 'In reality.'],
    examples: ['In fact, better than expected.', 'In fact, opposite is true.'],
    synonyms: ['actually', 'really'],
    antonyms: ['in theory'],
    shortStory:
      'In fact, pauper wore invisible crown of destiny. Beggar Sara revealed royal lineage through birthmark, fact proving gold threads weave poorest rags.',
  },

  {
    audioData: [' ', ''],
    word: 'it may be',
    meaning: ['Possible or potential situation.', 'Might be true.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Possibly.', 'Might be.'],
    examples: ['It may be true.', 'It may be raining.'],
    synonyms: ['possibly', 'perhaps'],
    antonyms: [],
    shortStory:
      'It may be foolish to trust raven, yet Lena followed bird to hidden valley. Paradise bloomed where maps showed stone, may-be proving wings guide wiser than scrolls.',
  },
  {
    audioData: [' ', ''],
    word: 'appears to be',
    meaning: ['Seems based on evidence.', 'Gives impression of.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Seems.', 'Looks like.'],
    examples: ['Appears to be genuine.', 'Situation appears to be stable.'],
    synonyms: ['seems', 'looks'],
    antonyms: [],
    shortStory:
      'Appears to be ordinary rock revealed diamond heart. Miner Kai cracked surface finding fortune, appearance proving greatest treasures wear plainest disguises.',
  },
  {
    audioData: [' ', ''],
    word: 'does not appear to be',
    meaning: ['Lacks evidence of being.', 'Seems not to be.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ["Doesn't seem.", 'Not likely.'],
    examples: ['Does not appear to be damaged.', 'Does not appear to work.'],
    synonyms: ["doesn't seem", 'not likely'],
    antonyms: [],
    shortStory:
      'Does not appear to be breathing, yet child Lena revived drowned sailor. Perfect breath restored life, non-appearance proving hope animates silent chests.',
  },
  {
    audioData: [' ', ''],
    word: 'seems to be',
    meaning: ['Gives impression of being.', 'Appears likely.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Appears.', 'Looks like.'],
    examples: ['Seems to be working.', 'Seems to be correct.'],
    synonyms: ['appears', 'looks'],
    antonyms: [],
    shortStory:
      'Seems to be dead end revealed secret passage. Explorer Sara pushed stone wall discovering treasure vault, seeming proving false walls hide truest riches.',
  },
  {
    audioData: [' ', ''],
    word: 'it could/can be argued that',
    meaning: [
      'Reasonable position possible.',
      'Debatable perspective offered.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Can argue.', 'Debatable view.'],
    examples: [
      'It can be argued that education matters most.',
      'Could be argued that risk pays.',
    ],
    synonyms: ['one might argue', 'debatable that'],
    antonyms: [],
    shortStory:
      "It could be argued that failure teaches best. Inventor Lena's thousand explosions birthed perfect engine, argument proving scorched hands forge brightest innovations.",
  },
  {
    audioData: [' ', ''],
    word: 'argue(s) that',
    meaning: ['Presents reasoning for position.', 'Maintains specific claim.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Claims.', 'Reasons.'],
    examples: [
      'Scholars argue that climate changed.',
      'She argues that peace works.',
    ],
    synonyms: ['claims', 'asserts'],
    antonyms: [],
    shortStory:
      'Argues that stars speak truth, astronomer Kai predicted eclipse perfectly. Village worshipped stargazer, argument proving celestial grammar outshines earthly tongues.',
  },
  {
    audioData: [' ', ''],
    word: 'held that',
    meaning: ['Believed or maintained position.', 'Past assertion made.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Believed.', 'Maintained.'],
    examples: [
      'Ancient sages held that Earth was flat.',
      'Court held that verdict stands.',
    ],
    synonyms: ['believed', 'maintained'],
    antonyms: [],
    shortStory:
      "Held that animals understand justice, farmer Lena witnessed trial by fox court. Beasts judged thief fairly, holding proving nature's law rivals man's.",
  },
  {
    audioData: [' ', ''],
    word: 'claim that',
    meaning: ['Assert as true.', 'State position confidently.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Assert.', 'State confidently.'],
    examples: [
      'Scientists claim that theory proven.',
      'He claims that treasure exists.',
    ],
    synonyms: ['assert', 'state'],
    antonyms: ['deny'],
    shortStory:
      'Claim that mountain holds gold proved true. Prospector Sara panned first nugget from peak stream, claim staking legend from doubted dirt.',
  },
  {
    audioData: [' ', ''],
    word: 'it is (not) possible to/that',
    meaning: [
      'Feasibility confirmed or denied.',
      'Capability exists or absent.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Can/cannot.', 'Feasible/not.'],
    examples: ['Possible to achieve.', 'Not possible that he knew.'],
    synonyms: ['feasible', 'capable'],
    antonyms: ['impossible'],
    shortStory:
      "It is not possible to tame wild river, yet engineer Lena dammed torrent perfectly. Valley bloomed, impossibility proving human will redirects nature's fury.",
  },
  {
    audioData: [' ', ''],
    word: 'it is impossible to',
    meaning: ['Cannot be done.', 'Beyond capability.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Cannot.', 'Beyond ability.'],
    examples: [
      'Impossible to predict weather perfectly.',
      'Impossible to forget trauma.',
    ],
    synonyms: ['cannot', 'unachievable'],
    antonyms: ['possible'],
    shortStory:
      'Impossible to cross chasm, claimed wise men. Acrobat Kai tightrope-walked gorge carrying child, impossibility crumbling before daring footsteps.',
  },
  {
    audioData: [' ', ''],
    word: 'it may be possible to',
    meaning: ['Potential feasibility exists.', 'Might be achievable.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Might achieve.', 'Potentially feasible.'],
    examples: ['May be possible to cure.', 'Possible to improve later.'],
    synonyms: ['potentially', 'perhaps able'],
    antonyms: [],
    shortStory:
      'It may be possible to speak with winds, whispered shaman. Lena learned breeze language predicting storms, possibility proving air carries human words.',
  },
  {
    audioData: [' ', ''],
    word: 'the possibility of',
    meaning: [
      'Potential existence or occurrence.',
      'Chance something might happen.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Chance.', 'Potential.'],
    examples: ['Possibility of rain tomorrow.', 'Possibility of success high.'],
    synonyms: ['chance of', 'potential for'],
    antonyms: ['certainty'],
    shortStory:
      "The possibility of flying haunted dreamer's mind. Wright sister Lena built first glider soaring, possibility transforming wingbeats into human destiny.",
  },
  {
    audioData: [' ', ''],
    word: 'the probability of',
    meaning: ['Likelihood of occurrence.', 'Mathematical chance.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Likelihood.', 'Chance.'],
    examples: ['Probability of winning low.', 'High probability of success.'],
    synonyms: ['likelihood', 'odds'],
    antonyms: ['certainty'],
    shortStory:
      'Probability of finding pearl in oyster slim, yet diver Kai harvested strand daily. Marketplace marveled at statistic-defying fortune, probability bowing to persistent nets.',
  },

  {
    audioData: [' ', ''],
    word: 'as a whole',
    meaning: ['Considering everything together.', 'In total or completely.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Altogether.', 'Completely.'],
    examples: ['Society as a whole improved.', 'Project as a whole succeeded.'],
    synonyms: ['overall', 'entirely'],
    antonyms: [],
    shortStory:
      'As a whole, village ants lifted grain larger than mountain. Collective strength amazed Lena, whole proving unity moves impossible burdens effortlessly.',
  },
  {
    audioData: [' ', ''],
    word: 'assume that',
    meaning: ['Take as true without proof.', 'Presume for reasoning.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Presume.', 'Take as true.'],
    examples: ['Assume that plan works.', "Don't assume success."],
    synonyms: ['presume', 'suppose'],
    antonyms: [],
    shortStory:
      "Assume that stars fell nightly, astronomer Lena charted meteor shower perfectly. Village marveled at 'falling sky,' assumption revealing cosmic fireworks.",
  },
  {
    audioData: [' ', ''],
    word: 'it is reasonable to assume that',
    meaning: [
      'Logical presumption justified.',
      'Fair inference based on evidence.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Logical to presume.', 'Fair inference.'],
    examples: [
      'Reasonable to assume rain coming.',
      'It is reasonable to assume growth.',
    ],
    synonyms: ['logical to presume', 'fair to infer'],
    antonyms: [],
    shortStory:
      'Reasonable to assume cave held death, yet explorer Kai found healing spring. Glowing waters cured plague, reasonableness proving danger hides greatest cures.',
  },
  {
    audioData: [' ', ''],
    word: 'it is fair to say that',
    meaning: ['Reasonable or balanced statement.', 'Justified generalization.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Reasonable statement.', 'Balanced claim.'],
    examples: [
      'Fair to say progress made.',
      'It is fair to say challenge remains.',
    ],
    synonyms: ['reasonable to claim', 'just to state'],
    antonyms: [],
    shortStory:
      "Fair to say pauper outshone princes at feast. Lena's simple grace captivated court, fairness proving true nobility shines through plainest garments.",
  },
  {
    audioData: [' ', ''],
    word: 'more or less',
    meaning: ['Approximately or roughly.', 'Substantially but not exactly.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Approximately.', 'Roughly.'],
    examples: ['More or less complete.', 'Cost more or less 100.'],
    synonyms: ['approximately', 'roughly'],
    antonyms: ['exactly'],
    shortStory:
      'More or less blind painter captured perfect sunset. Lena felt light through fingertips, approximation proving heart sees clearer than perfect eyes.',
  },
  {
    audioData: [' ', ''],
    word: 'in general',
    meaning: ['Usually or typically.', 'Broadly speaking.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Usually.', 'Typically.'],
    examples: ['In general, people agree.', 'Works in general cases.'],
    synonyms: ['typically', 'broadly'],
    antonyms: ['specifically'],
    shortStory:
      'In general, wolves fear fire, but Lena tamed pack with single torch. Flame-lit dance forged alliance, general proving exceptions birth legends.',
  },
  {
    audioData: [' ', ''],
    word: 'is/are likely to be',
    meaning: ['Probable future state.', 'Expected condition.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Probable.', 'Expected.'],
    examples: ['Likely to be successful.', 'Results likely to vary.'],
    synonyms: ['probable', 'expected'],
    antonyms: ['unlikely'],
    shortStory:
      'Likely to be barren field bloomed golden. Farmer Sara planted against odds harvesting abundance, likelihood proving faith harvests heavier than certainty.',
  },
  {
    audioData: [' ', ''],
    word: 'is/are/were more likely to (be)',
    meaning: [
      'Higher probability compared.',
      'Greater chance than alternative.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Greater chance.', 'Higher probability.'],
    examples: ['More likely to succeed.', 'Were more likely to fail.'],
    synonyms: ['higher probability', 'greater chance'],
    antonyms: ['less likely'],
    shortStory:
      'More likely to drown than swim, yet child Kai crossed raging river. Instinct outswam statistics, likelihood proving courage paddles faster than odds.',
  },
  {
    audioData: [' ', ''],
    word: '(are) less likely to',
    meaning: ['Lower probability of occurrence.', 'Reduced chance compared.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Lower chance.', 'Less probable.'],
    examples: ['Less likely to work.', 'Are less likely to agree.'],
    synonyms: ['lower probability', 'unlikely'],
    antonyms: ['more likely'],
    shortStory:
      'Less likely to win tournament, underdog Lena claimed crown. Perfect final shot stunned nobles, unlikelihood proving destiny favors darkest horses.',
  },
  {
    audioData: [' ', ''],
    word: 'is/are likely to',
    meaning: ['Probable to happen or occur.', 'Expected outcome.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Expected.', 'Probable.'],
    examples: ['Likely to rain.', 'Students likely to pass.'],
    synonyms: ['probable', 'expected'],
    antonyms: ['unlikely'],
    shortStory:
      'Likely to fail exam birthed greatest teacher. Student Sara mastered subject tutoring peers perfectly, likelihood proving stumbles birth sturdiest scholars.',
  },
  {
    audioData: [' ', ''],
    word: 'it is likely that',
    meaning: ['Probable situation or outcome.', 'Strong expectation.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Probable.', 'Strong expectation.'],
    examples: ['Likely that plan succeeds.', 'It is likely that change comes.'],
    synonyms: ['probable that', 'expected that'],
    antonyms: [],
    shortStory:
      "Likely that kingdom falls, yet queen Lena rallied peasants victoriously. Common spears outmatched noble swords, likelihood proving people's will forges strongest steel.",
  },
  {
    audioData: [' ', ''],
    word: 'be expected to',
    meaning: ['Anticipated or predicted outcome.', 'Normal or logical result.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Anticipated.', 'Predicted.'],
    examples: ['Expected to arrive soon.', 'Results expected to improve.'],
    synonyms: ['anticipated', 'predicted'],
    antonyms: ['unexpected'],
    shortStory:
      "Expected to crumble under storm, bridge Lena built stood firmest. Deep roots held through tempest, expectation proving preparation defies nature's worst fury.",
  },

  {
    audioData: [' ', ''],
    word: 'in other words',
    meaning: ['Rephrasing for clarity.', 'Alternative explanation.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Simply put.', 'To rephrase.'],
    examples: ['In other words, hurry up.', 'Cheap, in other words.'],
    synonyms: ['simply put', 'that is to say'],
    antonyms: [],
    shortStory:
      "In other words, single pebble sank armada. Fisherman Lena's stone hit perfect wave capsizing fleet, rephrasing proving smallest throws topple greatest ships.",
  },
  {
    audioData: [' ', ''],
    word: '(is) (often) referred to as',
    meaning: ['Commonly known or called.', 'Given specific name or title.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Commonly called.', 'Known as.'],
    examples: ['Often referred to as genius.', 'Referred to as disaster.'],
    synonyms: ['known as', 'called'],
    antonyms: [],
    shortStory:
      "Often referred to as fool's gold, pyrite saved kingdom. Alchemist Kai transmuted 'worthless' metal into perfect currency, reference proving scorn hides truest value.",
  },
  {
    audioData: [' ', ''],
    word: 'refer(s) to',
    meaning: [
      'Means or indicates specifically.',
      'Points to particular thing.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Means.', 'Indicates.'],
    examples: ['Refers to ancient practice.', 'Term refers to tool.'],
    synonyms: ['means', 'indicates'],
    antonyms: [],
    shortStory:
      "Refers to crooked staff that parted seas. Shepherd Lena's stick guided flock through flood, reference proving humble wood wields heaven's might.",
  },
  {
    audioData: [' ', ''],
    word: 'this means that',
    meaning: ['Indicates consequence or result.', 'Logical outcome follows.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Therefore.', 'Results in.'],
    examples: ['This means that delay.', 'Success means promotion.'],
    synonyms: ['therefore', 'consequently'],
    antonyms: [],
    shortStory:
      'This means that broken clock still right twice daily. Tinker Sara fixed village timekeeper perfectly, meaning proving even failures mark truth occasionally.',
  },
  {
    audioData: [' ', ''],
    word: 'this does not mean that',
    meaning: [
      'Clarifies no further implication.',
      "Doesn't necessarily follow.",
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Not necessarily.', "Doesn't imply."],
    examples: ["Doesn't mean failure.", 'This does not mean impossible.'],
    synonyms: ['not necessarily', "doesn't imply"],
    antonyms: [],
    shortStory:
      'This does not mean dragons extinct, cave painting proved. Explorer Lena found recent claw marks, negation revealing fire-breathers stalk modern shadows.',
  },
  {
    audioData: [' ', ''],
    word: 'in the sense that/of',
    meaning: ['Specific meaning or aspect.', 'Particular interpretation.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Specifically.', 'Particularly.'],
    examples: [
      'Freedom in sense that choice exists.',
      'In sense of tradition.',
    ],
    synonyms: ['specifically', 'particularly'],
    antonyms: [],
    shortStory:
      'In sense that one spark ignites inferno, match girl Lena saved city. Tiny flame signaled rescuers through smoke, sense proving smallest lights pierce darkest nights.',
  },
  {
    audioData: [' ', ''],
    word: 'in this way',
    meaning: ['By this method or manner.', 'Through described process.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Thus.', 'By this method.'],
    examples: ['In this way, success achieved.', 'Problem solved in this way.'],
    synonyms: ['thus', 'thereby'],
    antonyms: [],
    shortStory:
      'In this way, orphan built cathedral alone. Stone by stone, Lena created heaven reaching village, method proving patient hands weave eternality from dust.',
  },
  {
    audioData: [' ', ''],
    word: 'in such a way (that)',
    meaning: [
      'Manner resulting in specific outcome.',
      'Method causing particular effect.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['So that.', 'Resulting in.'],
    examples: [
      'Arranged in such way that light entered.',
      'Spoke in such way crowd cheered.',
    ],
    synonyms: ['so that', 'resulting in'],
    antonyms: [],
    shortStory:
      'Whistled in such way that wolves obeyed. Shepherd Kai commanded pack protecting flock, way proving music tames wilder than chains or whips.',
  },
  {
    audioData: [' ', ''],
    word: 'in a way that',
    meaning: ['Manner achieving specific result.', 'Method producing effect.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['So as to.', 'Causing.'],
    examples: [
      'Built in way that lasted centuries.',
      'Taught in way students loved.',
    ],
    synonyms: ['so as to', 'causing'],
    antonyms: [],
    shortStory:
      "Planted in way that single seed fed nation. Farmer Sara's deep hole grew miracle crop, way proving perfect depth births impossible harvests.",
  },
  {
    audioData: [' ', ''],
    word: '(as) a way of',
    meaning: ['Method or means to achieve.', 'Approach for purpose.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Method to.', 'Means of.'],
    examples: ['As way of saying thanks.', 'Used as way of learning.'],
    synonyms: ['method of', 'means to'],
    antonyms: [],
    shortStory:
      'As way of honoring dead, Lena carved faces into mountain. Cliff sculptures watched valley eternally, way proving stone remembers longer than parchment.',
  },
  {
    audioData: [' ', ''],
    word: 'be regarded as',
    meaning: ['Considered or viewed to be.', 'Held in particular opinion.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Considered.', 'Viewed as.'],
    examples: ['Regarded as genius.', 'Best solution regarded as.'],
    synonyms: ['considered', 'viewed'],
    antonyms: [],
    shortStory:
      "Regarded as mad inventor, Lena launched first rocket successfully. Village hailed 'lunatic' who conquered stars, regard proving vision outshines contemporary scorn.",
  },
  {
    audioData: [' ', ''],
    word: '(can) be thought of as',
    meaning: [
      'Conceptualized or understood as.',
      'Alternative perspective offered.',
    ],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Understood as.', 'Conceptualized.'],
    examples: ['Can be thought of as tool.', 'Thought of as progress.'],
    synonyms: ['understood as', 'seen as'],
    antonyms: [],
    shortStory:
      "Can be thought of as useless rock revealed diamond. Miner Kai recut 'flawed' gem perfectly, thought proving rough exteriors hide flawless cores.",
  },
  {
    audioData: [' ', ''],
    word: 'the definition of',
    meaning: ['Precise meaning or explanation.', 'Exact criteria established.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Exact meaning.', 'Criteria.'],
    examples: ['Definition of success.', 'The definition of courage.'],
    synonyms: ['meaning of', 'criteria for'],
    antonyms: [],
    shortStory:
      "Definition of miracle became milkmaid's golden bucket. Lena's ordinary pail overflowed endlessly feeding nation, definition expanding from divine to daily wonders.",
  },
  {
    audioData: [' ', ''],
    word: 'is defined as',
    meaning: ['Formally established meaning.', 'Specific criteria met.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Formally means.', 'Criteria met.'],
    examples: [
      'Love is defined as sacrifice.',
      'Success is defined as growth.',
    ],
    synonyms: ['means', 'constitutes'],
    antonyms: [],
    shortStory:
      'Genius is defined as seeing invisible connections. Child Sara linked cloud patterns to coming storms perfectly, definition proving young eyes pierce adult blindness.',
  },
  {
    audioData: [' ', ''],
    word: 'to account for',
    meaning: ['Explain or provide reason.', 'Include factor in explanation.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Explain.', 'Include reason.'],
    examples: ['To account for delay.', 'Factors to account for.'],
    synonyms: ['explain', 'consider'],
    antonyms: ['ignore'],
    shortStory:
      'To account for crooked bridge standing longest, engineer Lena explained wind dynamics perfectly. Structure outlasted rivals, accounting proving curves breathe better than straight lines.',
  },
  {
    audioData: [' ', ''],
    word: 'reasons for',
    meaning: ['Explanations or causes.', 'Factors causing phenomenon.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Causes.', 'Explanations.'],
    examples: ['Reasons for failure.', 'Reasons for success.'],
    synonyms: ['causes of', 'explanations for'],
    antonyms: [],
    shortStory:
      "Reasons for ant colony's perfect order revealed by observer Kai. Pheromone trails orchestrated million workers flawlessly, reasons proving chemistry conducts silent symphonies.",
  },
  {
    audioData: [' ', ''],
    word: 'the reason for this is that',
    meaning: ['Specific cause explained.', 'Causal explanation provided.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Cause is.', 'Explanation.'],
    examples: ['Reason for delay is weather.', 'Reason is preparation.'],
    synonyms: ['because', 'due to'],
    antonyms: [],
    shortStory:
      'Reason for river flowing uphill revealed ancient cavern. Explorer Lena discovered magnetic mountain pulling water, reason transforming physics textbooks overnight.',
  },
  {
    audioData: [' ', ''],
    word: 'it is for this reason that',
    meaning: ['Consequently or therefore.', 'Logical outcome follows.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Therefore.', 'Consequently.'],
    examples: [
      'For this reason training needed.',
      'It is for this reason we study.',
    ],
    synonyms: ['therefore', 'consequently'],
    antonyms: [],
    shortStory:
      'For this reason peasant became king: birthmark proved lineage. Lena revealed royal mark washing face, reason elevating stable girl to throne.',
  },
  {
    audioData: [' ', ''],
    word: 'for a number of reasons',
    meaning: ['Multiple causes or factors.', 'Several explanations exist.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Several reasons.', 'Multiple factors.'],
    examples: [
      'Rejected for number of reasons.',
      'Chose for number of reasons.',
    ],
    synonyms: ['several reasons', 'various factors'],
    antonyms: [],
    shortStory:
      "For number of reasons bridge collapsed except Lena's span. Deep pilings withstood flood, reasons proving foresight stacks safer than single solutions.",
  },
  {
    audioData: [' ', ''],
    word: 'can be described/explained in terms of',
    meaning: ['Expressible through concepts.', 'Understood via framework.'],
    partOfSpeech: ['phrase'],
    simpleDefinition: ['Explained by.', 'Described through.'],
    examples: [
      'Explained in terms of physics.',
      'Described in terms of culture.',
    ],
    synonyms: ['understood as', 'expressed through'],
    antonyms: [],
    shortStory:
      'Flight can be explained in terms of invisible air rivers. Bird watcher Sara mapped thermal currents perfectly, terms proving wings surf silent skies.',
  },
];
