export const PageThreeOfSpokenSingle = [
  {
    audioData: ['/ˌθɪəˈretɪkl/ ', '../../../app_assets/audio/theoretical.mp3'],
    word: 'theoretical',
    meaning: ['Based on theory not practice.', 'Hypothetical.'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Theory-based.', 'Hypothetical.'],
    examples: [
      'Theoretical physics advanced.',
      'Theoretical possibility exists.',
    ],
    synonyms: ['hypothetical', 'abstract'],
    antonyms: ['practical'],
    shortStory:
      "Theoretical equation predicted black hole. Scientist Lena proved math bends reality, theory becoming universe's deepest truth.",
  },
  {
    audioData: ['/θruːˈaʊt/ ', '../../../app_assets/audio/throughout.mp3'],
    word: 'throughout',
    meaning: ['In every part or during whole time.'],
    partOfSpeech: ['preposition', 'adverb'],
    simpleDefinition: ['Everywhere.', 'During whole time.'],
    examples: ['Snow throughout valley.', 'Studied throughout summer.'],
    synonyms: ['everywhere', 'during'],
    antonyms: [],
    shortStory:
      'Loyalty throughout generations preserved secret. Family Kai guarded ancient spring, throughout proving time strengthens sacred trusts.',
  },
  {
    audioData: ['/ˈtəʊtl/ ', '../../../app_assets/audio/total.mp3'],
    word: 'total',
    meaning: ['Complete amount.', 'Absolute.'],
    partOfSpeech: ['noun', 'adjective'],
    simpleDefinition: ['Whole amount.', 'Complete.'],
    examples: ['Total cost 100.', 'Total disaster occurred.'],
    synonyms: ['whole', 'complete', 'sum'],
    antonyms: ['partial'],
    shortStory:
      "Total darkness hid diamond mine. Miner Sara's torch revealed fortune, totality proving greatest treasures hide complete blackness.",
  },
  {
    audioData: ['/trænsˈfɜː(r)/ ', '../../../app_assets/audio/transfer.mp3'],
    word: 'transfer',
    meaning: ['Move from one place to another.', 'Change possession.'],
    partOfSpeech: ['verb', 'noun'],
    simpleDefinition: ['Move.', 'Change owner.'],
    examples: ['Transfer files now.', 'Property transfer complete.'],
    synonyms: ['move', 'shift', 'convey'],
    antonyms: [],
    shortStory:
      "Knowledge transfer saved dying art. Master Zoe taught apprentice final secrets, transfer ensuring beauty outlives master's hands.",
  },
  {
    audioData: [' /traɪ/', '../../../app_assets/audio/try.mp3'],
    word: 'try',
    meaning: ['Attempt to do.', 'Court trial.'],
    partOfSpeech: ['verb', 'noun'],
    simpleDefinition: ['Attempt.', 'Trial.'],
    examples: ['Try harder please.', 'Court try tomorrow.'],
    synonyms: ['attempt', 'test', 'effort'],
    antonyms: ['succeed'],
    shortStory:
      "One try changed loser's destiny. Archer Lena split arrow dead center, single try transforming failure into champion legend.",
  },
  {
    audioData: ['/ˈtjuːtə(r)/ ', '../../../app_assets/audio/tutor.mp3'],
    word: 'tutor',
    meaning: ['Private teacher.', 'To teach privately.'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Private teacher.'],
    examples: ['Hire math tutor.', 'Tutor struggling students.'],
    synonyms: ['teacher', 'coach', 'instruct'],
    antonyms: [],
    shortStory:
      "Village tutor taught kings secretly. Scholar Kai's humble hut birthed emperors, tutoring proving greatest minds mentor from shadows.",
  },
  {
    audioData: ['/ˈtɪpɪkl/ ', '../../../app_assets/audio/typical.mp3'],
    word: 'typical',
    meaning: ['Normal or usual.'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Normal.'],
    examples: ['Typical teenager behavior.', 'Typical rainy season.'],
    synonyms: ['normal', 'usual', 'standard'],
    antonyms: ['unusual'],
    shortStory:
      'Typical day hid extraordinary discovery. Librarian Sara found da Vinci code in return book, typical proving portals to wonder.',
  },
  {
    audioData: ['/ˈtɪpɪkli/ ', '../../../app_assets/audio/typically.mp3'],
    word: 'typically',
    meaning: ['Usually or normally.'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['Usually.'],
    examples: ['Typically arrives late.', 'Typically British weather.'],
    synonyms: ['usually', 'normally'],
    antonyms: ['unusually'],
    shortStory:
      'Typically shy child saved concert. Timid Eli hit perfect finale note, typical reserve hiding stage-shattering talent.',
  },
  {
    audioData: [' /juːst/', '../../../app_assets/audio/used.mp3'],
    word: 'used',
    meaning: ['Previously owned.', 'Employed or utilized.'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Second-hand.', 'Employed.'],
    examples: ['Used car bargain.', 'Used all resources.'],
    synonyms: ['second-hand', 'employed', 'utilized'],
    antonyms: ['new', 'unused'],
    shortStory:
      "Used broomstick flew better than new. Witch Lena's faithful sweeper outraced fancy wands, used proving trusty magic beats shiny.",
  },
  {
    audioData: ['/ˈwelfeə(r)/ ', '../../../app_assets/audio/welfare.mp3'],
    word: 'welfare',
    meaning: ['Well-being or health.', 'Government aid.'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Well-being.', 'Aid.'],
    examples: ['Child welfare priority.', 'Welfare check arrived.'],
    synonyms: ['well-being', 'health', 'assistance'],
    antonyms: [],
    shortStory:
      'Animal welfare changed circus forever. Trainer Raj freed elephants first, welfare proving compassion tames wilder than whips.',
  },
  {
    audioData: ['/əˈkwaɪə(r)/ ', '../../../app_assets/audio/acquire.mp3'],
    word: 'acquire',
    meaning: ['Obtain or gain possession.'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Get.', 'Obtain.'],
    examples: ['Acquire new skills.', 'Acquire company assets.'],
    synonyms: ['obtain', 'gain', 'get'],
    antonyms: ['lose'],
    shortStory:
      'Acquired wisdom trumped royal birthright. Peasant Zoe advised king perfectly, acquisition proving knowledge buys heavier crowns.',
  },
  {
    audioData: ['/əˈdæpt/ ', '../../../app_assets/audio/adapt.mp3'],
    word: 'adapt',
    meaning: ['Adjust to new conditions.', 'Modify.'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Adjust.', 'Change to fit.'],
    examples: ['Adapt to climate.', 'Adapt old recipe.'],
    synonyms: ['adjust', 'modify', 'acclimatize'],
    antonyms: ['resist'],
    shortStory:
      "Adapt or perish faced desert caravan. Trader Lena's tent became boat, adaptation sailing sands where rigid wagons sank.",
  },
  {
    audioData: ['/æd/ ', '../../../app_assets/audio/add.mp3'],
    word: 'add',
    meaning: ['Join one thing to another.', 'Mathematical sum.'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Join.', 'Sum.'],
    examples: ['Add sugar slowly.', 'Add numbers correctly.'],
    synonyms: ['join', 'combine', 'sum'],
    antonyms: ['subtract'],
    shortStory:
      "Single spice added transformed bland stew. Chef Kai's pinch created legend dish, addition proving tiny changes birth greatness.",
  },
  {
    audioData: [' /ˈædʌlt/', '../../../app_assets/audio/adult.mp3'],
    word: 'adult',
    meaning: ['Grown-up person.', 'Mature.'],
    partOfSpeech: ['noun', 'adjective'],
    simpleDefinition: ['Grown-up.'],
    examples: ['Adult supervision needed.', 'Adult decision made.'],
    synonyms: ['grown-up', 'mature', 'grown'],
    antonyms: ['child'],
    shortStory:
      "Adult wisdom learned from child. Elder Sara knelt learning hopscotch joy, adulthood discovering innocence holds life's truest lessons.",
  },
  {
    audioData: ['/əˈfekt/ ', '../../../app_assets/audio/affect.mp3'],
    word: 'affect',
    meaning: ['Influence or change.', 'Show emotion.'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Influence.', 'Pretend feeling.'],
    examples: ['Weather affects mood.', 'Affect sadness poorly.'],
    synonyms: ['influence', 'impact', 'pretend'],
    antonyms: ['ignore'],
    shortStory:
      "Single smile affected entire village mood. Lena's kindness rippled through hearts, affect proving one face brightens darkest days.",
  },
  {
    audioData: ['/ɔːlˈredi/ ', '../../../app_assets/audio/already.mp3'],
    word: 'already',
    meaning: ['Before now or expected time.'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['By now.'],
    examples: ['Dinner already ready.', 'Already finished homework.'],
    synonyms: ['by now', 'previously'],
    antonyms: ['not yet'],
    shortStory:
      'Already champion by age ten. Prodigy Kai dominated chess world, already proving genius ignores calendar years.',
  },
  {
    audioData: ['/ˈɑːnsə(r)/ ', '../../../app_assets/audio/answer.mp3'],
    word: 'answer',
    meaning: ['Reply to question.', 'Solution to problem.'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Reply.', 'Solution.'],
    examples: ['Give correct answer.', 'Answer the phone.'],
    synonyms: ['reply', 'solution', 'respond'],
    antonyms: ['question'],
    shortStory:
      'Perfect answer unlocked ancient vault. Scholar Sara spoke forgotten tongue, answer opening doors sealed for centuries.',
  },
  {
    audioData: ['/əˈraɪz/ ', '../../../app_assets/audio/arise.mp3'],
    word: 'arise',
    meaning: ['Come into being.', 'Get up.'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Begin.', 'Get up.'],
    examples: ['Problems arise daily.', 'Arise early tomorrow.'],
    synonyms: ['emerge', 'occur', 'rise'],
    antonyms: ['end'],
    shortStory:
      'New hope arose from ashes. Villager Lena rebuilt after fire, arise proving phoenix spirit lives every human heart.',
  },
  {
    audioData: ['/ˈɑːtɪkl/ ', '../../../app_assets/audio/article.mp3'],
    word: 'article',
    meaning: ['Piece of writing.', 'Object or item.'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Writing piece.', 'Item.'],
    examples: ['Newspaper article read.', 'Article of clothing.'],
    synonyms: ['essay', 'item', 'piece'],
    antonyms: [],
    shortStory:
      'Single article changed public opinion. Journalist Kai exposed corruption, article proving words wound deeper than swords.',
  },
  {
    audioData: ['/əˈtæk/ ', '../../../app_assets/audio/attack.mp3'],
    word: 'attack',
    meaning: ['Violent assault.', 'Criticize strongly.'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Assault.', 'Criticize.'],
    examples: ['Enemy attack launched.', 'Attack bad policy.'],
    synonyms: ['assault', 'criticize', 'strike'],
    antonyms: ['defend'],
    shortStory:
      'Surprise attack repelled by clever child. Little Zoe rolled logs downhill, attack turning defense into legendary victory.',
  },
  {
    audioData: ['/əˈtenʃn/ ', '../../../app_assets/audio/attention.mp3'],
    word: 'attention',
    meaning: ['Notice or concentration.', 'Military command.'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Focus.', 'Notice.'],
    examples: ['Pay attention class.', 'Attention soldiers stand.'],
    synonyms: ['focus', 'notice', 'concentration'],
    antonyms: ['ignore'],
    shortStory:
      'One detail caught attention changed history. Detective Lena spotted clue everyone missed, attention proving microscope to genius.',
  },
  {
    audioData: ['/ˈɔːθə(r)/ ', '../../../app_assets/audio/author.mp3'],
    word: 'author',
    meaning: ['Writer of book.', 'Creator of work.'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Writer.', 'Creator.'],
    examples: ['Famous author signs.', 'Author new method.'],
    synonyms: ['writer', 'creator'],
    antonyms: [],
    shortStory:
      "Unknown author penned world-changing manifesto. Words spread revolution fire, authorship proving mightier than king's scepter.",
  },
  {
    audioData: ['/əˈvɔɪd/ ', '../../../app_assets/audio/avoid.mp3'],
    word: 'avoid',
    meaning: ['Keep away from.', 'Prevent happening.'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Stay away.', 'Prevent.'],
    examples: ['Avoid dark alley.', 'Avoid making mistake.'],
    synonyms: ['evade', 'prevent', 'shun'],
    antonyms: ['face'],
    shortStory:
      "Avoided certain death through quick thinking. Climber Sara sidestepped avalanche, avoidance carving legend from mountain's deadly breath.",
  },
  {
    audioData: ['/ˈbæləns/ ', '../../../app_assets/audio/balance.mp3'],
    word: 'balance',
    meaning: ['Even distribution.', 'Remain steady.'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Even weight.', 'Stay steady.'],
    examples: ['Perfect balance achieved.', 'Balance on tightrope.'],
    synonyms: ['equilibrium', 'stability', 'even'],
    antonyms: ['imbalance'],
    shortStory:
      "Perfect balance saved circus from disaster. Acrobat Kai caught falling partner mid-air, balance weaving miracle from gravity's jaws.",
  },
  {
    audioData: ['/bɪˈheɪv/ ', '../../../app_assets/audio/behave.mp3'],
    word: 'behave',
    meaning: ['Act in proper way.', 'Conduct oneself.'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Act properly.'],
    examples: ['Behave in class.', 'Children behave well.'],
    synonyms: ['act', 'conduct'],
    antonyms: ['misbehave'],
    shortStory:
      'Behaved like king though peasant born. Prince Eli earned throne through character, behavior proving crown fits soul not birth.',
  },
  {
    audioData: ['/ˈbenɪfɪt/ ', '../../../app_assets/audio/benefit.mp3'],
    word: 'benefit',
    meaning: ['Advantage or help.', 'Receive good.'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Advantage.', 'Help.'],
    examples: ['Health benefit great.', 'Benefit from advice.'],
    synonyms: ['advantage', 'gain', 'help'],
    antonyms: ['harm'],
    shortStory:
      "Shared harvest benefited entire village. Farmer Lena's generosity doubled yield next year, benefit proving kindness fertile as soil.",
  },
  {
    audioData: ['/bɪˈjɒnd/ ', '../../../app_assets/audio/beyond.mp3'],
    word: 'beyond',
    meaning: ['Further than.', 'Outside limits.'],
    partOfSpeech: ['preposition'],
    simpleDefinition: ['Further.', 'Outside.'],
    examples: ['Beyond help now.', 'Beyond imagination wild.'],
    synonyms: ['past', 'outside'],
    antonyms: ['within'],
    shortStory:
      "Beyond map's edge waited paradise. Explorer Sara discovered Eden, beyond proving greatest adventures hide where 'here be dragons'.",
  },
  {
    audioData: ['/brɔːd/ ', '../../../app_assets/audio/broad.mp3'],
    word: 'broad',
    meaning: ['Wide or large.', 'General not specific.'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Wide.', 'General.'],
    examples: ['Broad river crossed.', 'Broad understanding gained.'],
    synonyms: ['wide', 'general', 'vast'],
    antonyms: ['narrow'],
    shortStory:
      'Broad shoulders carried village hopes. Giant Lena bridged canyon alone, breadth proving single strong back lifts entire communities.',
  },
  {
    audioData: ['/ˈsentə(r)/ ', '../../../app_assets/audio/centre.mp3'],
    word: 'centre',
    meaning: ['Middle point.', 'Main focus.'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Middle.', 'Focus.'],
    examples: ['Town centre busy.', 'Centre discussion around.'],
    synonyms: ['middle', 'focus', 'heart'],
    antonyms: ['edge'],
    shortStory:
      'Village centre tree whispered ancient wisdom. Elder Kai listened daily, centre proving where roots deepest, secrets surface clearest.',
  },

  {
    audioData: ['/ˈsɜːkəmstəns/,  ', '../../../app_assets/audio/circumstance.mp3'],
    word: 'circumstance',
    meaning: ['Situation or condition.', 'External conditions affecting.'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Situation.', 'Conditions.'],
    examples: ['Under normal circumstance.', 'Circumstance changed plans.'],
    synonyms: ['situation', 'condition', 'context'],
    antonyms: [],
    shortStory:
      'Harsh circumstance forged unbreakable spirit. Orphan Lena built empire from nothing, circumstance proving adversity births greatest triumphs.',
  },
  {
    audioData: ['/klɪə(r)/ ', '../../../app_assets/audio/clear.mp3'],
    word: 'clear',
    meaning: ['Easy to understand.', 'Free from obstruction.'],
    partOfSpeech: ['adjective', 'verb'],
    simpleDefinition: ['Obvious.', 'Remove block.'],
    examples: ['Clear explanation given.', 'Clear the table.'],
    synonyms: ['obvious', 'transparent', 'remove'],
    antonyms: ['unclear', 'block'],
    shortStory:
      'Clear vision through storm saved ship. Captain Kai spotted reef barely visible, clarity turning disaster into safe harbor.',
  },
  {
    audioData: ['/ˈkləʊsli/ ', '../../../app_assets/audio/closely.mp3'],
    word: 'closely',
    meaning: ['Very near or carefully.'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['Carefully.', 'Near.'],
    examples: ['Watch closely now.', 'Work closely together.'],
    synonyms: ['carefully', 'nearby'],
    antonyms: ['loosely'],
    shortStory:
      'Closely examined painting revealed hidden signature. Curator Sara authenticated masterpiece, close scrutiny proving devil hides in details.',
  },
  {
    audioData: ['/kəʊd/ ', '../../../app_assets/audio/code.mp3'],
    word: 'code',
    meaning: ['System of symbols.', 'Programming instructions.'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Symbols system.', 'Program.'],
    examples: ['Morse code message.', 'Code new app.'],
    synonyms: ['cipher', 'program'],
    antonyms: [],
    shortStory:
      'Cracked enemy code won battle. Spy Lena decoded plans overnight, code-breaking turning certain defeat into glorious victory.',
  },
  {
    audioData: ['/kəmˈbaɪn/ ', '../../../app_assets/audio/combine.mp3'],
    word: 'combine',
    meaning: ['Join together.', 'Mix ingredients.'],
    partOfSpeech: ['verb', 'noun'],
    simpleDefinition: ['Join.', 'Mix.'],
    examples: ['Combine forces now.', 'Combine flour and eggs.'],
    synonyms: ['join', 'mix', 'unite'],
    antonyms: ['separate'],
    shortStory:
      'Combined unlikely allies defeated giant. Farmer Kai and scholar united strengths, combination proving unity crushes strongest foes.',
  },
  {
    audioData: ['/ˈkɒnsntreɪt/ ', '../../../app_assets/audio/concentrate.mp3'],
    word: 'concentrate',
    meaning: ['Focus attention.', 'Gather together.'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Focus.', 'Gather.'],
    examples: ['Concentrate on task.', 'Concentrate troops here.'],
    synonyms: ['focus', 'gather'],
    antonyms: ['distract'],
    shortStory:
      "Concentrated study unlocked genius. Student Zoe mastered quantum physics alone, concentration proving mind's greatest superpower.",
  },
  {
    audioData: ['/kənˈkluːd/ ', '../../../app_assets/audio/conclude.mp3'],
    word: 'conclude',
    meaning: ['Bring to end.', 'Form opinion.'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['End.', 'Decide.'],
    examples: ['Conclude meeting now.', "Conclude he's guilty."],
    synonyms: ['end', 'decide', 'finish'],
    antonyms: ['begin'],
    shortStory:
      "Concluded peace treaty after war. Diplomat Lena's wisdom ended bloodshed, conclusion proving words heal deeper than swords.",
  },
  {
    audioData: ['/kənˈsɪdə(r)/ ', '../../../app_assets/audio/consider.mp3'],
    word: 'consider',
    meaning: ['Think about carefully.'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Think about.'],
    examples: ['Consider all options.', 'Consider him friend.'],
    synonyms: ['think', 'ponder', 'regard'],
    antonyms: ['ignore'],
    shortStory:
      'Considered every angle before leap. Climber Sara chose perfect route, consideration turning impossible ascent into textbook triumph.',
  },
  {
    audioData: ['/ˈkɒntent/ ', '../../../app_assets/audio/content.mp3'],
    word: 'content',
    meaning: ['Satisfied state.', 'Information contained.'],
    partOfSpeech: ['noun', 'adjective'],
    simpleDefinition: ['Satisfied.', 'Information.'],
    examples: ['Happy with content.', 'Website content rich.'],
    synonyms: ['satisfied', 'material'],
    antonyms: ['dissatisfied'],
    shortStory:
      'Content with simple life discovered treasure. Shepherd Kai found cave gold accidentally, contentment proving attracts greatest fortunes.',
  },
  {
    audioData: ['/diːl/ ', '../../../app_assets/audio/deal.mp3'],
    word: 'deal',
    meaning: ['Agreement or arrangement.', 'Distribute.'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Agreement.', 'Distribute.'],
    examples: ['Good deal offered.', 'Deal the cards.'],
    synonyms: ['agreement', 'distribute'],
    antonyms: [],
    shortStory:
      'Fair deal united warring tribes. Merchant Lena traded peace for spices, deal proving commerce builds bridges stronger than armies.',
  },
  {
    audioData: ['/dɪˈklaɪn/ ', '../../../app_assets/audio/decline.mp3'],
    word: 'decline',
    meaning: ['Refuse politely.', 'Become less.'],
    partOfSpeech: ['verb', 'noun'],
    simpleDefinition: ['Refuse.', 'Decrease.'],
    examples: ['Decline invitation please.', 'Decline in sales.'],
    synonyms: ['refuse', 'decrease'],
    antonyms: ['accept', 'increase'],
    shortStory:
      "Declined king's riches chose freedom. Peasant Zoe walked away loaded, decline proving true wealth weighs lightest on soul.",
  },
  {
    audioData: ['/dɪˈpɑːtmənt/ ', '../../../app_assets/audio/department.mp3'],
    word: 'department',
    meaning: ['Division of organization.', 'Area of study.'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Division.', 'Study area.'],
    examples: ['HR department hiring.', 'Physics department lab.'],
    synonyms: ['division', 'section', 'faculty'],
    antonyms: [],
    shortStory:
      'Janitor from maintenance department solved equation. Eli understood patterns others missed, department proving genius ignores job titles.',
  },
  {
    audioData: ['/dɪˈskrɪpʃn/ ', '../../../app_assets/audio/description.mp3'],
    word: 'description',
    meaning: ['Account giving details.'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Detail account.'],
    examples: ['Detailed description needed.', 'Vivid description painted.'],
    synonyms: ['account', 'explanation'],
    antonyms: [],
    shortStory:
      'Perfect description captured unicorn sighting. Witness Sara convinced scientists, description making mythical creatures walk among facts.',
  },
  {
    audioData: ['/dɪˈstrɔɪ/ ', '../../../app_assets/audio/destroy.mp3'],
    word: 'destroy',
    meaning: ['Completely ruin.', 'Demolish.'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Ruin.', 'Demolish.'],
    examples: ['Fire destroyed house.', 'Destroy enemy plans.'],
    synonyms: ['ruin', 'demolish'],
    antonyms: ['build'],
    shortStory:
      'Destroyed village rebuilt stronger than steel. Survivor Lena led reconstruction, destruction proving best foundation for unbreakable futures.',
  },
  {
    audioData: ['/ˈdɪfə(r)/ ', '../../../app_assets/audio/differ.mp3'],
    word: 'differ',
    meaning: ['Be different or disagree.'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Disagree.', 'Be different.'],
    examples: ['Opinions differ greatly.', 'They differ on price.'],
    synonyms: ['disagree', 'vary'],
    antonyms: ['agree'],
    shortStory:
      'Differing opinions birthed breakthrough. Scientists Kai and Zoe debated to discovery, difference proving sparks ignite greatest innovations.',
  },
  {
    audioData: ['/dɪˈskʌvə(r)/ ', '../../../app_assets/audio/discover.mp3'],
    word: 'discover',
    meaning: ['Find something new or unexpected.'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Find.'],
    examples: ['Discover new species.', 'Discover hidden talent.'],
    synonyms: ['find', 'uncover'],
    antonyms: ['lose'],
    shortStory:
      "Discovered ancient city beneath vineyard. Farmer Sara unearthed Rome's lost sister, discovery rewriting history textbooks overnight.",
  },
  {
    audioData: ['/ˈiːzəli/ ', '../../../app_assets/audio/easily.mp3'],
    word: 'easily',
    meaning: ['Without difficulty.', 'Very likely.'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['Simply.', 'Readily.'],
    examples: ['Solved easily now.', 'Easily best choice.'],
    synonyms: ['simply', 'readily'],
    antonyms: ['difficultly'],
    shortStory:
      "Easily dismissed idea changed world. Inventor Lena's 'crazy' wheel revolutionized travel, ease proving genius hides obvious solutions.",
  },
  {
    audioData: ['/end/ ', '../../../app_assets/audio/end.mp3'],
    word: 'end',
    meaning: ['Final part or conclusion.', 'To finish or stop.'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Finish.', 'Conclusion.'],
    examples: ['Movie end credits.', 'End the discussion.'],
    synonyms: ['finish', 'conclusion', 'stop'],
    antonyms: ['beginning', 'start'],
    shortStory:
      "Journey's end revealed starting truth. Traveler Lena circled globe home, end proving wisdom circles back to simple roots.",
  },
  {
    audioData: ['/ɪnˈtaɪəli/ ', '../../../app_assets/audio/entirely.mp3'],
    word: 'entirely',
    meaning: ['Completely or wholly.'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['Completely.'],
    examples: ['Entirely different opinion.', 'Entirely new approach.'],
    synonyms: ['completely', 'totally', 'wholly'],
    antonyms: ['partly'],
    shortStory:
      'Entirely ordinary rock held diamond heart. Miner Kai cracked surface treasure, entirety proving greatest gems hide plainest shells.',
  },
  {
    audioData: ['/ɪˈsenʃl/ ', '../../../app_assets/audio/essential.mp3'],
    word: 'essential',
    meaning: ['Absolutely necessary.', 'Basic or fundamental.'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Necessary.', 'Basic.'],
    examples: ['Essential supplies packed.', 'Essential amino acids.'],
    synonyms: ['necessary', 'vital', 'basic'],
    antonyms: ['unnecessary'],
    shortStory:
      "Essential single seed fed nation. Farmer Sara's hybrid crop ended famine, essential proving one life sustains millions.",
  },
  {
    audioData: ['/ɪɡˈzæktli/ ', '../../../app_assets/audio/exactly.mp3'],
    word: 'exactly',
    meaning: ['Precisely or just so.', 'No more, no less.'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['Precisely.'],
    examples: ['Exactly right answer.', 'Arrive exactly 5pm.'],
    synonyms: ['precisely', 'accurately'],
    antonyms: ['approximately'],
    shortStory:
      'Exactly right timing saved dynasty. Messenger Zoe delivered treaty midnight hour, exactness preserving peace fragile as dewdrop.',
  },
  {
    audioData: ['/ɪɡˈzæm/ ', '../../../app_assets/audio/exam.mp3'],
    word: 'exam',
    meaning: ['Test of knowledge.', 'Medical examination.'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Test.', 'Check-up.'],
    examples: ['Final exam tomorrow.', 'Annual health exam.'],
    synonyms: ['test', 'quiz', 'checkup'],
    antonyms: [],
    shortStory:
      'Failed exam birthed greatest teacher. Student Kai mastered subject tutoring others, exam proving failure forges finest educators.',
  },
  {
    audioData: ['/ɪkˈsplɔː(r)/ ', '../../../app_assets/audio/explore.mp3'],
    word: 'explore',
    meaning: ['Travel through to learn.', 'Investigate thoroughly.'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Travel discover.', 'Investigate.'],
    examples: ['Explore new continent.', 'Explore career options.'],
    synonyms: ['investigate', 'discover', 'search'],
    antonyms: ['ignore'],
    shortStory:
      'Explore forbidden cave found Atlantis. Adventurer Lena mapped sunken city, exploration rewriting maps humanity thought complete.',
  },
  {
    audioData: ['/feɪl/ ', '../../../app_assets/audio/fail.mp3'],
    word: 'fail',
    meaning: ['Not succeed.', 'Stop working.'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Not succeed.', 'Break.'],
    examples: ["Don't fail now.", 'Engine failed suddenly.'],
    synonyms: ['flop', 'collapse'],
    antonyms: ['succeed'],
    shortStory:
      "Epic fail launched moon mission. Engineer Sara's rocket exploded teaching perfection, failure proving greatest rocket fuel.",
  },
  {
    audioData: ['/faɪnd/ ', '../../../app_assets/audio/find.mp3'],
    word: 'find',
    meaning: ['Discover or locate.', 'Opinion or result.'],
    partOfSpeech: ['verb', 'noun'],
    simpleDefinition: ['Discover.', 'Result.'],
    examples: ['Find lost keys.', 'Research findings published.'],
    synonyms: ['discover', 'locate'],
    antonyms: ['lose'],
    shortStory:
      'Found penny led to fortune. Pauper Kai followed lucky coin to vault, finding proving small beginnings birth vast wealth.',
  },
  {
    audioData: ['/ˌfʌndəˈmentl/ ', '../../../app_assets/audio/fundamental.mp3'],
    word: 'fundamental',
    meaning: ['Basic principle.', 'Essential part.'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Basic.', 'Essential.'],
    examples: ['Fundamental human rights.', 'Fundamental math concepts.'],
    synonyms: ['basic', 'essential', 'primary'],
    antonyms: ['secondary'],
    shortStory:
      'Fundamental flaw fixed changed history. Architect Lena reinforced single beam, fundamental proving one right angle saves civilizations.',
  },
  {
    audioData: [' /ɡrəʊ/', '../../../app_assets/audio/grow.mp3'],
    word: 'grow',
    meaning: ['Increase in size.', 'Develop or cultivate.'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Get bigger.', 'Develop.'],
    examples: ['Plants grow quickly.', 'Business grows rapidly.'],
    synonyms: ['expand', 'develop', 'cultivate'],
    antonyms: ['shrink'],
    shortStory:
      'Grow from seed to skyscraper. Entrepreneur Zoe built empire single idea, growth proving tallest towers spring tiniest roots.',
  },
  {
    audioData: ['/ˈhəʊpfəli/ ', '../../../app_assets/audio/hopefully.mp3'],
    word: 'hopefully',
    meaning: ['With hope or expectation.'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['With hope.'],
    examples: ['Hopefully passes test.', 'Hopefully rain tomorrow.'],
    synonyms: ['optimistically'],
    antonyms: ['hopelessly'],
    shortStory:
      "Hopefully whispered prayer answered spectacularly. Widow Lena found golden goose egg, hope proving louder than despair's darkest nights.",
  },
  {
    audioData: ['/aɪˈdentɪfaɪ/ ', '../../../app_assets/audio/identify.mp3'],
    word: 'identify',
    meaning: ['Recognize or name.', 'Associate oneself.'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Recognize.', 'Name.'],
    examples: ['Identify the suspect.', 'Identify with heroes.'],
    synonyms: ['recognize', 'name'],
    antonyms: ['confuse'],
    shortStory:
      'Identified single clue solved century mystery. Detective Sara spotted rare flower petal, identification turning cold case to legend.',
  },
  {
    audioData: ['/ɪmˈplaɪ/ ', '../../../app_assets/audio/imply.mp3'],
    word: 'imply',
    meaning: ['Suggest indirectly.', 'Indicate without stating.'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Hint.', 'Suggest.'],
    examples: ['Her silence implied agreement.', 'Statistics imply trend.'],
    synonyms: ['hint', 'suggest'],
    antonyms: ['state'],
    shortStory:
      "Implied threat silenced entire court. Warrior Lena's single glance spoke volumes, implication proving sharper sword than steel.",
  },
  {
    audioData: ['/ɪnˈkriːsɪŋli/ ', '../../../app_assets/audio/increasingly.mp3'],
    word: 'increasingly',
    meaning: ['More and more.', 'Growing in degree.'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['More and more.'],
    examples: ['Increasingly popular trend.', 'Increasingly difficult task.'],
    synonyms: ['growing', 'ever more'],
    antonyms: ['decreasingly'],
    shortStory:
      'Increasingly strange lights signaled invasion. Watchman Kai alerted kingdom timely, increasing vigilance saving realm from silent conquest.',
  },
  {
    audioData: ['/ɪnˈdiːd/ ', '../../../app_assets/audio/indeed.mp3'],
    word: 'indeed',
    meaning: ['In truth or really.', 'Used for emphasis.'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['Truly.', 'Really.'],
    examples: ['Indeed very tired.', 'Beautiful indeed scenery.'],
    synonyms: ['truly', 'really'],
    antonyms: [],
    shortStory:
      'Indeed ordinary librarian held extraordinary secret. Sara catalogued alien artifacts, indeed proving greatest mysteries hide plainest shelves.',
  },
  {
    audioData: [' /ɪˈnɪʃl/', '../../../app_assets/audio/initial.mp3'],
    word: 'initial',
    meaning: ['First or beginning.', 'Early stage.'],
    partOfSpeech: ['adjective', 'noun'],
    simpleDefinition: ['First.', 'Early.'],
    examples: ['Initial reaction surprise.', 'Sign your initials.'],
    synonyms: ['first', 'beginning', 'preliminary'],
    antonyms: ['final'],
    shortStory:
      'Initial mistake led greatest discovery. Chemist Lena spilled compound creating superconductor, initial error birthing scientific revolution.',
  },
  {
    audioData: ['/ɪnˈtɜːprət/ ', '../../../app_assets/audio/interpret.mp3'],
    word: 'interpret',
    meaning: ['Explain meaning.', 'Translate or understand.'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Explain.', 'Understand.'],
    examples: ['Interpret the data.', 'Interpret ancient script.'],
    synonyms: ['explain', 'translate'],
    antonyms: ['misinterpret'],
    shortStory:
      'Interpreted stars correctly predicted eclipse. Ancient Sara saved village panic, interpretation turning celestial fear into communal awe.',
  },
  {
    audioData: ['/ɪnˈvɒlvd/ ', '../../../app_assets/audio/involved.mp3'],
    word: 'involved',
    meaning: ['Participating or included.', 'Complicated.'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Participating.', 'Complicated.'],
    examples: ['Involved in project.', 'Very involved process.'],
    synonyms: ['participating', 'complicated'],
    antonyms: ['uninvolved', 'simple'],
    shortStory:
      'Deeply involved detective cracked impossible case. Inspector Kai connected thousand clues, involvement proving obsession solves unsolvable.',
  },
  {
    audioData: ['/ˈleɪbl/ ', '../../../app_assets/audio/label.mp3'],
    word: 'label',
    meaning: ['Tag or name identifying.', 'Classify or categorize.'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Tag.', 'Classify.'],
    examples: ['Read nutrition label.', 'Label jars clearly.'],
    synonyms: ['tag', 'name', 'classify'],
    antonyms: [],
    shortStory:
      'Wrong label hid priceless artifact. Curator Lena reclassified pottery as Mayan treasure, label proving single word buries history.',
  },
  {
    audioData: ['/ˈlɪmɪtɪd/ ', '../../../app_assets/audio/limited.mp3'],
    word: 'limited',
    meaning: ['Restricted in amount.', 'Not widespread.'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Restricted.', 'Small amount.'],
    examples: ['Limited seats available.', 'Limited success gained.'],
    synonyms: ['restricted', 'scarce'],
    antonyms: ['unlimited'],
    shortStory:
      'Limited resources built unlimited empire. Trader Kai bartered wisely, limitation forging creativity sharper than endless wealth.',
  },
  {
    audioData: ['/lɪŋk/ ', '../../../app_assets/audio/link.mp3'],
    word: 'link',
    meaning: ['Connection between things.', 'Web hyperlink.'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Connection.', 'Join.'],
    examples: ['Missing link found.', 'Link arms together.'],
    synonyms: ['connection', 'join', 'bond'],
    antonyms: ['separate'],
    shortStory:
      "Single link connected ancient civilizations. Archaeologist Sara traced bead trade route, link weaving humanity's shared story.",
  },
  {
    audioData: ['/meɪnˈteɪn/ ', '../../../app_assets/audio/maintain.mp3'],
    word: 'maintain',
    meaning: ['Keep in condition.', 'Continue or preserve.'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Keep up.', 'Preserve.'],
    examples: ['Maintain garden daily.', 'Maintain good posture.'],
    synonyms: ['keep', 'preserve', 'sustain'],
    antonyms: ['neglect'],
    shortStory:
      "Maintained ancient tradition saved culture. Elder Lena taught chants unbroken, maintenance proving time's strongest enemy yields to persistence.",
  },
  {
    audioData: ['/məˈdʒɒrəti/ ', '../../../app_assets/audio/majority.mp3'],
    word: 'majority',
    meaning: ['Most of group.', 'Greater number.'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Most.', 'Greater part.'],
    examples: ['Majority voted yes.', 'Majority opinion prevails.'],
    synonyms: ['most', 'bulk'],
    antonyms: ['minority'],
    shortStory:
      "Minority voice swayed majority vote. Wise child Zoe convinced elders, majority proving numbers bow to truth's quiet strength.",
  },
  {
    audioData: ['/ˈmeni/ ', '../../../app_assets/audio/many.mp3'],
    word: 'many',
    meaning: ['Large number of.', 'A lot.'],
    partOfSpeech: ['determiner', 'pronoun'],
    simpleDefinition: ['Lots.', 'Numerous.'],
    examples: ['Many people attended.', 'Many thanks given.'],
    synonyms: ['numerous', 'several'],
    antonyms: ['few'],
    shortStory:
      'Many hands built cathedral quickly. Village united stone by stone, many proving collective strength towers over solo genius.',
  },
  {
    audioData: ['/ˈmentl/ ', '../../../app_assets/audio/mental.mp3'],
    word: 'mental',
    meaning: ['Related to mind.', 'Psychological.'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Mind-related.'],
    examples: ['Mental arithmetic fast.', 'Mental health important.'],
    synonyms: ['psychological', 'intellectual'],
    antonyms: ['physical'],
    shortStory:
      'Mental calculation beat computer. Math prodigy Kai solved equations instantly, mentality proving human brain outpaces silicon every time.',
  },
  {
    audioData: ['/ˈməʊmənt/ ', '../../../app_assets/audio/moment.mp3'],
    word: 'moment',
    meaning: ['Very short time.', 'Important point.'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Short time.', 'Key instant.'],
    examples: ['Wait moment please.', 'Moment of truth now.'],
    synonyms: ['instant', 'second'],
    antonyms: [],
    shortStory:
      "Single moment changed world forever. Photographer Lena captured war's horror perfectly, moment freezing history's turning point eternally.",
  },
  {
    audioData: ['/ˌməʊtɪˈveɪʃn/ ', '../../../app_assets/audio/motivation.mp3'],
    word: 'motivation',
    meaning: ['Reason for acting.', 'Enthusiasm drive.'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Drive.', 'Reason.'],
    examples: ['Strong motivation needed.', 'Find motivation daily.'],
    synonyms: ['drive', 'incentive'],
    antonyms: ['apathy'],
    shortStory:
      "Lost motivation found in child's smile. Depressed artist Sara painted masterpiece, motivation proving tiny sparks reignite greatest fires.",
  },
  {
    audioData: ['/ˌnevəðəˈles/ ', '../../../app_assets/audio/nevertheless.mp3'],
    word: 'nevertheless',
    meaning: ['In spite of that.'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['However.'],
    examples: ['Rainy, nevertheless went.', 'Failed, nevertheless tried.'],
    synonyms: ['however', 'yet'],
    antonyms: [],
    shortStory:
      "Nevertheless persisted through rejection. Author Lena's 99th publisher accepted manuscript, nevertheless proving endurance writes greatest success stories.",
  },
  {
    audioData: ['/ˈɒpʃn/ ', '../../../app_assets/audio/option.mp3'],
    word: 'option',
    meaning: ['Choice available.', 'Alternative.'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Choice.'],
    examples: ['Three options remain.', 'Consider all options.'],
    synonyms: ['choice', 'alternative'],
    antonyms: [],
    shortStory:
      'No options left chose impossible path. Climber Kai free-soloed sheer cliff, option-less proving desperation births boldest innovations.',
  },
  {
    audioData: [' /ˌɔːɡənaɪˈzeɪʃn/', '../../../app_assets/audio/organization.mp3'],
    word: 'organization',
    meaning: ['Structured group.', 'Arrangement system.'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Group.', 'System.'],
    examples: ['Join organization now.', 'Poor organization failed.'],
    synonyms: ['group', 'company', 'system'],
    antonyms: ['chaos'],
    shortStory:
      'Perfect organization turned chaos symphony. Conductor Zoe aligned hundred musicians flawlessly, organization proving harmony hides in disciplined patterns.',
  },
  {
    audioData: ['/ˈpɑːtli/ ', '../../../app_assets/audio/partly.mp3'],
    word: 'partly',
    meaning: ['To some degree.', 'Not completely.'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['Somewhat.'],
    examples: ['Partly cloudy skies.', 'Partly responsible too.'],
    synonyms: ['somewhat', 'partially'],
    antonyms: ['completely'],
    shortStory:
      'Partly blind sculptor carved perfect faces. Artist Lena felt beauty through touch, partial sight proving deeper vision than perfect eyes.',
  },
  {
    audioData: ['/pəˈfɔːm/ ', '../../../app_assets/audio/perform.mp3'],
    word: 'perform',
    meaning: ['Carry out action.', 'Entertain audience.'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Do.', 'Entertain.'],
    examples: ['Perform surgery now.', 'Perform on stage.'],
    synonyms: ['execute', 'entertain'],
    antonyms: [],
    shortStory:
      'Performed miracle surgery saved king. Village doctor Kai operated candlelight, performance proving skill outshines palace physicians.',
  },
  {
    audioData: ['/pəˈhæps/ ', '../../../app_assets/audio/perhaps.mp3'],
    word: 'perhaps',
    meaning: ['Maybe or possibly.'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['Maybe.'],
    examples: ['Perhaps tomorrow works.', "Perhaps you're right."],
    synonyms: ['maybe', 'possibly'],
    antonyms: ['definitely'],
    shortStory:
      "Perhaps impossible became reality. Engineer Sara built flying machine skeptics mocked, perhaps proving dreamers engineer tomorrow's truths.",
  },
  {
    audioData: [' /ˈpɒpjələ(r)/', '../../../app_assets/audio/popular.mp3'],
    word: 'popular',
    meaning: ['Liked by many people.'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Well-liked.'],
    examples: ['Popular new song.', 'Popular vote winner.'],
    synonyms: ['well-liked', 'famous'],
    antonyms: ['unpopular'],
    shortStory:
      "Unpopular inventor became popular legend. Lena's 'foolish' electric car powered world, popularity proving vision outlives contemporary scorn.",
  },
  {
    audioData: ['/prɪˈsaɪsli/ ', '../../../app_assets/audio/precisely.mp3'],
    word: 'precisely',
    meaning: ['Exactly or accurately.'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['Exactly.'],
    examples: ['Arrive precisely at noon.', 'Hit target precisely.'],
    synonyms: ['exactly', 'accurately'],
    antonyms: ['roughly'],
    shortStory:
      "Precisely timed leap caught falling child. Acrobat Lena snatched toddler mid-air, precision turning circus trick into life's greatest save.",
  },
  {
    audioData: ['/prɪˈfɜː(r)/ ', '../../../app_assets/audio/prefer.mp3'],
    word: 'prefer',
    meaning: ['Like better or choose.'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Like more.'],
    examples: ['Prefer coffee to tea.', 'Students prefer weekends.'],
    synonyms: ['favor', 'choose'],
    antonyms: ['dislike'],
    shortStory:
      'Preferred dangerous path led to treasure. Explorer Kai chose thorny trail over safe road, preference proving risk hides richest rewards.',
  },
  {
    audioData: ['/ˈprəʊɡres/ ', '../../../app_assets/audio/progress.mp3'],
    word: 'progress',
    meaning: ['Forward movement.', 'Improvement.'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Forward.', 'Improvement.'],
    examples: ['Make progress daily.', 'Technology progresses fast.'],
    synonyms: ['advancement', 'development'],
    antonyms: ['regression'],
    shortStory:
      "Slow progress built unbreakable bridge. Engineer Sara's steady spans outlasted hasty rivals, progress proving tortoise beats hare eternally.",
  },
  {
    audioData: ['/pjʊə(r)/ ', '../../../app_assets/audio/pure.mp3'],
    word: 'pure',
    meaning: ['Not mixed.', 'Clean or innocent.'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Clean.', 'Not mixed.'],
    examples: ['Pure gold necklace.', 'Pure heart motive.'],
    synonyms: ['clean', 'innocent'],
    antonyms: ['impure'],
    shortStory:
      "Pure water spring saved desert caravan. Nomad Lena found hidden source, purity proving life's essence flows clearest from deepest stone.",
  },
  {
    audioData: ['/kwəʊt/ ', '../../../app_assets/audio/quote.mp3'],
    word: 'quote',
    meaning: ['Repeat exact words.', 'Price estimate.'],
    partOfSpeech: ['verb', 'noun'],
    simpleDefinition: ['Repeat words.', 'Price.'],
    examples: ['Quote famous saying.', 'Get repair quote.'],
    synonyms: ['cite', 'estimate'],
    antonyms: [],
    shortStory:
      'Perfect quote won debate championship. Student Kai recalled ancient wisdom exactly, quotation proving memorized words slice sharper than fresh ones.',
  },
  {
    audioData: ['/riːtʃ/ ', '../../../app_assets/audio/reach.mp3'],
    word: 'reach',
    meaning: ['Arrive at place.', 'Stretch to touch.'],
    partOfSpeech: ['verb', 'noun'],
    simpleDefinition: ['Arrive.', 'Stretch.'],
    examples: ['Reach summit tomorrow.', 'Out of reach fruit.'],
    synonyms: ['arrive', 'achieve', 'touch'],
    antonyms: ['miss'],
    shortStory:
      'Reached impossible summit alone. Climber Sara touched peak clouds kissed, reach proving human spirit scales any height.',
  },
  {
    audioData: ['/ˌrekəɡˈnɪʃn/ ', '../../../app_assets/audio/recognition.mp3'],
    word: 'recognition',
    meaning: ['Identification or acknowledgment.', 'Appreciation shown.'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Acknowledgment.', 'Appreciation.'],
    examples: ['Voice recognition software.', 'Earn recognition award.'],
    synonyms: ['identification', 'appreciation'],
    antonyms: ['ignorance'],
    shortStory:
      'Instant recognition saved historic building. Architect Lena spotted rare cornerstone, recognition preserving century-old craftsmanship from wrecking ball.',
  },
  {
    audioData: ['/ˈreləvənt/ ', '../../../app_assets/audio/relevant.mp3'],
    word: 'relevant',
    meaning: ['Closely connected or appropriate.'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Appropriate.', 'Related.'],
    examples: ['Relevant experience needed.', 'Relevant facts only.'],
    synonyms: ['appropriate', 'pertinent'],
    antonyms: ['irrelevant'],
    shortStory:
      'Single relevant clue cracked cold case. Detective Kai ignored red herrings perfectly, relevance proving signal cuts through noise.',
  },
  {
    audioData: ['/ˈrʌfli/ ', '../../../app_assets/audio/roughly.mp3'],
    word: 'roughly',
    meaning: ['Approximately.', 'Not smoothly.'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['About.', 'Not smooth.'],
    examples: ['Roughly 100 people.', 'Roughly cut edges.'],
    synonyms: ['approximately', 'crudely'],
    antonyms: ['precisely'],
    shortStory:
      "Roughly drawn map led exactly right. Shepherd Lena's crude sketch hid perfect shortcut, roughness proving destination trumps perfection.",
  },
  {
    audioData: ['  /ˈsɑːmpl/', '../../../app_assets/audio/sample.mp3'],
    word: 'sample',
    meaning: ['Small part representing whole.', 'Test portion.'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Small part.', 'Test.'],
    examples: ['Free sample please.', 'Sample the soup.'],
    synonyms: ['specimen', 'trial', 'taste'],
    antonyms: [],
    shortStory:
      'Tiny sample rock contained universe. Geologist Sara discovered cosmic diamond, sample proving greatest worlds hide smallest fragments.',
  },
  {
    audioData: ['/ˈsekəndli/ ', '../../../app_assets/audio/secondly.mp3'],
    word: 'secondly',
    meaning: ['Used for second point.', 'Second in order.'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['Second point.'],
    examples: ['Firstly eat, secondly sleep.', 'Secondly consider cost.'],
    synonyms: ['second', 'next'],
    antonyms: [],
    shortStory:
      "Secondly mentioned idea proved best. Debater Lena's overlooked point won case, second-place proving diamonds shine after first dazzle fades.",
  },
  {
    audioData: [' /ˈsekʃn/', '../../../app_assets/audio/section.mp3'],
    word: 'section',
    meaning: ['Part or division.', 'Cut piece.'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Part.', 'Divide.'],
    examples: ['Sports section newspaper.', 'Section the cake.'],
    synonyms: ['part', 'division', 'portion'],
    antonyms: [],
    shortStory:
      'Critical section failure spared cathedral. Mason Kai reinforced single pillar perfectly, section proving one strong bone holds skeleton.',
  },
  {
    audioData: ['  /saɪn/ ', '../../../app_assets/audio/sign.mp3'],
    word: 'sign',
    meaning: ['Symbol representing idea.', 'Indication or signal.'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Symbol.', 'Signal.'],
    examples: ['Stop sign ahead.', 'Sign language used.'],
    synonyms: ['symbol', 'indication', 'gesture'],
    antonyms: [],
    shortStory:
      'Faint sign led through endless desert. Nomad Sara followed distant smoke signal, sign proving hope guides where maps fail.',
  },
  {
    audioData: ['/ˌsɪtʃ.uˈeɪ.ʃən/ ', '../../../app_assets/audio/situation.mp3'],
    word: 'situation',
    meaning: ['Set of circumstances.', 'Place and condition.'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Circumstances.', 'Condition.'],
    examples: ['Difficult situation arose.', 'Emergency situation handled.'],
    synonyms: ['circumstance', 'condition', 'position'],
    antonyms: [],
    shortStory:
      'Hopeless situation birthed greatest escape. Prisoner Lena tunneled freedom through rock, situation proving desperation digs deepest.',
  },
  {
    audioData: ['/speɪs/ ', '../../../app_assets/audio/space.mp3'],
    word: 'space',
    meaning: ['Empty area.', 'Universe beyond Earth.'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Empty area.', 'Cosmos.'],
    examples: ['Need more space.', 'Space exploration begins.'],
    synonyms: ['room', 'area', 'cosmos'],
    antonyms: ['crowded'],
    shortStory:
      'Infinite space hid tiny home planet. Astronaut Kai spotted blue marble, space proving our world smallest speck greatest treasure.',
  },
  {
    audioData: ['/splɪt/ ', '../../../app_assets/audio/split.mp3'],
    word: 'split',
    meaning: ['Divide into parts.', 'Break suddenly.'],
    partOfSpeech: ['verb', 'noun'],
    simpleDefinition: ['Divide.', 'Break.'],
    examples: ['Split the bill.', 'Iceberg split loudly.'],
    synonyms: ['divide', 'separate', 'crack'],
    antonyms: ['join'],
    shortStory:
      "Perfect split arrow won tournament. Archer Lena cleaved rival's shaft dead center, split proving precision carves legend.",
  },
  {
    audioData: ['  /ˈsteɪ.bəl/', '../../../app_assets/audio/stable.mp3'],
    word: 'stable',
    meaning: ['Not likely to change.', 'Steady and firm.'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Steady.', 'Firm.'],
    examples: ['Stable condition improving.', 'Stable table wobbles not.'],
    synonyms: ['steady', 'firm', 'secure'],
    antonyms: ['unstable'],
    shortStory:
      "Stable foundation held through earthquake. Builder Sara's deep pilings saved village, stability proving roots outlast surface storms.",
  },
  {
    audioData: [' /streŋθ/', '../../../app_assets/audio/strength.mp3'],
    word: 'strength',
    meaning: ['Power or capacity.', 'Degree of intensity.'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Power.', 'Intensity.'],
    examples: ['Great physical strength.', 'Strength of feeling deep.'],
    synonyms: ['power', 'might', 'intensity'],
    antonyms: ['weakness'],
    shortStory:
      'Greatest strength hid in quiet patience. Farmer Lena outwaited drought, strength proving enduring spirit crushes brute force.',
  },

  {
    audioData: ['/staɪl/ ', '../../../app_assets/audio/style.mp3'],
    word: 'style',
    meaning: ['Manner of doing something.', 'Fashion or distinctive way.'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Manner.', 'Fashion.'],
    examples: ['Unique writing style.', 'Modern style clothing.'],
    synonyms: ['manner', 'fashion', 'approach'],
    antonyms: ['uniformity'],
    shortStory:
      "Distinctive style turned baker into legend. Lena's twisted pretzels charmed kings, style proving one twist conquers blandest competition.",
  },
  {
    audioData: ['/ˈsɪm.bəl/  ', '../../../app_assets/audio/symbol.mp3'],
    word: 'symbol',
    meaning: ['Thing representing idea.', 'Sign or emblem.'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Representation.', 'Sign.'],
    examples: ['Dove symbol peace.', 'National flag symbol.'],
    synonyms: ['sign', 'emblem', 'representation'],
    antonyms: [],
    shortStory:
      'Simple broken chain became freedom symbol. Slave Kai wore it proudly, symbol inspiring generations to shatter iron bonds.',
  },
  {
    audioData: ['/ˈtiː.tʃər/ ', '../../../app_assets/audio/teacher.mp3'],
    word: 'teacher',
    meaning: ['Person who teaches.', 'Instructor or educator.'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Educator.'],
    examples: ['Favorite teacher inspired.', 'Math teacher explains.'],
    synonyms: ['educator', 'instructor'],
    antonyms: ['student'],
    shortStory:
      'Humble teacher shaped emperors secretly. Master Lena taught village children who ruled nations, teaching proving greatest power shapes unseen.',
  },
  {
    audioData: ['/treɪs/ ', '../../../app_assets/audio/trace.mp3'],
    word: 'trace',
    meaning: ['Small remaining amount.', 'Find origin or path.'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Small amount.', 'Track.'],
    examples: ['Trace of evidence.', 'Trace family roots.'],
    synonyms: ['hint', 'track', 'follow'],
    antonyms: [],
    shortStory:
      'Trace footprint solved wilderness mystery. Tracker Sara followed faint prints to lost city, trace proving whispers guide louder than shouts.',
  },
  {
    audioData: ['/trəˈdɪʃ.ən.əl/ ', '../../../app_assets/audio/traditional.mp3'],
    word: 'traditional',
    meaning: ['Following long-established customs.', 'Conventional.'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Customary.', 'Conventional.'],
    examples: ['Traditional wedding ceremony.', 'Traditional medicine works.'],
    synonyms: ['conventional', 'customary'],
    antonyms: ['modern'],
    shortStory:
      "Traditional recipe won modern contest. Grandma Lena's ancient stew outshone chefs, tradition proving timeless taste defeats trendy fads.",
  },
  {
    audioData: ['/triːt/ ', '../../../app_assets/audio/treat.mp3'],
    word: 'treat',
    meaning: ['Behave toward.', 'Special pleasure or reward.'],
    partOfSpeech: ['verb', 'noun'],
    simpleDefinition: ['Behave to.', 'Reward.'],
    examples: ['Treat others kindly.', 'Ice cream treat today.'],
    synonyms: ['behave', 'reward', 'delight'],
    antonyms: ['mistreat'],
    shortStory:
      'Treated stray dog like royalty. Grateful hound found treasure leading Lena to fortune, treatment proving kindness returns golden.',
  },
  {
    audioData: ['/trend/ ', '../../../app_assets/audio/trend.mp3'],
    word: 'trend',
    meaning: ['General direction or pattern.', 'Current fashion.'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Pattern.', 'Fashion.'],
    examples: ['Upward sales trend.', 'Follow fashion trend.'],
    synonyms: ['pattern', 'fashion', 'direction'],
    antonyms: [],
    shortStory:
      'Against trend invested in old tech. Visionary Kai bought vinyl records cheap, trend-defying proving cycles always return.',
  },
  {
    audioData: ['/trʌst/ ', '../../../app_assets/audio/trust.mp3'],
    word: 'trust',
    meaning: ['Belief in reliability.', 'Confidence in someone.'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Confidence.', 'Believe in.'],
    examples: ['Earn public trust.', 'Trust your instincts.'],
    synonyms: ['confidence', 'faith', 'rely'],
    antonyms: ['distrust'],
    shortStory:
      'Blind trust repaid thousandfold. Merchant Lena loaned stranger final coin, trust transforming poverty into prosperous partnership.',
  },
  {
    audioData: ['/ˈʌp.ər/  ', '../../../app_assets/audio/upper.mp3'],
    word: 'upper',
    meaning: ['Higher position.', 'Superior part.'],
    partOfSpeech: ['adjective', 'noun'],
    simpleDefinition: ['Higher.', 'Top part.'],
    examples: ['Upper floor please.', 'Upper class society.'],
    synonyms: ['higher', 'top', 'superior'],
    antonyms: ['lower'],
    shortStory:
      'Upper branches hid sweetest fruit. Climber Sara reached beyond low hanging, upper proving best rewards demand greatest effort.',
  },
  {
    audioData: ['/ˈveə.ri/ ', '../../../app_assets/audio/vary.mp3'],
    word: 'vary',
    meaning: ['Differ or change.', 'Be different.'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Differ.', 'Change.'],
    examples: ['Prices vary daily.', 'Opinions vary widely.'],
    synonyms: ['differ', 'change', 'diversify'],
    antonyms: ['stay'],
    shortStory:
      'Varied routine sparked creativity explosion. Artist Lena mixed mediums wildly, variety proving muse thrives on delicious change.',
  },
  {
    audioData: ['/wɒtˈev.ər/ ', '../../../app_assets/audio/whatever.mp3'],
    word: 'whatever',
    meaning: ['Any thing or amount.', 'No matter what.'],
    partOfSpeech: ['pronoun', 'determiner'],
    simpleDefinition: ['Anything.', 'No matter which.'],
    examples: ['Eat whatever you want.', 'Whatever happens, try.'],
    synonyms: ['anything', 'no matter'],
    antonyms: [],
    shortStory:
      'Whatever path chosen led to glory. Warrior Kai embraced fate fully, whatever proving destiny crowns all who dare journey.',
  },
];
