export const PageFiveOFInitial = [
  {
    audioData: ['/ˈfɔː.məl/ ', '../../app_assets/audio/formal.mp3'],
    word: 'formal',
    meaning: [
      'Done in accordance with rules or convention',
      'Suitable for official occasions',
    ],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Official', 'Proper dress'],
    examples: [
      'Wear formal clothes to the wedding.',
      'Formal letter needs proper format.',
    ],
    synonyms: ['official', 'proper', 'ceremonial'],
    antonyms: ['informal', 'casual'],
    shortStory:
      'The formal dinner required tuxedos and gowns. Nervous hands adjusted ties. Under starlight, strangers became lifelong friends.',
  },
  {
    audioData: [' /ˈfɔː.mər/', '../../app_assets/audio/former.mp3'],
    word: 'former',
    meaning: ['Belonging to a previous time', 'The first of two mentioned'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Previous', 'First one'],
    examples: [
      'My former teacher retired.',
      'Of the two jobs, I prefer the former.',
    ],
    synonyms: ['previous', 'past', 'earlier'],
    antonyms: ['current', 'latter'],
    shortStory:
      'The former champion trained quietly in his garage. Young fighters passed by, never recognizing greatness. Experience waited patiently.',
  },
  {
    audioData: [' /ˈfɔː.tʃən.ət.li/ ', '../../app_assets/audio/fortunately.mp3'],
    word: 'fortunately',
    meaning: ['It is lucky that'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['Luckily'],
    examples: [
      'Fortunately, we caught the last bus.',
      'Fortunately, no one was hurt.',
    ],
    synonyms: ['luckily', 'thankfully'],
    antonyms: ['unfortunately'],
    shortStory:
      'The car broke down miles from help. Fortunately, a passing farmer stopped with tools. Strangers helped strangers under wide skies.',
  },
  {
    audioData: ['/ˈfɔː.tʃuːn/ ', '../../app_assets/audio/fortune.mp3'],
    word: 'fortune',
    meaning: ['Large amount of money', 'Chance or luck'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Wealth', 'Luck'],
    examples: ['He made a fortune in business.', 'Fortune favors the brave.'],
    synonyms: ['wealth', 'luck', 'destiny'],
    antonyms: ['poverty', 'misfortune'],
    shortStory:
      "The cookie held a simple fortune: 'Share your smile.' She did, and doors opened everywhere. Small words changed everything.",
  },
  {
    audioData: ['/ˈfɔː.ti/ ', '../../app_assets/audio/forty.mp3'],
    word: 'forty',
    meaning: ['Number 40'],
    partOfSpeech: ['number'],
    simpleDefinition: ['40'],
    examples: [
      'She celebrated her fortieth birthday.',
      'Forty students passed the exam.',
    ],
    synonyms: [],
    antonyms: [],
    shortStory:
      'At forty, he ran his first marathon. Every step proved age means nothing. The finish line cheered loudest for him.',
  },
  {
    audioData: ['/ˈfɔː.wəd/ ', '../../app_assets/audio/forward.mp3'],
    word: 'forward',
    meaning: ['Towards the front', 'Send something on'],
    partOfSpeech: ['adverb', 'adjective', 'verb'],
    simpleDefinition: ['Ahead', 'Send on'],
    examples: ['Move forward in line.', 'Forward the email to your boss.'],
    synonyms: ['ahead', 'frontward', 'send'],
    antonyms: ['backward', 'keep'],
    shortStory:
      'The shy boy stepped forward during show-and-tell. His model rocket amazed everyone. Confidence grew with every cheer.',
  },
  {
    audioData: ['/faʊnd/ ', '../../app_assets/audio/found.mp3'],
    word: 'found',
    meaning: ['Past tense of find', 'Establish something'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Discovered', 'Started'],
    examples: ['She found her lost keys.', 'They found a charity last year.'],
    synonyms: ['discovered', 'established', 'created'],
    antonyms: ['lost', 'destroyed'],
    shortStory:
      'Lost at sea, they found land at dawn. Palm trees signaled safety. Survival became celebration.',
  },
  {
    audioData: [' /fɔːr/ ', '../../app_assets/audio/four.mp3'],
    word: 'four',
    meaning: ['Number 4'],
    partOfSpeech: ['number'],
    simpleDefinition: ['4'],
    examples: ['Four seasons in a year.', 'I have four brothers.'],
    synonyms: [],
    antonyms: [],
    shortStory:
      'Four friends built a treehouse kingdom. Each brought special skills. Their summer castle lasted through childhood.',
  },
  {
    audioData: ['/ˌfɔːˈtiːn/ ', '../../app_assets/audio/fourteen.mp3'],
    word: 'fourteen',
    meaning: ['Number 14'],
    partOfSpeech: ['number'],
    simpleDefinition: ['14'],
    examples: ["She's fourteen years old.", 'Fourteen players on two teams.'],
    synonyms: [],
    antonyms: [],
    shortStory:
      'At fourteen, she published her first poem. Words flowed from her heart. The world discovered her voice.',
  },
  {
    audioData: [' /fɔːθ/ ', '../../app_assets/audio/fourth.mp3'],
    word: 'fourth',
    meaning: ['Coming after third'],
    partOfSpeech: ['ordinal number'],
    simpleDefinition: ['4th'],
    examples: ['Fourth place still feels good.', 'July Fourth fireworks.'],
    synonyms: [],
    antonyms: [],
    shortStory:
      'Fourth grade brought her first best friend. Shared secrets and laughter filled recess. Childhood memories made in moments.',
  },
  {
    audioData: ['/freɪm/ ', '../../app_assets/audio/frame.mp3'],
    word: 'frame',
    meaning: ['Structure that surrounds', 'Body shape'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Border', 'Body'],
    examples: ['Picture frame on the wall.', 'She has a slender frame.'],
    synonyms: ['border', 'structure', 'body'],
    antonyms: ['destroy', 'fill'],
    shortStory:
      'The empty picture frame waited patiently. Finally, their wedding photo filled it. Memories found their perfect border.',
  },
  {
    audioData: [' /friː/ ', '../../app_assets/audio/free.mp3'],
    word: 'free',
    meaning: ['Not costing money', 'Not imprisoned'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['No cost', 'Not captured'],
    examples: ['Free samples at the store.', 'The bird flew free again.'],
    synonyms: ['gratis', 'liberated', 'unbound'],
    antonyms: ['paid', 'captive'],
    shortStory:
      'Free ice cream drew the longest line. Children laughed with sticky faces. Summer sweetness never tasted better.',
  },
  {
    audioData: ['/ˈfriː.dəm/', '../../app_assets/audio/freedom.mp3'],
    word: 'freedom',
    meaning: ['State of being free'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Liberty'],
    examples: ['Freedom to choose your path.', 'Birds symbolize freedom.'],
    synonyms: ['liberty', 'independence'],
    antonyms: ['slavery', 'captivity'],
    shortStory:
      'The freed elephant trumpeted joyfully. Years in chains forgotten. Wide savanna welcomed her home.',
  },
  {
    audioData: [' /friːz/', '../../app_assets/audio/freeze.mp3'],
    word: 'freeze',
    meaning: ['Turn into ice', 'Stop moving suddenly'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Turn to ice', 'Stop suddenly'],
    examples: ['Water freezes at 32°F.', 'Freeze when you hear the whistle.'],
    synonyms: ['solidify', 'halt', 'stop'],
    antonyms: ['melt', 'move'],
    shortStory:
      'Winter froze the pond solid. Children tested it carefully, then skated all day. Ice became their playground.',
  },
  {
    audioData: [' /ˈfriː.kwən.si/', '../../app_assets/audio/frequency.mp3'],
    word: 'frequency',
    meaning: ['How often something happens', 'Rate of occurrence'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['How often'],
    examples: ['High frequency of storms.', 'Radio frequency 98.5 FM.'],
    synonyms: ['oftenness', 'regularity'],
    antonyms: ['rarity'],
    shortStory:
      'Daily practice increased her piano frequency. Fingers flew across keys. Music became second nature.',
  },
  {
    audioData: ['/ˈfriː.kwənt.li/ ', '../../app_assets/audio/frequently.mp3'],
    word: 'frequently',
    meaning: ['Often'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['Often'],
    examples: ['She frequently visits grandma.', 'Frequently asked questions.'],
    synonyms: ['often', 'regularly'],
    antonyms: ['rarely', 'seldom'],
    shortStory:
      'He frequently walked the beach at dawn. Seashells and peace greeted him daily. Routine became treasure.',
  },
  {
    audioData: [' /freʃ/ ', '../../app_assets/audio/fresh.mp3'],
    word: 'fresh',
    meaning: ['Newly made', 'Clean and pure'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['New', 'Clean'],
    examples: ['Fresh bread smells wonderful.', 'Fresh start every Monday.'],
    synonyms: ['new', 'clean', 'pure'],
    antonyms: ['stale', 'dirty'],
    shortStory:
      "Fresh snow covered the world in silence. Footprints would write today's story. Nature offered blank pages.",
  },
  {
    audioData: [' /ˈfraɪ.deɪ/ ', '../../app_assets/audio/friday.mp3'],
    word: 'Friday',
    meaning: ['Sixth day of the week'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Day before weekend'],
    examples: ["TGIF - Thank God It's Friday!", 'Fish fry every Friday.'],
    synonyms: [],
    antonyms: [],
    shortStory:
      "Friday night lights lit the football field. Cheers echoed through town. Week's hard work celebrated together.",
  },
  {
    audioData: ['/frɪdʒ/ ', '../../app_assets/audio/fridge.mp3'],
    word: 'fridge',
    meaning: ['Household appliance for keeping food cold'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Cold food box'],
    examples: ['Put milk back in the fridge.', 'The fridge hummed softly.'],
    synonyms: ['refrigerator'],
    antonyms: ['oven'],
    shortStory:
      'The fridge light welcomed Mia home each night. Leftovers became midnight adventures. Comfort waited behind every door.',
  },
  {
    audioData: ['/frend/ ', '../../app_assets/audio/friend.mp3'],
    word: 'friend',
    meaning: ['Person you know well and like'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Close companion'],
    examples: [
      'My best friend shares all secrets.',
      'Friends help each other.',
    ],
    synonyms: ['buddy', 'pal', 'companion'],
    antonyms: ['enemy'],
    shortStory:
      'Two friends built a fort from blankets. Flashlights created magic worlds. Childhood lasted all night.',
  },
  {
    audioData: ['/ˈfrend.li/ ', '../../app_assets/audio/friendly.mp3'],
    word: 'friendly',
    meaning: ['Kind and pleasant to others'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Kind', 'Nice'],
    examples: [
      'The friendly dog wagged its tail.',
      'She gave friendly advice.',
    ],
    synonyms: ['kind', 'warm', 'amiable'],
    antonyms: ['unfriendly', 'hostile'],
    shortStory:
      'The friendly neighbor shared fresh cookies. Shy Tim smiled for the first time. Small kindnesses melt ice.',
  },
  {
    audioData: ['/ˈfrend.ʃɪp/ ', '../../app_assets/audio/friendship.mp3'],
    word: 'friendship',
    meaning: ['Close relationship between friends'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Being friends'],
    examples: ['Their friendship lasted decades.', 'Friendship needs trust.'],
    synonyms: ['companionship', 'bond'],
    antonyms: ['enmity'],
    shortStory:
      'Friendship survived distance and time. Reunion hugs lasted minutes. Some bonds never break.',
  },
  {
    audioData: [' /ˈfraɪ.tən/ ', '../../app_assets/audio/frighten.mp3'],
    word: 'frighten',
    meaning: ['Make someone afraid'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Scare'],
    examples: [
      'Loud thunder frightened the baby.',
      "Don't frighten the horses.",
    ],
    synonyms: ['scare', 'alarm'],
    antonyms: ['calm', 'reassure'],
    shortStory:
      'The dark shape frightened the camper. Morning revealed a friendly deer. Fear vanished with sunlight.',
  },
  {
    audioData: [' /ˈfraɪ.tənd/ ', '../../app_assets/audio/frightened.mp3'],
    word: 'frightened',
    meaning: ['Feeling fear'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Scared'],
    examples: ['The frightened child hid.', 'She felt frightened alone.'],
    synonyms: ['scared', 'afraid', 'terrified'],
    antonyms: ['brave', 'calm'],
    shortStory:
      'Frightened by shadows, Sara clutched her teddy. Thunder passed, stars appeared. Courage grows in darkness.',
  },
  {
    audioData: [' /ˈfraɪ.tən.ɪŋ/ ', '../../app_assets/audio/frightening.mp3'],
    word: 'frightening',
    meaning: ['Causing fear'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Scary'],
    examples: ['Frightening storm approached.', 'The movie was frightening.'],
    synonyms: ['scary', 'terrifying'],
    antonyms: ['calm', 'peaceful'],
    shortStory:
      'Frightening winds bent the trees sideways. Family huddled together safely. Storms pass, togetherness remains.',
  },
  {
    audioData: [' /frɒɡ/ ', '../../app_assets/audio/frog.mp3'],
    word: 'frog',
    meaning: ['Small jumping amphibian'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Jumpy green animal'],
    examples: ['The frog jumped into the pond.', 'Frogs croak at night.'],
    synonyms: ['toad'],
    antonyms: [],
    shortStory:
      'The frog prince waited patiently. One kiss changed everything. Fairy tales sometimes come true.',
  },
  {
    audioData: ['  strong /frɒm/ weak /frəm/', '../../app_assets/audio/from.mp3'],
    word: 'from',
    meaning: ['Indicating origin or starting point'],
    partOfSpeech: ['preposition'],
    simpleDefinition: ['Starting place'],
    examples: ['From New York to LA.', 'From Monday to Friday.'],
    synonyms: ['out of'],
    antonyms: ['to'],
    shortStory:
      "From humble beginnings came greatness. Small seeds grow mighty oaks. Origins don't limit destiny.",
  },
  {
    audioData: [' /frʌnt/ ', '../../app_assets/audio/front.mp3'],
    word: 'front',
    meaning: ['Foremost part', 'Opposite of back'],
    partOfSpeech: ['noun', 'adjective'],
    simpleDefinition: ['Forward part'],
    examples: ['Front door of the house.', 'Sit in the front row.'],
    synonyms: ['fore', 'forward'],
    antonyms: ['back', 'rear'],
    shortStory:
      'Front porch swings held summer memories. Lemonade and lightning bugs. Perfect evenings never ended.',
  },
  {
    audioData: ['/ˈfrəʊ.zən/ ', '../../app_assets/audio/frozen.mp3'],
    word: 'frozen',
    meaning: ['Turned into ice', 'Very cold'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Iced over', 'Ice cold'],
    examples: [
      'Frozen lake perfect for skating.',
      'Frozen dinner in microwave.',
    ],
    synonyms: ['icy', 'solidified'],
    antonyms: ['melted', 'thawed'],
    shortStory:
      'Frozen breath hung in winter air. Children built snow forts. Cold created warm memories.',
  },
  {
    audioData: [' /fruːt/ ', '../../app_assets/audio/fruit.mp3'],
    word: 'fruit',
    meaning: ['Sweet plant product', 'Result of action'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Apple, banana', 'Result'],
    examples: ['Fresh fruit for breakfast.', 'Fruit of hard labor.'],
    synonyms: ['produce', 'result'],
    antonyms: ['vegetable'],
    shortStory:
      'Fresh fruit market burst with colors. Childhood favorites tempted everyone. Summer tasted sweetest there.',
  },
  {
    audioData: ['/fraɪ/', '../../app_assets/audio/fry.mp3'],
    word: 'fry',
    meaning: ['Cook in hot oil', 'Young fish'],
    partOfSpeech: ['verb', 'noun'],
    simpleDefinition: ['Cook in oil', 'Baby fish'],
    examples: ['Fry eggs for breakfast.', 'Fish lay thousands of fry.'],
    synonyms: ['sauté', 'young fish'],
    antonyms: ['boil', 'adult fish'],
    shortStory:
      'Fish and chips frying filled the air. Beachside shack served happiness. Crispy perfection every bite.',
  },
  {
    audioData: ['/ˈfjuː.əl/ ', '../../app_assets/audio/fuel.mp3'],
    word: 'fuel',
    meaning: ['Material for burning', 'Power source'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Gas, wood', 'Power'],
    examples: ['Gasoline fuels the car.', 'Kindness fuels good deeds.'],
    synonyms: ['gas', 'energy'],
    antonyms: ['brake'],
    shortStory:
      'Rocket fuel ignited dreams. Countdown echoed across plains. Humanity reached for stars.',
  },
  {
    audioData: ['/fʊl/ ', '../../app_assets/audio/full.mp3'],
    word: 'full',
    meaning: ['Completely filled', 'Complete amount'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Completely filled'],
    examples: ['Full glass of water.', 'Full moon tonight.'],
    synonyms: ['filled', 'complete'],
    antonyms: ['empty'],
    shortStory:
      'Full hearts gathered for farewell. Tears mixed with laughter. Love fills every space.',
  },
  {
    audioData: [' /ˈfʊl.i/ ', '../../app_assets/audio/fully.mp3'],
    word: 'fully',
    meaning: ['Completely', 'Totally'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['Completely'],
    examples: ['Fully understand the problem.', 'Fully grown adult.'],
    synonyms: ['completely', 'totally'],
    antonyms: ['partly'],
    shortStory:
      'Fully recovered, she danced again. Scars told victory stories. Strength rebuilt stronger.',
  },
  {
    audioData: [' /fʌn/ ', '../../app_assets/audio/fun.mp3'],
    word: 'fun',
    meaning: ['Enjoyment', 'Playful activity'],
    partOfSpeech: ['noun', 'adjective'],
    simpleDefinition: ['Enjoyment'],
    examples: ['Picnic was so much fun.', 'Fun games at the party.'],
    synonyms: ['enjoyment', 'amusement'],
    antonyms: ['boredom'],
    shortStory:
      'Fun fair lights twinkled magically. Cotton candy dreams came true. Laughter louder than music.',
  },
  {
    audioData: ['/ˈfʌŋk.ʃən/  ', '../../app_assets/audio/function.mp3'],
    word: 'function',
    meaning: ['Purpose', 'Work properly', 'Math operation'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Purpose', 'Work'],
    examples: ["Heart's main function.", 'Phone stopped functioning.'],
    synonyms: ['purpose', 'operate', 'role'],
    antonyms: ['malfunction'],
    shortStory:
      'Broken watch finally functioned. Timekeeper told perfect stories. Patience fixed everything.',
  },
  {
    audioData: ['/fʌnd/ ', '../../app_assets/audio/fund.mp3'],
    word: 'fund',
    meaning: ['Money for purpose', 'Provide money'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Money supply'],
    examples: ['Emergency fund saved them.', 'Fund new business venture.'],
    synonyms: ['money', 'finance'],
    antonyms: ['spend'],
    shortStory:
      'Small fund grew mighty. Community dream became reality. Pennies built palaces.',
  },
  {
    audioData: [' /ˌfʌn.dəˈmen.təl/', '../../app_assets/audio/fundamental.mp3'],
    word: 'fundamental',
    meaning: ['Basic', 'Essential'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Basic', 'Main'],
    examples: ['Fundamental human rights.', 'Fundamental math skills.'],
    synonyms: ['basic', 'essential'],
    antonyms: ['minor'],
    shortStory:
      'Fundamental kindness changed everything. Simple smile opened doors. Basics build greatness.',
  },
  {
    audioData: ['/ˈfʌn.dɪŋ/ ', '../../app_assets/audio/funding.mp3'],
    word: 'funding',
    meaning: ['Money provided for project'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Project money'],
    examples: ['New funding approved.', 'Research needs more funding.'],
    synonyms: ['financing', 'support'],
    antonyms: ['cuts'],
    shortStory:
      'Funding arrived just in time. Dream school doors opened. Education changed lives forever.',
  },
  {
    audioData: ['/ˈfʌn.i/ ', '../../app_assets/audio/funny.mp3'],
    word: 'funny',
    meaning: ['Causing laughter', 'Strange'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Hilarious', 'Strange'],
    examples: ['Funny joke made everyone laugh.', 'Funny smell in kitchen.'],
    synonyms: ['hilarious', 'odd'],
    antonyms: ['serious', 'normal'],
    shortStory:
      'Funny uncle told silly stories. Dinner table shook with laughter. Family bonds strengthened nightly.',
  },
  {
    audioData: ['/fɜːr/ ', '../../app_assets/audio/fur.mp3'],
    word: 'fur',
    meaning: ['Animal hair', 'Coat made of animal hair'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Animal hair'],
    examples: ['Soft fur kitten purred.', 'Fur coat kept her warm.'],
    synonyms: ['pelt', 'coat'],
    antonyms: ['skin'],
    shortStory:
      "Lost puppy's wet fur dripped. Warm towel and love dried everything. Home found its heart.",
  },
  {
    audioData: ['/ˈfɜː.nɪ.tʃər/ ', '../../app_assets/audio/furniture.mp3'],
    word: 'furniture',
    meaning: [
      'Movable objects used to make a room suitable for living',
      'Articles like chairs, tables, beds',
    ],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Chairs, tables, beds'],
    examples: [
      'New furniture arrived today.',
      'The room needs more furniture.',
    ],
    synonyms: ['furnishings', 'household items'],
    antonyms: ['empty'],
    shortStory:
      'The empty apartment transformed with simple furniture. One chair, one lamp created home. Possessions matter less than heart.',
  },
  {
    audioData: [' /ˈfɜː.ðər/ ', '../../app_assets/audio/further.mp3'],
    word: 'further',
    meaning: [
      'At or to a greater distance',
      'Additional amount',
      'To a greater extent',
    ],
    partOfSpeech: ['adverb', 'adjective'],
    simpleDefinition: ['Farther', 'More'],
    examples: ['Walk further down the road.', 'Further details needed.'],
    synonyms: ['farther', 'additional', 'more'],
    antonyms: ['nearer', 'less'],
    shortStory:
      'Further exploration revealed hidden waterfall. Brave steps led to paradise. Adventure rewards the curious.',
  },
  {
    audioData: ['/ˌfɜː.ðəˈmɔːr/', '../../app_assets/audio/furthermore.mp3'],
    word: 'furthermore',
    meaning: ['In addition', 'Moreover'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['Also'],
    examples: [
      "It's expensive. Furthermore, it's unreliable.",
      'She was late; furthermore, she forgot homework.',
    ],
    synonyms: ['moreover', 'also', 'besides'],
    antonyms: [],
    shortStory:
      'He studied hard. Furthermore, he practiced daily. Success arrived exactly as planned.',
  },
  {
    audioData: ['/ˈfjuː.tʃər/ ', '../../app_assets/audio/future.mp3'],
    word: 'future',
    meaning: ['Time yet to come', 'What will happen later'],
    partOfSpeech: ['noun', 'adjective'],
    simpleDefinition: ['Tomorrow time'],
    examples: ['Plan for your future.', 'Future tense in grammar.'],
    synonyms: ['tomorrow', 'later'],
    antonyms: ['past'],
    shortStory:
      "Future dreams fueled present actions. Small steps built tomorrow's castle. Vision creates reality.",
  },
  {
    audioData: [' /ɡeɪn/ ', '../../app_assets/audio/gain.mp3'],
    word: 'gain',
    meaning: ['Obtain or increase something', 'Get weight or advantage'],
    partOfSpeech: ['verb', 'noun'],
    simpleDefinition: ['Get', 'Increase'],
    examples: ['Gain knowledge from books.', 'She gained five pounds.'],
    synonyms: ['get', 'earn', 'profit'],
    antonyms: ['lose', 'decrease'],
    shortStory:
      'Daily practice gained him mastery. Small steps climbed mountains. Persistence turned dreams real.',
  },
  {
    audioData: ['/ˈɡæl.ər.i/ ', '../../app_assets/audio/gallery.mp3'],
    word: 'gallery',
    meaning: ['Room or building for art display', 'Upper floor in theater'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Art room', 'Theater balcony'],
    examples: ['Visit the art gallery.', 'Tickets in the gallery section.'],
    synonyms: ['museum', 'balcony'],
    antonyms: ['basement'],
    shortStory:
      'Quiet gallery walls whispered stories. Each painting held lifetimes. Visitors left changed forever.',
  },
  {
    audioData: [' /ɡeɪm/ ', '../../app_assets/audio/game.mp3'],
    word: 'game',
    meaning: ['Competitive activity with rules', 'Wild animals hunted'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Play with rules', 'Wild animals'],
    examples: ['Play a board game.', 'Hunters track game.'],
    synonyms: ['sport', 'match', 'prey'],
    antonyms: ['work'],
    shortStory:
      'Game night laughter filled the house. Friends battled Monopoly empires. Victory tasted like popcorn.',
  },
  {
    audioData: ['/ɡæŋ/ ', '../../app_assets/audio/gang.mp3'],
    word: 'gang',
    meaning: ['Group of friends or criminals', 'Work crew'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Group', 'Crew'],
    examples: ['Gang of kids played outside.', 'Road gang fixed potholes.'],
    synonyms: ['group', 'crew', 'band'],
    antonyms: ['individual'],
    shortStory:
      'Neighborhood gang built secret clubhouse. Cardboard castle ruled summer. Friendship forged in forts.',
  },
  {
    audioData: ['/ɡæp/ ', '../../app_assets/audio/gap.mp3'],
    word: 'gap',
    meaning: ['Space between two things', 'Difference'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Space', 'Difference'],
    examples: ['Gap in the fence.', 'Close the generation gap.'],
    synonyms: ['space', 'hole', 'difference'],
    antonyms: ['connection'],
    shortStory:
      'Gap in clouds revealed shooting star. One wish changed everything. Magic slips through cracks.',
  },
  {
    audioData: ['/ˈɡær.ɑːʒ/ /ˈɡær.ɪdʒ/ ', '../../app_assets/audio/garage.mp3'],
    word: 'garage',
    meaning: ['Building for storing cars', 'Repair cars'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Car house', 'Fix cars'],
    examples: ['Park in the garage.', 'Garage needs oil change.'],
    synonyms: ['carport'],
    antonyms: ['driveway'],
    shortStory:
      'Garage sale treasures waited patiently. Old lamp found new home. Stories traveled with junk.',
  },
  {
    audioData: [' /ˈɡɑː.dən/ ', '../../app_assets/audio/garden.mp3'],
    word: 'garden',
    meaning: ['Piece of ground for growing plants'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Flower area'],
    examples: ['Beautiful garden in bloom.', 'Garden vegetables taste best.'],
    synonyms: ['yard', 'plot'],
    antonyms: ['desert'],
    shortStory:
      "Grandma's garden grew magic beans. Tiny seeds became giants. Love watered every root.",
  },
  {
    audioData: [' /ɡæs/ ', '../../app_assets/audio/gas.mp3'],
    word: 'gas',
    meaning: ['Fuel for engines', 'Air like substance'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Car fuel', 'Air form'],
    examples: ['Gas prices rose again.', 'Natural gas heats homes.'],
    synonyms: ['fuel', 'petrol'],
    antonyms: ['solid'],
    shortStory:
      'Gas station became roadside oasis. Road-weary travelers refueled. Hot coffee revived dreams.',
  },
  {
    audioData: ['/ɡeɪt/ ', '../../app_assets/audio/gate.mp3'],
    word: 'gate',
    meaning: ['Door in fence or wall', 'Airport departure point'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Fence door'],
    examples: ['Open the garden gate.', 'Flight leaves gate 12.'],
    synonyms: ['door', 'entrance'],
    antonyms: ['wall'],
    shortStory:
      'Golden gate opened to new world. First step crossed thresholds. Adventure began beyond fences.',
  },
  {
    audioData: [' /ˈɡæð.ər/', '../../app_assets/audio/gather.mp3'],
    word: 'gather',
    meaning: ['Bring together', 'Collect information'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Collect'],
    examples: ['Gather around the fire.', 'Gather facts before deciding.'],
    synonyms: ['collect', 'assemble'],
    antonyms: ['scatter'],
    shortStory:
      'Family gathered for holiday feast. Laughter bridged years apart. Love collected missing pieces.',
  },
  {
    audioData: [' /ˈdʒen.ər.əl/ ', '../../app_assets/audio/general.mp3'],
    word: 'general',
    meaning: ['Affecting all', 'High army officer'],
    partOfSpeech: ['adjective', 'noun'],
    simpleDefinition: ['All', 'Army leader'],
    examples: ['General store sells everything.', 'General led the troops.'],
    synonyms: ['common', 'overall', 'commander'],
    antonyms: ['specific', 'private'],
    shortStory:
      'General store held childhood wonders. Penny candy bought happiness. Small town heart beat there.',
  },
  {
    audioData: ['/ˈdʒen.ə r.əl.i/ ', '../../app_assets/audio/generally.mp3'],
    word: 'generally',
    meaning: ['Usually', 'In most cases'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['Usually'],
    examples: ['Generally happy person.', 'Generally speaking, yes.'],
    synonyms: ['usually', 'normally'],
    antonyms: ['rarely'],
    shortStory:
      'Generally quiet town erupted Friday nights. Football cheers echoed valleys. Tradition trumped tranquility weekly.',
  },
  {
    audioData: ['/ˈdʒen.ə.reɪt/ ', '../../app_assets/audio/generate.mp3'],
    word: 'generate',
    meaning: ['Produce or create'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Make', 'Create'],
    examples: [
      'Solar panels generate electricity.',
      'Ideas generate progress.',
    ],
    synonyms: ['produce', 'create'],
    antonyms: ['destroy'],
    shortStory:
      'Single idea generated movement. Grassroots grew mighty oaks. One spark lights worlds.',
  },
  {
    audioData: ['/ˌdʒen.əˈreɪ.ʃən/ ', '../../app_assets/audio/generation.mp3'],
    word: 'generation',
    meaning: ['All people born same time', 'Single step between grandparents'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Age group'],
    examples: ['Millennial generation.', 'Lost generation wrote classics.'],
    synonyms: ['age group', 'era'],
    antonyms: [],
    shortStory:
      'Generation gap bridged by shared music. Grandparents danced with teens. Rhythm united ages.',
  },
  {
    audioData: ['/ˈdʒen.ər.əs/ ', '../../app_assets/audio/generous.mp3'],
    word: 'generous',
    meaning: ['Giving more than expected', 'Willing to give'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Giving freely'],
    examples: ['Generous tip for good service.', 'Generous with time.'],
    synonyms: ['giving', 'kind'],
    antonyms: ['stingy'],
    shortStory:
      'Generous stranger paid lunch tab. Ripple kindness spread all day. One act multiplied blessings.',
  },
  {
    audioData: [' /ˈʒɑ̃ː.rə/ /ˈʒɒn.rə/', '../../app_assets/audio/genre.mp3'],
    word: 'genre',
    meaning: ['Category of art or literature'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Type'],
    examples: ['Horror genre scares readers.', 'Different music genres.'],
    synonyms: ['category', 'style', 'type'],
    antonyms: [],
    shortStory:
      'Mystery genre pulled her in. Clues led to midnight revelations. Fiction felt real.',
  },
  {
    audioData: [' /ˈdʒen.təl/ ', '../../app_assets/audio/gentle.mp3'],
    word: 'gentle',
    meaning: ['Mild or kind', 'Soft or light'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Kind', 'Soft'],
    examples: ['Gentle breeze cooled summer.', 'Gentle with scared animals.'],
    synonyms: ['kind', 'soft', 'mild'],
    antonyms: ['harsh', 'rough'],
    shortStory:
      'Gentle hands calmed frightened horse. Trust rebuilt stroke by stroke. Patience speaks louder than whips.',
  },
  {
    audioData: ['/ˈdʒen.təl.mən/ ', '../../app_assets/audio/gentleman.mp3'],
    word: 'gentleman',
    meaning: ['Polite well-mannered man'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Polite man'],
    examples: ['Perfect gentleman held door.', 'Gentleman always tips hat.'],
    synonyms: ['gent', 'sir'],
    antonyms: ['cad'],
    shortStory:
      'Gentleman farmer shared first strawberries. Neighbors blessed yearly. Soil grew more than fruit.',
  },
  {
    audioData: [' /dʒiˈɒɡ.rə.fi/', '../../app_assets/audio/geography.mp3'],
    word: 'geography',
    meaning: ["Study of earth's surface"],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Earth study'],
    examples: [
      'Geography class learned capitals.',
      'Mountain geography fascinates.',
    ],
    synonyms: ['earth science'],
    antonyms: [],
    shortStory:
      'Geography shaped their adventures. Maps became treasure hunts. World unfolded page by page.',
  },
  {
    audioData: [' /ɡet/ ', '../../app_assets/audio/get.mp3'],
    word: 'get',
    meaning: ['Receive', 'Become', 'Understand'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Receive'],
    examples: ['Get good grades.', 'Get angry easily.'],
    synonyms: ['receive', 'obtain', 'become'],
    antonyms: ['give', 'lose'],
    shortStory:
      'Get-rich schemes failed spectacularly. Honest work built true wealth. Character compounds better than money.',
  },
  {
    audioData: [' /ɡəʊst/ ', '../../app_assets/audio/ghost.mp3'],
    word: 'ghost',
    meaning: ['Spirit of dead person'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Spirit'],
    examples: ['Ghost haunts old house.', 'Ghost someone on social media.'],
    synonyms: ['spirit', 'phantom', 'ignore'],
    antonyms: ['corpse'],
    shortStory:
      'Friendly ghost helped lost children. Lantern light guided safely home. Spirits watch over us.',
  },
  {
    audioData: ['/ˈdʒaɪ.ənt/ ', '../../app_assets/audio/giant.mp3'],
    word: 'giant',
    meaning: ['Extremely large person', 'Very successful company'],
    partOfSpeech: ['noun', 'adjective'],
    simpleDefinition: ['Very big'],
    examples: ['Giant slayed by clever boy.', 'Tech giant dominates market.'],
    synonyms: ['huge', 'massive', 'titan'],
    antonyms: ['tiny'],
    shortStory:
      'Gentle giant lifted car off child. Strength served kindness. Heroes hide among us.',
  },
  {
    audioData: ['/ɡɪft/ ', '../../app_assets/audio/gift.mp3'],
    word: 'gift',
    meaning: ['Present given', 'Natural talent'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Present', 'Talent'],
    examples: ['Birthday gift surprised her.', 'Gift for music.'],
    synonyms: ['present', 'talent'],
    antonyms: [],
    shortStory:
      "Unwrapped gift revealed family recipe book. Grandmother's handwriting brought tears. Love travels through generations.",
  },
  {
    audioData: ['/ɡɜːl/ ', '../../app_assets/audio/girl.mp3'],
    word: 'girl',
    meaning: ['Young female', 'Daughter'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Young female'],
    examples: ['Little girl loves dolls.', "Daddy's girl always."],
    synonyms: ['lass', 'gal'],
    antonyms: ['boy'],
    shortStory:
      'Girl with kite dreamed big. String broke, dreams flew free. Sky became her playground.',
  },
  {
    audioData: ['/ˈɡɜːl.frend/ ', '../../app_assets/audio/girlfriend.mp3'],
    word: 'girlfriend',
    meaning: ['Female romantic partner', 'Close female friend'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Girl partner'],
    examples: ["Met girlfriend's parents.", 'Bring your girlfriend.'],
    synonyms: ['partner', 'sweetheart'],
    antonyms: ['boyfriend'],
    shortStory:
      "Girlfriend's smile lit rainy days. Shared umbrella, shared dreams. Love finds shelter anywhere.",
  },
  {
    audioData: ['/ɡɪv/ ', '../../app_assets/audio/give.mp3'],
    word: 'give',
    meaning: ['Transfer possession', 'Provide help or information'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Hand over', 'Provide'],
    examples: ['Give me the book.', 'Give good advice.'],
    synonyms: ['hand', 'provide', 'donate'],
    antonyms: ['take', 'receive'],
    shortStory:
      'She gave her last dollar to the homeless man. His grateful smile warmed winter. Kindness costs nothing.',
  },
  {
    audioData: ['/ɡlæd/ ', '../../app_assets/audio/glad.mp3'],
    word: 'glad',
    meaning: ['Pleased or happy'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Happy'],
    examples: ['Glad to see you.', 'Glad it stopped raining.'],
    synonyms: ['happy', 'pleased'],
    antonyms: ['sad'],
    shortStory:
      'Glad tears fell at graduation. Years of work crystallized. Dreams wore caps and gowns.',
  },
  {
    audioData: ['/ɡlɑːs/ ', '../../app_assets/audio/glass.mp3'],
    word: 'glass',
    meaning: ['Hard transparent material', 'Container for drinking'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Clear material', 'Drinking container'],
    examples: ['Glass window broke.', 'Full glass of water.'],
    synonyms: ['crystal', 'tumbler'],
    antonyms: ['plastic'],
    shortStory:
      "Glass slipper fit perfectly. Midnight chime warned magic's end. True love outruns clocks.",
  },
  {
    audioData: [' /ˈɡləʊ.bəl/ ', '../../app_assets/audio/global.mp3'],
    word: 'global',
    meaning: ['Worldwide', 'Affecting the whole world'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Worldwide'],
    examples: [
      'Global warming concerns everyone.',
      'Global economy connects nations.',
    ],
    synonyms: ['worldwide', 'international'],
    antonyms: ['local'],
    shortStory:
      'Global village shrank through screens. Distant cousins waved hello. Technology built family bridges.',
  },
  {
    audioData: [' /ɡlʌv/', '../../app_assets/audio/glove.mp3'],
    word: 'glove',
    meaning: ['Covering for hand'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Hand cover'],
    examples: [
      'Baseball glove caught fly ball.',
      'Winter gloves kept hands warm.',
    ],
    synonyms: ['mitt'],
    antonyms: [],
    shortStory:
      'Lost glove found its match years later. Same bench, same park. Fate reunites pairs.',
  },
  {
    audioData: ['/ɡəʊ/ ', '../../app_assets/audio/go.mp3'],
    word: 'go',
    meaning: ['Move or travel', 'Function properly'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Move'],
    examples: ['Go to school.', "Car won't go."],
    synonyms: ['move', 'travel', 'function'],
    antonyms: ['stop', 'stay'],
    shortStory:
      'Green light said go. Adventure waited beyond intersection. Roads lead to destinies.',
  },
  {
    audioData: [' /ɡəʊl/ ', '../../app_assets/audio/goal.mp3'],
    word: 'goal',
    meaning: ['Aim or purpose', 'Sports scoring'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Aim', 'Score'],
    examples: ['Reach career goal.', 'Soccer goal won match.'],
    synonyms: ['aim', 'target'],
    antonyms: [],
    shortStory:
      'Goal posts moved closer with effort. Daily practice scored victories. Determination shrinks distances.',
  },
  {
    audioData: [' /ɡɒd/', '../../app_assets/audio/god.mp3'],
    word: 'god',
    meaning: ['Supreme being'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Creator'],
    examples: [
      'Thank God for blessings.',
      'God helps those who help themselves.',
    ],
    synonyms: ['deity', 'creator'],
    antonyms: ['devil'],
    shortStory:
      'Quiet prayer found listening ears. Silent storms calmed. Faith speaks without words.',
  },
  {
    audioData: ['/ɡəʊld/', '../../app_assets/audio/gold.mp3'],
    word: 'gold',
    meaning: ['Precious yellow metal', 'First place prize'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Yellow metal', 'First prize'],
    examples: ['Gold wedding ring.', 'Won gold medal.'],
    synonyms: ['precious metal'],
    antonyms: ['silver'],
    shortStory:
      "Gold nugget changed miners' lives. Simple rock built dreams. Value hides in ordinary.",
  },
  {
    audioData: [' /ɡɒlf/ ', '../../app_assets/audio/golf.mp3'],
    word: 'golf',
    meaning: ['Game played on course with clubs'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Club and ball game'],
    examples: ['Play golf every weekend.', 'Golf tournament on TV.'],
    synonyms: [],
    antonyms: [],
    shortStory:
      'Perfect golf swing found inner peace. Fairway became meditation path. Sports teach zen.',
  },
  {
    audioData: ['/ɡʊd/ ', '../../app_assets/audio/good.mp3'],
    word: 'good',
    meaning: ['High quality', 'Morally right'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Nice', 'Right'],
    examples: ['Good grades earned.', 'Good person helps others.'],
    synonyms: ['nice', 'excellent', 'moral'],
    antonyms: ['bad'],
    shortStory:
      'Good deeds multiplied quietly. Community strengthened by invisible hands. Virtue builds silently.',
  },
  {
    audioData: ['/ɡʊdˈbaɪ/ ', '../../app_assets/audio/goodbye.mp3'],
    word: 'goodbye',
    meaning: ['Farewell'],
    partOfSpeech: ['noun', 'interjection'],
    simpleDefinition: ['See you later'],
    examples: ['Say goodbye to friends.', 'Goodbye, see you tomorrow!'],
    synonyms: ['farewell', 'bye'],
    antonyms: ['hello'],
    shortStory:
      'Goodbye waves hid brave tears. New school awaited. Fresh starts hide hellos.',
  },
  {
    audioData: ['/ɡʊdz/ ', '../../app_assets/audio/goods.mp3'],
    word: 'goods',
    meaning: ['Products for sale', 'Possessions'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Things for sale'],
    examples: ['Goods arrived by truck.', 'Stolen goods recovered.'],
    synonyms: ['merchandise', 'products'],
    antonyms: [],
    shortStory:
      'Market goods traded stories too. Spices carried ancient routes. Commerce weaves cultures.',
  },
  {
    audioData: ['/ˈɡʌv.ən/ ', '../../app_assets/audio/govern.mp3'],
    word: 'govern',
    meaning: ['Rule or control'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Rule'],
    examples: ['Govern the country wisely.', 'Self-control governs success.'],
    synonyms: ['rule', 'control'],
    antonyms: ['obey'],
    shortStory:
      'Wise ruler governed with listening ears. Kingdom flourished peacefully. Leadership serves, never rules.',
  },
  {
    audioData: ['/ˈɡʌv.ə.mənt/ /ˈɡʌv.ən.mənt/ ', '../../app_assets/audio/government.mp3'],
    word: 'government',
    meaning: ['System governing state'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Country rulers'],
    examples: ['Government builds roads.', 'New government elected.'],
    synonyms: ['authority', 'administration'],
    antonyms: ['anarchy'],
    shortStory:
      'Government by the people worked best. Voices shaped policies. Democracy breathed through ballots.',
  },
  {
    audioData: ['/ɡræb/ ', '../../app_assets/audio/grab.mp3'],
    word: 'grab',
    meaning: ['Take suddenly'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Take quickly'],
    examples: ['Grab your coat!', 'Grab opportunity when it comes.'],
    synonyms: ['seize', 'snatch'],
    antonyms: ['release'],
    shortStory:
      'Grabbed last lifeboat seat. Survival instinct trumped politeness. Life chooses strongest.',
  },
  {
    audioData: ['/ɡreɪd/ ', '../../app_assets/audio/grade.mp3'],
    word: 'grade',
    meaning: ['Mark given for schoolwork', 'Level or quality'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['School mark', 'Level'],
    examples: ['Got A grade.', 'Grade A eggs.'],
    synonyms: ['mark', 'score', 'level'],
    antonyms: [],
    shortStory:
      "Failing grade became turning point. Extra hours earned A's. Adversity forges scholars.",
  },
  {
    audioData: [' /ˈɡrædʒuəli/', '../../app_assets/audio/gradually.mp3'],
    word: 'gradually',
    meaning: ['Slowly over time'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['Slowly'],
    examples: ['Gradually improve skills.', 'Weather gradually warmed.'],
    synonyms: ['slowly', 'step by step'],
    antonyms: ['suddenly'],
    shortStory:
      'Gradually, caterpillar became butterfly. Patient transformation amazed watchers. Change happens quietly.',
  },
  {
    audioData: ['/ˈɡrædʒuət/ ', '../../app_assets/audio/graduate.mp3'],
    word: 'graduate',
    meaning: ['Complete course of study', 'Person who graduates'],
    partOfSpeech: ['verb', 'noun'],
    simpleDefinition: ['Finish school', 'School finisher'],
    examples: ['Graduate from college.', 'College graduate got job.'],
    synonyms: ['complete', 'alumnus'],
    antonyms: ['dropout'],
    shortStory:
      'Graduate walked confidently across stage. Diploma weighed dreams. Future opened wide.',
  },
  {
    audioData: ['/ɡreɪn/ ', '../../app_assets/audio/grain.mp3'],
    word: 'grain',
    meaning: ['Small hard seed', 'Tiny bit'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Wheat seed', 'Tiny piece'],
    examples: ['Grain of rice.', 'Not a grain of truth.'],
    synonyms: ['seed', 'particle'],
    antonyms: [],
    shortStory:
      'Single grain fed village through famine. Wise storage saved thousands. Small things sustain.',
  },
  {
    audioData: ['/ɡrænd/ ', '../../app_assets/audio/grand.mp3'],
    word: 'grand',
    meaning: ['Magnificent', 'Thousand dollars'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Magnificent', '1000'],
    examples: ['Grand piano filled hall.', 'Won grand prize.'],
    synonyms: ['magnificent', 'thousand'],
    antonyms: ['ordinary'],
    shortStory:
      'Grand entrance silenced room. Confidence wore finest gowns. Presence outshone jewels.',
  },
  {
    audioData: ['/ˈɡrænˌfɑðər/ ', '../../app_assets/audio/grandfather.mp3'],
    word: 'grandfather',
    meaning: ["Father of one's parent"],
    partOfSpeech: ['noun'],
    simpleDefinition: ["Dad's dad"],
    examples: [
      'Grandfather tells best stories.',
      'Grandfather clock chimed noon.',
    ],
    synonyms: ['grandpa'],
    antonyms: [],
    shortStory:
      "Grandfather's pocket watch ticked memories. Each second told adventures. Timepieces carry souls.",
  },
  {
    audioData: ['/ˈɡrænˌmʌðər/ ', '../../app_assets/audio/grandmother.mp3'],
    word: 'grandmother',
    meaning: ["Mother of one's parent"],
    partOfSpeech: ['noun'],
    simpleDefinition: ["Mom's mom"],
    examples: [
      'Grandmother bakes perfect cookies.',
      "Grandmother's wisdom guides.",
    ],
    synonyms: ['grandma', 'nana'],
    antonyms: [],
    shortStory:
      "Grandmother's quilt wrapped three generations. Each square held memories. Love stitches families.",
  },
  {
    audioData: [' /ˈɡrænˌpɛrənt/', '../../app_assets/audio/grandparent.mp3'],
    word: 'grandparent',
    meaning: ["Parent of one's parent"],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Grandma or grandpa'],
    examples: ['Grandparent visitation rights.', 'Spoiled by grandparents.'],
    synonyms: ['grandma', 'grandpa'],
    antonyms: [],
    shortStory:
      "Grandparents' house smelled like holidays. Cookie jars never emptied. Magic lived in every corner.",
  },
  {
    audioData: ['/ɡrænt/ ', '../../app_assets/audio/grant.mp3'],
    word: 'grant',
    meaning: ['Give formally', 'Money for project'],
    partOfSpeech: ['verb', 'noun'],
    simpleDefinition: ['Give officially', 'Money award'],
    examples: ['Grant permission.', 'Won research grant.'],
    synonyms: ['award', 'bestow'],
    antonyms: ['deny'],
    shortStory:
      'Grant changed everything. Small funding built big dreams. Opportunity knocks once.',
  },
  {
    audioData: ['/ɡræs/ ', '../../app_assets/audio/grass.mp3'],
    word: 'grass',
    meaning: ['Green plants covering ground'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Green ground cover'],
    examples: ['Cut the grass.', 'Grass stains on knees.'],
    synonyms: ['lawn', 'turf'],
    antonyms: ['concrete'],
    shortStory:
      'Freshly cut grass signaled summer. Barefoot kids ran free. Green carpet welcomed play.',
  },
  {
    audioData: ['/ˈɡreɪtfl/ ', '../../app_assets/audio/grateful.mp3'],
    word: 'grateful',
    meaning: ['Thankful'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Thankful'],
    examples: ['Grateful for your help.', 'Grateful heart sings.'],
    synonyms: ['thankful'],
    antonyms: ['ungrateful'],
    shortStory:
      "Grateful survivor hugged rescuers. Second chance breathed deeply. Life's true value revealed.",
  },
  {
    audioData: ['/ɡreɪt/ ', '../../app_assets/audio/great.mp3'],
    word: 'great',
    meaning: ['Excellent', 'Very large', "Grandparent's child"],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Excellent', 'Big'],
    examples: ['Great idea!', 'Great white shark.'],
    synonyms: ['excellent', 'wonderful'],
    antonyms: ['poor'],
    shortStory:
      'Great expectations met greatness. Self-belief created reality. Confidence forges destinies.',
  },
  {
    audioData: ['/ɡrin/ ', '../../app_assets/audio/green.mp3'],
    word: 'green',
    meaning: ['Color of grass', 'Inexperienced', 'Environmentally friendly'],
    partOfSpeech: ['adjective', 'noun'],
    simpleDefinition: ['Grass color', 'New'],
    examples: ['Green apple.', 'Green recruit.'],
    synonyms: ['verdant', 'inexperienced'],
    antonyms: ['red', 'experienced'],
    shortStory:
      'Green fields called wanderers home. Nature healed city wounds. Earth welcomes returnees.',
  },
  {
    audioData: [' /ɡrit/', '../../app_assets/audio/greet.mp3'],
    word: 'greet',
    meaning: ['Give welcome', 'Meet with reaction'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Say hello'],
    examples: ['Greet guests warmly.', 'Dawn greeted mountain climbers.'],
    synonyms: ['welcome', 'hail'],
    antonyms: ['ignore'],
    shortStory:
      'Sunrise greeted early risers. Golden welcome warmed souls. New days promise fresh starts.',
  },
  {
    audioData: ['/ɡreɪ/ ', '../../app_assets/audio/grey.mp3'],
    word: 'grey',
    meaning: ['Color between black and white'],
    partOfSpeech: ['adjective', 'noun'],
    simpleDefinition: ['Dull color'],
    examples: ['Grey clouds promised rain.', 'Grey hair showed wisdom.'],
    synonyms: ['gray'],
    antonyms: ['colorful'],
    shortStory:
      'Grey skies matched melancholy mood. Single rainbow broke clouds. Hope pierces darkness.',
  },
  {
    audioData: ['/ɡraʊnd/ ', '../../app_assets/audio/ground.mp3'],
    word: 'ground',
    meaning: ['Earth surface', 'Crush into powder'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Earth', 'Powder'],
    examples: ['Touch ground safely.', 'Ground fresh pepper.'],
    synonyms: ['earth', 'soil', 'pulverize'],
    antonyms: ['sky'],
    shortStory:
      'Solid ground ended freefall fear. Safe landing birthed relief. Earth welcomes all wanderers.',
  },
  {
    audioData: ['/ɡruːp/ ', '../../app_assets/audio/group.mp3'],
    word: 'group',
    meaning: ['Number of people or things'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Collection'],
    examples: ['Study group meets weekly.', 'Group similar items.'],
    synonyms: ['team', 'collection'],
    antonyms: ['individual'],
    shortStory:
      'Small group changed history. United voices echoed worldwide. Strength multiplies in unity.',
  },
  {
    audioData: [' /ɡrəʊ/ ', '../../app_assets/audio/grow.mp3'],
    word: 'grow',
    meaning: ['Increase in size', 'Cultivate plants'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Get bigger'],
    examples: ['Plants grow toward sunlight.', 'Grow your own vegetables.'],
    synonyms: ['expand', 'cultivate'],
    antonyms: ['shrink'],
    shortStory:
      'Little seed grew mighty tree. Patience watered roots. Small beginnings birth wonders.',
  },
  {
    audioData: ['/ɡrəʊθ/', '../../app_assets/audio/growth.mp3'],
    word: 'growth',
    meaning: ['Process of growing', 'Increase'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Getting bigger'],
    examples: ['Rapid growth spurt.', 'Economic growth helps all.'],
    synonyms: ['development', 'expansion'],
    antonyms: ['decline'],
    shortStory:
      'Personal growth outshone mirrors. Inner strength shone brightest. True beauty grows within.',
  },
  {
    audioData: [' /ˌɡær.ənˈtiː/ ', '../../app_assets/audio/guarantee.mp3'],
    word: 'guarantee',
    meaning: ['Promise something works', 'Assurance'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Promise'],
    examples: ['Money-back guarantee.', 'Guarantee your satisfaction.'],
    synonyms: ['warranty', 'assure'],
    antonyms: ['risk'],
    shortStory:
      'Lifetime guarantee on love. Hearts promised forever. True commitments never expire.',
  },
  {
    audioData: ['/ɡɑːd/ ', '../../app_assets/audio/guard.mp3'],
    word: 'guard',
    meaning: ['Protect', 'Watchman'],
    partOfSpeech: ['verb', 'noun'],
    simpleDefinition: ['Protect'],
    examples: ['Guard the door.', 'Security guard patrols.'],
    synonyms: ['protect', 'watchman'],
    antonyms: ['attack'],
    shortStory:
      'Loyal guard dog saved family. Brave heart beat fiercely. Love makes fiercest warriors.',
  },
  {
    audioData: ['/ɡes/ ', '../../app_assets/audio/guess.mp3'],
    word: 'guess',
    meaning: ['Estimate without knowing'],
    partOfSpeech: ['verb', 'noun'],
    simpleDefinition: ['Think maybe'],
    examples: ['Guess the answer.', 'My guess was wrong.'],
    synonyms: ['estimate', 'suppose'],
    antonyms: ['know'],
    shortStory:
      'Educated guess won the prize. Intuition guided perfectly. Hearts know truths minds doubt.',
  },
  {
    audioData: ['/ɡest/ ', '../../app_assets/audio/guest.mp3'],
    word: 'guest',
    meaning: ['Visitor', 'Person invited'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Visitor'],
    examples: ['Welcome our guest.', 'Hotel guests checked in.'],
    synonyms: ['visitor', 'company'],
    antonyms: ['host'],
    shortStory:
      'Special guest changed evening. Unexpected wisdom fed souls. Hospitality welcomes miracles.',
  },
  {
    audioData: ['/ɡaɪd/ ', '../../app_assets/audio/guide.mp3'],
    word: 'guide',
    meaning: ['Show the way', 'Instruction book'],
    partOfSpeech: ['verb', 'noun'],
    simpleDefinition: ['Lead', 'Instruction'],
    examples: ['Guide leads tour.', 'Use tour guide book.'],
    synonyms: ['lead', 'direct', 'manual'],
    antonyms: ['follow'],
    shortStory:
      'Inner guide whispered correct path. Silent wisdom never fails. Hearts contain best compasses.',
  },
  {
    audioData: ['/ˈɡɪl.ti/ ', '../../app_assets/audio/guilty.mp3'],
    word: 'guilty',
    meaning: ['Responsible for crime', 'Feeling bad about something'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Did wrong'],
    examples: ['Guilty of theft.', 'Guilty about lying.'],
    synonyms: ['culpable', 'ashamed'],
    antonyms: ['innocent'],
    shortStory:
      'Guilty conscience weighed heaviest. Truth lifted burden instantly. Honesty frees heaviest chains.',
  },
  {
    audioData: ['/ɡɪˈtɑːr/ ', '../../app_assets/audio/guitar.mp3'],
    word: 'guitar',
    meaning: ['Stringed musical instrument'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['String instrument'],
    examples: ['Play guitar by campfire.', 'Acoustic guitar sounds warm.'],
    synonyms: [],
    antonyms: [],
    shortStory:
      'Old guitar sang family stories. Each string held memories. Music preserves generations.',
  },
  {
    audioData: ['/ɡʌn/ ', '../../app_assets/audio/gun.mp3'],
    word: 'gun',
    meaning: ['Weapon that fires bullets'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Bullet weapon'],
    examples: ['Police carry guns.', 'Gun control debate continues.'],
    synonyms: ['firearm', 'pistol'],
    antonyms: [],
    shortStory:
      'Toy gun sparked real friendship. Cowboys rode imaginary ranges. Childhood knows no danger.',
  },
  {
    audioData: ['/ɡaɪ/ ', '../../app_assets/audio/guy.mp3'],
    word: 'guy',
    meaning: ['Man', 'Person'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Man'],
    examples: ['Nice guy helped.', 'You guys ready?'],
    synonyms: ['man', 'fellow', 'dude'],
    antonyms: ['girl'],
    shortStory:
      'Regular guy saved the day. Ordinary heroes walk among us. No cape needed.',
  },
  {
    audioData: ['/dʒɪm/ ', '../../app_assets/audio/gym.mp3'],
    word: 'gym',
    meaning: ['Place for exercise', 'Physical education class'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Exercise place'],
    examples: ['Work out at gym.', 'Gym class ran laps.'],
    synonyms: ['fitness center'],
    antonyms: [],
    shortStory:
      'Empty gym echoed determination. Sweat wrote success stories. Muscles remember every rep.',
  },
  {
    audioData: [' /ˈhæb.ɪt/ ', '../../app_assets/audio/habit.mp3'],
    word: 'habit',
    meaning: ['Regular tendency or practice', 'Customary behavior'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Regular practice', 'Custom'],
    examples: [
      'Reading before bed is my habit.',
      'Bad habits are hard to break.',
    ],
    synonyms: ['routine', 'custom', 'practice'],
    antonyms: ['instinct'],
    shortStory:
      'Daily writing habit transformed thoughts into books. Empty pages filled with wisdom. Consistency crafts masterpieces.',
  },
  {
    audioData: [' /heər/ ', '../../app_assets/audio/hair.mp3'],
    word: 'hair',
    meaning: ['Thin threads growing from skin', 'Collection on head'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Head threads'],
    examples: ['She brushed her long hair.', 'Hair tangled in the wind.'],
    synonyms: ['locks', 'tresses'],
    antonyms: ['bald'],
    shortStory:
      'Single gray hair appeared overnight. Mirror showed wisdom earned. Age writes beautiful stories.',
  },
  {
    audioData: ['/hɑːf/ ', '../../app_assets/audio/half.mp3'],
    word: 'half',
    meaning: ['One of two equal parts', '50 percent'],
    partOfSpeech: ['noun', 'adjective'],
    simpleDefinition: ['50%', 'One of two'],
    examples: ['Half an apple.', 'Half past three.'],
    synonyms: ['semi', 'partial'],
    antonyms: ['whole'],
    shortStory:
      'Half a cookie shared doubled sweetness. Friendship multiplies simple joys. Sharing creates abundance.',
  },
  {
    audioData: [' /hɔːl/', '../../app_assets/audio/hall.mp3'],
    word: 'hall',
    meaning: ['Passageway in building', 'Large room for gatherings'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Corridor', 'Big room'],
    examples: ['Hang coats in the hall.', 'Graduation in the hall.'],
    synonyms: ['corridor', 'auditorium'],
    antonyms: [],
    shortStory:
      'Empty hall echoed childhood laughter. School memories lived in walls. Time travels through spaces.',
  },
  {
    audioData: ['/hænd/ ', '../../app_assets/audio/hand.mp3'],
    word: 'hand',
    meaning: ['Body part at end of arm', 'Help or assistance'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Finger part', 'Help'],
    examples: ['Raise your hand.', 'Lend a hand please.'],
    synonyms: ['palm', 'assist'],
    antonyms: ['foot'],
    shortStory:
      'Helping hand pulled climber to summit. Shared struggle forged brothers. Mountains build unbreakable bonds.',
  },
  {
    audioData: ['/ˈhæn.dəl/ ', '../../app_assets/audio/handle.mp3'],
    word: 'handle',
    meaning: ['Part to hold', 'Deal with situation'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Hold part', 'Manage'],
    examples: ['Door handle stuck.', 'Handle stress calmly.'],
    synonyms: ['grip', 'manage'],
    antonyms: ['drop'],
    shortStory:
      'Broken handle taught patience. Turn slowly, door opened. Obstacles build character.',
  },
  {
    audioData: [' /hæŋ/ ', '../../app_assets/audio/hang.mp3'],
    word: 'hang',
    meaning: ['Suspend or attach from above', 'Spend time idly'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Suspend', 'Spend time'],
    examples: ['Hang pictures on wall.', 'Hang out with friends.'],
    synonyms: ['suspend', 'loiter'],
    antonyms: ['drop'],
    shortStory:
      'Pictures hung crookedly told real stories. Perfect frames hold posed lies. Imperfection reveals truth.',
  },
  {
    audioData: [' /ˈhæp.ən/ ', '../../app_assets/audio/happen.mp3'],
    word: 'happen',
    meaning: ['Occur or take place', 'Chance occurrence'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Occur'],
    examples: ['What happened yesterday?', 'Accidents happen.'],
    synonyms: ['occur', 'take place'],
    antonyms: ['plan'],
    shortStory:
      'Chance meeting happened at corner store. Lifelong friendship began over spilled milk. Serendipity writes best stories.',
  },
  {
    audioData: ['/ˈhæp.əl.i/ ', '../../app_assets/audio/happily.mp3'],
    word: 'happily',
    meaning: ['In a happy manner'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['Happily'],
    examples: ['Happily married couple.', 'She sang happily.'],
    synonyms: ['cheerfully', 'joyfully'],
    antonyms: ['sadly'],
    shortStory:
      'Happily ever after began with dirty dishes. Daily chores built lifelong love. Real romance lives in ordinary.',
  },
  {
    audioData: ['/ˈhæp.i.nəs/ ', '../../app_assets/audio/happiness.mp3'],
    word: 'happiness',
    meaning: ['State of being happy', 'Good fortune'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Joy feeling'],
    examples: ['Happiness filled the room.', 'Source of happiness.'],
    synonyms: ['joy', 'contentment'],
    antonyms: ['sadness'],
    shortStory:
      "Happiness hid in small moments. Morning coffee, child laughter. Life's treasures weigh nothing.",
  },
  {
    audioData: ['/ˈhæp.i/ ', '../../app_assets/audio/happy.mp3'],
    word: 'happy',
    meaning: ['Feeling pleasure or contentment'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Joyful'],
    examples: ['Happy birthday!', 'Happy with decision.'],
    synonyms: ['joyful', 'pleased'],
    antonyms: ['sad'],
    shortStory:
      'Happy place existed in memories. Difficult days faded there. Mind holds healing gardens.',
  },
  {
    audioData: [' /hɑːd/ ', '../../app_assets/audio/hard.mp3'],
    word: 'hard',
    meaning: ['Not soft', 'Difficult', 'Intense effort'],
    partOfSpeech: ['adjective', 'adverb'],
    simpleDefinition: ['Solid', 'Difficult'],
    examples: ['Hard worker.', 'Study hard.'],
    synonyms: ['solid', 'difficult', 'intense'],
    antonyms: ['soft', 'easy'],
    shortStory:
      'Hard work built dreams brick by brick. Sweat wrote success stories. Effort outlasts talent.',
  },
  {
    audioData: [' /ˈhɑːd.li/ ', '../../app_assets/audio/hardly.mp3'],
    word: 'hardly',
    meaning: ['Almost not', 'Barely'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['Almost none'],
    examples: ['Hardly any left.', 'Hardly knew him.'],
    synonyms: ['barely', 'scarcely'],
    antonyms: ['fully'],
    shortStory:
      'Hardly recognizable after makeover. Inner beauty shone regardless. True worth needs no mirror.',
  },
  {
    audioData: [' /hɑːm/ ', '../../app_assets/audio/harm.mp3'],
    words: 'harm',
    meaning: ['Injury or damage'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Injury'],
    examples: ['No harm done.', 'Harm to environment.'],
    synonyms: ['injury', 'damage'],
    antonyms: ['help'],
    shortStory:
      'Words harmed deeper than fists. Healing took longer than bruises. Kindness repairs invisible wounds.',
  },
  {
    audioData: ['/ˈhɑːm.fəl/ ', '../../app_assets/audio/harmful.mp3'],
    word: 'harmful',
    meaning: ['Causing harm'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Dangerous'],
    examples: ['Harmful chemicals.', 'Harmful rumors.'],
    synonyms: ['dangerous', 'toxic'],
    antonyms: ['harmless'],
    shortStory:
      'Harmful habits crept silently. Small choices snowballed. Awareness broke chains before damage.',
  },
  {
    audioData: [' /hæt/ ', '../../app_assets/audio/hat.mp3'],
    word: 'hat',
    meaning: ['Head covering'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Head cover'],
    examples: ['Nice hat!', 'Hat and gloves.'],
    synonyms: ['cap'],
    antonyms: [],
    shortStory:
      'Magic hat pulled dreams from thin air. Child imagination needed no tricks. Wonder lives within.',
  },
  {
    audioData: ['/heɪt/ ', '../../app_assets/audio/hate.mp3'],
    word: 'hate',
    meaning: ['Strong dislike', 'Intense hostility'],
    partOfSpeech: ['verb', 'noun'],
    simpleDefinition: ['Strong dislike'],
    examples: ["Don't hate, appreciate.", 'Full of hate.'],
    synonyms: ['despise', 'loathe'],
    antonyms: ['love'],
    shortStory:
      'Hate melted under kindness sun. Frozen hearts thawed slowly. Love conquers coldest emotions.',
  },
  {
    audioData: [' strong /hæv/ weak /həv/ weak /əv/ ', '../../app_assets/audio/have.mp3'],
    word: 'have',
    meaning: ['Possess', 'Experience', 'Must do'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Own', 'Must'],
    examples: ['Have a car.', 'Have to go.'],
    synonyms: ['own', 'possess', 'must'],
    antonyms: ['lack'],
    shortStory:
      'Have-nots built empires from nothing. Determination proved possessions lie. Character creates true wealth.',
  },
  {
    audioData: ['/ˈhæf·tu, ˈhæv-, -tə/ ', '../../app_assets/audio/have_to.mp3'],
    word: 'have to',
    meaning: ['Must do something', 'Obligation'],
    partOfSpeech: ['verb phrase'],
    simpleDefinition: ['Must'],
    examples: ['Have to study.', 'Have to leave now.'],
    synonyms: ['must'],
    antonyms: ['want to'],
    shortStory:
      'Have to became want to. Duty blossomed into passion. Necessity births innovation.',
  },
  {
    audioData: ['strong /hiː/ weak /hi/ weak /i/ ', '../../app_assets/audio/he.mp3'],
    word: 'he',
    meaning: ['Male person', 'Subject pronoun'],
    partOfSpeech: ['pronoun'],
    simpleDefinition: ['Male person'],
    examples: ['He runs fast.', 'He is my brother.'],
    synonyms: [],
    antonyms: ['she'],
    shortStory:
      'He carried burdens silently. Quiet strength inspired thousands. Heroes speak through actions.',
  },
  {
    audioData: ['/hed/ ', '../../app_assets/audio/head.mp3'],
    word: 'head',
    meaning: ['Top part of body', 'Leader', 'Front'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Brain part', 'Leader'],
    examples: ['Head hurts.', 'Head of department.'],
    synonyms: ['skull', 'chief', 'lead'],
    antonyms: ['tail'],
    shortStory:
      'Clear head made wise decisions. Chaos calmed by thought. Reason guides through storms.',
  },
  {
    audioData: ['/ˈhed.eɪk/ ', '../../app_assets/audio/headache.mp3'],
    word: 'headache',
    meaning: ['Pain in head', 'Problem'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Head pain'],
    examples: ['Bad headache today.', "This project's a headache."],
    synonyms: ['migraine', 'problem'],
    antonyms: [],
    shortStory:
      'Headache vanished with deep breaths. Tension melted away. Peace cures what pills cannot.',
  },
  {
    audioData: [' /ˈhed.laɪn/ ', '../../app_assets/audio/headline.mp3'],
    word: 'headline',
    meaning: ['Main title of article', 'Most important news'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Big title'],
    examples: ['Front page headline.', 'Headline act performs.'],
    synonyms: ['title', 'top story'],
    antonyms: [],
    shortStory:
      'Headline changed history overnight. Ordinary names became legends. News creates immortality.',
  },
  {
    audioData: [' /helθ/ ', '../../app_assets/audio/health.mp3'],
    word: 'health',
    meaning: ['State of being well'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Well-being'],
    examples: ['Good health important.', 'Health comes first.'],
    synonyms: ['wellness'],
    antonyms: ['illness'],
    shortStory:
      "Health bought with yesterday's exercise. Future self thanked present sweat. Investment returns compound.",
  },
  {
    audioData: [' /ˈhel.θi/ ', '../../app_assets/audio/healthy.mp3'],
    word: 'healthy',
    meaning: ['In good health', 'Good for health'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Well'],
    examples: ['Healthy lifestyle.', 'Healthy food choices.'],
    synonyms: ['fit', 'well'],
    antonyms: ['sick'],
    shortStory:
      'Healthy habits created strong foundation. Small choices built mighty bodies. Discipline tastes better than regret.',
  },
  {
    audioData: [' /hɪər/', '../../app_assets/audio/hear.mp3'],
    word: 'hear',
    meaning: ['Perceive sound with ears', 'Listen to something'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Listen'],
    examples: ['Can you hear the music?', "I hear what you're saying."],
    synonyms: ['listen', 'detect'],
    antonyms: ['ignore', 'silence'],
    shortStory:
      'He heard her laughter across crowded room. Single sound cut through noise. Hearts recognize voices instantly.',
  },
  {
    audioData: ['/ˈhɪə.rɪŋ/ ', '../../app_assets/audio/hearing.mp3'],
    word: 'hearing',
    meaning: ['Ability to hear', 'Legal proceeding'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Hearing ability', 'Court session'],
    examples: ['Good hearing helps learning.', 'Court hearing scheduled.'],
    synonyms: ['listening', 'trial'],
    antonyms: ['deafness'],
    shortStory:
      'Hearing test revealed hidden loss. Small hearing aid restored symphony. Technology returns stolen sounds.',
  },
  {
    audioData: ['/hɑːt/ ', '../../app_assets/audio/heart.mp3'],
    word: 'heart',
    meaning: ['Organ that pumps blood', 'Center of emotions'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Blood pump', 'Feelings center'],
    examples: ['Heart beats fast when scared.', 'Follow your heart.'],
    synonyms: ['ticker', 'core'],
    antonyms: ['brain'],
    shortStory:
      'Broken heart mended through time. Scars made stronger muscle. Love rebuilds better than new.',
  },
  {
    audioData: ['/hiːt/ ', '../../app_assets/audio/heat.mp3'],
    word: 'heat',
    meaning: ['High temperature', 'Make hot'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Hotness', 'Make hot'],
    examples: ['Summer heat waves.', 'Heat soup on stove.'],
    synonyms: ['warmth', 'warm'],
    antonyms: ['cold'],
    shortStory:
      'Heat mirage danced on horizon. Desert promised water ahead. Hope beats in hot air.',
  },
  {
    audioData: ['/ˈhiː.tɪŋ/ ', '../../app_assets/audio/heating.mp3'],
    word: 'heating',
    meaning: ['System that warms building', 'Process of getting hot'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Warmth system'],
    examples: ['Turn on heating.', 'Heating costs rise in winter.'],
    synonyms: ['warmth', 'radiator'],
    antonyms: ['cooling'],
    shortStory:
      'Heating clicked on at dusk. Frosty windows cleared slowly. Warmth welcomed wanderers home.',
  },
  {
    audioData: ['/ˈhev.ən/ ', '../../app_assets/audio/heaven.mp3'],
    word: 'heaven',
    meaning: ['Place good people go after death', 'Place of great happiness'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Afterlife paradise', 'Perfect happiness'],
    examples: ['Heaven on earth.', 'Thank heaven for that!'],
    synonyms: ['paradise', 'bliss'],
    antonyms: ['hell'],
    shortStory:
      "Heaven's glimpse appeared in child's smile. Pure joy needed no pearly gates. Angels walk among us.",
  },
  {
    audioData: ['/ˈhev.əl.i/ ', '../../app_assets/audio/heavily.mp3'],
    word: 'heavily',
    meaning: ['With great weight or force', 'To a large degree'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['With weight', 'Greatly'],
    examples: ['Rain fell heavily.', 'Invested heavily in stocks.'],
    synonyms: ['greatly', 'intensely'],
    antonyms: ['lightly'],
    shortStory:
      'Heavily burdened traveler dropped pack. Helper carried both loads. Shared weights lighten journeys.',
  },
  {
    audioData: [' /ˈhev.i/ ', '../../app_assets/audio/heavy.mp3'],
    word: 'heavy',
    meaning: ['Great weight', 'Difficult', 'Serious'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Hard to lift', 'Serious'],
    examples: ['Heavy box.', 'Heavy heart.'],
    synonyms: ['weighty', 'serious'],
    antonyms: ['light'],
    shortStory:
      'Heavy crown weighed on young king. Wisdom made burden bearable. Leadership lifts while pressing down.',
  },
  {
    audioData: ['/hiːl/ ', '../../app_assets/audio/heel.mp3'],
    word: 'heel',
    meaning: ['Back part of foot', 'Command to dog'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Foot back', 'Follow closely'],
    examples: ['Blisters on heels.', 'Heel dog command.'],
    synonyms: ['back foot'],
    antonyms: ['toe'],
    shortStory:
      'High heels clicked confidence. Posture changed with shoes. Walk creates destiny.',
  },
  {
    audioData: ['/haɪt/ ', '../../app_assets/audio/height.mp3'],
    word: 'height',
    meaning: ['Measurement from base to top', 'Highest point'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Tallness'],
    examples: ['Height of five feet.', 'Height of summer.'],
    synonyms: ['tallness', 'peak'],
    antonyms: ['depth'],
    shortStory:
      'Great height revealed tiny problems. Perspective shrinks worries. Mountains teach true scale.',
  },
  {
    audioData: [' /ˈhel.ɪˌkɒp.tər/ ', '../../app_assets/audio/helicopter.mp3'],
    word: 'helicopter',
    meaning: ['Aircraft that flies with spinning blades'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Spinning top plane'],
    examples: ['Helicopter landed on roof.', 'Medevac helicopter saved lives.'],
    synonyms: ['chopper'],
    antonyms: [],
    shortStory:
      'Helicopter blades chopped anxious air. Rescued climber waved below. Technology defies gravity and fear.',
  },
  {
    audioData: ['/hel/ ', '../../app_assets/audio/hell.mp3'],
    word: 'hell',
    meaning: ['Place of punishment after death', 'Very bad situation'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Punishment place', 'Nightmare'],
    examples: ['What the hell?', 'Hell to pay.'],
    synonyms: ['underworld'],
    antonyms: ['heaven'],
    shortStory:
      'Hell week passed into glory. Grueling training forged warriors. Fire purifies gold.',
  },
  {
    audioData: [' /heˈləʊ/ ', '../../app_assets/audio/hello.mp3'],
    word: 'hello',
    meaning: ['Word used to greet'],
    partOfSpeech: ['interjection'],
    simpleDefinition: ['Greeting'],
    examples: ['Hello there!', 'Say hello to guests.'],
    synonyms: ['hi', 'greetings'],
    antonyms: ['goodbye'],
    shortStory:
      'Hello stranger changed lonely night. Single word built friendship. Courage speaks first.',
  },
  {
    audioData: ['/help/ ', '../../app_assets/audio/help.mp3'],
    word: 'help',
    meaning: ['Make things easier', 'Assist'],
    partOfSpeech: ['verb', 'noun'],
    simpleDefinition: ['Assist'],
    examples: ['Help me move.', 'Need help with homework.'],
    synonyms: ['assist', 'aid'],
    antonyms: ['hinder'],
    shortStory:
      "Help offered changed everything. Neighbor's ladder saved roof. Kindness climbs highest walls.",
  },
  {
    audioData: ['/ˈhelp.fəl/ ', '../../app_assets/audio/helpful.mp3'],
    word: 'helpful',
    meaning: ['Giving help', 'Useful'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Useful'],
    examples: ['Helpful advice appreciated.', 'Helpful neighbor always ready.'],
    synonyms: ['useful', 'beneficial'],
    antonyms: ['unhelpful'],
    shortStory:
      'Helpful stranger shared umbrella. Rainy walk became adventure. Goodwill warms wettest days.',
  },
  {
    audioData: [' strong /hɜːr/ weak /hər/ /ər/ ', '../../app_assets/audio/her.mp3'],
    word: 'her',
    meaning: ['Belonging to female', 'Object pronoun for she'],
    partOfSpeech: ['pronoun'],
    simpleDefinition: ['She’s', 'Her'],
    examples: ['Her book.', 'I saw her.'],
    synonyms: [],
    antonyms: ['his'],
    shortStory:
      'Her courage inspired thousands. Quiet strength roared loudest. Women lead through living.',
  },
  {
    audioData: [' /hɪər/ ', '../../app_assets/audio/here.mp3'],
    word: 'here',
    meaning: ['In this place', 'To this place'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['This place'],
    examples: ['Here is your coffee.', 'Come here please.'],
    synonyms: ['present'],
    antonyms: ['there'],
    shortStory:
      'Here and now held greatest gift. Past regrets fled. Future worries silenced.',
  },
  {
    audioData: ['/ˈhɪə.rəʊ/ ', '../../app_assets/audio/hero.mp3'],
    word: 'hero',
    meaning: ['Brave person', 'Main character'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Brave person'],
    examples: ['Fireman is hero.', "Book's hero saves village."],
    synonyms: ['champion', 'protagonist'],
    antonyms: ['villain'],
    shortStory:
      "Everyday hero shoveled elderly neighbor's walk. Snow fell, kindness accumulated. Heroes wear flannel.",
  },
  {
    audioData: [' /hɜːz/ ', '../../app_assets/audio/hers.mp3'],
    word: 'hers',
    meaning: ['Belonging to her', 'Possessive form of her'],
    partOfSpeech: ['pronoun'],
    simpleDefinition: ['Her things'],
    examples: ['The choice is hers.', 'The red shoes are hers.'],
    synonyms: [],
    antonyms: ['his'],
    shortStory:
      'The victory was hers alone. Years of training crowned triumph. She claimed what she earned.',
  },
  {
    audioData: ['/hɜːˈself/ ', '../../app_assets/audio/herself.mp3'],
    word: 'herself',
    meaning: ['Reflexive form of her', 'Emphasizes she'],
    partOfSpeech: ['pronoun'],
    simpleDefinition: ['Her, alone'],
    examples: ['She taught herself guitar.', 'She did it herself.'],
    synonyms: [],
    antonyms: ['himself'],
    shortStory:
      'She pulled herself from depths. Inner strength surfaced first. Self-reliance builds unbreakable spirits.',
  },
  {
    audioData: ['/ˈhez.ɪ.teɪt/ ', '../../app_assets/audio/hesitate.mp3'],
    word: 'hesitate',
    meaning: ['Pause before acting', 'Be uncertain'],
    partOfSpeech: ['verb'],
    simpleDefinition: ['Pause', 'Doubt'],
    examples: ["Don't hesitate to ask.", 'She hesitated at the door.'],
    synonyms: ['pause', 'waver'],
    antonyms: ['decide'],
    shortStory:
      "Moment's hesitation cost championship. Lesson learned through loss. Speed follows confidence.",
  },
  {
    audioData: [' /heɪ/ ', '../../app_assets/audio/hey.mp3'],
    word: 'hey',
    meaning: ['Casual greeting', 'Get attention'],
    partOfSpeech: ['interjection'],
    simpleDefinition: ['Hello'],
    examples: ['Hey, how are you?', 'Hey, watch out!'],
    synonyms: ['hi', 'yo'],
    antonyms: ['goodbye'],
    shortStory:
      'Hey stranger broke ice wall. Single word started lifelong friendship. Boldness opens doors.',
  },
  {
    audioData: ['  /haɪ/', '../../app_assets/audio/hi.mp3'],
    word: 'hi',
    meaning: ['Informal greeting'],
    partOfSpeech: ['interjection'],
    simpleDefinition: ['Hello'],
    examples: ['Hi everyone!', 'Hi from across room.'],
    synonyms: ['hello', 'hey'],
    antonyms: ['bye'],
    shortStory:
      'Shy hi began classroom friendship. Small voice carried big courage. First words build bridges.',
  },
  {
    audioData: [' /haɪd/  ', '../../app_assets/audio/hide.mp3'],
    word: 'hide',
    meaning: ['Put or keep out of sight', 'Animal skin'],
    partOfSpeech: ['verb', 'noun'],
    simpleDefinition: ['Conceal'],
    examples: ['Hide and seek game.', 'Hide your feelings.'],
    synonyms: ['conceal', 'pelt'],
    antonyms: ['show'],
    shortStory:
      'Children hid in perfect spots. Giggles gave positions away. Joy cannot stay hidden.',
  },
  {
    audioData: ['/haɪ/ ', '../../app_assets/audio/high.mp3'],
    word: 'high',
    meaning: ['Tall or elevated', 'Large amount', 'Excited state'],
    partOfSpeech: ['adjective', 'adverb'],
    simpleDefinition: ['Tall', 'Great'],
    examples: ['High mountain.', 'High prices.', 'High spirits.'],
    synonyms: ['tall', 'elevated', 'excited'],
    antonyms: ['low'],
    shortStory:
      'High places revealed small problems. Perspective dwarfed worries. Mountains teach true scale.',
  },
  {
    audioData: ['  /ˈhaɪ.laɪt/', '../../app_assets/audio/highlight.mp3'],
    word: 'highlight',
    meaning: ['Most important part', 'Make prominent'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Best part', 'Emphasize'],
    examples: ['Highlight of the trip.', 'Highlight key points.'],
    synonyms: ['best part', 'emphasize'],
    antonyms: ['lowlight'],
    shortStory:
      'Highlight reel showed career magic. Single plays defined legacy. Moments create immortality.',
  },
  {
    audioData: [' /ˈhaɪ.li/ ', '../../app_assets/audio/highly.mp3'],
    word: 'highly',
    meaning: ['Very much', 'To a high degree'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['Very'],
    examples: ['Highly recommend.', 'Highly skilled worker.'],
    synonyms: ['very', 'extremely'],
    antonyms: ['slightly'],
    shortStory:
      'Highly unlikely became reality. Persistence proved probabilities wrong. Faith defies mathematics.',
  },
  {
    audioData: ['/hɪl/ ', '../../app_assets/audio/hill.mp3'],
    word: 'hill',
    meaning: ['Raised land smaller than mountain'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Small mountain'],
    examples: ['Roll down the hill.', 'House on the hill.'],
    synonyms: ['knoll', 'rise'],
    antonyms: ['valley'],
    shortStory:
      'Hilltop view stole breath away. Valley sprawled like emerald quilt. Heights reward climbers.',
  },
  {
    audioData: ['strong /hɪm/ weak /ɪm/ ', '../../app_assets/audio/him.mp3'],
    word: 'him',
    meaning: ['Object form of he'],
    partOfSpeech: ['pronoun'],
    simpleDefinition: ['Male person'],
    examples: ['I saw him.', 'Give it to him.'],
    synonyms: [],
    antonyms: ['her'],
    shortStory:
      'Saw him across crowded room. Eyes locked, hearts recognized. Destiny writes in glances.',
  },
  {
    audioData: [' /hɪmˈself/ ', '../../app_assets/audio/himself.mp3'],
    word: 'himself',
    meaning: ['Reflexive form of he'],
    partOfSpeech: ['pronoun'],
    simpleDefinition: ['Him, alone'],
    examples: ['He cut himself.', 'He did it himself.'],
    synonyms: [],
    antonyms: ['herself'],
    shortStory:
      'He challenged himself daily. Comfort zone shrank behind growth. Self-imposed limits break easiest.',
  },
  {
    audioData: [' /haɪər/ ', '../../app_assets/audio/hire.mp3'],
    word: 'hire',
    meaning: ['Employ someone', 'Rent something'],
    partOfSpeech: ['verb', 'noun'],
    simpleDefinition: ['Employ'],
    examples: ['Hire a new teacher.', 'Car hire available.'],
    synonyms: ['employ', 'rent'],
    antonyms: ['fire'],
    shortStory:
      'Risky hire became star employee. Intuition trumped perfect resumes. People reveal through actions.',
  },
  {
    audioData: ['strong /hɪz/ weak /ɪz/ ', '../../app_assets/audio/his.mp3'],
    word: 'his',
    meaning: ['Belonging to him'],
    partOfSpeech: ['pronoun'],
    simpleDefinition: ['His things'],
    examples: ['His book.', 'This is his.'],
    synonyms: [],
    antonyms: ['hers'],
    shortStory:
      'His dream fueled midnight oil. Passion burned brighter than doubters. Ownership creates unstoppable force.',
  },
  {
    audioData: [' /hɪˈstɒr.ɪk/ ', '../../app_assets/audio/historic.mp3'],
    word: 'historic',
    meaning: ['Famous or important in history'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Famous past'],
    examples: ['Historic building preserved.', 'Historic first flight.'],
    synonyms: ['famous'],
    antonyms: ['unknown'],
    shortStory:
      'Historic moment froze time. Ordinary people became legends. History chooses unexpected heroes.',
  },
  {
    audioData: [' /hɪˈstɒr.ɪ.kəl/ ', '../../app_assets/audio/historical.mp3'],
    word: 'historical',
    meaning: ['Concerning history', 'From the past'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Past related'],
    examples: ['Historical novel.', 'Historical evidence.'],
    synonyms: ['past'],
    antonyms: ['modern'],
    shortStory:
      'Historical truth outshone fiction. Documents revealed hidden stories. Past whispers through papers.',
  },
  {
    audioData: ['/ˈhɪs.tər.i/ ', '../../app_assets/audio/history.mp3'],
    word: 'history',
    meaning: ['Study of past events', 'Past events'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Past events'],
    examples: ['Study history.', 'Make history.'],
    synonyms: ['past', 'record'],
    antonyms: ['future'],
    shortStory:
      'History repeated through forgotten lessons. Wise remembered, fools repeated. Knowledge prevents reruns.',
  },
  {
    audioData: ['/hɪt/  ', '../../app_assets/audio/hit.mp3'],
    word: 'hit',
    meaning: ['Strike with force', 'Great success', 'Reach a place'],
    partOfSpeech: ['verb', 'noun'],
    simpleDefinition: ['Strike', 'Success'],
    examples: ['Hit the ball hard.', 'Summer hit song.'],
    synonyms: ['strike', 'smash', 'success'],
    antonyms: ['miss'],
    shortStory:
      "Single hit changed baseball history. Rookie's homerun sparked legend. Moments define eras.",
  },
  {
    audioData: [' /ˈhɒb.i/', '../../app_assets/audio/hobby.mp3'],
    word: 'hobby',
    meaning: ['Activity done for pleasure'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Fun activity'],
    examples: ['Reading is my hobby.', 'Collect stamps as hobby.'],
    synonyms: ['pastime'],
    antonyms: ['work'],
    shortStory:
      'Secret hobby became career path. Weekend painter sold first canvas. Passion pays dividends.',
  },
  {
    audioData: [' /ˈhɒk.i/ ', '../../app_assets/audio/hockey.mp3'],
    word: 'hockey',
    meaning: ['Ice or field sport with sticks and puck'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Stick sport'],
    examples: ['Ice hockey game tonight.', 'Field hockey team won.'],
    synonyms: [],
    antonyms: [],
    shortStory:
      'Overtime hockey goal erupted arena. Fans hugged strangers. Sports unite beating hearts.',
  },
  {
    audioData: [' /həʊld/ ', '../../app_assets/audio/hold.mp3'],
    word: 'hold',
    meaning: ['Grasp', 'Contain', 'Have opinion'],
    partOfSpeech: ['verb', 'noun'],
    simpleDefinition: ['Grasp', 'Contain'],
    examples: ['Hold my hand.', 'Room holds 100 people.'],
    synonyms: ['grasp', 'contain'],
    antonyms: ['release'],
    shortStory:
      "Tight hold through storm. Captain's grip saved ship. Trust anchors strongest.",
  },
  {
    audioData: ['/həʊl/ ', '../../app_assets/audio/hole.mp3'],
    word: 'hole',
    meaning: ['Empty space in solid', 'Difficulty'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Empty space'],
    examples: ['Hole in sock.', 'Financial hole.'],
    synonyms: ['gap', 'opening'],
    antonyms: ['solid'],
    shortStory:
      'Perfect golf hole waited patiently. Putt dropped, celebration erupted. Precision rewards patience.',
  },
  {
    audioData: ['/ˈhɒl.ə.deɪ/ ', '../../app_assets/audio/holiday.mp3'],
    word: 'holiday',
    meaning: ['Day off work', 'Vacation'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Day off'],
    examples: ['Christmas holiday.', 'Summer holiday plans.'],
    synonyms: ['vacation', 'break'],
    antonyms: ['workday'],
    shortStory:
      'First holiday alone taught independence. Self-made dinner tasted best. Growth seasons solitude.',
  },
  {
    audioData: ['/ˈhɒl.əʊ/ ', '../../app_assets/audio/hollow.mp3'],
    word: 'hollow',
    meaning: ['Empty inside', 'Insincere'],
    partOfSpeech: ['adjective', 'noun'],
    simpleDefinition: ['Empty inside'],
    examples: ['Hollow tree perfect hideout.', 'Hollow promises.'],
    synonyms: ['empty', 'cavity'],
    antonyms: ['solid'],
    shortStory:
      'Hollow promises echoed empty. Actions proved true commitments. Deeds speak, words whisper.',
  },
  {
    audioData: [' /ˈhəʊ.li/ ', '../../app_assets/audio/holy.mp3'],
    word: 'holy',
    meaning: ['Sacred, dedicated to God'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Sacred'],
    examples: ['Holy Bible.', 'Holy place of worship.'],
    synonyms: ['sacred', 'divine'],
    antonyms: ['profane'],
    shortStory:
      'Holy silence filled cathedral. Prayers rose silently upward. Sacred spaces amplify spirits.',
  },
  {
    audioData: [' /həʊm/ ', '../../app_assets/audio/home.mp3'],
    word: 'home',
    meaning: ['Where you live', 'Where heart belongs'],
    partOfSpeech: ['noun', 'adverb'],
    simpleDefinition: ['Your house'],
    examples: ['Going home now.', 'Home sweet home.'],
    synonyms: ['house', 'residence'],
    antonyms: ['away'],
    shortStory:
      "Home waited with open arms. Distance couldn't dim welcome. Love makes houses homes.",
  },
  {
    audioData: ['/ˈhəʊm.wɜːk/ ', '../../app_assets/audio/homework.mp3'],
    word: 'homework',
    meaning: ['Schoolwork done at home'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Home schoolwork'],
    examples: ['Finish homework first.', 'Too much homework tonight.'],
    synonyms: [],
    antonyms: ['playtime'],
    shortStory:
      'Homework battles built discipline. Future success rooted in drudgery. Boring tasks birth brilliance.',
  },
  {
    audioData: ['/ˈɒn.ɪst/ ', '../../app_assets/audio/honest.mp3'],
    word: 'honest',
    meaning: ['Truthful', 'Not hiding truth'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Truthful'],
    examples: ['Honest answer appreciated.', 'Honest hard worker.'],
    synonyms: ['truthful', 'sincere'],
    antonyms: ['dishonest'],
    shortStory:
      'Honest mistake forgiven instantly. Truth builds trust bridges. Integrity outweighs perfection.',
  },
  {
    audioData: ['/həʊp/ ', '../../app_assets/audio/hope.mp3'],
    word: 'hope',
    meaning: ['Wish for good outcome', 'Optimism'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Wish'],
    examples: ['Hope you feel better.', 'Best hopes for success.'],
    synonyms: ['wish', 'optimism'],
    antonyms: ['despair'],
    shortStory:
      'Last hope flickered weakly. Single candle lit darkness. Faith burns brightest alone.',
  },
  {
    audioData: [' /ˈhɒr.ə.bəl/ ', '../../app_assets/audio/horrible.mp3'],
    word: 'horrible',
    meaning: ['Very bad', 'Causing horror'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Very bad'],
    examples: ['Horrible weather outside.', 'Horrible movie choice.'],
    synonyms: ['awful', 'terrible'],
    antonyms: ['wonderful'],
    shortStory:
      'Horrible day redeemed by sunset. Beauty follows worst storms. Light always finds darkness.',
  },
  {
    audioData: [' /ˈhɒr.ər/ ', '../../app_assets/audio/horror.mp3'],
    word: 'horror',
    meaning: ['Extreme fear', 'Horror genre'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Great fear'],
    examples: ['Looked in horror.', 'Horror movie night.'],
    synonyms: ['terror', 'fright'],
    antonyms: ['joy'],
    shortStory:
      'Horror movie laughter replaced screams. Friends mocked monsters. Fear flees in fellowship.',
  },
  {
    audioData: [' /hɔːs/ ', '../../app_assets/audio/horse.mp3'],
    word: 'horse',
    meaning: ['Large four-legged animal'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Riding animal'],
    examples: ['Ride horse at ranch.', 'Horse won the race.'],
    synonyms: ['steed'],
    antonyms: [],
    shortStory:
      'Gentle horse carried fears away. Gallop healed heart wounds. Animals understand without words.',
  },
  {
    audioData: ['/ˈhɒs.pɪ.təl/ ', '../../app_assets/audio/hospital.mp3'],
    word: 'hospital',
    meaning: ['Place treating sick people'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Sick people place'],
    examples: ['Born in hospital.', 'Visit friend in hospital.'],
    synonyms: ['medical center'],
    antonyms: [],
    shortStory:
      'Hospital waiting room held hope. Time stretched, prayers shortened. Healing happens beyond walls.',
  },
  {
    audioData: ['/həʊst/ ', '../../app_assets/audio/host.mp3'],
    word: 'host',
    meaning: ['Person entertaining guests', 'Large number'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Party giver'],
    examples: ['Perfect host tonight.', 'Host the party.'],
    synonyms: ['entertainer', 'multitude'],
    antonyms: ['guest'],
    shortStory:
      'Gracious host transformed strangers. Shared table built instant family. Hospitality creates belonging.',
  },
  {
    audioData: ['/hɒt/', '../../app_assets/audio/hot.mp3'],
    word: 'hot',
    meaning: ['High temperature', 'Popular', 'Spicy'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Very warm'],
    examples: ['Hot soup burns mouth.', 'Hot new song.'],
    synonyms: ['warm', 'popular', 'spicy'],
    antonyms: ['cold'],
    shortStory:
      'Hot coffee thawed frozen morning. First sip woke dreams. Warmth starts chains reactions.',
  },
  {
    audioData: ['/həʊˈtel/ ', '../../app_assets/audio/hotel.mp3'],
    word: 'hotel',
    meaning: ['Place providing rooms for travelers'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Traveler rooms'],
    examples: ['Book hotel room.', 'Nice hotel service.'],
    synonyms: ['inn'],
    antonyms: ['home'],
    shortStory:
      'Grand hotel lobby whispered adventures. Bellhops carried more than bags. Travel begins at check-in.',
  },
  {
    audioData: ['  /aʊər/', '../../app_assets/audio/hour.mp3'],
    word: 'hour',
    meaning: ['Time unit of 60 minutes'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['60 minutes'],
    examples: ['One hour lunch.', 'Rush hour traffic.'],
    synonyms: [],
    antonyms: [],
    shortStory:
      'Golden hour painted world magic. Photographers chased fleeting light. Perfect moments demand pursuit.',
  },
  {
    audioData: [' /haʊs/ ', '../../app_assets/audio/house.mp3'],
    word: 'house',
    meaning: ['Building for living', 'Family living there'],
    partOfSpeech: ['noun', 'verb'],
    simpleDefinition: ['Living building'],
    examples: ['Big old house.', 'House full guests.'],
    synonyms: ['home', 'residence'],
    antonyms: ['street'],
    shortStory:
      'Empty house filled with laughter. New family wrote fresh stories. Walls remember happiness.',
  },
  {
    audioData: [' /ˈhaʊs.həʊld/ ', '../../app_assets/audio/household.mp3'],
    word: 'household',
    meaning: ['People living together', 'Common items'],
    partOfSpeech: ['noun', 'adjective'],
    simpleDefinition: ['Family group'],
    examples: ['Household chores.', 'Household name famous.'],
    synonyms: ['family', 'common'],
    antonyms: [],
    shortStory:
      'Household harmony created symphony. Different notes blended perfectly. Unity sounds beautiful.',
  },
  {
    audioData: [' /ˈhaʊ.zɪŋ/ ', '../../app_assets/audio/housing.mp3'],
    word: 'housing',
    meaning: ['Homes or accommodation'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Living places'],
    examples: ['Affordable housing crisis.', 'Student housing nearby.'],
    synonyms: ['shelter'],
    antonyms: [],
    shortStory:
      'Housing dreams built community. Empty lots became neighborhoods. Hope constructs foundations.',
  },
  {
    audioData: [' /haʊ/ ', '../../app_assets/audio/how.mp3'],
    word: 'how',
    meaning: ['In what way', 'Question degree'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['What way'],
    examples: ['How are you?', 'How interesting!'],
    synonyms: [],
    antonyms: [],
    shortStory:
      'How questions opened wisdom doors. Curious minds found treasures. Questions unlock universes.',
  },
  {
    audioData: [' /ˌhaʊˈev.ər/', '../../app_assets/audio/however.mp3'],
    word: 'however',
    meaning: ['But', 'Nevertheless'],
    partOfSpeech: ['adverb'],
    simpleDefinition: ['But'],
    examples: ['Rainy, however beautiful.', 'Tired, however happy.'],
    synonyms: ['but', 'nevertheless'],
    antonyms: [],
    shortStory:
      'However impossible seemed possible. Obstacles crumbled before will. Determination rewrites reality.',
  },
  {
    audioData: ['/hjuːdʒ/ ', '../../app_assets/audio/huge.mp3'],
    word: 'huge',
    meaning: ['Extremely large'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Very big'],
    examples: ['Huge elephant.', 'Huge success.'],
    synonyms: ['enormous', 'giant'],
    antonyms: ['tiny'],
    shortStory:
      'Huge dreams fit small hearts. Vision expands realities. Imagination knows no size limits.',
  },
  {
    audioData: ['/ˈhjuː.mən/ ', '../../app_assets/audio/human.mp3'],
    word: 'human',
    meaning: ['Person', 'Having human qualities'],
    partOfSpeech: ['noun', 'adjective'],
    simpleDefinition: ['Person'],
    examples: ['Human beings.', 'Very human mistake.'],
    synonyms: ['person', 'mortal'],
    antonyms: ['animal'],
    shortStory:
      'Human kindness crossed language barriers. Smiles spoke universal truth. Compassion needs no translation.',
  },
  {
    audioData: [' /ˈhjuː.mə.rəs/ ', '../../app_assets/audio/humorous.mp3'],
    word: 'humorous',
    meaning: ['Funny', 'Amusing'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Funny'],
    examples: ['Humorous story.', 'Humorous person.'],
    synonyms: ['funny', 'witty'],
    antonyms: ['serious'],
    shortStory:
      'Humorous timing saved awkward moment. Laughter healed tension instantly. Wit wields magic wand.',
  },
  {
    audioData: ['/ˈhjuː.mər/ ', '../../app_assets/audio/humour.mp3'],
    word: 'humour',
    meaning: ['Ability to be funny', 'Quality causing laughter'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Funny quality'],
    examples: ['Great sense of humour.', 'British humour.'],
    synonyms: ['humor'],
    antonyms: ['seriousness'],
    shortStory:
      'Dry humour cut through grief fog. Laughter honored lost loved one. Joy remembers best.',
  },
  {
    audioData: [' /ˈhʌn.drəd/', '../../app_assets/audio/hundred.mp3'],
    word: 'hundred',
    meaning: ['Number 100'],
    partOfSpeech: ['noun', 'number'],
    simpleDefinition: ['100'],
    examples: ['Hundred people attended.', 'Hundred dollars.'],
    synonyms: [],
    antonyms: [],
    shortStory:
      'Hundredth customer won free lifetime supply. Lucky stranger became legend. Milestones reward patience.',
  },
  {
    audioData: ['/ˈhʌŋ.ɡri/ ', '../../app_assets/audio/hungry.mp3'],
    word: 'hungry',
    meaning: ['Needing food'],
    partOfSpeech: ['adjective'],
    simpleDefinition: ['Want food'],
    examples: ['Very hungry now.', 'Hungry for success.'],
    synonyms: ['starving'],
    antonyms: ['full'],
    shortStory:
      'Hungry eyes devoured first feast. Famine ended with single bowl. Gratitude flavors empty stomachs.',
  },
  {
    audioData: ['/hʌnt/ ', '../../app_assets/audio/hunt.mp3'],
    word: 'hunt',
    meaning: ['Search for', 'Chase wild animals'],
    partOfSpeech: ['verb', 'noun'],
    simpleDefinition: ['Search'],
    examples: ['Hunt for keys.', 'Treasure hunt fun.'],
    synonyms: ['search', 'pursue'],
    antonyms: ['find'],
    shortStory:
      'Job hunt led to dream career. Rejection paved perfect path. Persistence finds hidden doors.',
  },
  {
    audioData: ['  /ˈhʌn.tɪŋ/', '../../app_assets/audio/hunting.mp3'],
    word: 'hunting',
    meaning: ['Searching for animals to kill', 'Looking for something'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Animal search'],
    examples: ['Deer hunting season.', 'House hunting.'],
    synonyms: ['searching'],
    antonyms: [],
    shortStory:
      'Bargain hunting filled home treasures. Patience found greatest deals. Value hides among ordinary.',
  },
  {
    audioData: [' /ˈhʌr.ɪ.kən/ /ˈhʌr.ɪ.keɪn/ ', '../../app_assets/audio/hurricane.mp3'],
    word: 'hurricane',
    meaning: ['Violent tropical storm'],
    partOfSpeech: ['noun'],
    simpleDefinition: ['Big storm'],
    examples: ['Hurricane warning issued.', 'Hurricane destroyed homes.'],
    synonyms: ['typhoon'],
    antonyms: [],
    shortStory:
      'Hurricane passed, rainbows appeared. Cleared skies shone brightest. Storms birth spectacular sunrises.',
  },
];
